#!/bin/bash -e
source ~/.shell/func.d/packages

pkg_inst -p 'gpg' gnupg
pkg_inst keychain

if distro arch; then
    pkg_inst pinentry

elif distro ubuntu; then
    pkg_inst gnupg-agent pinentry-curses  pinentry-gtk2
fi
