#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
mkdir -p ~/.gnupg && chmod 700 ~/.gnupg
linkcp -t  ~/.gnupg gpg{,-agent}.conf

# svc_activate -cue gpg-agent.service
d=/usr/share/doc/gnupg/examples/systemd-user
svc_activate -cue -f "$d" gpg-agent-ssh.socket gpg-agent.socket
svc_activate -cu -f "$d" gpg-agent.service
# dirmngr.service dirmngr.socket


echo RELOADAGENT | tee >(gpg-connect-agent)
