#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
mkdir -p ~/.gnupg && chmod 700 ~/.gnupg
link -t  ~/.gnupg gpg{,-agent}.conf

# usvc_activate -e gpg-agent

echo RELOADAGENT | tee >(gpg-connect-agent)
