#!/bin/bash -e
# source ~/.shell/profile
# CHECK: maybe broken, as airy/setup sets DISPLAY=:0
# FAIL:(xset q &>/dev/null): will launch socket-activated Xorg when not needed
[[ $DISPLAY ]] || exit 0

# TEMP: new layout on startup
# cd /t  # NOTE: writes debug compilation file into $PWD
# /@/airy/xkb/cfg/apply || /@/airy/xkb/cfg/debug
# exit

# declare -A CURR_XKB=(
#   [layout]='us,ua,ru' [variant]='basic,winkeys,winkeys'
#   [overlay]='vim' [option]='misc:typo,amer:lvl3,amer:mods'
# )

# THINK: replace overlay for any layouts
# MAYBE: is calling setxkbmap again with only '-option "over:$over"' enough?

# over=${1:-${CURR_XKB[overlay]:-vim}}
# r.xkb-has-overlay "${over:?}"
#
# # ALT: use libxkbcommon :: /usr/lib/xkbcommon/xkbcli-{compile-keymap,list}
# xkb_remap(){ setxkbmap -I/usr/share/X11/xkb \
#   -display "${DISPLAY:?}" ${1:+-device "$1"} \
#   -option "" -model pc104 -rules amer \
#   -layout "${CURR_XKB[layout]:-us,ru,ua}" \
#   -variant "${CURR_XKB[variant]:-amer,amer,amer}" \
#   -option "${CURR_XKB[option]:-misc:typo,amer:nums,amer:lvl3,amer:mods},over:${over:?}"
# }

xkb_remap(){ local dev=$1; shift; local opt=$*
   # FIXED:(-I/@/airy/xkb/cfg): use symblinks to allow reloads by other apps
   setxkbmap -v 5 -I "" -I/usr/share/X11/xkb -device "$dev" \
   -model airy -rules airy -layout us,zip -option "" -option "airy${opt:+,$opt}"
}

# NOTE: prefer to remap only STD keyboards
declare -A kbds
# TEMP:FAIL: can't disable, because I must be able to change language
kbds["ZSA Moonlander Mark I"]="airy:zsa"
kbds["ZSA Technology Labs Moonlander Mark I"]="airy:zsa"
# COS: old habits on laptop die hard
# kbds["AT Translated Set 2 keyboard"]="airy:neo"
kbds["AT Translated Set 2 keyboard"]="airy:hpx"
kbds["Kinesis Advantage2 Keyboard"]="airy:hpx"
# "Logitech K340"
# "Logitech K750"

for k in "${!kbds[@]}"; do
  if id=$(xinput list --id-only "keyboard:$k" 2>/dev/null); then
    xkb_remap "$id" "${kbds["$k"]}"
    echo "OK: $k"
  fi
done
