#!/bin/bash -e
source ~/.shell/profile
# CHECK: maybe broken, as airy/setup sets DISPLAY=:0
# FAIL:(xset q &>/dev/null): will launch socket-activated Xorg when not needed
[[ $DISPLAY ]] || exit 0

# declare -A CURR_XKB=(
#   [layout]='us,ua,ru' [variant]='basic,winkeys,winkeys'
#   [overlay]='vim' [option]='misc:typo,amer:lvl3,amer:mods'
# )

# THINK: replace overlay for any layouts
# MAYBE: is calling setxkbmap again with only '-option "over:$over"' enough?

over=${1:-${CURR_XKB[overlay]:-vim}}
r.xkb-has-overlay "${over:?}"

# ALT: use libxkbcommon :: /usr/lib/xkbcommon/xkbcli-{compile-keymap,list}
xkb_remap(){ setxkbmap -I/usr/share/X11/xkb \
  -display "${DISPLAY:?}" ${1:+-device "$1"} \
  -option "" -model pc104 -rules amer \
  -layout "${CURR_XKB[layout]:-us,ru,ua}" \
  -variant "${CURR_XKB[variant]:-amer,amer,amer}" \
  -option "${CURR_XKB[option]:-misc:typo,amer:nums,amer:lvl3,amer:mods},over:${over:?}"
}

# NOTE: prefer to remap only STD keyboards
kbds=(
  "Kinesis Advantage2 Keyboard"
  # TEMP:FAIL: can't disable, because I must be able to change language
  "ZSA Moonlander Mark I"
  # COS: old habits on laptop die hard
  "AT Translated Set 2 keyboard"
  "Logitech K340"
)

for k in "${kbds[@]}"; do
  if id=$(xinput list --id-only "keyboard:$k"); then
    xkb_remap "$id"
    echo "OK: $k"
  fi
done
