#!/bin/bash -eu
# tags: xorg
source ~/.shell/func.d/cfgsetup

### LINKS ###
# linkcp -t /etc/X11 xkb
# BET: create local PKGBUILD and install settings through package
linkcp -kt '/usr/share/X11' xkb/{compat,rules,symbols,types}/*

# CHECK: maybe broken, as airy/setup sets DISPLAY=:0
# NOTE: broken after exporting DISPLAY for *monitor*
# FAIL:(xset q &>/dev/null): will launch socket-activated Xorg when not needed
running_X && ./run

### GENS ###
# DISABLED:CHECK: because we can't replace setxkbmap by xorg.conf
# MAYBE only XkbRules work
# ./xkb-xorg.gen

### SYSD ###
# dbus=/usr/share/dbus-1/system-services
# linkcp -c ./unit/kbdd-dbus.service "$dbus/ru.gentoo.KbddService"
# BUG: https://bbs.archlinux.org/viewtopic.php?id=172798
# DISABLED:(xcape.service): unnecessary for ZSA Moonlander
svc_activate -cue kbdd.service
