#!/bin/bash -eu
source ~/.shell/func.d/packages

## ALT:
# jarun/bcal: :1234: Storage and general-purpose calculator ⌇⡠⡏⠿⡦
#   https://github.com/jarun/bcal
## DISABLED:(use ipython): |community/calc| Arbitrary precision console calculator
pkg_inst bc
