#!/bin/bash
#%USAGE: $ ./$0 <account> [-- [<mbsync_args>]]
#% * sync all   $ -- all
#% * sync inbox $ -- -qV inbox
#% * pull new   $ -- -qq new
#%
#%DEBUG pull    $ -- -qV --pull-new new
#% -a|--all     # all channels
#% -l|--list    # only list mailboxes
#% -V|--verbose # verbose (show files to remove/resync: <dir>/.uidvalidity)
set -euo pipefail

# ALT:DFL:BAD: reduced orthogonality
# source ~/.shell/profile
# (($#)) && [[ $1 != -- ]] || set -- "${MUTT_DEFAULT:?}" "$@"
# ALT: use $(readlink $acc/default) to get name of default acc

acc=$1
shift
[[ ${1-} == -- ]] && shift

cfg=${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/acc/"$acc"

# ALT: mdir=${MAIL:-${MAILDIR:-${MAILROOT:-$HOME/.mail}/$acc}}
mdir=$(sed -rn "/^\s*Path\s+(.*)\s*($|#.*)/{s//\1/;s|^~|$HOME|p}" "$cfg")
mdir=$(realpath -sm "$mdir")
mkdir -p "$mdir"

# NOTE: only if using local davmail w/o encryption
grep -qwF 'Host 127.0.0.1' "$cfg" \
  && grep -qwF 'SSLType None' "$cfg" \
  && exec 2> >(grep -vxF '*** IMAP Warning *** Password is being sent in the clear')

# INFO: "davmail" sync speed is ~100 / min
#   ~50 dirs is 1 min for idle check; no effect from PipelineDepth
flock -FxE13 -w15 "$mdir" \
  mbsync --config "$cfg" "$@"
