#!/bin/bash -e
CURR_DIR_PKG=~/aura/pj  # Change dst dir
source ~/.shell/func.d/packages

# | urxvt | fast terminal, image support, perl extensions

if distro arch; then
    aur_inst rxvt-unicode-patched || pkg_inst rxvt-unicode

elif distro ubuntu; then
    pkg_inst rxvt-unicode-256color
fi

git_inst -d 'amerlyq/urxvt-ext-evolved'
dir="${CURR_DIR_PKG:?}/urxvt-ext-evolved/"
(cd "$dir" && ./setup)
