#!/bin/bash -eu
# tags: term, obsolete
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

### LINKS ###
linkcp "$PWD" ~/.urxvt
linkcp "$PWD/themes/amer-${THEME}" "$config/theme-urxvt"


# https://wiki.archlinux.org/index.php/Rxvt-unicode
# ! FIX:  если будут глюки с цветами в терминале или терминальном виме по сравнению с lxterminal
# !       http://unixforum.org/index.php?showtopic=135828
# ! NOTE: dump all commands with description:
# !urxvt --help 2>&1| sed -n '/:  /s/^ */! URxvt*/gp' >> ~/.urxvtrc_dump
# !TERM=dump command man -Pcat urxvt | sed -n '/depth: b/,/^BA/p'|sed '$d'|sed '/^       [a-z]/s/^ */^/g'|sed -e :a -e 'N;s/\n/@@/g;ta;P;D'|sed 's,\^\([^@]\+\)@*[\t ]*\([^\^]\+\),! \2\n! URxvt*\1\n\n,g'|sed 's,@@\(  \+\),\n\1,g'|sed 's,@*$,,g'|sed '/^[^!]/d'|tr -d "'\`" >> ~/.urxvtrc_dump

# /usr/share/icons
# Xcursor.theme: Vanilla-DMZ-AA
# Xcursor.size:  22
# https://wiki.archlinux.org/index.php/XScreenSaver


### GENS ###
# http://linuxoid.in/%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3:Xresources
# Color schemes with scrshots:
# http://linsovet.org.ua/terminal-color-schemes-2

dst="${CURR_DIR_CACHE:?No}/Xres-urxvt"
# size=11
cat > "$dst" << EOT
#define LETTER_SPACE $(distro arch && ${LETTER_SPACE:-0} || LETTER_SPACE=-1)
#include "$HOME/.urxvt/etc/xtermrc"
#include "$HOME/.urxvt/urxvtrc"
#include "$(if [[ -f ~/.config/airy/theme-urxvt ]]
then printf "$HOME/.config/airy/theme-urxvt"
else printf "$HOME/.urxvt/themes/amer-dark"
fi)"
EOT
echo "W: $dst"
# xrdb -merge -I"$PWD" urxvtrc "$dst"
# ! xrdb -load ~/.Xresources 2>&1 | grep 'error'
