#!/bin/bash -e
source ~/.shell/func.d/packages

# Provides a minimalistic means for transferring files. It is generally used as
# a part of PXE booting or for updating configuration and firmware on devices
# SEE:  http://archlinuxarm.org/forum/viewtopic.php?f=57&t=7386

if distro arch; then
  pkg_inst -p 'tftp' tftp-hpa

elif distro ubuntu; then
  pkg_inst -p 'tftp' tftpd-hpa
fi
