#!/bin/bash -e
# tags: net
source ~/.shell/func.d/cfgsetup

# http://linux.die.net/man/8/tftpd
dir=${CURR_DIR_TFTP:-${CURR_DIR_WORK:?}/tftpboot}

if cfgOpt u && [[ -d $dir ]]; then
    add_sysuser tftp

    mkdir -p "$dir"
    if [[ $(stat -c '%u %g' "$dir") != "$(id -u tftp) $(id -g tftp)" ]]
    then sudo chown -R tftp:tftp "$dir"; fi

    if distro arch; then
        linkcp -c ./config /etc/conf.d/tftpd
        svc_activate -eR tftpd

    elif distro ubuntu; then
        linkcp -c ./config /etc/default/tftpd-hpa
        svc_activate -eR tftpd-hpa
    fi
fi
