#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

# To enable socket activation for xorg on display 0 and tty 2:
# $ systemctl --user set-environment XDG_VTNR=2
# $ systemctl --user start xorg@0.socket
# -> Now running any X app will launch xorg on vt 2 automatically.

if distro arch; then
  link -sct /etc/X11 Xwrapper.config

  link -ct ~/.config/systemd/user \
    xorg@.{socket,target,service} \
    xmonad@.service wm@.target

  systemctl --user daemon-reload
  # systemctl --user enable wm@1.target xorg@1 xmonad@1
  # systemctl --user enable xmo{bar,nad}@1
  #@${DISPLAY:?}

elif distro ubuntu; then

  echo "Err: use standart ~/.xinitrc instead of systemd"
fi
