#!/bin/bash -e

# Don't forget to set primary PCH to card 0 or disable all others.
# instead of <5% | 2dB>

WM=$(wmctrl -m | awk 'NR==1{print$2}')
case "$WM"
in i3) notifywm(){ ~/.i3/blocks/update volume; }
;;  *) notifywm(){ :; }
esac

# DEPRECATED: use 20% unmute directly
# EXPL: this script is called too many times on wheel scroll
# case "$1" in [0-9]*) CMD="$1 unmute" ;; esac

amixer -q -D pulse set Master ${1:-toggle}
# pactl set-sink-volume 0 -- 20%  # +10%
# pactl set-sink-mute 0 toggle
# mocp -r

# ./dvolbar -g

notifywm
