#!/bin/bash -eu
source ~/.shell/func.d/packages

if distro arch; then
  # THINK:SEE gtags (GNU Global) -- instead of ctags?
  pkg_inst ctags cscope
  aur_inst global  # https://www.gnu.org/software/global/
  loc_inst -P 'ccglue-airy-git' ./PKGBUILD

elif distro ubuntu; then
  pkg_inst exuberant-ctags cscope
fi
