#!/bin/bash -eu
source ~/.shell/func.d/packages

if distro arch; then
  # THINK:SEE gtags (GNU Global) -- instead of ctags?
  pkg_inst ctags cscope

elif distro ubuntu; then
  pkg_inst exuberant-ctags cscope
fi
