#!/bin/bash -eu
source ~/.shell/func.d/packages

if distro arch; then
  pkg_inst ctags cscope
  aur_inst global
  loc_inst -P 'ccglue-airy-git' ./PKGBUILD

elif distro ubuntu; then
  pkg_inst exuberant-ctags cscope
fi
