#!/usr/bin/env bash

# BET:USE: for kernel -- current single arch only
# https://stackoverflow.com/questions/934233/cscope-or-ctags-why-choose-one-over-the-other
# http://cscope.sourceforge.net/large_projects.html
#   $ make tags
#   $ make cscope
# [_] MOVE: ./kernel/scripts/extract-src-ctags

EFL=.ctags_exclude
> "$EFL"
printf "drivers/*\nsound/*\ntags\n" >> "$EFL"
find arch -mindepth 1 -maxdepth 1 -type d ! -name arm -printf "%p/*\n" >> "$EFL"

ctags-exuberant --verbose --recurse --excmd=number --sort=foldcase --tag-relative --fields=+nS --exclude=@"$EFL"
