#!/usr/bin/env bash
set -euo pipefail

# BET:USE: for kernel -- current single arch only
# https://stackoverflow.com/questions/934233/cscope-or-ctags-why-choose-one-over-the-other
# http://cscope.sourceforge.net/large_projects.html
#   $ make tags
#   $ make cscope
# [_] MOVE: ./kernel/scripts/extract-src-ctags

arch=${1:-arm}

exclude=$(find arch -mindepth 1 -maxdepth 1 -type d ! -name "$arch")
readarray -t excldirs <<< "$exclude"

excldirs+=(
  drivers
  sound
)
exclude=$(printf '%s/*\n' "${excldirs[@]}")
exclude+=$'\ntags'
exec <<< "$exclude"

# ALSO: ignore search for "ag"
printf '/%s/\n' "${excldirs[@]}" > .ignore
echo tags >> .ignore

# BUG: ignored static inlines and macro inside includes
# --languages=C --kinds-c='+{prototype}{label}x'
# --verbose
# DISABLED:(--sort=foldcase): must distinguish macro and functions
exec ctags --recurse --exclude=@/dev/stdin \
  --excmd=number --sort=yes \
  --tag-relative=yes --fields='+{signature}{extras}{xpath}'
