#!/bin/bash -eu
host=127.0.0.1
port=2224

# BUG: socat not always killed on exit
onexit(){ kill $(jobs -p) &>/dev/null; wait; }
trap 'onexit' HUP QUIT TERM ERR INT

# BAD: can't kill forked process
# ALT: nc -l "$host" "$port" | xsel -i -b
# DEBUG: -d -d -d
socat -4u TCP-L:$port,reuseaddr,fork EXEC:xsel-auto &

# ATT: ssh returns code of last executed
# TODO: make universal wrapper and leave here only #!bash\nexec xsel-host ssh "$@"
ssh "$@"  # TEMP:(removed -R): can't forward port to the same one when testing localhost
# ssh -R "$port:$host:$port" "$@"
