#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

# linkcp -f unit -st /etc/X11/xorg.conf.d \
#   52-wacom-options.conf

# ATT: Can't use symlinks
#   -- udev triggers only on symlink creation
#   -- on reboot its not triggered at all
linkcp -f unit -sct /etc/udev/rules.d \
  99-wacom.rules
