#!/bin/bash
source ~/.shell/func.d/packages

# Installation man
# http://www.linuxrussia.com/2013/04/oracle-java-7-ubuntu-1304-1204-1210.html
#apt_noprompt openjdk-7-jdk #openjdk-7-jdk:i386 == broken

#ppa:eugenesan/java
# Can't dld. Use offsite, dld .rpm package, then
#   sudo apt-get install alien && sudo alien *.rpm && dpkg -i *.deb


if distro arch; then
    aur_inst -p java jdk

elif distro ubuntu; then
    ppa_add 'ppa:webupd8team/java'
    pkg_inst 'oracle-java8-installer'
    # sudo update-java-alternatives -s java-8-oracle
fi

java -version
javac -version



# IF ppa CAN'T DOWNLOAD java (ex: oracle changed cookies)
# manually dld from offsite
#   http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
#   sudo cp -t /var/cache/oracle-jdk8-installer ./jdk-8u25-linux-x64.tar.gz
# comment lines in file /var/lib/dpkg/info/oracle-java7-installer.postinst
#       echo "Downloading..."
#       #rm -f $FILENAME
#       #WGETRC=wgetrc wget $PARTNER_URL
#       #    || fp_exit_with_error "download failed"
#       #rm -f wgetrc
#       echo "Download done."
# do again
#   sudo apt-get install oracle-java8-installer
### FROM: http://rootzwiki.com/topic/23008-howto-install-java-7-on-ubuntu-1204/

## for java8 -- dld from site. If VM can't start -- you must unpack it's files.
# find . -type f -name '*.pack' | while read fl; do sudo ./bin/unpack200 $fl ${fl%.*}.jar; done
