#!/bin/bash -e
source ~/.shell/func.d/packages

# | inotify-tools | watch on downloaded files in dir and auto-open them
pkg_inst 'inotify-tools'

if distro arch; then
    aur_inst 'vimb'

elif distro ubuntu; then
    pkg_inst 'libsoup2.4-dev libwebkit-dev libgtk-3-dev libwebkitgtk-3.0-dev'
    git_inst 'fanglingsu/vimb'
fi
