#!/bin/bash -e
# tags: browser
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

### LINKS ###
dir=~/.config/vimb
# Skip if you only toggle them
cfgOpt t || linkcp -t "$dir" config 'dld-start' theme setup
linkcp "$dir/theme/${THEME}.css" "$dir/style.css"
