#!/bin/bash -e
cd $(dirname $(readlink -m ${0}))
[[ "${THEME:=$(< ~/.cache/airy/theme)}" =~ ^(dark|light)$ ]] || THEME=dark

dir=~/.config/vimb
mkdir -p $dir

### LINKS ###
link(){ [[ ! -e $2 || -L $2 ]] && ln -sfvT "$1" $2; }

link "$dir/theme/${THEME}.css" "$dir/style.css"
[[ "$1" == '-t' ]] && exit

for nm in config 'dld-start' theme setup
do link "$PWD/$nm" "$dir/$nm"; done
