#!/bin/bash -e
source ~/.shell/func.d/packages

#| ag      | The silver searcher -- 'ag' instead of 'grep' inside of git project -- very best!
#| at      | Read commands from standard input or a specified file which are to
#|_________|    be executed at a later time, using /bin/sh.
#| iotop   | Show disk r/w statistics for processes like htop (press 'a')
#| dstat   | Versatile tool for generating system resource statistics
#| jshon   | Bash json parser to use in scripts with i3-msg output # http://kmkeen.com/jshon/
#| shyaml  | Read access to YAML files through command line # https://github.com/0k/shyaml
# ALT:  jq (https://stedolan.github.io/jq/), paired with yaml2json (https://github.com/coolaj86/yaml2json).
#| urlview | Extracting URLs from text files and displaying a menu from which
#|_________|    you may launch a command to view a specific item
#| mlocate | Searching indexed (daily or by 'sudo updatedb') files on arch

# Desktop search: (USE 'whereis' along with which)
#   https://wiki.archlinux.org/index.php/File_system_search

pkg_inst "at htop iotop dstat jshon"

if distro arch; then
    aur_inst shyaml
    pkg_inst -p 'locate' mlocate
    pkg_inst -p 'ag' the_silver_searcher

elif distro ubuntu; then
    pkg_inst -p 'checkinstall' checkinstall
    pkg_inst locate
    pkg_inst urlview  # No for arch?
    # pkg_inst silversearcher-ag
    pkg_inst automake pkg-config libpcre3-dev zlib1g-dev liblzma-dev
    git_inst "ggreer/the_silver_searcher"
fi
