#!/bin/bash -e
source ~/.shell/func.d/packages

### Ag ### : The silver searcher
# :: 'ag' instead of 'grep' inside of git project -- very best!

if distro arch; then
    aur_inst silver-searcher-git

elif distro ubuntu; then
    # pkg_inst silversearcher-ag
    pkg_inst automake pkg-config libpcre3-dev zlib1g-dev liblzma-dev
    git_inst "ggreer/the_silver_searcher"
fi
