#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
# valgrindrc
link "$PWD/agignore" ~/.agignore

if cfgOpt u; then
  # DISABLED: dfl unit don't have prunepaths and hangs on 'activating'
  svc_disable 'updatedb'
  # svc_disable 'updatedb.timer'
  # MAYBE:BETTER? simply fix /etc/updatedb.conf
  fork_m ./update
fi
