#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
# valgrindrc
link "$PWD/agignore" ~/.agignore

if cfgOpt u; then
  # Gen db for 'locate'
  fork_m sudo updatedb --add-prunepaths /cryptfs
fi
