#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
    # device drivers
    pkg_inst -f '/usr/lib/xorg/modules/input/synaptics_drv.so' xf86-input-synaptics

elif distro ubuntu; then
    echo "Err: "
fi
