#!/bin/bash -e
# http://www.x.org/archive/X11R7.5/doc/man/man4/synaptics.4.html


# Then you can set edges:
# xinput --set-prop --type=int "AlpsPS/2 ALPS DualPoint TouchPad" "Synaptics Edges" 150 920 150 650
# ALT: xinput set-int-prop "SynPS/2 Synaptics TouchPad" "Synaptics Movement Bottom Edge" 32 4100
# You also can see what is set now:
# xinput --list-props "AlpsPS/2 ALPS DualPoint TouchPad" |grep Edges


case "$1"
in -l|--list)
# locate *synaptics.conf
TPAD_NM=$(xinput -list | grep Touchpad | sed "s@\W*\(\w*.*Touchpad\).*@\1@")
    echo $TPAD_NM
    echo O: [{left, middle, right}, {two-fing, three-fing}, {conf-vert-resolution, ..-horiz-...}]
    # See w/o grep -- there plenty of properties
    xinput list-props "${TPAD_NM:?No touchpad}"
    #xinput list-props "$TPAD_NM" | grep Capabilities
    exit
;; -o|--options) synclient -l | sort; exit
;; -s|--show) CMD=echo
;; esac

touchpad() { ${CMD:-synclient} $(sed -r \
    ':a; s/#.*$//; /^\s*$/d; /$/N; s/\n\s*(.*)/ \1/; ta'); }

touchpad << EOT
## Tap Dragging
LockedDrags=1
# LockedDragTimeout 5000

## Tapping as Buttons (number of fingers)
TapButton1=1
TapButton2=3
TapButton3=2

## Two Finger Scrolling
VertTwoFingerScroll=1
HorizTwoFingerScroll=1
EOT

## Enable touchpad
#  TouchpadOff        0
## Allow run-time configuration
##  SHMConfig           on  # deprecated

## Edge Limits
# LeftEdge 1748  RightEdge 5640  TopEdge 1274  BottomEdge 4752
## Speed
#  MinSpeed 0.4   MaxSpeed 0.7   AccelFactor 0.00995223
## Pressure
#  FingerLow 24   FingerHigh 29   FingerPress 255
## Tapping Detection  (MaxTapTime=0 -- disables tap)
#  MaxTapTime 0
#  MaxTapMove 29
#  MaxDoubleTapTime 180
#  SingleTapTimeout 180
#  ClickTime 100
#  FastTaps 0
## Tap Gesture Dragging
#  TapAndDragGesture 0
## Corner Tap Buttons
#  RTCornerButton 0
#  RBCornerButton 0
#  LTCornerButton 0
#  LBCornerButton 0
## Scrolling Edges
#  VertEdgeScroll 1
#  VertScrollDelta 100
#  HorizEdgeScroll 0
#  HorizScrollDelta 100
## Circular Scrolling
#  CircularScrolling 0
#  CircScrollDelta 0.1
#  CircScrollTrigger 0
## Corner Coasting
#  CornerCoasting 0
#  CoastingSpeed 20
#  CoastingFriction 50
## Kernel Event Protocol
#  GrabEventDevice 1
## Edge Ignore Boundaries
#  AreaLeftEdge 0
#  AreaRightEdge 0
#  AreaTopEdge 0
#  AreaBottomEdge 0
## Trackstick
#  TrackstickSpeed 40
## Circular Trackpad
#  CircularPad 0
## Multi-function Buttons
#  ClickFinger1 1
#  ClickFinger2 1
#  ClickFinger3 1
## Edge Movements
#  EdgeMotionMinZ 29
#  EdgeMotionMaxZ 159
#  EdgeMotionMinSpeed 1
#  EdgeMotionMaxSpeed 401
#  EdgeMotionUseAlways 0
## Pressure Motion
#  PressureMotionMinZ 29
#  PressureMotionMaxZ 159
#  PressureMotionMinFactor 1
#  PressureMotionMaxFactor 1
## Emulations
#  EmulateMidButtonTime 75
#  EmulateTwoFingerMinZ 280
#  EmulateTwoFingerMinW 7
## Palm Detection
#  PalmDetect 0
#  PalmMinWidth 10
#  PalmMinZ 199
