#!/bin/bash -e

# It may be usefull to disable mouse pointer and/or touchpad while layouting.
# Another solution how to disable/enable
# https://github.com/deterenkelt/dotfiles/blob/master/.i3/autostart.sh

getId(){ xinput list | sed -rn '/.*('"$1"').*id=([0-9]+).*/s//\2/p'; }
id=$(getId 'TouchPad|FTE1001')
[[ $id ]] || id=$(getId 'Mouse')
state=$(xinput list-props "$id" | awk '/Device Enabled/{print$NF}')

# TODO: if no mouse connected and touchpad disabled --> mouse pointer off

if ((state)); then
  xinput disable "$id"
  # ALT: xinput set-prop "$id" "Device Enabled" 0
  r.n -Ut2 Touchpad Disabled
else
  xinput enable "$id"
  r.n Touchpad Enabled
fi
