#!/bin/bash -e
exit

## For UHD displays:
setfont latarcyrheb-sun32 -m 8859-1
# OR setfont  # To reset

# SEE
# https://gist.github.com/jasonwryan/4618490
# https://gist.github.com/binaerbaum/535884a7f5b8a8697557

# Add partition for encrypted lvm (dual-windows)
# Firstly, create unallocated space under Windows.
# SEE (gdisk example) http://www.rodsbooks.com/gdisk/walkthrough.html
gdisk /dev/nvme0n1
# n - new, number - 6, start/end -- default, type: 8e00 (lvm)
# v - check, w - write+exit

# Default AES cipher in XTS mode (effective key 256-bit)
cryptsetup -s 512 luksFormat /dev/nvme0n1p6
cryptsetup open --type luks /dev/nvme0n1p6 crypto-lvm
# OR luksOpen?

## NOTE: change password
# https://unix.stackexchange.com/questions/252672/how-do-i-change-a-luks-password
# INFO: look at occupied key slots
# sudo cryptsetup luksDump /dev/sdb5 | grep ABLED
# WARN: don't overwrite passphrase directly (failure-prone)
# -- BET: repeat safe change two times with same password
# sudo cryptsetup luksChangeKey /dev/sdb5

# Create LVM parts for SSD
lvmdiskscan

pvcreate --dataalignment 1m /dev/mapper/crypto-lvm
pvdisplay
pvs

vgcreate lvm /dev/mapper/crypto-lvm
vgdisplay
vgs

# lvcreate lvm -Wy --yes -L 4G -C y -n swap
lvcreate lvm -Wy --yes -L 40G -n root
lvcreate lvm -Wy --yes -L 40G -n home
lvcreate lvm -Wy --yes -l +100%FREE -n media
lvs

# Format
# mkswap -f /dev/mapper/lvm-swap
mkfs.btrfs -f /dev/mapper/lvm-root
mkfs.btrfs -f /dev/mapper/lvm-home
mkfs.ext4 /dev/mapper/lvm-media

# Mount
# swapon /dev/mapper/lvm-swap
mount -o compress=lzo,autodefrag /dev/mapper/lvm-root /mnt
mkdir /mnt/boot
mount /dev/nvme0n1p1 /mnt/boot
mkdir /mnt/home
mount -o compress=lzo,autodefrag /dev/mapper/lvm-home /mnt/home
mkdir /mnt/home/media
mount /dev/mapper/lvm-home /mnt/home/media

# Create loader.conf
cat > /boot/loader/loader.conf <<EOT
default arch
timeout 3
editor 0
EOT

# <UUID> is raw encrypted device /dev/nvme0n1p6 -- find by ':r!blkid' in vi
cat > /boot/loader/entries/arch.conf <<EOT
title Arch Linux Enc
linux /vmlinuz-linux
initrd /initramfs-linux.img
options cryptdevice=UUID=<UUID>:lvm root=/dev/mapper/lvm-root rw
EOT
# WTF? intel_pstate=no_hwp

# Sync
cp /etc/nectl/{examples/,}wireless-wpa
# THEN: edit /etc/netctl/wireless-wpa
netctl start wireless-wpa
timedatectl set-ntp true

# Install
pacstrap base base-devel lvm2 btrfs-progs ntp sudo polkit wpa_supplicant wget xorg-server xorg-server-utils xorg-xinit xf86-video-intel xf86-video-vesa mesa-libgl

# ATTENTION:SEE:
# https://wiki.archlinux.org/index.php/ASUS_Zenbook_Pro_UX501

# END
# ALSO: umount -l /mnt
# swapoff /dev/mapper/lvs-swap
vgs
lvchange --activate n vg0   # stop LVM group
cryptsetup -v close crypto-lvm
# BUG: device-mapper: remove ioctl on crypto-lvm  failed: Device or resource busy
# SEE: https://askubuntu.com/questions/429612/device-mapper-remove-ioctl-on-luks-xxxx-failed-device-or-resource-busy
# $ sudo dmsetup ls | grep 'crypto-lvm\|^vg0-'  => (254:6) :7 :8
# $ sudo lsof | grep '254,[678]'
