#!/bin/sh
xrdb -merge ~/.Xresources

xset b off s off dpms 900 1500 1800 r rate 250 40

/@/airy/xkb/run

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

exec /usr/bin/qtile start
