#!/bin/sh

xcv

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

if ! systemctl --user is-active xsession.target &> /dev/null
then
  systemctl --user import-environment DISPLAY XAUTHORITY \
    PATH EDITOR PAGER DBUS_SESSION_BUS_ADDRESS
  systemctl --no-block --user start xsession.target
fi

exec /usr/bin/qtile start
