#!/bin/bash -e
source ~/.shell/func.d/packages

#| tmux | multi-window customizable terminal with vi navigation, useful for SSH connections

if distro arch; then
  pkg_inst tmux  # TrueColor support in version >=2.2
  aur_inst -p fpp fpp-git  # Facebook PathPicker

elif distro ubuntu; then
  pkg_inst tmux
fi

./update $(cfgOpt u && echo -u)
