#!/bin/bash -e

## NEED: ~/.tmux.conf
#   set -g focus-events on
# if [[ "$TERM" =~ 'rxvt' ]]; then
#   trap 'printf "\e]777;focus;off\x7"'  INT TERM EXIT
#   printf "\e]777;focus;on\x7"
# fi

# BUG:
# $ r.t -e tmux
# > child finished with error '256'

# Exit session on kill
name="st-$$"
trap "tmux kill-session -t $name" INT TERM EXIT
# WARNING: to keep 'trap' working, don't use exec
tmux new-session -s $name "$@"
