#!/bin/bash -e
hash tmux &>/dev/null && tmux start-server || exit

session='jobs'
maincmd=r.ranger  # USE:($2) r.ranger, htop, r.notify-watch
name=main

while getopts 'm:n:t:' o; do case "$o"
in t) session=$OPTARG
;; n) name=$OPTARG
;; m) maincmd=$OPTARG
;; *) exit; esac; done; shift $((OPTIND-1))

if ! tmux has-session -t "$session" 2>/dev/null; then
  tmux new-session -d -c "$PWD" -n "$name" -s "$session" "$maincmd"
  tmux set-option -s -t "$session" status on
fi

# ATTENTION: Each starting command must be unique!
tmux list-window -F '#{pane_start_command}' -t "$session" | grep -qxF "$*" \
|| tmux new-window -d -c "$PWD" -n "$1-$$" -t "$session" "$@"
