#!/bin/bash -e
cd $(dirname $(readlink -m ${0})) && source ~/.shell/func.d/cfgsetup
[[ "$THEME" =~ ^(dark|light)$ ]] || THEME=dark

### LINKS ###
link "$PWD/tmux.conf" ~/.tmux.conf
link "$PWD/theme-${THEME}.conf" ~/.cache/airy/theme-tmux.conf
