#!/bin/bash -e
source ~/.shell/func.d/cfgsetup
[[ $THEME =~ ^(dark|light)$ ]] || THEME=dark

### LINKS ###
linkcp "$PWD/tmux.conf" ~/.tmux.conf
linkcp "$PWD/theme-${THEME}.conf" ~/.cache/airy/theme-tmux.conf

if distro arch; then
  svc_activate -cue tmux.service
fi
