#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

echo 'N: Defaults'

### AUTO ###
if has_pr st; then term=st
elif has_pr urxvt; then term=urxvt
else term=xterm; fi

mkdef r.t         r.${term:?}
mkdef r.tf        r.${term}-float
mkdef r.n         r.notify
mkdef r.b         r.qute
mkdef r.bt        r.elinks
mkdef r.wm        r.xmonad

mkdef xmessage    r.vim-xmessage
mkdef notify-send /usr/bin/dunstify
[[ -z $EDITOR ]] || mkdef editor      $EDITOR

if distro ubuntu; then
  mkdef x-terminal-emulator $(which $term)
  mkdef www-browser $(which elinks)
  mkdef x-www-browser $(which qutebrowser)
  mkdef x-window-manager $(which xmonad)
  for nm in vim view rview; do mkdef $nm $(which vim.gtk); done
fi
