#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

echo 'N: Defaults'

### AUTO ###
if has_pr st; then term=st
elif has_pr urxvt; then term=urxvt
else term=xterm; fi

cd "${CURR_DIR_CACHE:?}/bin"
link "r.${term:?}"        ./r.t
link "r.${term}-float"    ./r.tf
link "r.notify"           ./r.n
link "r.qute"             ./r.b
link "r.elinks"           ./r.bt
link "r.xmonad"           ./r.wm
link "r.vim-xmessage"     ./xmessage
link "/usr/bin/dunstify"  ./notify-send

mkdef editor $(which $EDITOR)

if distro ubuntu; then
  mkdef x-terminal-emulator $(which $term)
  mkdef www-browser $(which elinks)
  mkdef x-www-browser $(which qutebrowser)
  mkdef x-window-manager $(which xmonad)
  for nm in vim view rview; do mkdef $nm $(which vim.gtk); done
fi
