#!/bin/bash -eu
# tags: net mail
# OBSOL: use getmail + sort locally
source ~/.shell/func.d/cfgsetup

### LINKS ###
linkcp -t "$(dconfig)" cfg

# ALT:DFL:
# dfl=$(dconfig)/acc/${MUTT_DEFAULT:?}.lua
# ! [[ -f $dfl && -s $dfl ]] || linkcp "$dfl" "$(dconfig)/config.lua"
