#!/bin/bash -e
source ~/.shell/profile

smbclient //${ROUT_IPL?}/share -N
# ALT: ~/.bin/mnt -s router :OR: mount -t cifs
# Linux: smb://<HOST_IP_OR_NAME>/<folder_name>/
# Windows: \\<HOST_IP_OR_NAME>\<folder_name>\
