#!/bin/bash
#%USAGE: r.sh-perf-parse /tmp/profiling.16850 | cut -c -80 | sort -k1,1
set -euo pipefail

flog=$1
ftime=${2:-$flog.time}

# TODO: sep accumulate times per function call on the right
parse_times(){ while read t; do
  [[ -z ${end-} ]] && end=${t//.} && beg=${t//.}
  crt="000000000$((${t//.}-10#0$end))"
  ctot="000000000$((${t//.}-10#0$beg))"
  printf "%12.9f %12.9f\n" \
    "${crt:0:${#crt}-9}.${crt:${#crt}-9}" \
    "${ctot:0:${#ctot}-9}.${ctot:${#ctot}-9}"
  end=${t//.}
done < "$ftime"
}

exec < <(parse_times)
exec paste - "$flog"
