#!/bin/bash -e
source ~/.shell/func.d/packages

#| conky | show system info on screen overlay

pkg_inst conky
pkg_inst -p 'sensors' lm-sensors

if cfgOpt u; then
    echo "Configure cpu and etc sensors. Reply 'yes' on all questions"
    sudo sensors-detect
    # Display all found sensors
    sensors
fi
