#!/bin/sh -eu
fmt=${1:-%f:%l:%c:%m}
# |bwipe
# excmd="setl noro ma bt=nofile nowrap efm=$fmt|cbuffer|if len(getqflist())>1|copen|en"
## HACK: wait until lazy plugins loaded before reading QF
excmd="autocmd User LazyPluginsLoaded  setl noro ma bt=nofile nowrap efm=$fmt|cbuffer|copen"

if [ -n "${NVIM_LISTEN_ADDRESS-}" ]; then
  # exec xargs -rn1 -d\\n realpath | ifne nvr - -c "$excmd"
  exec xargs -rn1 -d\\n realpath | ifne nvr -q /dev/stdin
else
  exec ifne $EDITOR - -c "$excmd"
fi
