#!/bin/sh -eu
fmt=${1:-%f:%l:%c:%m}
# BUG:(nvr): below qf loading from stdin don't work with nvr instance redirection
exec ifne $EDITOR -c "setl noro ma bt=nofile nowrap efm=$fmt|cb|if len(getqflist())>1|copen|en"
