#!/bin/bash -eu
fmt=${1:-%f:%l:%c:%m}
pfx=${2:-$PWD}

# exec awk -vd="$pfx" '{if(/^[^/]/){print d"/"$0}else{print$0}}' |
#   ifne nvr -q /dev/stdin -c 'if len(getwininfo())>1|close|en|if len(getqflist())>1|copen|else|cfirst|en'

awk -vd="$pfx" '{if(/^[^/]/){print d"/"$0}else{print$0}}' > /tmp/nvim.qf
# FAIL: stopped working with !nvr
# qf=$(awk -vd="$pfx" '{if(/^[^/]/){print d"/"$0}else{print$0}}')
# exec 3<<<"$qf"
#caddfile /dev/fd/3|
# TODO:SEE: how !rnvimr is closing its own window when you open files from it
#   [_] FIXME: only close specific "rnvimr" window (by id or bufname)
# exec nvr -q /dev/fd/3 -c 'if len(getwininfo())>1|close|en|if len(getqflist())>1|copen|else|cfirst|en'
# exec nvr -q /dev/fd/3 -c 'exe"RnvimrToggle"|if len(getqflist())>1|copen|else|cfirst|en'
# exec nvr -q /dev/fd/3 -c 'if len(getqflist())>1|copen|else|cfirst|en'
exec nvr -s -q /tmp/nvim.qf -c 'if len(getqflist())>1|copen|else|cfirst|en'

# DEBUG: nvim --server "${NVIM-}" --remote -q /dev/fd/3 -c 'if len(getqflist())>1|copen|else|cfirst|en' 3<<<"./xtref:101:    --sort='yes'"
# WAIT? https://github.com/neovim/neovim/issues/24788
#   https://stackoverflow.com/questions/76024656/can-i-use-nvim-remote-to-replace-nvr
#   https://github.com/mhinz/neovim-remote/issues/196
# nvim -q /dev/fd/3 ${NVIM:+--server "$NVIM" --remote} +'if len(getqflist())>1|copen|else|cfirst|en'

exit 13
#########################

# |bwipe
# excmd="setl noro ma bt=nofile nowrap efm=$fmt|cbuffer|if len(getqflist())>1|copen|en"
## HACK: wait until lazy plugins loaded before reading QF
# BAD:(copen -- prevents syntax hl -- BET: open manually by <,q> after that)
excmd="setl bt=nofile nowrap efm=$fmt | cbuffer"
# excmd="setl noro ma bt=nofile nowrap efm=$fmt | autocmd User LazyPluginsLoaded  cbuffer "
# excmd="setl noro ma bt=nofile nowrap efm=$fmt | autocmd User LazyPluginsLoaded  cbuffer|copen"
# excmd="autocmd User LazyPluginsLoaded  setl noro ma bt=nofile nowrap efm=$fmt|cbuffer|copen"

if [ -n "${NVIM_LISTEN_ADDRESS-}" ]; then
  # exec xargs -rn1 -d\\n realpath | ifne nvr - -c "$excmd"
  # sed -r 's/:([0-9]|\s).*//' | xargs -rn1 -d\\n realpath | ifne nvr -q /dev/stdin
  exec awk -vd="$pfx" '{if(/^[^/]/){print d"/"$0}else{print$0}}' |
    ifne nvr -q /dev/stdin -c 'close|if len(getqflist())>1|copen|else|cfirst|en'
  # ... | ifne nvr -l - -c "$excmd | wincmd p"
else
  exec ifne $EDITOR - -c "$excmd"
fi
