#!/usr/bin/env bash

ARG="$1"

sys_lock() {
    local pic=~/aura/screenlock.png
    if [ ! -f $pic ]; then
        pic=/tmp/aura/screenlock.png
        mkdir -p "${pic%/*}"
        scrot $pic  # Lock with cool bkgd
        mogrify -scale 10% -scale 1000% $pic
    fi
    { notify-send "DUNST_COMMAND_PAUSE";   # pause notifications
      i3lock --dpms --nofork --color 111111 --image $pic;
      notify-send "DUNST_COMMAND_RESUME";  # resume notifications
    } &
    ## With this you can hold backlight 3 sec longer
    ## But then it will not off after wrong passwords!
    # xset dpms force on && sleep 3;
    # pgrep i3lock >/dev/null && xset dpms force off;
    # ALT:
    # xscreensaver-command -lock
    # xautolock -time 15 -locker '~/.local/bin/fuzzy_lock.sh'
}

scratchpad_is_empty(){
    if ! i3-msg -t get_tree | jshon | awk '/scratchpad_state/{a[$2]=0}
        END{exit (length(a)>1)}'; then
    i3-input -l 1 -P "Your scratchpad isn't empty" -F "scratchpad show"
    return 1; fi
}

sys_logout(){ i3-nagbar -t warning \
    -m 'Logout: exit i3, end your X session, move to login screen' \
    -b 'Yes, exit i3' 'i3-msg exit'
}

sys_power(){ #Suspend #Hibernate
    # PORTABLE: http://askubuntu.com/questions/1792/how-can-i-suspend-hibernate-from-command-line/131022#131022
    dbus-send --system --print-reply --dest="org.freedesktop.UPower" \
        /org/freedesktop/UPower org.freedesktop.UPower.$1
    # sudo pm-suspend -- from pm-utils for Debian-based distros.
    # ALT: (sleep 0.5 && systemctl suspend) & #systemctl poweroff
    # dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" \
    #    /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart #Stop
}

case "$ARG" in
       lock|-l) sys_lock            ;;
    suspend|-s) sys_power Suspend   ;;
  hibernate|-h) sys_power Hibernate ;;
     logout|-o) scratchpad_is_empty && sys_logout    ;;
     reboot|-r) scratchpad_is_empty && sudo reboot   ;;
   shutdown|-t) scratchpad_is_empty && sudo poweroff ;;
             *) echo "Usage: $0
    <[l]ock|log[o]ut|[s]uspend|[h]ibernate|[r]eboot|shu[t]down>"; exit 2
esac

