#!/bin/bash

# So, it has not much sense -- I have not so huge window set
# and it will not help in that case anywhere.
# Replace this idea by showing name in i3blocks

getName() {
    local myid myclass myname
    myid=`xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}'`
    myclass=`xprop -id $myid | awk '/WM_CLASS\(STRING\)/{print $NF}'`
    myname=`xprop -id $myid | awk '/WM_NAME\(STRING\)/{print $0}' | sed 's@.*"\(.*\)"@\1@'`
    if [ ${#myname} -le 10 ]; then
        echo "${myname:0:10}"
    else echo "${myname:0:7}..."; fi

    #echo "`xdotool getwindowname $(xdotool getwindowfocus)`"
}

getWorkspace() {
    local tmpfl cnt
    tmpfl=/tmp/i3wksps
    i3-msg -t get_workspaces > $tmpfl
    cnt=`jshon -l < $tmpfl`

    for (( i=0; i<$cnt; i++ )); do
        if [ "$(jshon -e $i -e focused < $tmpfl)" == "true" ]; then
            wname="$(jshon -e $i -e name -u < $tmpfl)"
            wnum=${wname%%:*}
            echo $wnum
        fi
    done
}

getWorkspace
i3-msg "rename workspace \"$wname\" to \"$wnum:$(getName)\""
