#!/bin/bash -e
source ~/.shell/func.d/packages

# haskell
pkg_inst c2hs  # -pr-lang: haskell
pkg_inst hlint  # src enh suggestions
# pkg_inst hoogle  # search for fn sig

# SEE: https://hackage.haskell.org/package/cabalg
pkg_inst cabal-install


# CHECK: need immediate ./update for clean install when processing mods all setup before all update ?
# ERR: can't run on clean -- because "cabal" is not installed yet
#  MAYBE: => move mods into "update" BUT:BAD: all mods must be in "install"
# [[ -d ~/.cabal/packages ]] || ./update

# cabal-install ghc-mod
# cabal install hdevtools
