#!/bin/bash -e
source ~/.shell/func.d/packages

# haskell
pkg_inst c2hs # -pr-lang: haskell

# SEE: https://hackage.haskell.org/package/cabalg
pkg_inst cabal-install


# CHECK: need immediate ./update for clean install when processing mods all setup before all update ?
if cfgOpt u || [[ ! -d ~/.cabal/packages ]]
then ./update; fi

# cabal-install ghc-mod
# cabal install hdevtools
