#!/bin/bash -eu
hash cabal &>/dev/null || exit 0
source ~/.shell/func.d/system
exec < /dev/tty
exec > /dev/tty
# FIXME: Warning: The update command is a part of the legacy v1 style of cabal usage.
# BUG: ./root.json parse error when using root CA on corporate network
exec cabal new-update
