#!/bin/bash -e
source ~/.shell/func.d/packages

#| kbdd      | Individual language for each window + dbus commands for i3
#| xcape     | To configure modifier keys to act as other keys when pressed and
#|___________|  released on their own

pkg_inst kbdd

if distro arch; then
    aur_inst -p 'xcape' 'xcape'

elif distro ubuntu; then
    # FIXED???, works after reboot only after you once press REAL Control_L
    git_inst 'alols/xcape'
fi
