#!/bin/bash -e
source ~/.shell/func.d/packages

#| kbdd      | Individual language for each window + dbus commands for i3
#| xcape     | To configure modifier keys to act as other keys when pressed and
#|___________|  released on their own
# ALT:(xcape) https://gitlab.com/at-home-modifier/at-home-modifier-evdev/wikis/home
#   -- aur_inst xf86-input-evdev-ahm


if distro arch; then
    aur_inst 'kbdd-git xcape xorg-xev'

elif distro ubuntu; then
    pkg_inst kbdd
    # FIXED???, works after reboot only after you once press REAL Control_L
    git_inst 'alols/xcape'
fi
