#!/bin/bash -e
source ~/.shell/func.d/system

run_single kbdd

# SEE: /usr/include/X11/keysymdef.h
run_single -r xcape -t 250 -e "\
ISO_Level3_Shift=Super_R;\
Overlay1_Enable=Multi_key"

# Overlay1_Enable=Control_R\
# Control_L=Escape;\
# Hyper_L=Multi_key"
# clearMods:  ;Hyper_L=space
# EXPL: To be able to press RCtrl by double tap and Mod-RCtrl by one more tap
