#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
    aur_inst copyq-git  # copyq -- last tag 2.5.0 is w/o my enhances
    echo "Err: change to copyq when last tag > 2.5.0 in pkg"

elif distro ubuntu; then
    # libxtst-dev (optional; auto-paste into some applications),
    pkg_inst libqt4-dev libxfixes-dev libxtst-dev \
                libxinerama-dev libqtwebkit-dev
    git_inst 'hluk/CopyQ'
fi
