#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
    if cfgOpt u || ! has_pr copyq; then
        aur_inst copyq
    fi

elif distro ubuntu; then
    # libxtst-dev (optional; auto-paste into some applications),
    pkg_inst libqt4-dev libxfixes-dev libxtst-dev \
                libxinerama-dev libqtwebkit-dev
    git_inst 'hluk/CopyQ'
fi
