#!/bin/bash -e

# User-choosen bkgr
pic=~/aura/screenlock.png
txt=${TMPDIR:?}/screenlock.txt

if [[ ! -f $pic ]]; then
  pic=${TMPDIR:?}/screenlock.png
  scrot "$pic"  # Lock with cool bkgd
  mogrify -scale 10% -scale 1000% "$pic"

  # TODO: apply text to user-choosen bkgr, not only to screenshot
  ((!$#)) || cat > "${txt:?}" <<< "$*"
  if [[ -f $txt ]]; then mogrify \
    -pointsize 72 -font DejaVu-Sans -fill Yellow \
    -annotate +200+200 "$(<"$txt")" "$pic"
  fi
fi

# Notifications demon pause/resume
trap "notify-send DUNST_COMMAND_RESUME" HUP INT TERM ERR EXIT
notify-send 'DUNST_COMMAND_PAUSE'

[[ -f $txt ]] || xset dpms force off
i3lock --nofork --color 111111 --image "$pic"

## With this you can hold backlight 3 sec longer
## But then it will not off after wrong passwords!
# xset dpms force on && sleep 3;
# pgrep i3lock >/dev/null && xset dpms force off;
# ALT:
# xscreensaver-command -lock
# xautolock -time 15 -locker '~/.local/bin/fuzzy_lock.sh'
