#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
  pkg_inst qutebrowser
  pkg_inst gst-libav gst-plugins-bad gst-plugins-base gst-plugins-base-libs gst-plugins-good gst-plugins-ugly

elif distro ubuntu; then
    echo "Err: no"
fi
