#!/bin/bash -e
source ~/.shell/func.d/packages

# https://syncthing.net/
# https://github.com/syncthing/syncthing
# https://github.com/syncthing/syncthing/releases/download/v0.11.3/syncthing-linux-amd64-v0.11.3.tar.gz

if distro arch; then
    if cfgOpt u || ! has_pr syncthing; then
        aur_inst 'syncthing'
    fi

elif distro ubuntu; then
    ppa_add 'ppa:ytvwld/syncthing'
    pkg_inst 'syncthing'
fi
