#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### GENS ###
./config.gen

if cfgOpt u; then
    # http://docs.syncthing.net/users/autostart.html#systemd
    svc_enable syncthing@$USER
    svc_enable syncthing-inotify@$USER
    svc_restart syncthing@$USER
fi
