#!/bin/bash -eu
source ~/.shell/func.d/system
distro arch || exit
cwd_origin

# NOTE: create local AUR repo beforehand (ALSO: actualize "bin,ctl" symlinks)
./setup

## Install AUR helper
has_pkgs(){ command pacman -Qq "$@" &>/dev/null; }
has_pkgs devtools || sudo pacman -S --asdeps devtools

KEY=DBE7D3DD8C81D58D0A13D0E76BC26A17B9B7018A \
  r.pacman-aur-helper 'aurutils-git' \
    'https://raw.githubusercontent.com/AladW/aurutils/master/makepkg/PKGBUILD'


pkg_inst pacman pacman-contrib
pkg_inst pkgfile   # grep packages content w/o downloading

# ATT: abs deprecated from 20170515, use asp :: $ asp checkout isync
aur_inst aurutils-git
