#!/bin/bash -e
source ~/.shell/func.d/packages
distro arch || exit

# TRY:ALT: packer (lightweight but less automatable and w/o shell completion)
ayr_inst pacaur
pkg_inst pkgfile  # To investigate packages content w/o downloading
