#!/bin/bash -eu
source ~/.shell/func.d/system
distro arch || exit
cwd_origin

# NOTE: create local AUR repo beforehand (ALSO: actualize "bin,ctl" symlinks)
# DISABLED: call setup explicitly in main Makefile target "configure"
# ./setup -m

## Install AUR helper
has_pkgs(){ command pacman -Qq "$@" &>/dev/null; }
has_pkgs devtools || sudo pacman -S --asdeps devtools

# TRY: https://github.com/cassava/repoctl -- use for removing pkgs
#   recommended by AladW :: https://github.com/AladW/aurutils/issues/208

# FAIL: error on clean install
# MAYBE:BET: install manually according to :/archlinux/doc/layout-2020-05-fractal
KEY=DBE7D3DD8C81D58D0A13D0E76BC26A17B9B7018A \
  r.pacman-aur-helper 'aurutils-git' \
    'https://raw.githubusercontent.com/AladW/aurutils/master/makepkg/PKGBUILD'


# [_] WTF: why reiserfsprogs installed on clean system with aur ?


pkg_inst pacman pacman-contrib
pkg_inst pkgfile   # grep packages content w/o downloading

# ATT: abs deprecated from 20170515, use asp :: $ asp checkout isync
aur_inst aurutils-git
