#!/bin/bash -e
# FIXME: must be installed first on clean system
# tags: core
source ~/.shell/func.d/cfgsetup
distro arch || exit

# OR: $XDG_CONFIG_HOME/pacman/makepkg.conf OR ~/.makepkg.conf
# OR: system-wide export MAKEFLAGS="-j$(expr $(nproc) \+ 1)"
#   http://unix.stackexchange.com/questions/268221/use-multi-threaded-make-by-default
cfg=/etc/makepkg.conf
mf="MAKEFLAGS='-j$(nproc)'"
grep -qxF "$mf" "$cfg" || sudo gawk -i inplace -vmf="$mf" \
  '/^(#\s*)?MAKEFLAGS=/{$0=mf}1' "$cfg"

# Step 4: When you use yaourt an option is given to edit the PKGBUILD.
#   Make sure there is a line in the PKGBUILD which says options=('!makeflags').
#   If it is not there, you will need to add this line, otherwise multi-core
#   compilation will not proceed.

append_repo(){ local nm=$1 at=$2
  local inc="Include = /etc/pacman.d/$nm.conf"
  local cfg=/etc/pacman.conf
  local dcache=/var/cache/pacman
  linkcp -ct /etc/pacman.d -- ./cfg/"$nm".conf
  grep -qxF "$inc" "$cfg" || sudo sed -ri "$at$inc" "$cfg"
  [[ -f $dcache/$nm/$nm.db.tar ]] && return
  sudo install -d "$dcache/$nm" -o "$USER"
  repo-add "$dcache/$nm/$nm.db.tar"
  sudo pacman -Sy
}

# BET?USE:(aurto):
append_repo dev '/^#\[testing\]$/i'
append_repo aur '$a'
