#!/bin/bash -eu
source ~/.shell/profile

skip(){ set -- ${!1:+"${!1}"}; (($#))||return 0
  printf -- '--ignore '; (IFS=,;printf '%s\n' "${*// /\\ }")
}

# HACK: first update GPG keys
# sudo pacman -Syu archlinux-keyring ca-certificates

sudo -v
(while sleep 30; do sudo -v; done || true) & pidsudo=$!
onexit(){ kill -TERM "$pidsudo"; wait "$pidsudo"; }
trap onexit INT ERR

# NOTE: three-stage process to upgrade AUR together with dependencies
# HACK: skip 'exit 1' if update 'n' in pacman
pkgupd(){ sudo pacman -Syu $(skip 'PKG_IGNORE[@]') || ((1==$?)); }
pkgupd
aur sync --database=aur --no-view --no-confirm --upgrades $(skip 'AUR_IGNORE[@]')
pkgupd

if [[ " $* " =~ " -u " || ! -f /var/cache/pkgfile/core.files ]]
then sudo pkgfile --update; fi
