#!/bin/bash -eu

[[ ${1-} != -u ]] && unmount=0 || { unmount=1; shift; }

# ATT: only first entry used
dir=${1-}
[[ $dir ]] || dir=$(showmount -d | sed -n '2{p;q}')
mnt=${2:-/mnt}

if ((unmount)); then
  sudo umount "$mnt"
else
  # WARN:(/etc/hosts) 'hostname' must be bound to subnet ip
  sudo mount "$(hostname):$dir" "$mnt"
fi

showmount -a
mount | tail -5 | column -t
