#!zsh
# vim:ft=zsh
# SEE: /d/research/airy/zsh/prezto/modules/git/alias.zsh

## pacman
alias auri='pikaur --sync --noedit --nodiff'
alias aurq='pikaur --query --info'
alias aurs='pikaur --sync --noedit --nodiff --search'
alias aurx='pikaur --remove --recursive'

alias pacr1='pactree --color --depth 1'
alias pacR1='pactree --color --depth 1 --reverse'
alias pacr='pactree -c'
alias pacR='pactree -cr'

alias pac\?='checkupdates'
alias pacD='sudo pacman -D --asdeps'
alias paci='sudo pacman -S'
alias pacx='sudo pacman -Rsu'

alias pacg='pacman -Sg'
alias pacl='pacman -Ql'
alias pacL='pacman -Qo'
alias pacQ='pacman -Qi'
alias pacq='pacman -Si'
alias pacS='pacman -Qs'
alias pacs='pacman -Ss'
alias pacz='pacman -Qdt'


## apt-get
alias apti='sudo apt-get install'
alias aptu='sudo apt-get update'
alias aptQ='apt-cache show'
alias aptR='apt-cache rdepends'
#   apt-cache rdepends --installed systemd | sort -u
#   apt-cache rdepends --installed libblkid1 | grep -vxF <(dpkg --get-selections | cut -d' ' -f1)
alias aptS='apt-cache search'
alias aptl='dpkg -L'     # [docker-ce-cli]
alias apti='dpkg -l'     # [docker-ce-cli]
alias aptI='apt list --installed'
alias apts='apt search'
alias aptp='apt policy'  # docker-ce-cli
alias aptd='dpkg -S'     # /usr/bin/docker
alias aptD='dpkg -s'     # docker-ce-cli
alias aptG='dpkg --get-selections'


## just.lib
alias j.s='just moni scr | ifne v - -c "setl ft=nou fdl=99 bt=nofile"'
alias ymd3='for i in {01..31}; do print -- $(just xts cvt 2023-08-$i date ymd3) $i; done | column -xc40'
alias ji='just airy install'
alias wks='just tenjo wk'
alias j.j='just tenjo cat --timefmt=h --begdate=d --enddate=0 --outputfmt=j -t'
alias fs='just miur navi'
alias jm='just miur navi'
alias ii='ipython'
alias ij='jupyter console'  # PYDEVD_DISABLE_FILE_VALIDATION=1
alias ijk='ipython kernel -f ipython-kernel.json --IPKernelApp.parent_handle=1'
alias ijc='jupyter console --existing ipython-kernel.json'
alias ijq='jupyter run --existing ipython-kernel.json =(echo quit)'


alias yt='noglob yt-dlp -o "%(title).64s.%(ext)s"'

## utils
dec() { printf "%s\n" $(($*)); }
hex() { printf "0x%lx\n" $(($*)); }
alias readelf='readelf -W'
alias objdump='objdump -w'
alias rscp='rsync -Pavh --stats'
alias rscp.='rscp --dry-run'
alias rsmv='rsync -Pavh --stats --remove-source-files'
alias rsmv.='rsmv --dry-run'
