# PERF:(startup): =100ms= $ for i in {1..10}; do time zsh -i -c exit; done
#   sync=~120ms lazy=15ms WSL2=30m (mostly delayed by git-status)
# PERF:(profiling/beg):
# zmodload zsh/zprof
# 1)   11          47.53     4.32   50.98%     31.23     2.84   33.50%  source  (autopair + zsh_highlight)
# 2)    1          21.46    21.46   23.02%     21.07    21.07   22.60%  (anon) [/home/user/.zshrc:597] (gitstatus_start)
# 3)    1          12.04    12.04   12.91%     12.04    12.04   12.91%  compinit
# 5)    1           8.01     8.01    8.60%      7.81     7.81    8.38%  _zsh_highlight_load_highlighters 4)    2          11.96     5.98   12.83%     11.96     5.98   12.83%  autopair-init
# 6)    1          24.98    24.98   26.80%      3.18     3.18    3.41%  prompt_git_init

if [[ $HOST =~ (MINIPC|VD600) ]]; then
  # TEMP: for WSL2 and NUC
  export EDITOR=nvim

  # FIXED: override PATH to more sane and controllable value
  # OR:CFG: $ echo '. "$HOME/.cargo/env"' >> ~/.zshenv
  export PATH=/b:$HOME/.local/bin:$HOME/.cargo/bin:/usr/local/bin:/usr/bin

  # BET:USAGE: $ sudo systemd-run --system --scope -- su -l myuser -w DISPLAY
  #   ALSO;BAD:OBSOL: export XDG_RUNTIME_DIR="/run/user/$(id -u)"
  # TEMP: for SSH connections to be immediately functional
  [[ -n ${DISPLAY:+x} ]] || export DISPLAY=":10.0"

  ## FAIL: shell-out from ranger should keep $PWD intact
  #   FIXED: do it in ~/.zlogin
  # cd /w

else
  # DFL: /usr/local/bin:/usr/bin:/opt/android-sdk/cmdline-tools/latest/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
  # export PATH=/b:$HOME/.local/bin:$HOME/.cargo/bin:/usr/local/bin:/usr/bin
  export PATH=/b:$HOME/.local/bin:/usr/bin
fi

## TEMP: override for "clipboard"
# OBSOL(due !su whitelist=DISPLAY): [[ -z ${DISPLAY-} && ... ]]
[[ -n ${SSH_CONNECTION+x} && $PATH != */b/xc-ssh:* && -d /b/xc-ssh ]] && PATH=/b/xc-ssh:$PATH

[[ -n $XDG_RUNTIME_DIR ]] && export SSH_AUTH_SOCK=${XDG_RUNTIME_DIR:?}/gnupg/S.gpg-agent.ssh
[[ -n $SSH_CONNECTION ]] && export PINENTRY_USER_DATA='USE_CURSES=1'
# autoload -Uz add-zsh-hook
# function _gpg-agent-update-tty {
#   gpg-connect-agent UPDATESTARTUPTTY /bye >/dev/null
# }
# add-zsh-hook preexec _gpg-agent-update-tty

## Disable suspending on <C-s>, <C-q>
setopt noflowcontrol

## DFL:VIZ: interactive monitor shinstdin zle
setopt pipefail

## Directory
setopt autocd
setopt autopushd
setopt cdablevars
setopt extendedglob
setopt noclobber
setopt pushdignoredups
setopt pushdsilent
setopt pushdtohome
for i ({1..9}) alias "$i"="cd +$i"; unset i


############################################################
### History
# PERF=~20000cmds/year
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
setopt extendedhistory
setopt histexpiredupsfirst
setopt histfindnodups
setopt histignorealldups
setopt histignoredups
setopt histignorespace
setopt histsavenodups
# setopt histverify
setopt incappendhistorytime

# DISABLED: it's more annoying than useful for me
setopt nobanghist


## FIXED: trim trailing newline from confl-triple-click
# SRC: https://unix.stackexchange.com/questions/693118/trim-trailing-newline-from-pasted-text-in-zsh
bracketed-paste() {
  zle .$WIDGET && LBUFFER=${LBUFFER%$'\n'}
}
zle -N bracketed-paste


## NOTE: store audit events from zsh history by days ⌇⡟⢏⠰⣔
# [_] CHECK:FAIL? shells local sessions don't sync immediately anymore -- only after shell was closed
# SEE: INC_APPEND_HISTORY or SHARE_HISTORY
zshaddhistory() { local f
  [[ ${1:0:1} == " " ]] && return 2  # [[ -o hist_ignore_space ]] &&
  print -sr -- ${1%%$'\n'}  # BAD: no dur and "-n" does not help to strip
  print -v f -P -- '%D{%Y/%Y-%m-%d}'
  f=/d/audit/$HOST/zsh/$f
  # BAD:PERF: checks directory existence on each command
  [[ -d $f:h ]] || mkdir -p $f:h
  fc -p $f  # BAD:(no ts/dur): print -rn -- $1 >> $f
}

# HACK:(split): cvt ZSH histfile to audit logs ⌇⡟⢔⣳⡀
#   $ gawk '/^: [0-9]{10}:[0-9];/{f=strftime("%Y/%Y-%m-%d",substr($0,3,10))} {print >> f}' ~/.zsh_history
# HACK:(sync): pre-populate history file on new system from all audit logs of old PC ⌇⡟⢏⠱⣻
# if [[ -n $HISTFILE ]] && [[ ! -f $HISTFILE ]] && [[ -d $_audit[d_log] ]]; then
#   (set +o clobber; <$_audit[d_log]/20??/20??-* > $HISTFILE)
# fi


# FIXED: Save the unfinished editing line when the terminal sends SIGINT on <C-c>.
# `print -s` puts it in the current interactive history list immediately.
TRAPINT() {
  ## ERR:(sometimes) TRAPINT:2: command not found: g
  # zle && [[ -n $BUFFER ]] && print -s -r -- "$BUFFER"
  # return $1
  ## OLD~~ return "1" or don't return anything if no zle
  # if [[ -n "$BUFFER" ]]
  # then zle && print -s -r -- $BUFFER && return $1  # Default
  # else return 1; fi

  ## safe test for "am I in a context where zle exists as a widget-capable function", no side effect, no error.
  if (( ${+builtins[zle]} )) && [[ -n $BUFFER ]]; then
    print -s -r -- "$BUFFER"
  fi
  return $(( 128 + $1 ))
}

## ALT:BUG?
# save-buffer-on-interrupt() {
#   [[ -n $BUFFER ]] && print -s -r -- "$BUFFER"
#   zle kill-whole-line   # or: zle send-break
# }
# zle -N save-buffer-on-interrupt
# bindkey '^C' save-buffer-on-interrupt


############################################################
### Prompt (+30ms due git)
_plugins=/d/plugins/zsh
source $_plugins/zsh-defer/zsh-defer.plugin.zsh

(){ local dcfg=${${(%):-%x}:A:h}
  # source /d/airy/zsh/arc/prompt.d/path
  source $dcfg/prompt_git
  source $dcfg/prompt
  prompt_setup
}

############################################################
### completions (+12ms)

# DEBUG: $ rm -f ~/.zcompdump; compinit
fpath=($_plugins/zsh-completions/src $fpath)

zstyle ':completion::complete:*' use-cache on
zstyle ':completion::complete:*' cache-path ~/.zcompcache
zstyle ':completion:*' completer _expand _complete _files _correct _approximate
# zstyle ':completion:*' completer _complete _match _approximate

## NOTE: completion for "kill nvim<TAB>"
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:*:kill:*:processes' command 'ps xo pid,user:10,cmd |tac| grep -Ev "(ps xo|firefox|/bin/zsh|-zsh|runsv)"'


# IDEA:CHECK: if it works
#   Caveat: this toggles for the next completion invocation, not mid-menu
#     -- no live re-sort of an already-open completion list at the zsh level
toggle-comp-sort() {
  local cur=$(zstyle -L ':completion:*' sort)
  if [[ -z "$cur" ]]; then
    zstyle ':completion:*' sort false
  else
    zstyle -d ':completion:*' sort
  fi
}
zle -N toggle-comp-sort
bindkey '^X^S' toggle-comp-sort


# WARN:(order): should be loaded b4 oth plugins, but *after* fpath and 'zstyle :completion:' options
# WARN:(no zsh-defer): defer breaks live complet for first prompt (zle-line-init/widgets need to be hooked)
#   PERF: +10ms (out of my 9ms)
# WARN:(keymap): overrides ^R, Tab, and up/down-history behavior by default
# source $_plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh

# ATT:(zsh-autocomplete): comment-out my own compinit -- dont run it twice
zsh-defer -c '
  # WARN:USAGE: should run "$ compinit" after editing my own completions!
  # INFO: -C (skip function check) implies -i (skip security check).
  autoload -Uz compinit; compinit -C
'

############################################################
### TEMP (+20ms for all my old cfgs)

function _usercli { local _airy="${${(%):-%x}:A:h:h:h}"  # =${BASH_SOURCE[0]:-...}

  source $_airy/zsh/arc/amer-widgets.zsh

  # TEMP: cdauto paths (OLD-style)
  # TODO:CHG:(cdauto): cd /path/to/somefile(:h)
  source $_airy/sh/alias/cd

  # PERF=+10ms
  while read -r k p; do
    # SEE: https://vincent.bernat.ch/en/blog/2015-zsh-directory-bookmarks
    # USAGE: cd ~.a
    [[ ${k:0:1} == "." && -z ${${k:1}//[a-zA-Z0-9.]} ]] && hash -d -- "${k:1}"="${p#-l }"
    alias "$k"="cdauto $p"
  done < <(sed -r 's/(^|\s+)#.*$//; /^\s*$/d' /d/airy/airy/pathes)
}; zsh-defer -c '_usercli && unset -f _usercli'


# TODO: replace "fm()/zshexit()" by "source =miur/sync-cwd"
fm(){ local d f=${XDG_RUNTIME_DIR:-/tmp}/ranger/cwd
  # NOTE: exit ranger-nested shell && sync last PWD (inof ZSHEXIT)
  [[ -n ${RANGER_LEVEL-} ]] && exit  # && (set +C && pwd > "$f")
  [[ -d ${f%/*} ]] || command mkdir -p "${f%/*}"
  command fm --choosedir="$f" "$@"
  [[ -s $f ]] && d=$(<"$f")
  if [[ -d ${d-} && $d != $PWD ]]; then builtin cd -- "$d" || return; fi
}

# FIXED:(<C-d>): should sync PWD even when exiting on <C-D> inof <,s>
zshexit(){  # _ranger_cwd
  local tmp=${XDG_RUNTIME_DIR:-/tmp}/ranger
  [[ -d $tmp && $RANGER_LEVEL ]] || return 0
  [[ -d $tmp ]] || command mkdir -p "$tmp"
  (set +C && print -n -- "$PWD" > "$tmp/cwd")  # Disable clobbering
}

## FAIL:DISABLED:#1: somehow breaks fzf-tab due to .zwc mismatch
# ALT: zsh-defer -c 'autoload -Uz zrecompile; zrecompile -q $_plugins/**/*.zsh(N) &!'
#   BET? add to /d/plugins/recache or git-hook
# function source {
#   # NOTE: don't compile anything inside /usr/*
#   [[ ! -w ${1:h} ]] || [[ $1.zwc -nt $1 ]] || zcompile $1
#   builtin source $@
# }

## FIXED: don't use !zsh-defer for aliases -- startup is too slow on WSL2,
##   and I may execute first command before they load
local _airy="${${(%):-%x}:A:h:h:h}"
source $_airy/zsh/arc/amer-key-mix.zsh
source $_airy/zsh/arc/alias/aliases  # PERF=5ms
source $_airy/zsh/cfg/aliases_git
source $_airy/zsh/cfg/aliases
source $_airy/ssh/alias

## FAIL:DISABLED:#2: somehow breaks fzf-tab due to .zwc mismatch
# EXPL: we redefine "source()" with recompile only to speed up next startup
#   >> sourcing in interactive session shouldn't create *.zwc everywhere!
#   == and plugins should be recompiled by ./recache after git-pull
# zsh-defer unset -f source


# Expand aliases
function glob-alias {
  zle _expand_alias
  zle expand-word
  zle magic-space
}
zle -N glob-alias
# control-space expands all aliases, including global
bindkey -M viins "^ " glob-alias


# NOTE: remove "/" from default set to prevent deleting whole path at once
WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

## DISABLED: long running
# TIMEFMT='e=%*E u=%U s=%S memsh=%XkB memun=%DkB memmax=%MkB nswap=%W nmajflt=%F nmnrflt=%R nrecv=%r nsent=%s nctxyield=%w nctxforce=%c nm=%J'
TIMEFMT='%mE %P(%mU+%mS) | ram=%D+%XkB,%MkB fault=%F/%R ios=%I/%O/%k ctx=%w/%c'


############################################################
### Plugins (+45ms)

## DISABLED: takes too much time when I mistype command
##   ~~ suggested pkgs are interesting, but I almost never use them,
##     as I have pkgfile and other pac*/aur* cmds
# source /usr/share/doc/pkgfile/command-not-found.zsh

source ${${(%):-%x}:A:h}/fzf-tab-cfg
# FIXED? run 'build-fzf-tab-module' aft sourcing the plugin
#   ERR:(<Tab>): wc: 'J:=__': No such file or directory, wc: ...
#   ? source <(fzf --zsh)
zsh-defer -c '
  # ATT:(redefines): bindkey "^I" fzf-tab-complete
  source "$_plugins/fzf-tab/fzf-tab.plugin.zsh"  # <PERF=7ms
'

zsh-defer source $_plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
## BAD: conflicts with forward-char
# bindkey -M viins "^F" vi-forward-word
bindkey -M viins "^E" vi-add-eol

zsh-defer source $_plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
# source $_plugins/alias-tips/alias-tips.plugin.zsh

zsh-defer -c '
  source $_plugins/zsh-autopair/autopair.zsh
  autopair-init
'

# ATT: should be at the end of ZSHRC
zsh-defer source $_plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


############################################################
# DEP=mcfly NICE: fzf-like Ctrl-R history by frecency/timestamp
# eval "$(mcfly init zsh)"
# eval "$(thefuck --alias '!' --enable-experimental-instant-mode)"
_m=${${:-miur}:c:A:h:h}
[[ $_m == /usr/* ]] && _m="$_m/share/miur"
_m=$_m/integ/miur-shell-sync-cwd.zsh
if [[ -f $_m ]]; then builtin source $_m; fi; unset _m

# HACK: remove pre-printed prompt to replace by actual one
#   WARN: will overwrite whatever you already typed
#     and will keep pieces intact if you <CR> in-between prompts
# print -rn -- $'\e[2F'   # CUP-style: cursor to start of line N-up

# PERF:(profiling/end):
# zprof
