#!/bin/bash -e
source ~/.shell/func.d/packages

#| sxiv  | Image-thumbnail viewer, vim-like, ALT OLD: xzgv
#| exiv2 | Meta-info

# OBSOLETE: not maintained anymore
pkg_inst sxiv exiv2

## FUTURE:
# aur_inst nsxiv  # https://github.com/nsxiv/nsxiv
# aur_inst mage  # https://github.com/explosion-mental/mage

# ALT:BETTER:TRY: pqiv + libspectre poppler imagemagick
# https://github.com/phillipberndt/pqiv/
# ALT: picture-gallery (like FSImageViewer or ACDSee Ultimate)
# https://wiki.gnome.org/Apps/Shotwell
# http://wiki.rosalab.ru/ru/index.php/Shotwell
