#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
    # pkg_inst "base-devel"  # In conflict with multilibs!
    pkg_inst -p 'x86_64-pc-linux-gnu-gcc' gcc-multilib
    pkg_inst -f '/usr/lib32/libstdc++.so' lib32-gcc-libs
    pkg_inst -f '/usr/lib/valgrind/callgrind-amd64-linux' valgrind-multilib
    pkg_inst doxygen # C++
    pkg_inst c2hs clisp   # -pr-lang: haskell, lisp

    # haskell
    # SEE: https://hackage.haskell.org/package/cabalg
    pkg_inst -p 'cabal' cabal-install
    if cfgOpt u || [[ ! -d ~/.cabal/packages ]]
    then cabal update; fi
    # cabal-install ghc-mod
    # cabal install hdevtools

elif distro ubuntu; then
  pkgs=()
  # Those libs also necessary to build x32 under x64 system
  pkgs+=( build-essential gcc-multilib g++-multilib lib32stdc++6 )
  pkgs+=( make checkinstall pkg-config autoconf automake cmake ) #binutils-gold
  #| libc6-dbg:i386 | need to prevent valgrind error with strlen -> strnlen
  pkgs+=( valgrind libc6-dbg:i386 gdb doxygen )  #rabbit valkyrie  <GUI>
  # pkgs=( google-perftools libgoogle-perftools-dev libgoogle-glog-dev google-mock)
  # Cross-compilers
  # pkgs=( gcc-arm-linux-gnueabi) #Or ...-androideabi

  pkg_inst "${pkgs[@]}"
  echo "Err: Not enough packages"
fi
