#!/bin/bash -eu
source ~/.shell/func.d/packages

# VIZ. |community/xdelta3| -- make patch for binary files

pkg_inst patch patchutils
# MAN: http://manpages.ubuntu.com/manpages/zesty/man1/wiggle.1.html
# aur_inst wiggle
