#!/bin/bash -e
# tags: media
# source ~/.shell/func.d/cfgsetup
PATH=/@/airy/airy/bin:$PATH

## Downloaders
# https://github.com/squizduos/ReadMangaDownloaderGUI/releases

### LINKS ###
linkcp -bct ~/.config/mcomix ./keybindings.conf
linkcp -bct ~/.config/mcomix ./preferences.conf
