#!/bin/bash -e
# tags: media
# source ~/.shell/func.d/cfgsetup
PATH=/@/airy/airy/bin:$PATH

## Downloaders
# https://github.com/squizduos/ReadMangaDownloaderGUI/releases

### LINKS ###
# TIP: merge keys by doing:
# jq -S . keybindings.conf | sponge keybindings.conf
# jq -S . preferences.conf | sponge preferences.conf
linkcp -bct ~/.config/mcomix ./keybindings.conf
linkcp -bct ~/.config/mcomix ./preferences.conf
