#!/bin/bash -eu
# tags: net security
source ~/.shell/func.d/cfgsetup

# systemctl enable iptables.service

linkcp -ct /etc -- cfg/nftables.conf

# WARN:(-erR): needs reboot on clean setup ERR: "Netlink socket: Protocol not supported"
svc_activate -eR nftables.service
