#!/bin/bash -eu
# tags: mail
source ~/.shell/func.d/cfgsetup

linkcp -t ~/.config/khal khal/config
# linkcp -t ~/.config/vdirsyncer vdir/config

# systemctl --user enable vdirsyncer.timer
#
# vdirsyncer discover work
# vdirsyncer sync
