#!/bin/bash -e
# tags: net
source ~/.shell/func.d/cfgsetup

if distro arch; then
  # OBSOLETE:(/etc/sysconfig/nfs): for nfs-utils>=v2.1.1 use /etc/nfs.conf
  linkcp -ct /etc nfs.conf
  # BAD: need uncomment section too
  # grep '^vers2=y' /etc/nfs.conf || sudo sed -r '/^[# ]*(vers2=).*/s//\1y/' -i /etc/nfs.conf
  # BAD: nfs-config  -- not found in last versions of nfs-utils
  svc_activate -e$(cfgOpt uU&&echo R) rpcbind rpc-statd nfs-mountd nfs-server

elif distro ubuntu; then
  echo "Err: No NFS config conversion. Works by default?"
  svc_activate -e$(cfgOpt uU&&echo R) nfs-kernel-server
fi
