#!/bin/bash -e
# tags: vcs
# deps: ruby
source ~/.shell/func.d/cfgsetup

### LINKS ###
linkcp -t ~/.config/git cfg ignore attributes

# Customization
# http://git-scm.com/docs/git-config

echo "USE: replace name/email for private repo before push:
  $ r.git-my-repo /path/to/repo"

### GENS ###
dst=~/.config/git/config
> "$dst"
if [[ -n "${WORK_NAME:=${MAIN_NAME-}}" &&
      -n "${WORK_MAIL:=${MAIN_MAIL-}}" ]]; then
    git config --global user.name  "$WORK_NAME"
    git config --global user.email "$WORK_MAIL"
    # git config --global user.signingkey = C8A2DA6E
fi

for f in cfg/*; do
  git config --global --add include.path "$f"
done

echo "W: $dst"
