#!/bin/bash -eu
source ~/.shell/func.d/packages

# ALT:(xdg-open/rifle):
# Log - plumber - Plumber – a modern approach to plumbing ⌇⡠⡏⡅⢸
#   http://r-36.net/scm/plumber/log.html
#
# chmln/handlr: A better xdg-utils ⌇⡠⡏⡐⢋
#   https://github.com/chmln/handlr
# mimeo ⌇⡠⡏⡐⢙
#   https://xyne.archlinux.ca/projects/mimeo/

pkg_inst xdg-user-dirs
