#!/bin/bash -e
# tags: xorg
source ~/.shell/func.d/cfgsetup

# SEE http://unix.stackexchange.com/questions/36380/how-to-properly-and-easy-configure-xdg-open-without-any-enviroment

### LINKS ###
linkcp -t ~/.local/share/applications defaults.list
