#!/bin/bash -eu
# tags: xorg
source ~/.shell/func.d/cfgsetup

### LINKS ###

# BUG:REQ: using any xdg-set command overwrites symlink in ~/.config/ by real file
#
# MAYBE:(old): must be symlinked into two locations
#   https://bugs.freedesktop.org/show_bug.cgi?id=98562
[[ ! -L ~/.config/mimeapps.list ]] \
  && [[ -f ~/.config/mimeapps.list ]] \
  && diff -q ~/.config/mimeapps.list mimeapps.list &>/dev/null \
  && rm ~/.config/mimeapps.list
linkcp -ct ~/.config -- mimeapps.list
# linkcp -t ~/.local/share/applications -- mimeapps.list


# TODO: override from private -- if existing
# WARN: don't use 'xdg-user-dirs-update' -- it's irritating
# BAD:(xdg-user-dirs-update): replaces symlink by file
#   CHG: must be generated :: embed by cmd AIRY_BIN => user-dirs
#   /usr/lib/systemd/user/xdg-user-dirs-update.service
# BET: enable=False in config
linkcp -t ~/.config cfg/user-dirs.{dirs,conf,locale}

# BAD:DEV: r.airy-xdg
#   * I need to show error or fallback to /var/error on nonexistent dir instead of fallback to home
#   * use AIRY_ vars w/o XDG_ prefix
#   * NEED: user-dirs.dirs for Firefox, etc
