#!/bin/bash -e
case "$1"
in -t) dir=$2; shift 2
;;  *) dir=/home/media/amv
esac

path=${1?}

# WARNING: we can move only already donwloaded files!
# -- THINK: make queuing operations, waiting for close_write event from tmux?
[[ -f $path ]] \
  && exec r.dmenu-move -n 'AMV:' "$dir" "$path" \
  || exit
