#!/usr/bin/perl -w
# http://karma-lab.net/creer-plugin-urxvt-sauvegarder-vim-automatiquement
# ENABLE:  echo -ne "\033]777;focus;on\007"
# DISABLE: echo -ne "\033]777;focus;off\007"
# VIM: -- add appropriate snippet with checking only to urxvt!

# my $csi_in = "\033[UlFocusIn";
# my $csi_out = "\033[UlFocusOut";
my $csi_in = "\033[I";
my $csi_out = "\033[O";

sub on_start {
    my($self) = @_;
    $self->{focus_activated} = 0;
}

sub on_osc_seq_perl {
    my ($self, $osc, $resp) = @_;
    # Catching urxvt control group "OSC 777 xxx BEL"
    return unless $osc =~ s/^focus;//;
    $self->{focus_activated} = $osc eq 'on' ? 1 : 0;
}

sub on_focus_in {
    my($self) = @_;
    if ($self->{focus_activated}) {
        $self->tt_write($csi_in);
    }
}

sub on_focus_out {
    my($self) = @_;
    if ($self->{focus_activated}) {
        $self->tt_write($csi_out);
    }
}
