#!/bin/bash -e
cd $(dirname $(readlink -m ${0}))/lib

OPTS=(dmenu -p 'Play me:' -fn monospace:size=10
     -nb '#000000' -nf '#b0e0e6' -sb '#227410' -sf '#ccaa00')

case "$1" in -p) shift
  game=$(ls | "${OPTS[@]}")
;; *) game=$1 ;; esac

[[ -f $game ]] || { r.n 'No such' "$game"; exit 1; }
ON_EXIT=('r.video-single 1')

if r.xkb-has-overlay "$game"; then
  r.xkb "$game" && xkbset ov1
  ON_EXIT+=('xkbset -ov1' 'r.xkb')
fi

r.wm -w g  # Jump to game workspace

# CHECK: called only one trap or sometimes multiple of them?
trap 'for c in "${ON_EXIT[@]}"; do $c; done' HUP INT QUIT ILL TRAP KILL BUS TERM EXIT ERR

./"$game"
