#!/bin/bash -e
source ~/.shell/func.d/packages

#| scrot | screenshoter
pkg_inst scrot

# SRC: https://github.com/flameshot-org/flameshot
# CFG: https://wiki.archlinux.org/title/Flameshot#Troubleshooting
# TUT: https://ubunlog.com/en/flameshot-una-excelente-herramienta-para-capturar-y-editar-screenshots/
pkg_inst flameshot
