#!/bin/sh

#LG=$(setxkbmap -query | awk '/layout/{print toupper($2)}')
LG=$(xkb-switch -p | sed 's/am(\(.*\))\|\(\w\+\)/\U\1\2/')

case "${LG}" in
    US) color="#00AE00" ;;
    RU) color="#00AEFF" ;;
    UA) color="#FFFF00" ;;
     *) color="#C60101" ;;
esac

change() { #nex_layout, prev_layout
    dbus-send --dest=ru.gentoo.KbddService /ru/gentoo/KbddService ru.gentoo.kbdd.set_layout uint32:$1
    ~/.i3/scripts/update 2
}

case $BLOCK_BUTTON in
    1) change 0 ;;
    3) change 1 ;;
    *) ;;
esac

printf "%s\n%s\n%s\n" "$LG" "$LG" "$color"
