#!/bin/sh

#LG=$(setxkbmap -query | awk '/layout/{print toupper($2)}')
LG=$(xkb-switch -p | sed 's/am(\(.*\))\|\(\w\+\)/\U\1\2/')
#LG="$LG"
case "${LG}" in
    US) dat="#00AE00" ;;
    RU) dat="#00AEFF" ;;
    UA) dat="#FFFF00" ;;
     *) dat="#C60101"
esac

printf "%s\n%s\n%s\n" "$LG" "$LG" "$dat"
