#!/bin/bash
#%SUMMARY: print list of headers-in-use
#%USAGE: $ ./$0 /path/to/pj/cmpt/src
set -euo pipefail
exec grep -ornHP '^#include\s+\K.*[">](?=.*)' "$@" \
| awk -F: '{print$3,$1":"$2}' \
| sort -u -k1,1
