#!/bin/bash -e
source ~/.shell/func.d/packages

# | urxvt | fast terminal, image support, perl extensions

if distro arch; then
    aur_inst 'rxvt-unicode-patched' || pkg_inst 'rxvt-unicode'

elif distro ubuntu; then
    pkg_inst 'rxvt-unicode-256color'

    mkdef() { update-alternatives --get-selections | grep -q "^$1.*$2\$" ||
        sudo update-alternatives --set $1 "$2"; }
    mkdef x-terminal-emulator $(which urxvt)
fi
