#!/bin/bash -e
source ~/.shell/func.d/packages

# | urxvt | fast terminal, image support, perl extensions

if distro arch; then
    aur_inst -p urxvt 'rxvt-unicode-patched' || pkg_inst -p urxvt 'rxvt-unicode'

elif distro ubuntu; then
    pkg_inst -p urxvt 'rxvt-unicode-256color'

    mkdef x-terminal-emulator $(which urxvt)
fi
