#!/usr/bin/env bash
#%SUMMARY: count visited links -- yesterday from 18:30 to 22:30
set -euo pipefail

db=${XDG_DATA_HOME:-~/.local/share}/qutebrowser/history.sqlite
ts=$(date +%s -d 'today - 24 hours + 6 hours')

exec sqlite3 "$db" \
  "SELECT count(*) FROM History WHERE atime > $ts AND url NOT LIKE '%soundcloud%'"
