#!/bin/bash
#%SUMMARY: separate windows and NSS chain for qutebrowser proxy
#   https://www.reddit.com/r/qutebrowser/comments/677nsh/keeping_windows_separate/
#%USAGE: $ r.qute-new [~/qute-session-1]
#%REF: https://github.com/ayekat/dotfiles/blob/master/bin/qutebrowser
set -euo pipefail

basedir=$1
shift

linkcp -t "$basedir"/config -f ~/.config/qutebrowser \
  bookmarks quickmarks theme \
  config.py config-private.py style.css

linkcp -t "$basedir"/data -f ~/.local/share/qutebrowser \
  greasemonkey userscripts

linkcp -t "$basedir" -- ~/.password-store ~/.gnupg
linkcp -t "$basedir/.config" -- ~/.config/mimeapps.list

# HACK: use different NSS/PKI chain to override root cert from ~/.pki/nssdb/
#   <= according to ~/sdk/nss-3.46/nss/lib/sysinit/nsssysinit.c: getUserDB()
export HOME="$basedir"
export XDG_DATA_HOME="$basedir/share"

exec qutebrowser --basedir "$basedir" "$@"
