#!/bin/bash
#%SUMMARY: separate windows
#   https://www.reddit.com/r/qutebrowser/comments/677nsh/keeping_windows_separate/
#%USAGE: $ r.qute-new [~/qute-session-1]
set -euo pipefail

basedir=$1
shift

linkcp -t "$basedir"/config -f ~/.config/qutebrowser \
  bookmarks config.py config-private.py quickmarks style.css

export QT_AUTO_SCREEN_SCALE_FACTOR=1  # HiDpi for Qt>=5.6

exec qutebrowser --basedir "$basedir" "$@"
