#!/bin/bash
set -euo pipefail

# ALT: --temp-basedir
basedir=$(mktemp -dt "qute@${0##*/}~XXXX")
onexit(){ rm -rf "$basedir"; }
trap 'onexit' INT HUP QUIT TERM ERR


swd=$(dirname "$(realpath "$0")")

"$swd/new" "$basedir" "$@" \
  --set content.proxy "socks://[::1]:17321" \
  --set content.proxy_dns_requests true
