#!/bin/sh
#%USAGE: from flashdrive $ sh smaps-dump prg1 [prg2...]
set -eu

pfx=/data/
sfx=-$(date +%Y%m%d_%H%M%S).smaps

for nm in "${@:?}"; do
  cat /proc/$(pidof "$nm")/smaps > "${pfx}${nm}${sfx}"
done
