#!/bin/sh
#%FORMAT:(out): [ts %cpu mem]
#%USAGE: $ ./$0 processname
#%LICENSE: MIT, (c) amerlyq, 2019
set -eu

pid=$(pidof "$1")

awk '$1=="MemTotal:"{print;exit}' /proc/meminfo

pticks=$(awk '{for(i=2;i<NF;++i)t+=$(i);print t;exit}' /proc/stat)
pcpu=$(awk '{print$14+$15}' "/proc/$pid/stat")

while usleep 100000; do
  ts=$(awk '3==NR{print$3;exit}' /proc/timer_list)
  ticks=$(awk '{for(i=2;i<NF;++i)t+=$(i);print t;exit}' /proc/stat)
  cpu=$(awk '{print$14+$15}' "/proc/$pid/stat")
  pss=$(awk '$1=="Pss:"{m+=$2}END{print m}' "/proc/$pid/smaps")
  awk "BEGIN{printf\"%.3f %.2f %.2f\\n\", $ts/1000000000, 100*($cpu-$pcpu)/($ticks-$pticks), $pss/1024}"
  pticks="$ticks"
  pcpu="$cpu"
done > /data/sys.perf
