#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
  # aur_inst gcalcli
  # BAD:(gcalcli-git): OAuth2 don't start automatically
  # BAD:(gcalcli-git): can't add events beside 'Quick'
  # aur_inst -p gcalcli{,-git}

  loc_inst -p 'gcalcli' ./PKGBUILD  # v4.0a2

  aur_inst -Y {,python2-}vobject
  pkg_inst -Y {,python2-}parsedatetime

elif distro ubuntu; then
  echo "Err: fix use pip2"
fi
