#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
  # aur_inst gcalcli
  # BAD:(gcalcli-git): OAuth2 don't start automatically
  # BAD:(gcalcli-git): can't add events beside 'Quick'
  # aur_inst -p gcalcli{,-git}

  pkg=gcalcli-git
  dst=$(dcache "pacaur/$pkg")/PKGBUILD
  if cfgOpt u || [[ ! -f $dst ]]; then  # v4.0a2
    linkcp -c ./PKGBUILD "$dst"
    (cd "${dst%/*}" && updpkgsums && makepkg -sf &&
      paccache -d "$pkg" && sudo pacman -U --noconfirm "$pkg"-*.xz)
  fi

  aur_inst -Y {,python2-}vobject
  pkg_inst -Y {,python2-}parsedatetime

elif distro ubuntu; then
  echo "Err: fix use pip2"
fi
