#!/bin/bash -e
cd $(dirname $(readlink -m ${0}))

game=$1

if r.xkb-has-overlay "$1"; then
  r.xkb "$1"
  # CHECK: called only one trap or sometimes multiple of them?
  trap 'r.xkb' HUP INT QUIT ILL TRAP KILL BUS TERM EXIT ERR
fi

./prf/"$1"
