#!/bin/bash -eu
# WARN: for timestamping you need non-regex name w/o spaces: $a = \S+

mod=${PWD##*/}
from='alias'  # NOTE: either file or dir
output=''  # ${TMPDIR:-/tmp}/airy-cache-alias

header='# vim:ft=sh'
begfmt='_alias_cat(){ : # %s'
endfmt='}; _alias_cat'

# q=quiet, r=reset (always replace)
opts=; while getopts 'f:g:m:o:qr' o; do case $o in :|'?') exit 1
;; m) mod=$OPTARG
;; g) group=$OPTARG
;; f) from=$(readlink -e "$OPTARG")
;; o) output=$(readlink -f "$OPTARG")
esac; opts+=$o; done; shift $((OPTIND - 1))
log(){ [[ $opts =~ q ]] || printf '%s\n' "$@"; }

# BAD: can't update, append only. After removing appended -- deletes rest of file
section_recache(){ local f s id b e t tt timestamp=1
  [[ $1 == -r ]] && { timestamp=0; shift; }
  f=$1
  s=$(readlink -e "$2")
  id=${group:+${group}_}$mod/${s##*/}
  b=$(printf "$begfmt" "$id")
  e=$(printf "$endfmt" "$id")
  t=$(command stat -c%Y "$s")
  if ((timestamp)); then
    tt=$(sed -n "\|^$b\s*\([0-9]\{10\}\)\$|{s//\1/p;q}" "$f")
    (( t == tt )) && log "* A: $id" && return
  fi
  if grep -q "$b\b" "$f"; then sed -i "
    \|^$b|,\|^$e$| {
      \|^$b|{
        i $b $t\n# $s
        r $s
      }; \|^$e$|b; d
    }" "$f"
  else
    printf '\n\n%s\n# %s\n%s\n%s\n' "$b $t" "$s" "$(<"$s")" "$e" >> "$f"
  fi
  log "+! A: $id"
}

[[ -n $output ]] || output=$(r.airy-get-cache)/cfg/aliases
[[ -s $output ]] || (set +C; printf '%s\n' "$header" > "$output")
[[ -d $from ]] && from=$(find "$from" -type f ! -name tags -print)

while IFS= read -r f; do
  [[ -s $f ]] || continue
  section_recache $([[ $opts =~ r ]] && printf -r) "$output" "$f"
done <<< "$from"
