#!/bin/bash -eu
shopt -s nullglob

while getopts 'qt:p:' o; do case $o in :|'?') exit 1
;; t) bin=$(readlink -m "$OPTARG")
;; p) prf=$OPTARG
;; q) quiet=1
esac; done; shift $((OPTIND - 1))

[[ ${bin-} ]] || bin=$(r.airy-get-cache)/bin
[[ ${prf-} ]] || prf='r.%d-'
prf=${prf//%d/${PWD##*/}}


bins(){ local i a=()
  for((i=1;i<=$#;++i)); do [[ ${!i} == -- ]] && break; done
  for f in "${@:i+1}"; do [[ -f $f && -s $f && -x $f ]] && a+=("$f"); done
  linkcp ${quiet:+-q} -t "$bin" "${@:1:i-1}" -- "${a[@]}"
}

# ALT: bins(){
#   lst=$(find . -maxdepth 1 -type f -name 'run*' -not -empty -executable -print0)
#   a=(); while IFS= read -rd $'\0'; do a+=("$REPLY"); done <<< "$lst"; }


bins -- ./bin/*  # bin/* -> bin/*
bins -p "${prf}" -- ./ctl/*  # ctl/* -> bin/r.%d-*
bins -p "${prf%-}" -s 'run/' -- ./run*  # run* -> bin/r.%d*


# BAD:(frail dep): used explicit dst dir
# BAD:(frail dep): explicit name for dst bin
# BAD: builds only binaries, can't distinguish libs
srcs(){ local nm d=~/.cache/airy/build/bin
  for p in "$@"; do
    [[ -f $p && -s $p && ! -x $p ]] || continue
    r.airy-compile-src -ft "$d" -- "$p"
    nm=${p##*/}; nm=${nm%.*}
    bins -p "${prf}" -- "$d/$nm"
  done
}
srcs ./src/*  # src/* -> $cache/build/* -> bin/r.%d-*
