#!/bin/bash -eu
cache=${1:-$(r.airy-get-cache)}
cd "$cache" || exit 0

rmdc(){ find "$1" -xdev -depth -mindepth 1 -delete; }

echo "N: clean mods cache"
rm -f "$cache/mods" /tmp/airy-cache-mods  # REM:HACK: hardcoded queue

echo "N: clean tags"
r.airy-link-tags -t "$cache/tags" -d

# BAD: when deleting all together -- must run whole setup for other cleared areas
#   NEED: clean only systemd ==> link only systemd
echo "N: clean systemd user units"
rmdc ~/.config/systemd/user

echo "N: clean aliases cache"
rm -f "$cache/cfg/aliases"

## WARN! finally remove symlinks, as all next r.* calls become invalid
# BAD: if symlinks will be always deleted, r.xorg will be never used in core/xorg
echo "N: clean r.* symlinks"
rmdc "$cache/bin"
