#!/bin/bash -eu

mods=( "$PWD" )

# RFC: more logical flags
opts=; while getopts 'maiIsSuUrR' o; do case $o in :|'?') exit 1
# ;; t) dst=$(readlink -m "$OPTARG")
# ;; f) readarray -t mods < "$OPTARG"  # WARN: empty/misconfigured lines
esac; opts+=$o; done; shift $((OPTIND - 1))
((!$#)) || mods=( "$@" )

# TODO: boolean ops for flags \s = or atom, \w = and (in any order)
has(){ [[ $opts =~ [$*] ]]; }

# EXPL: -m (in main 'setup') forces single thread execution
run(){ if [[ -f $1 ]]; then "$@" $(has m || echo -m); else echo "(no ${1##*/})"; fi; }

for m in "${mods[@]}"; do
  echo ">>> $m <<<"
  # BUG: some packages (like gcc-multilib) aren't replaced even with -u)
  if has iIa; then run "$m/install" $(has Ia && echo -u); fi
  if has sSa; then run "$m/setup"   $(has Sa && echo -u); fi
  if has uUa; then run "$m/update"  $(has Ua && echo -u); fi
  if has rRa; then run "$m/recache" $(has Ra && echo -u); fi
done
