#!/usr/bin/env bash
#%VIEW: $ <"${TMPDIR:-/tmp}/airy.log" r.airy-pretty | less -r
#%
set -euo pipefail

log=${XDG_CACHE_HOME:-$HOME/.cache}/airy/log/$(date +'%Y%m%d_%H%M%S').log
# log=${XDG_CACHE_HOME:-$HOME/.cache}/airy/airy.log
# log=${TMPDIR:-/tmp}/airy.log

mkdir -p "${log%/*}"

[[ -t 1 ]] && exec > >(r.airy-pretty)

make "$@" | stdbuf -oL -eL tee -a "$log"
