#!/usr/bin/env bash
#%SUMMARY: list of available mods/paths sorted in overlay order
set -euo pipefail

# THINK: how to be with overlapping of trivial names i.a. local to repo

reversed=
sortkeys='%f/%f'

# TODO: sort by guesstimate install time
#   => HACK: store this time inside first line of stampfiles and sum them by mods
#   => difference {total - allmods} show instrumental time of "airy" scripts
# i.e. if (guess && 0<(getline duration < $0)) { printf strtonum(duration); close($0) }
sortbyguesstimate=

while getopts 'd:pr' o; do case $o in :|'?') exit 1
;; d) sortkeys="%f/%f$OPTARG%p"   #% d:= print both name and path separated by delimiter
;; p) sortkeys='%f/%p'            #% p = print mod path instead of name
;; r) reversed=1                  #% r = search overlays in reversed order
;; S) sortbyguesstimate=1
esac; done; shift $((OPTIND - 1))
repos=$(r.airy-mods-repos ${reversed:+-r} "$@")
readarray -t repos <<< "$repos"

# NOTE: sort in overlay order by mod name
find -H "${repos[@]}" -mindepth 1 -maxdepth 1 \
  -type d -not -name '[_.]*' -printf "$sortkeys\n" \
| LC_ALL=C sort -st/ -k1,1 \
| cut -d/ -f2- \
| uniq
