#!/usr/bin/env bash
set -euo pipefail

# TODO: sort by guesstimate install time
#   => HACK: store this time inside stampfiles and sum them by mods
sorted=1

while getopts '' o; do case $o in :|'?') exit 1
;; S) sorted=
esac; done; shift $((OPTIND - 1))

if (($#)); then
  paths=("$@")
elif [[ ! -t 0 ]]; then
  readarray -t paths
else
  tmp=$(r.airy-overlay -Q)
  readarray -t paths <<< "$tmp"
fi

find -H "${paths[@]}" -mindepth 1 -maxdepth 1 \
  -type d -not -name '[_.]*' -printf '%f\n' \
| LC_ALL=C sort -u
