#!/usr/bin/env bash
source ~/.shell/profile
set -euo pipefail

# NOTE: always necessary and installed first
mod_base=( airy pacman )

paths=$(cfg-overlay -Q -b "${AIRY_OVERLAY_BASE-}" -o "${AIRY_OVERLAY_PATH-}")
readarray -t paths <<< "$paths"

mod_deps=$(find -H "${paths[@]}" \
  -mindepth 2 -maxdepth 2 -type f -name 'setup' -print0 \
| xargs -0 grep -PHo '^#+\s*deps:\s*\K[^#]+' \
| awk -F/ '{split(substr($NF,index($NF,":")+1),a," "); for(i in a)print a[i],$(NF-1)}' \
| tsort \
| grep -vxFf <(printf '%s\n' "${mod_base[@]}") \
)

mod_rest=$(find -H "${paths[@]}" \
  -mindepth 1 -maxdepth 1 -type d -not -name '[_.]*' -printf '%f\n' \
| LC_ALL=C sort -u \
| grep -vxFf <(printf '%s\n' "${mod_base[@]}" "${mod_deps[@]}") \
)

# TODO: also sort by guessed size
printf '%s\n' "${mod_base[@]}" "${mod_deps[@]}" "${mod_rest[@]}"
