#!/usr/bin/env bash
#%SUMMARY: resolve {modlist + subpaths} to full paths inside of overlay
#%USAGE: $ r.airy-mods-all | ./$0 'setup'
source ~/.shell/profile
set -euo pipefail

# THINK:(option): grouping order -- all subpaths for each dir or single subpath for all dirs ?
# MAYBE: searching for all subpaths first and filtering+sorting afterwards is more efficient ?

for((i=1;i<=$#;++i)); do [[ ${!i} == -- ]] && break; done
subpaths=( "${@:1:i-1}" )
modlist=( "${@:i+1}" )

existing_subpaths(){
  while IFS= read -r d; do
    for f in "${subpaths[@]}"; do
      [[ -e $d/$f ]] && printf '%s\n' "$d/$f"
    done
  done
  return 0
}

(( ${#subpaths[@]} )) && exec > >(existing_subpaths)

exec r.airy-overlay -M+ -- "${modlist[@]}"
