#!/usr/bin/env bash
source ~/.shell/profile
set -euo pipefail

# THINK: grouping order -- all subpaths for each dir or single subpath for all dirs ?
subpaths=( "$@" )

# MAYBE: searching for all subpaths first and filtering+sorting afterwards is more efficient ?
r.airy-mods-req-sorted \
| cfg-overlay -M+ -b "${AIRY_OVERLAY_BASE-}" -o "${AIRY_OVERLAY_PATH-}" \
| if ((!${#subpaths[@]})); then cat; else
  while IFS= read -r d; do
    for f in "${subpaths[@]}"; do
      [[ -e $d/$f ]] && printf '%s\n' "$d/$f"
    done
  done
fi
exit 0
