#!/usr/bin/env bash
#%SUMMARY: print topologically ordered deps or their graph
set -euo pipefail

# [_] DEV: allow local subpaths i.a. dot self-refs "#deps: ./setup"
# [_] DEV: allow very first/last specifiers e.g. "#deps: 0 $"
#   => still they will be after global "first" and before "last" of "./mods-ordered"
#   => NEED: separate script to sort in groups {beg,body,end}

graph=

while getopts 'g' o; do case $o in :|'?') exit 1
;; g) graph=1
esac; done; shift $((OPTIND - 1))

# ALT:(tsort): https://sourceforge.net/projects/dep-trace/
r.airy-mods-modelines -K deps -p: -- "$@" \
| awk -F: '{split($NF,a," "); for(k in a)print a[k],$1}' \
| if ((graph)); then cat; else tsort; fi
