#!/usr/bin/env bash
set -euo pipefail

declare -a tags
declare -A flags

opts=; while getopts 'maAiIsSuUrR' o; do case $o in :|'?') exit 1
esac; opts+=$o; done; shift $((OPTIND - 1))
has(){ [[ $opts =~ [$*] ]]; }

has m && flg=m || flg=

# BUG: some packages (like gcc-multilib) aren't replaced even with -u) due to pacman defaults to [y/N] in --noconfirm
#   => TRY: disable "--noconfirm"
# FIXME: adds "$flg" only together with "-u" :: must be separate
if has iIaA; then tags+=(install) ; has IA && flags[install]="-u$flg" ; fi
if has sSaA; then tags+=(setup)   ; has SA && flags[setup]="-u$flg"   ; fi
if has uUaA; then tags+=(update)  ; has UA && flags[update]="-u$flg"  ; fi
if has rRaA; then tags+=(recache) ; has RA && flags[recache]="-u$flg" ; fi

[[ -n ${tags[*]:+x} ]] || { echo "Err: option not specified" >&2; exit 1; }

[[ -t 1 ]] && exec > >(r.airy-pretty)  # colorize

# MAYBE: use parallel
r.airy-mods-required \
| r.airy-mods-subpaths "${tags[@]}" \
| while IFS= read -r f; do
  echo ">>> $f <<<"
  "$f" "${flags[${f##*/}]-}"
done
