#!/bin/bash -eu
# REF:(groups list): https://www.archlinux.org/groups/

db=~/.cache/airy/install-pkgs.txt
dsrc=${TMPDIR:?}/airy

# NOTE: generate active db w/o actual cmds execution
[[ -d $dsrc ]] || airyctl -- all/install flags=-m

# NOTE: filter-out pre-installed deps and pacstrap:
#   ?: sudo grub os-prober ntp lvm2 polkit
sort - "$dsrc"/*.list > "$db" <<'EOT'
base
base-devel
EOT

# FIXME: $ comm -23 <(pacman -Qqett | sort) <(pacman -Qqg base -g base-devel | sort | uniq)
#   USE:(-Qqe): to include explicit packages which are also deps to others
## DISABLED: "base" is not a group anymore -- it's an empty package with deps
{ cat -- "$dsrc"/*.list
  pacman -Qqg base-devel
} | sort -u > "$db"

# pacman -Qei | awk '
#   /^Name\s/{n=$3}
#   /^Groups\s/{print($3=="None"?n:n" "$3)}
# ' | grep -vwFf "$db"

pacman -Qqe | grep -vwFf "$db"
