#!/usr/bin/env bash
set -euo pipefail
source ~/.shell/profile

[[ -x ./setup || -x ./install ]] || exit 3
mod=${PWD##*/}

exec cfg-overlay -M~ -s "$mod/{}" \
  -b "${AIRY_OVERLAY_BASE-}" \
  -o "${AIRY_OVERLAY_PATH:?}" \
  -- "$@"
