#!/bin/bash -eu

hruler=$(printf -- '-%.0s' $(seq 1 "$(tput cols)"))
# HACK: remove last char visible in less(1) as "^O"
CR=$(tput sgr0 | rev | cut -c 2- | rev)
CB=$(tput bold)
for n in {0..15}; do
  readonly C$n="$(tput setaf "$n")"
done

exec sed -u -r "
  s|$HOME|\~|g
  />>>|\{\{\{|^--.+--$/!s|^|  |
  /^\{\{\{ .* \}\}\}$/s//\n$C15\0$CR/
  /^--(.+)--$/s//$C15$hruler\r---\1$CR/

  /^>>> .* <<<$/ {
    s|^>>> \~/.local/airy/([[:alnum:]_-]+\s)|\n$C2\[\1|
    s|^>>> \~/.local/airy/|\n$C13\[|
    s|^>>> |\n$C9\[|
    s| <<<$|\]$CR|
  }

  /^\s\s\(.*\)$/s//$C10&$CR/
  /\b(C|W|Fix):\s.*/s//$C13&$CR/
  /\b(I|N):\s.*/s//$C6&$CR/
  /(\+!|\*) A:\s.*/s//$C3&$CR/
  /.*\s(-> L\s|(::\/|\*\s).*->).*/s//$C4&$CR/
  /\(%\)  .*/s//$C2&$CR/
  /~\/\.config\/systemd\/user\//s///g
  /^(\s*)Created symlink (from )?(.*) (to|→) (.*)\.$/s//\1@@-\3 -> \5/
  /^\s*(-> @\s|@@-.*\s->\s).*/s//$C9&$CR/
  /.*\s-> C\s.*/s//$C3&$CR/
  /\b(E|Err|Wrn|ERR):\s.*/s//$CB$C1&$CR/
" "$@"
