#!/bin/bash -eu
# NOTE: reserve word 'agenda' for todo mapped on calendar
# TODO: sort desc by priority (i.e. anything between path and [_])
set -o pipefail
cd ~/aura
# ATT:NEED: ./.ignore
exec ag --vimgrep \
  -G '.*/.[^/]+\.nou$' "$@" \
  '^\s*!+[0-9]+\s\[_\]\s' \
| sort -t: -k4,4 \
| $EDITOR - -c 'setl ft=nou bt=nofile bh=wipe|cgetb|copen|only|%s/\v^%([^|]+\|){2}\s+//|setl nomod noma ft=nou|norm!gg'
# ALT: Tabularize /\|/ instead of '%s/^\S\{-}:\s\+//'
# exec grep -r --exclude-dir='_build' "$@" \

# RFC: construct more long -c '...'
# eopt=( ... )
# ecmd=$(IFS=$'|';printf '%s\n' "${eopt[*]// /\\ }")
