#!/bin/bash -eu
# NOTE: reserve word 'agenda' for todo mapped on calendar
set -o pipefail
cd ~/aura
# ATT:NEED: ./.ignore
exec ag --vimgrep \
  -G '.*/.[^/]+\.nou$' "$@" \
  '^\s*!+[0-9]+\s\[_\]\s' \
| $EDITOR - -c 'setl bt=nofile bh=wipe|cgetb|copen|only|%s/\v^%([^|]+\|){2}\s+//|set ft=nou'
# ALT: Tabularize /\|/ instead of '%s/^\S\{-}:\s\+//'
# exec grep -r --exclude-dir='_build' "$@" \
