#!/usr/bin/env bash
# On Host linux
#   ssh-keygen -N "" -f ~/.ssh/arch
#   cat ~/.ssh/arch.pub >> ~/.ssh/authorized_keys
# From within Arch vbox:
#   scp user@local.ip:~/.ssh/arch  ~/.ssh/arch
#   scp -i ~/.ssh/arch user@local.ip:~/aura/airy/arch-install .

if [ "$(uname -n)" != "archiso" ]; then
    echo "Use this script only under archiso image!"
    exit 1
fi


sd=/dev/sda
nd=(boot root swap home)
for nm in "${nd[@]}"; do ((++i)); declare n_${nm}=$i s_${nm}=$sd$i; done

layout="
    /boot ext4       100MB
    /     ext4       8GB
    *     linux-swap 10GB
    /home ext4       100%
"

if [ "$1" == --force ]; then
    swapoff -a
    umount -fR /mnt

    ## Partitioning
    gawk -v sd="$sd" '
    BEGIN { pp="parted -s -a opt "sd; ps="1MB"; N=0
        print pp,"mklabel msdos && lsblk",sd,"&& echo"
    } /\S/ {
        a[$1]=sd""(++N); t[$1]=$2
        print pp,"mkpart primary",$2,ps,$3
        ps=$3
    } END {
        print pp,"set 1 boot on"
        PROCINFO["sorted_in"]="@ind_str_asc"
        for(m in a) {
            if(m == "*") { print "mkswap",a[m],"&& swapon",a[m] }
            else { print "mkfs."t[m],a[m],"&& mkdir -p /mnt"m,"&& mount",a[m],"/mnt"m }
        }
    }' <<< "$layout" | bash
fi

## Layout
# parted -l
lsblk $sd

## Select a mirror
pm=/etc/pacman.d/mirrorlist
pmt=/tmp/mrlst
cat - <<-'EOT' > $pmt
#%BEGIN Prepended during install
## Score: 0.7, Ukraine
Server = http://archlinux.bln-ua.net/$repo/os/$arch
## Score: 25.8, Ukraine
Server = http://mirrors.nix.org.ua/linux/archlinux/$repo/os/$arch
#%END
EOT
sed '/#%BEGIN/,/#%END/d' $pm >> $pmt
mv -vf $pmt $pm


if [ "$1" == --force ]; then
    ## Install the base system  # -i -- interactive
    pacstrap /mnt base base-devel
fi

fs=/mnt/etc/fstab
sed -i '4q' $fs && genfstab -U -p /mnt >> $fs && less $fs

# Chroot
arch-chroot /mnt /bin/bash
