#!/usr/bin/env bash
# From within Arch VBox:
#   scp user@local.ip:~/aura/airy/arch-install .

# if [ "$(uname -n)" != "archiso" ]; then
#     echo "Use this script only under archiso image!"
#     exit 1
# fi


sd=/dev/sda
nd=(boot root swap home)
for nm in "${nd[@]}"; do ((++i)); declare n_${nm}=$i s_${nm}=$sd$i; done

if [ "$1" == --force ]; then
    swapoff $s_swap
    umount -f /mnt

    ## Partitioning
    parted -s -a opt $sd mklabel msdos
    lsblk $sd && echo
    parted -s -a opt $sd  \
        mkpart primary ext4 1MB 100MB      \
        mkpart primary ext4 100MB 8GB      \
        mkpart primary linux-swap 8GB 10GB \
        mkpart primary ext4 10GB 100%

    parted -s -a opt $sd set $n_boot boot on
fi

if [ "$1" == --force ]; then
    ## Format
    mkswap $s_swap
    mkfs.ext4 $s_boot
    mkfs.ext4 $s_root
    mkfs.ext4 $s_home
fi

## Layout
parted -l
# lsblk $sd

exit

if [ "$1" == --force ]; then
    # Mount
    swapon $s_swap
    mnt() { mkdir -p /mnt$2 && mount $1 /mnt$2; }
    mnt $s_root /
    mnt $s_boot /boot
    mnt $s_home /home
fi


## Select a mirror
pm=/etc/pacman.d/mirrorlist
pmt=/tmp/mrlst
cat - <<-'EOT' > $pmt
#%BEGIN Prepended during install
## Score: 0.7, Ukraine
Server = http://archlinux.bln-ua.net/$repo/os/$arch
## Score: 25.8, Ukraine
Server = http://mirrors.nix.org.ua/linux/archlinux/$repo/os/$arch
#%END
EOT
sed '/#%BEGIN/,/#%END/d' $pm >> $pmt
mv -vf $pmt $pm


## Install the base system
# pacstrap -i /mnt base base-devel

## Need more then one-go method
# genfstab -U -p /mnt >> /mnt/etc/fstab
# vim /mnt/etc/fstab

# Chroot
# arch-chroot /mnt /bin/bash
