#!/usr/bin/env bash
# From within Arch VBox:
#   scp user@local.ip:~/aura/airy/arch-install .

sd=/dev/sda

if [ "$1" == --force ]; then
    parted -s -a opt $sd mklabel msdos   \
        mkpart primary ext4 1MB 100MB      \
        mkpart primary ext4 100MB 8GB      \
        mkpart primary linux-swap 8GB 10GB \
        mkpart primary ext4 10GB 100%      \
        set 1 boot on
fi

## MORE:
# parted -l
lsblk $sd


if [ "$1" == --force ]; then
    # Enable swap
    mkswap ${sd}1
    swapon ${sd}1

    # Mount
    mnt() { mkdir -p /mnt/$2 && mount ${sd}$1 /mnt/$2; }
    mnt 2 /
    mnt 1 /boot
    mnt 4 /home
fi


## Select a mirror
pm=/etc/pacman.d/mirrorlist
pmt=/tmp/mrlst
cat - <<-'EOT' > $pmt
#%BEGIN Prepended during install
## Score: 0.7, Ukraine
Server = http://archlinux.bln-ua.net/$repo/os/$arch
## Score: 25.8, Ukraine
Server = http://mirrors.nix.org.ua/linux/archlinux/$repo/os/$arch
#%END
EOT
sed '/#%BEGIN/,/#%END/d' $pm >> $pmt
mv -vf $pmt $pm


## Install the base system
pacstrap -i /mnt base base-devel

## Need more then one-go method
# genfstab -U -p /mnt >> /mnt/etc/fstab
# vim /mnt/etc/fstab

# Chroot
arch-chroot /mnt /bin/bash
