#!/bin/bash -e
source ~/.shell/func.d/system
trap_errors

# NOTE: If problem with package update, firts update 'archlinux-keyring' pkg
#   E.G: signature from "Ambrevar <ambrevar@gmail.com>" is unknown trust
#        corrupted (invalid or corrupted package (PGP signature)
#     => CHECK expiration date $ pacman-key -l ambrevar
# ALSO: $ gpg --recv-keys 249B39D24F25E3B6

if distro arch; then
  if [[ " $* " =~ " -u " ]]; then
    pacaur -Syu
  else
    sudo pacman -Syu  # NOTE: --ignore=firefox
  fi
  # OR: /etc/pacman.conf: IgnorePkg=firefox ; IgnoreGroup=core
  # Degrade manually:
  #   pacman -U /var/cache/pacman/pkg/firefox-42.0-3-x86_64.pkg.tar.xz

elif distro ubuntu; then
  sudo apt-get install gawk
  echo "sudo apt-get update && sudo apt-get upgrade"
fi

# TODO:ADD: 'gem/python/cabal update && upgrade' if pr is found
#   -- THINK: not much necessary -- as pacman-like packages are preffered
#   -- MAYBE place into './update' of their relative dir?
#   -- NOT: ./update reserved for local machine caching stuff

if has_pr cabal; then cabal update; fi    # Haskell
# DISABLED: unreasonable for kedi
# if has_pr bundle; then bundle update; fi  # Ruby
