# /etc/hostapd/hostapd.conf

# NEED:
# $ iw list | grep -A8 "Supported interface modes"
# $ pacman -S hostapd dnsmasq

interface=wlan0
driver=nl80211
country_code=UA
ieee80211d=1

## WTF: country regulatory NO-IR (no initial radiation)
##   cannot use 5G until it first receives a beacon from another AP (passive-scan)
# ssid=homeH5
# ieee80211ac=1
# hw_mode=a
# channel=36

ssid=homeH2
ieee80211n=1
wmm_enabled=1
hw_mode=g
channel=7

max_num_sta=10
auth_algs=3

wpa=2
wpa_passphrase=...
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
