#!/bin/bash -e
source ~/.shell/func.d/packages

## ALSO:
# community/ngrep 1.47-2
#   A grep-like utility that allows you to search for network packets on an interface.

if distro arch; then
  pkg_inst tcpdump sslsplit  # mitmproxy
  pkg_inst wireshark-cli
  pkg_inst wireshark-qt

  # TRY: +++ https://termshark.io/
  #   https://linux.org.ua/index.php?topic=11426.0
  #   https://github.com/gcla/termshark
  # Tshark | Editing Hex ⌇⡠⠋⠸⡺
  #   https://tshark.dev/edit/editing_hex/
  # gcla/termshark: A terminal UI for tshark, inspired by Wireshark ⌇⡠⠋⠸⡾
  #   https://github.com/gcla/termshark
  # aur_inst termshark-bin

elif distro ubuntu; then
  echo "Err: fixme"
fi
