#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
  # ALT:
  # jbruchon/jdupes: A powerful duplicate file finder and an enhanced fork of 'fdupes'. ⌇⡟⢝⣿⠨
    https://github.com/jbruchon/jdupes
  pkg_inst rmlint
else
  echo "E: no rmlint"
fi
