#!/bin/bash -e
SWD=$(readlink -e "$0"); SWD=${SWD%/*}
PATH=$SWD/get:$SWD/mod:$SWD/set:$SWD:$PATH
source "${SWD%/*}/funcs-lib"

curve=$1

if [[ -z $curve ]]; then
  read -r curve < <(cache-get curve default)
  declare -A _curve=([soft]=firm [firm]=soft)
  curve=${_curve[${curve:?}]:-default}
fi
cache-set curve "$curve"

case $curve
in soft) bezier=( 20 0 10 100 )
;; firm|default|*) bezier=( 50 0 20 75 )
esac

for w in "$WSTYLUS" ; do #"$WERASER"
  xsetwacom set "$w" PressureCurve "${bezier[@]}"
done

r.n "Wacom: Curve" "$curve"
