#!/bin/bash -e
SWD=$(readlink -e "$0"); SWD=${SWD%/*}
source "${SWD%/*}/funcs-lib"

s=$1

if [[ -z $s ]]; then
  s=$(xsetwacom get "$WTOUCH" Touch)
  declare -A _s=([on]=off [off]=on)
  s=${_s[${s:?}]:?}
fi
s=${s^^}

xsetwacom set "$WTOUCH" Touch "${s:?}"

r.n 'Wacom: Touch' "${s:?}"
