#!/bin/bash -e
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

### LINKS ###
linkcp "$PWD" ~/.shell
linkcp "input/dircolors-${THEME}.ansi" ~/.config/dircolors
linkcp "input/inputrc" ~/.inputrc
