#!/bin/bash -e
cd $(dirname $(readlink -m ${0}))
[[ "${THEME:=$(< ~/.cache/airy/theme)}" =~ ^(dark|light)$ ]] || THEME=dark

case "$SHELL" in *bash) RC=~/.bashrc ;; *zsh) RC=~/.zshrc ;; esac
link(){ [[ ! -e $2 || -L $2 ]] && ln -sfvT "$1" $2; }

### LINKS ###
link "$PWD" ~/.shell
link "$PWD/input/dircolors-${THEME}.ansi" ~/.dircolors
link "$PWD/tmux/theme-${THEME}.conf" ~/.cache/airy/theme-tmux.conf

for nm in bash/bashrc tmux/tmux.conf input/inputrc
do link "$PWD/$nm" ~/.${nm##*/}; done
