#!/bin/bash
set -euo pipefail
# MODEL: remote = [xsel -> socat -> remote.sock -> sshd]
#   ===> [ssh -> local.sock -> socat -> xsel] = local

conn=${1:?Need: user@host[:port]}
[[ $conn =~ @ ]] || conn=$conn@$USER
[[ $conn =~ : ]] || conn+=:22

ruser=${conn%%@*}
rsock=/tmp/xsel-shared.remote
## WTF: why it doesn't work despite looking right MAYBE: conflict with local socat ?
# lsock=${TMPDIR:-/tmp}/xsel-shared.local
## WTF: how it works at all with wrong path ?
lsock=/tmp/$ruser/xsel-shared.local

exec ssh -O forward -R "$rsock:$lsock" -S "${TMPDIR:-/tmp}/$conn" "$conn"
