#!/bin/bash -e
source ~/sys_funcs

### Host
echo "${SYS_HOST:?No}" > /etc/hostname

sed -ri 's/^(127\.0\.0\.1\s+\S+\s+\S+).*$/\1 '"${SYS_HOST:?No}"'/' /etc/hosts
# NOTE: Need active dbus -- impossible at setup time
# hostnamectl set-hostname "$myhost"
echo ':: writing host ended'
