#!/bin/bash -e
source ~/.shell/func.d/packages

#| st     | suckless terminal -- lacks of all, but very small
#| abduco | screen-like programs detaching NEW:ALT: to dtach
#| dvtm   | tmux-like dwm-adhere split/tiling management

if distro arch; then
    if cfgOpt u; then
        src="${CURR_DIR_PKG:?No}/st"
        if [[ -e "$src" ]]; then (cd "$src" && git pull ||:)
        else (git clone "https://github.com/amerlyq/st" "$src"); fi
    fi
    pkg_inst 'dvtm'
    aur_inst 'abduco' 'xurls'

elif distro ubuntu; then
    pkg_inst 'st dtach'
fi
