#!/bin/bash -e
source ~/.shell/func.d/packages

#| st     | suckless terminal -- lacks of all, but very small
#| abduco | screen-like programs detaching NEW:ALT: to dtach
#| dvtm   | tmux-like dwm-adhere split/tiling management

if distro arch; then
  if cfgOpt u; then
    src=${CURR_DIR_PKG:?}/st
    [[ -d $src ]] || (git clone "https://github.com/amerlyq/st" "$src")
    (cd "$src" && git-up)
  fi
  pkg_inst dvtm
  aur_inst abduco xurls

elif distro ubuntu; then
  pkg_inst st dtach
fi
