#!/bin/bash -e
source ~/.shell/func.d/cfgsetup
[[ "$THEME" =~ ^(dark|light)$ ]] || THEME=dark

if cfgOpt u; then (
  cd "${CURR_DIR_PKG:?No}/st" && git checkout amerlyq

  # [[ $FONT_ST ]] || FONT_ST=$(( ${MAIN_DPI:?} * 9/72 + 1))
  FNSZ="$FONT_ST" THEME="$THEME" ./install -mbi
) fi
