#!/bin/bash -e
source ~/.shell/func.d/cfgsetup
[[ "$THEME" =~ ^(dark|light)$ ]] || THEME=dark

if cfgOpt u; then (
  cd "${CURR_DIR_PKG:?No}/st" && git checkout amerlyq

  fs=$(( ${MAIN_DPI:?} * 9/72 + 1))
  FNSZ="$fs" THEME="$THEME" ./install -mbi
) fi
