#!/bin/bash

source ~/.bash_export

# Tip: There Should be in the spaces between the lines, and note que also there should be a single space both before and after each of the equal signs.

#sudo smbpasswd -a "$CURR_USER"

sudo restart smbd

# Once Samba has restarted, use this command to check your smb.conf for any syntax errors


#To access your network share use your username (<user_name>) and password through the path "smb://<HOST_IP_OR_NAME>/<folder_name>/" (Linux users) or "\\<HOST_IP_OR_NAME>\<folder_name>\" (Windows users). Note that "<folder_name>" value is passed in "[<folder_name>]", in other words, the share name you entered in "/etc/samba/smb.conf".
testparm
