#!/bin/bash -eu
#%USAGE: add user to group 'leds', otherwise 'sudo' is required
#%  (-n) notify pop-up
set -o pipefail
O=; while getopts 'n' o; do O+=$o; done; shift $((OPTIND-1))

val=${1-}
dev=asus::kbd_backlight
dir=/sys/class/leds/$dev

set_led(){ local val=$1
  val=$((val > max ? max : val < 0 ? 0 : val))
  [[ -w $dir/brightness ]] || sudo=sudo
  ((val == cur)) || ${sudo-} tee "$dir/brightness" <<< "$val"
  [[ ! $O =~ n ]] || r.n $'\U0001F4A1\U0001F5AE' "$((val*100/max))%"
}

max=$(<"$dir/max_brightness")
cur=$(<"$dir/brightness")

case $val
in [0-$max]) set_led "$val"
;; [+-]) set_led $(( cur "$val" 1 ))
;; '') echo "$cur $((cur * 100 / max))%"
;;  *) echo "Error: wrong value: '$val'. Use: [0-$max]|+|-"; exit 1
esac
