#!/bin/bash
#%USAGE: $ ./$0 <account> [-- [<getmail_args>]]
#%
set -euo pipefail

acc=$1
shift
[[ ${1-} == -- ]] && shift

cfg=${XDG_CONFIG_HOME:-$HOME/.config}/getmail/acc/"$acc"

# ALT: mdir=${MAIL:-${MAILDIR:-${MAILROOT:-$HOME/.mail}/$acc}}
mdir=$(sed -rn "/^\s*path\s*=\s*(.+)($|#.*)/{s//\\1/;s|^~|$HOME|p}" "$cfg")
mdir=$(realpath -sm "$mdir")
mkdir -p "$mdir"/{cur,new,tmp}
chmod 700 "$mdir"

# INFO: "davmail" sync speed is ~100 / min
#   ~50 dirs is 1 min for idle check; no effect from PipelineDepth
exec flock -FxE13 -w15 "$mdir" \
  getmail --getmaildir "${cfg%/*}" --rcfile "$cfg" "$@"
