#!/bin/bash -e
# EXPL: wraps command in start/end notifies
# BUG: <i> isn't parsed -- possible to use only inside 'dunstrc/format'?
# OR: possible only for %s='summary'?

while getopts 'n:f:' o; do case "$o"
in n) normal="<i>$OPTARG</i>"
;; f) failed="<i>$OPTARG</i>"
;; *) exit; esac; done; shift $((OPTIND-1))

"${@:?}" \
&& r.notify -t50  "OK" "\$ $*\n$normal" \
|| r.notify -Ut200 "Failed ($?)" "\$ $*\n$failed"
