# vim: ft=sh

# See
# Commands to bind
# http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Standard-Widgets

##### Vars #####

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export GPG_TTY=$(tty)

# Set name of the theme to load.
# random, robbyrussell # Look in ~/.oh-my-zsh/themes/
ZSH_THEME="airy" #made from jonathan

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# I use aliases and headers getting cumbersome
# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
#ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

## There is $SHLVL instead of this
# if [[ -z ${MY_SHELL_LEVEL} ]]; then
#     export MY_SHELL_LEVEL=0
# else
#     export MY_SHELL_LEVEL=$(($MY_SHELL_LEVEL+1))
# fi

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large
# repositories much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# export MANPATH="/usr/local/man:$MANPATH"

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/.bash/zsh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(autojump completion git grep history-substring-search)

# Main configuration
source "$ZSH_CUSTOM/options.zsh"
source "$ZSH_CUSTOM/completion.zsh"
source "$ZSH/oh-my-zsh.sh"

# User configuration
if [ -f ~/.bash_export  ]; then source ~/.bash_export  ; fi
source "$ZSH_CUSTOM/amer-widgets.zsh"
source "$ZSH_CUSTOM/amer-key-mix.zsh"
source "$ZSH_CUSTOM/filetypes.zsh"
DEFAULT_USER="$CURR_USER"

# ~/.zshenv -- always sourced by zsh (before ~/.zshrc).
# WARNING: Available even in scripts! With #!/zsh
# But as I mostly writing portable scripts in bash, it's not a problem.
# WARNING: It should not contain commands that produce output or assume the
# shell is attached to a tty.
# So it can't be used to source aliases to be available in ranger.
# For bash use analogue BASH_ENV=$HOME/.zshenv before launching
if [ -f ~/.bash/aliases ]; then source ~/.bash/aliases ; fi
export SHELL=$(which zsh)

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then export EDITOR='vim'; fi
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# For ranger auto_changedir
function finish {
    tempfile='/tmp/ranger_shelldir'
    echo "$PWD" > "$tempfile"
}
trap finish EXIT
