# vim: ft=sh

# See
# Commands to bind
# http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Standard-Widgets

##### Vars #####

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

setopt noflowcontrol
stty stop '' -ixoff -ixon
# new history lines are added to the $HISTFILE incrementally (as soon as they are entered), rather than waiting until the shell exits.
setopt INC_APPEND_HISTORY

## don't beep on errors
setopt nobeep
## type the name of a directory -> it will become the current directory
setopt autocd
## glob's expanding magic
setopt extended_glob

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#"robbyrussell"
ZSH_THEME="airy" #made from jonathan

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# I use aliases and headers getting cumbersome
# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
#ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

if [[ -z ${MY_SHELL_LEVEL} ]]; then
    export MY_SHELL_LEVEL=0
else
    export MY_SHELL_LEVEL=$(($MY_SHELL_LEVEL+1))
fi

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/.bash/zsh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(autojump completion git grep history-substring-search)

source $ZSH/oh-my-zsh.sh

# User configuration

if [ -f ~/.bash_export  ]; then source ~/.bash_export  ; fi
DEFAULT_USER="$CURR_USER"

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

source "$ZSH_CUSTOM/lib/amer-key-mix.zsh"


# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
# if it will print out, you can do 1&> /dev/null
if [ -f ~/.bash/aliases ]; then source ~/.bash/aliases ; fi

export SHELL=$(which zsh)

# MPogoda's
alias -s {avi,mpeg,mpg,mov,mkv}=mpv

# For ranger auto_changedir
function finish {
    tempfile='/tmp/ranger_shelldir'
    echo "$PWD" > "$tempfile"
}
trap finish EXIT
