#!/usr/bin/env bash

# LG=$(setxkbmap -query | awk '/layout/{print toupper($2)}')

# LG=$(xkb-switch -p | sed 's/am(\(.*\))\|\(\w\+\)/\U\1\2/')
# $exno xkb-switch -s us [ru ua]

# Those maps drop focus from input fields in browser.
#   Better use own layout switcher in ~/.Xrc/xkb
get_current() { qdbus ru.gentoo.KbddService \
    /ru/gentoo/KbddService ru.gentoo.kbdd.getCurrentLayout; }

change() { dbus-send --dest=ru.gentoo.KbddService \
    /ru/gentoo/KbddService ru.gentoo.kbdd.$@; }

setnum() { change "set_layout uint32:$1"; }

case "$1" in
[0-9]) setnum $1 ;;
   us) setnum 0 ;;
   ru) setnum 1 ;;
   ua) setnum 2 ;;
    +) change 'next_layout' ;;
    -) change 'next_layout' ;;
    *) get_current ;;
esac

~/.i3/blocks/update lang
