#!/bin/sh

# BAD? zsh launched raw or after ranger -- has SHELL=/usr/bin/zsh
#   instead of =.../r.sh. OR it's intended behaviour?

# BAD:($SHELL == zsh): don't work when SHELL=r.sh
#   http://stackoverflow.com/questions/3327013/how-to-determine-the-current-shell-im-working-on
#   ALT: => [[ -n $ZSH_NAME ]]

# EXPL: simplify when r.sh -c $SHELL
if [ "$#" -eq 2 ] && [ "$1" = -c ]
then if [ "$2" = "$SHELL" ] || [ "$2" = '$SHELL' ]
then shift 2; fi; fi

# EXPL: overwrite when SHELL=r.sh
[ -x /usr/bin/zsh ] \
&& export SHELL=/usr/bin/zsh \
|| export SHELL=/usr/bin/bash

# USE: Interactive shell
[ "$1" != -c ] && exec ${SHELL:?} "$@"

# USE: Cmdline populated with aliases
[ "$1" != -c ] || shift
exec ${SHELL:?} -c '
(( $(id -u) )) || HOME=/home/${SUDO_USER:-${USER:-${USERNAME:?}}}
source ~/.config/airy/aliases
if [[ -n ${ZSH_NAME-} ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/modules/git/alias.zsh"
  setopt aliases
elif [[ -n ${BASH-} ]]; then
  shopt -s expand_aliases
fi
eval "$@"
' "$0" "$@"
