#!/bin/bash -e
source ~/.shell/func.d/packages
has_pr X || die

pkg_inst firefox

if distro arch; then
    echo "W: BROKEN:(signing) pentadactyl"
    echo "N: USE:(manually) https://github.com/willsALMANJ/pentadactyl-signed/releases"
    # aur_inst -p 'firefox' pentadactyl-git
    pkg_inst -f '/usr/lib/mozilla/plugins/libflashplayer.so' flashplugin

elif distro ubuntu; then
    echo "Err: install manually pentadactyl and flashplugin"
fi
