#!/bin/bash -e

# d3dx9_43 | complete directx9_june_2010
# xact     | for XAudio2
# X3DAudio1_7.dll | copy manually
# d3dcompiler_43  | D3DXCompilerShader failed
# MAYBE: vcrun2010 directx9 xact_jun2010

exec primusrun playonlinux --run grimrock2
