#!/bin/bash -e
source ~/sys_funcs
echo "Err: broken, fix for current snippets"
exit 1

user="tester"
zone="Europe/Kiev"
sd=/dev/sda
host="archvbox"
VBOX_HOST_IP="192.168.56.1"
LOCAL_SRV="http://${VBOX_HOST_IP}:23208"


hopt() { [ "${ARCH_OPTS/[$1]}" != "$ARCH_OPTS" ]; }
oadd() { ARCH_OPTS="${ARCH_OPTS}${1}"; }
die() { local ret=$?
    case "$1" in [0-9]) ret=$1; shift ;; esac
    printf "%s${1+\n}" "$1"; exit $ret
}
do_each() {  # Split args on 'most' and 'last'
sed '/#.*$/s///; /^\s*$/d' | while read L
    do ${@:1:${#@}-1} "${@:${#@}}${L}" || die
done; }

# ========================================================================

### Options chooser ###
hlst=cdpmMhsuR
case "$1"
in -[$hlst])  oadd "-${1##*-}"
;; +[$hlst]*) oadd "${1##*+}"
    echo "::: no chain -- choosen options only :::"
;; *) die 1 "Need option -/+'$hlst'" ;; esac
if hopt -; then
    hopt c && oadd dM  # create -> disks, unmount
    hopt d && oadd pm  # disk -> mount, packstrap
    hopt p && oadd f   # pacstrap -> fstab, repo/cache (r)
    hopt m && oadd h   # mount -> host/scripts
    hopt h && oadd s   # host -> system
    hopt s && oadd u   # system -> user
fi

# ========================================================================


### BASE step (1/3)
hopt cdpm && { chmod -R 700 ~/arch/base || die; }

do_each /bin/bash -c ~/arch/base/ <<EOTBASE
$(hopt m && hopt v && echo "01-disk-vbox $(hopt d && echo '--new') $sd")
$(hopt m && false  && echo "02-disk-lvm  $(hopt d && echo '--new') $sd")
$(hopt v && echo "35-custom-pacman $LOCAL_SRV /etc/pacman.conf")
$(hopt p && echo "40-pacstrap")
$(hopt f && echo "50-fstab")
EOTBASE
echo ":: {disk, pacstrap, fstab} ended"

# ========================================================================

### HOST CHROOT step (2/3)
if hopt h; then
    cp -vrft /mnt/root/ ~/arch/{host,user} ~/id_rsa.pub || die
    chmod -R 700 /mnt/root/host || die

# ALT: systemd-nspawn
do_each arch-chroot /mnt /bin/bash -c ~/host/ <<EOTHOST
00-setup $zone
10-network $host
$(hopt v && echo "15-network-vbox $VBOX_HOST_IP")
20-grub $sd
$(hopt v && echo "22-grub-vbox $sd")
40-AUR
50-X
80-add-user $user
$(hopt v && echo "88-ssh-nopswd $user")
$(hopt v && echo "92-autologin -c $user")
EOTHOST
fi && echo ':: host chroot ended'

# ========================================================================

### USER SU step (3/3)
if hopt u; then
do_each arch-chroot /mnt /usr/bin/su $user -c "" <<EOTUSER
chown -R $user:$user ~/user && chmod -R 700 ~/user
~/user/30-configs
EOTUSER
fi && echo ":: '$user' <su in chroot> ended"

# ========================================================================

## Used: only for exporting repo to [custom] local server
if hopt R; then
    rep=/var/cache/pacman/pkg
    arch-chroot /mnt /bin/bash -c "repo-add $rep/custom.db.tar.gz $rep/*.pkg.tar.xz"
    scp -r /mnt/$rep frees@${VBOX_HOST_IP}:\~/home/VMs
fi

# NOTE: use 'fuser' to find by what it is busy
hopt M && umount -R /mnt

echo '::: install complete, reboot now :::'
