#!/bin/sh

DIR="${1:-$HOME}"
ALERT_LOW="${2:-10}" # color will turn red under this value (default: 10%)

df -h -P -l "$DIR" 2>/dev/null |
	awk -v alert_low=$ALERT_LOW '
/\/.*/ {
	# full text
	print $4

	# short text
	print $4

	use=$5

	# no need to continue parsing
	exit 0
}
END {
	gsub(/%$/,"",use)
	if (100 - use < alert_low) {
		# color
		print "#FF0000"
	}
}
'
