#!/usr/bin/env bash

DIR=~/enc

# cp /usr/share/doc/mutt/examples/gpg.rc $DIR/.gpgrc
# echo "source ~/.gpg.rc" >> ~/.muttrc

# gpg --gen-key

mkdir -p $DIR
touch $DIR/.tmp

cat - << EOT > $DIR/.gmpass
Gmail1 yourfirstpassword
Gmail2 yoursecondpassword
Gmail3 yourthirdpassword
EOT

# Encrypt it
gpg --encrypt --recipient 'Your Name' .gmpass
