#!/bin/bash -e
source ~/.shell/func.d/packages

# VIZ: cmp diff diff3 sdiff
pkg_inst diffutils

# VIZ: diffstat | cdiff colordiff | dwdiff
pkg_inst diffstat colordiff dwdiff

# ==== X only ====
# BET:(clean install): separate package for meld -- to exclude it on headless servers
# has_pr X || die
# cool text/directory comparator
pkg_inst meld
