#!/bin/bash -e
source ~/.shell/func.d/packages

# VIZ: cmp diff diff3 sdiff
pkg_inst diffutils

# NICE: Difftastic is a structural diff engine. It doesn't care about newlines or indentation; it cares if the code's meaning changed.
pkg_inst difftastic

# dandavison/delta: A syntax-highlighting pager for git, diff, grep, and blame output ⌇⡩⢾⠎⠥
#   https://github.com/dandavison/delta
pkg_inst delta

# VIZ: diffstat | cdiff colordiff | dwdiff
pkg_inst diffstat colordiff dwdiff

# ==== X only ====
# BET:(clean install): separate package for meld -- to exclude it on headless servers
# has_pr X || die
# cool text/directory comparator
# pkg_inst meld
