#!/bin/bash
cd $(dirname $(readlink -m ${0})) || exit

### LINKS ###
link(){ [[ ! -e $2 || -L $2 ]] && ln -sfvT "$1" $2; }
for nm in profile; do link "$PWD/$nm" ~/.${nm##*/}; done


case "$1" in
 dark|light) echo "colorscheme $1" ;;
--clean) echo "nothing" ;;
-u|--update) update="$1" ;;
esac

