#!/bin/bash -e
source ~/.shell/func.d/packages

# SEE:
#   http://www.linuxveda.com/2015/03/09/how-to-install-virtualbox-in-arch-linux/

if distro arch; then
    # USE:(guest-iso): to install adds to guests other than Arch
    pkg_inst -d linux-headers virtualbox-host-modules-arch
    pkg_inst virtualbox virtualbox-guest-iso

    # ALT:(conflict) aur_inst 'virtualbox-bin' 'virtualbox-host-modules'  # NOT FOUND
    # SEE: https://forum.antergos.com/topic/818/can-t-run-my-vitualbox/4
    # dkms autoinstall  # For custom, also: pkg_inst virtualbox-host-dkms

    ## -> VNC, USB2.0
    # pkg_inst virtualbox-ext-vnc
    ## BAD: non-free for corporate usage
    # aur_inst virtualbox-ext-oracle

    ## NEED for bridge network and host-only to assign host ip
    # pkg_inst -d net-tools
    # -> now this command should work :)
    #  sudo modprobe -a vboxdrv vboxnetflt vboxpci vboxnetadp
    #  sudo vboxreload  # reload modules after update
    ## you may run this to rebuild
    # sudo /sbin/rcvboxdrv -h

elif distro ubuntu; then
    echo "Dld manually!"

    # VBox guest
    # pkg_inst "virtualbox-guest-additions virtualbox-guest-utils \
    #           virtualbox-guest-dkms virtualbox-guest-x11"
fi
