#!/bin/bash -eu
# tags: core
source ~/.shell/func.d/cfgsetup

id | grep -qwF vboxusers || sudo gpasswd -a "${LOGNAME:?}" vboxusers
# lsmod | grep -q '^vboxdrv\>' || sudo modprobe vboxdrv

linkcp -ct /etc/tmpfiles.d  "unit/vbox.conf"
cfgOpt uU || [[ ! -d /srv/share ]] && sudo systemd-tmpfiles --create "vbox.conf"


### CFG: ~/.config/VirtualBox/VirtualBox.xml
# TODO: symlink /vm to xdg_airy_vm_dir with fallback to ~/vm OR /data/vm OR ~/VMs OR /data/VMs
mkdir -p /vm
VBoxManage setproperty machinefolder /vm

# NOTE: change Host key to ISO_first_group_lock=65037
#   OR:(as usual): AltGr=65027 OR:(less annoying): RightAlt+RightShift="165,161"
VBoxManage setextradata global GUI/Input/HostKeyCombination 65037

# NOTE: exchange Host-Del and Host-Backspace -- for easier sending Ctrl-Alt-Del
VBoxManage setextradata global GUI/Input/MachineShortcuts TypeCABS=Del,TypeCAD=Backspace

## NOTE: disable annoying miniToolBar
# SEE: http://helpdeskgeek.com/virtualization/hide-the-menu-bar-and-status-bar-in-virtualbox/
VBoxManage setextradata global GUI/Customizations noMenuBar,noStatusBar
# ALT: $ sed -i '/ShowMiniToolBar/ s/\(value="\)\w\+"/\1no"/' ~/VMs/arch64/arch64.vbox

linkcp -ct /etc/modules-load.d -- unit/virtualbox-host-modules-arch.conf

# USAGE: $ s.r vbox-run@my_debian
svc_activate -cu vbox-run@.service
