#!/bin/bash -e
source "${0%/*}/../funcs-lib"

# map=$(~/.i3/ctl/get_current_output)
map=eDP1

# ROTATION: table must be rotated before!
# ONE: 1920x1080+0+0, TWO: 3286x1080+0+0, NAME: <name>, WHOLE: 'desktop'
for w in "$WPAD" "$WSTYLUS" "$WERASER" "$WTOUCH" "$WCURSOR"; do
    xsetwacom set "$w" MapToOutput "$map"
done

r.n "Wacom: output" "$map"
