#!/bin/bash -e
set -o pipefail

output=$1  # [<output>|desktop|WxH+X+Y|next]
# FIXME: tested only for rotate=none
rotate=$2  # [none|half|cw|ccw]
region=$3  # [full|center|WxH+X+Y] -- WxH+X+Y is related to output

_xrandr=$(xrandr -q --current)

qmons(){ sed -rn '/^(\S+) connected.*/s//\1/p' <<< "$_xrandr"; }
qscrn(){ sed -rn '/^Screen .*, current ([0-9]+) x ([0-9]+),.*/{s//\1x\2+0+0/p;q}' <<< "$_xrandr"; }
qdisp(){ sed -rn "s/^${1:?}"' connected.* ([0-9]+x[0-9]+\+[0-9]+\+[0-9]+).*/\1/p' <<< "$_xrandr"; }
qwids(){ xsetwacom --list devices | gawk -vT="STYLUS|ERASER" '$NF~T{print$(NF-2)}'; }

# ALT:(broken?) KeepShape option
new_area(){ local w=${1:?} h=${2:?}
  read -r ax ay aw ah
  # keep_width: 16:9 => 10/9 => 1
  (( (w/h) / (aw/ah) )) && { nx=$aw; ny=$((aw*oh/ow)); } || { nx=$((ah*ow/oh)); ny=$ah; }
  printf '%d %d %d %d\n' "$ax" "$ay" "$nx" "$ny"
}

map_wid() { local wid=${1:?} geom=${2:?}
  xsetwacom --set "$wid" ResetArea
  local area=( $(xsetwacom --get "$wid" Area | new_area "$ow" "$oh") )
  # BAD: rotation don't keep aspect? Don't rotate tablet area?
  # ATT: Rotate before MapTo
  xsetwacom --set "$wid" Rotate "${rotate:=none}"
  xsetwacom --set "$wid" Area "${area[@]}"
  xsetwacom --set "$wid" MapToOutput "$geom"
  # OR xinput set-prop "$wid" --type=float "Coordinate Transformation Matrix" 0 0.333333 0.666666 -1 0 1 0 0 1
}

mons=( $(qmons) )
wids=( $(qwids) )

[[ $output ]] || { IFS='|'; printf 'USAGE: %s|desktop|WxH+X+Y|next\n' "${mons[*]// /|}"; exit; }
[[ $output =~ ^[0-9]+$ ]] && { ((output < ${#mons[@]})) && output=${mons[$output]} || exit; }

case ${output:=${mons[0]}}
in desktop) geom=$(qscrn)
;;  [0-9]*) geom=$output
;;       *) geom=$(qdisp "$output")
esac
IFS='x+' read -r ow oh ox oy <<< "$geom"

# HACK:TEMP: many hardcoded values/regimes
# TODO: affect vars/aspect by rotation
case ${region:=full}
in full) geom=$output
;; center)
  nw=$((oh*16/10))
  nx=$((ox+(ow - oh*16/10)/2))
  ow=$nw; ox=$nx
  geom=${ow}x${oh}+${ox}+${oy}
;; cursor)
  eval "$(xdotool getmouselocation --shell)"
  zone='1/5'
  nw=$((oh*16/10*$zone))
  nh=$((oh*$zone))
  nx=$((X-nw/2))
  ny=$((Y-nh/2))
  ow=$nw; oh=$nh; ox=$nx; oy=$ny
  geom=${ow}x${oh}+${ox}+${oy}
;; *) geom=$region
esac

for wid in "${wids[@]}"; do
  map_wid "$wid" "$geom"
done
