#!/bin/bash -e
SWD=$(readlink -e "$0"); SWD=${SWD%/*}
PATH=$SWD/get:$SWD/set:$PATH
set -o pipefail

output=$1  # [<output>|desktop|WxH+X+Y|next]
rotate=$2  # [none|half|cw|ccw]
region=$3  # [full|center|WxH+X+Y] -- WxH+X+Y is related to output

# HACK: export before 'xbindkeys' to propagate cached env var
_xr=${_XRANDR:-$(query-xrandr)}

mons=( $(list-outputs <<< "$_xr") )

[[ $output =~ ^[0-9]+$ ]] && { ((output < ${#mons[@]})) && output=${mons[$output]} || exit; }

case ${output:=${mons[0]}}
in desktop) geom=$(geom-screen <<< "$_xr")
;;  [0-9]*) geom=$output
;;       *) geom=$(geom-display "$output" <<< "$_xr")
esac
IFS='x+' read -r ow oh ox oy <<< "$geom"


# HACK:TEMP: many hardcoded values/regimes
# TODO: affect vars/aspect by rotation
case ${region:=full}
in full)
  geom=$output

;; center)
  nw=$((oh*16/10))
  nx=$((ox+(ow - oh*16/10)/2))
  ow=$nw; ox=$nx
  geom=${ow}x${oh}+${ox}+${oy}

;; cursor)
  read mx my scr wnd < <(query-mouse)
  zone='1/5'
  nw=$((oh*16/10*$zone))
  nh=$((oh*$zone))
  nx=$((mx-nw/2))
  ny=$((my-nh/2))
  ow=$nw; oh=$nh; ox=$nx; oy=$ny
  geom=${ow}x${oh}+${ox}+${oy}

;; *)
  geom=$region
esac

map_wid() { local wid=${1:?}
  read -r ax ay aX aY < <(wacom-area-max "$wid")
  local aw=$((aX-ax)) ah=$((aY-ay)) w=$ow h=$oh

  g=0  # 0..100%
  # keep_width: 16:9 => 10/9 => 1
  # BAD: fail when aw<ah
  if (( (w/h) / (aw/ah) )); then
    # FIX: BROKEN
    nx=$ax
    ny=$((ay + aw*h/w))
    nX=$aX
    nY=$((ny + aw*h/w))
  else
    nx=$ax
    ny=$ay
    nX=$((ax + ah*w/h))
    nY=$aY
  fi

  local area="$nx $ny $nX $nY"

  wacom-map "$wid" "$area" "$geom" "$rotate"
}

while read -r wid; do map_wid "$wid"
done < <(wacom-ids 'STYLUS|ERASER')
