#!/bin/bash -e
set -o pipefail
# Online-demo: http://linuxwacom.sourceforge.net/misc/bezier.html
#   http://www.imagemagick.org/Usage/draw/

# My Windows original curve
# PressureCurveControlPoint: 40 0 239 23 1407 2047

SWD=$(readlink -e "$0"); SWD=${SWD%/*}
PATH=$SWD/mod:$PATH

cd "${SWD%/*}/profile.d"
for pf in *; do
  cat "$pf" | pressure-extract "$pf" | bash
done

sxiv /tmp/wacom_*.gif
