#!/usr/bin/env perl

use warnings;
use strict;
use lib "$ENV{HOME}/.urxvt/ext";
use urxcommon qw(:API);


my %actions = (
    close => sub { $_[0]->deactivate(); },
    openx => sub { print 'x-www',"\n"; },
    # openx => sub { $_[0]->exec_async(@{$_[0]->{browser}}, ${$self->{found}[$self->{n}]}[4]); }
    yank  => sub { $_[0]->status_osd("yes"); print 'yank',"\n"; },
    next => sub { print 'next',"\n"; },
    prev => sub { print 'prev',"\n"; },
    frst => sub { print 'frst',"\n"; },
    last => sub { print 'last',"\n"; },
);

sub staying { makecurry(\%actions, @_) }
sub closing { staying(@_, 'close') }

my %keymap = (
    o => staying('openx'),
    y => staying('yank'),
    pairto(qw(j Down Right) => staying('next')),
    pairto(qw(k   Up  Left) => staying('prev')),
    pairto(qw(O S-o Return) => closing('openx')),
    pairto(qw(Y S-y)        => closing('yank')),
    pairto(qw(q Escape C-c) => closing()),
);

# DEV for hints use vertical overlay over whole screen on left side
#   (two char width)
# DEV bind to current visible text (plus some lines around which contain
# visible parts of links/pathes)
# DEV open file path in vim/ranger/xsel current/nested/fork/float
# THINK toggle on_line_update by shortcut or osc code from lau-serial?
#       man says it could spend alot of time on filtering and redrawing...
#       possibly dropping some of output
# NEED keep selected cursor position and highlight when re-activate
# FIX long multiline url -- concatenate and refine before launching in browser
# BUG press Return -- when in active mode -- first time has no effect.


sub status_osd
{
    my ($self, $pref, $str) = @_;
    my $status = $pref .': ';
    $status .= $str if $str;

    $self->{overlay}->set(0,0, $self->special_encode($status));
}

sub key_press
{
    my ($self, $event, $keysym, $string) =  @_;
    my $key = fmt_key($self, $event, $keysym);
    # Check on white list: $action =~ m/[0-9][a-z]/i
    ($keymap{$key} || sub {})->($self, $key);
    $self->status_osd($key);

    1  # EXPL intercept all keys until confirm choice
}


sub activate {
    my ($self) = @_;
    $self->{overlay}->show();
    $self->enable (
        key_press => \&key_press,
        tt_write  => sub { 1 }
    );
}

sub deactivate {
    my ($self) = @_;
    $self->{overlay}->hide();
    $self->disable('key_press', 'tt_write');
}


sub on_user_command
{
    my ($self, $cmd) = @_; $_ = $cmd;
    return () unless s/^selector://;

    if (/^run$/) {
        # print "S:", @INC, "\n";
        $self->status_osd("Run? (y/n)");
        $self->activate();

    } else { cmd_err($_); }

    ()
}

sub on_start
{
    my ($self) = @_;
    $self->{overlay} = $self->overlay(0,-1, $self->ncol,1, urxvt::OVERLAY_RSTYLE, 0);
    $self->{overlay}->hide();

    ()
}

sub on_destroy
{
    my ($self) = @_;
    $self->deactivate();
    delete $self->{overlay} if $self->{overlay};
}
