#!/bin/bash -eu
set -o pipefail

# REF:
# https://stackoverflow.com/questions/24460486/cmake-build-type-not-being-used-in-cmakelists-txt
# https://stackoverflow.com/questions/11437692/how-to-add-a-custom-build-type-to-cmake-targeting-make
# https://stackoverflow.com/questions/25980411/using-build-type-in-cmake-3-x
