#!/bin/bash -e
source ~/.shell/func.d/packages

#| sxiv  | Image-thumbnail viewer, vim-like, ALT OLD: xzgv
#| exiv2 | Meta-info

pkg_inst sxiv exiv2

# ALT:BETTER:TRY: pqiv + libspectre poppler imagemagick
# https://github.com/phillipberndt/pqiv/
