#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

src="${1:-$HOME/res/dicts}"
[[ -d "$src" ]] || die "No dir with *.dict.dz specified"

## Link directory to access it by 'nobody'
dst=/usr/share/dictd
[[ ! -e $dst || -L $dst ]] || sudo mv -vf -- $dst ${dst}_
[[ "$src" -ef $dst ]] || sudo ln -sfvT "$src" $dst


## Generate database of all dictionaries in 'dir'
dblst="$src/custom.list"  # /var/lib/dictd/custom.list
> "$dblst"

find "$dst/" -regex '.*\.dict\(\.dz\)?' | while read fl; do
    nm="${fl%.dz}"; nm="${nm%.dict}";
    if [[ -e "${nm}.index" ]]; then
        echo "database \"${nm##*/}\" {
  data  \"$fl\"
  index \"${nm}.index\"
}" >> "$dblst"
fi; done

echo "W: $dblst"
