# /etc/systemd/system/ollama.service.d/override.conf
# vim:ft=systemd

[Service]
# BUG? still debug mode spam in journalctl
Environment="GIN_MODE=release"
# StandardOutput=null
# StandardError=journal
# OR: "=10m" to auto-unload (inof systemctl stop ollama)
Environment="OLLAMA_KEEP_ALIVE=-1"
Environment="OLLAMA_NUM_THREADS=8"
Environment="OLLAMA_MAX_LOADED_MODELS=1"
Environment="OLLAMA_NUM_PARALLEL=1"

# don't override manual settings
Environment="LLAMA_ARG_FIT=off"
Environment="OLLAMA_FLASH_ATTENTION=1"
Environment="OLLAMA_KV_CACHE_TYPE=q8_0"
# OR: ctx=8192 for DFL=q16_0
Environment="OLLAMA_CONTEXT_LENGTH=12288"
