#!/bin/bash -e
source ~/sys_funcs

## Console font
# cat > /etc/vconsole.conf <<EOT
# KEYMAP=us
# FONT=
# FONT_MAP=
# EOT


### Locale
loc="en_US.UTF-8"
sed -ri "s/^#(${loc}.*)\$/\1/" /etc/locale.gen
locale-gen
echo LANG=${loc} > /etc/locale.conf
export LANG=${loc}
echo ':: locale generated'

## On Ubuntu 12, fix:
# sudo locale-gen en_US.UTF-8
# sudo dpkg-reconfigure locales
# sudo sh -c 'echo LANG=en_US.UTF-8 > /etc/default/locale'
## People with a similar problem have had good luck with:
# sudo sh -c 'echo LANG=en_US.UTF-8 >> /etc/environment'


## Time
zone="/usr/share/zoneinfo/Europe/Kiev"
rm -vf /etc/localtime
ln -sv $zone /etc/localtime
# WARNING: dual boot with Windows: https://wiki.archlinux.org/index.php/Time#UTC_in_Windows
hwclock --systohc --utc
echo ':: time setted up'


## ROOT setup
echo ":: set root password"
printf "root:root" | chpasswd
