#!/usr/bin/env bash
if ! [[ "$(uname -n)" =~ archiso|vbox ]]; then echo "Use under vbox guest!"; exit 1; fi

loc="en_US.UTF-8"
zone=/usr/share/zoneinfo/${1?No zone localtime}

## Console font
cat > /etc/vconsole.conf <<EOT
KEYMAP=us
FONT=
FONT_MAP=
EOT

## Locale
sed -ri "s/^#(${loc}.*)\$/\1/" /etc/locale.gen
locale-gen
echo LANG=${loc} > /etc/locale.conf
export LANG=${loc}
echo ':: locale generated'


## Time
rm -vf /etc/localtime
ln -sv $zone /etc/localtime
# WARNING: dual boot with Windows: https://wiki.archlinux.org/index.php/Time#UTC_in_Windows
hwclock --systohc --utc
echo ':: time setted up'


## ROOT setup
echo ":: set root password"
printf "root:root" | chpasswd
