#!/bin/bash -e
if ! [[ "$(uname -n)" =~ archiso|vbox ]]; then echo "Use under vbox guest!"; exit 1; fi

myhost="${1?No current host name}"

## Host
echo "$myhost" | tee /etc/hostname
sed -ri 's/^(127\.0\.0\.1\s+\S+\s+\S+).*$/\1 '"$myhost"'/' /etc/hosts

# NOTE: Need active dbus -- impossible at setup time
# hostnamectl set-hostname "$myhost"
echo ':: writing host ended'


### Network
ifcs=($(ip link | sed -rn '/^[0-9]+:\s+(e\w+):.*$/{s//\1/p}'))
# systemctl enable dhcpcd@${ifcs[0]}.service  # Disable if use netctl

cat >/etc/netctl/eth_dhcp <<EOT
Description='General network connection'
Interface=${ifcs[0]}
Connection=ethernet
IP=dhcp
EOT
netctl enable eth_dhcp

echo ':: eth_dhcp is active'


### ENABLE Services
systemctl enable sshd.service
