#!/bin/bash -e
source ~/sys_funcs
is_enabled 'lan' || exit 0

nm=eth_dhcp

### Network
ifcs=($(ip link | sed -rn '/^[0-9]+:\s+(e\w+):.*$/{s//\1/p}'))
ifc=${ifcs[0]:?No}

cat > /etc/netctl/${nm?:No} <<EOT
Description='General LAN dhcp connection'
Interface=${ifc?:No}
Connection=ethernet
IP=dhcp
EOT

nm=eth_static
gate="${SYS_IP%.*}.1"
cat > /etc/netctl/${nm?:No} <<EOT
Description='Static LAN connection behind NAT'
Interface=${ifc?:No}
Connection=ethernet
IP=static
Address=('${SYS_IP:?No}/24')
#Routes=('192.168.0.0/24 via 192.168.1.2')
Gateway='$gate'
DNS=('$gate')
EOT

## For dhcp to transmit MAC instead DUID, so server could attach ip:
# vi /etc/dhcpcd.conf
# clientid  # Uncomment
# # duid   # Comment o

netctl enable $nm

echo ":: $nm is active"

# systemctl enable dhcpcd@${ifcs[0]}.service  # Disable if use netctl

# Вы можете запускать профиль Ethetnet со статическим IP независимо от того,
# подключен кабель или нет. Для этого добавьте SkipNoCarrier=yes в файл
# конфигурации профиля.
