#!/bin/bash -e
source ~/sys_funcs
is_enabled 'lvm' || exit 0

## CHECK: unnecessary? vi /etc/rc.conf
#: USELVM="yes"


## Add lvm2 hook
mv -vf --backup=t /etc/mkinitcpio.conf{,}
cat > /etc/mkinitcpio.conf <<-'EOT'
MODULES=""
BINARIES=""
FILES=""
HOOKS="base udev autodetect modconf block lvm2 filesystems keyboard fsck"
#COMPRESSION="gzip"
#COMPRESSION_OPTIONS=""
EOT

## Re-create /boot/initrd.img-...
mkinitcpio -p linux


## Show available hooks and help for them
# mkinitcpio -L
# mkinitcpio -H udev
