#!/bin/bash -e
source ~/sys_funcs
is_enabled 'lvm' || exit 0

## Add lvm2 hook
cfg=/etc/mkinitcpio.conf
cp -vf --backup=t ${cfg}{,}
cat > $cfg <<-'EOT'
MODULES=""
BINARIES=""
FILES=""
HOOKS="base udev autodetect modconf block lvm2 filesystems keyboard fsck"
#COMPRESSION="gzip"
#COMPRESSION_OPTIONS=""
EOT

## Re-create /boot/initrd.img-...
mkinitcpio -p linux


## Show available hooks and help for them
# mkinitcpio -L
# mkinitcpio -H udev
