#!/usr/bin/env bash
if ! [[ "$(uname -n)" =~ archiso|vbox ]]; then echo "Use under vbox guest!"; exit 1; fi


### Install X, etc
LST="xorg-server xorg-server-utils xorg-xinit"

# VBox needs at least vesa GPU driver: or X will not start!
LST="$LST xf86-video-vesa mesa-libgl"  # xorg-xdm
# 1) mesa-libgl  2) nvidia-304xx-libgl  3) nvidia-340xx-libgl  4) nvidia-libgl
# pacman -S xf86-input-synaptics mesa nvidia lib32-nvidia-utils

LST="$LST git i3-wm dmenu"  # ttf-dejavu
pacman -S --noconfirm $LST
# pacman -S --needed $LST

## Create initial database running as root
# /usr/bin/mandb --quiet
