#!/usr/bin/env bash
if ! [[ "$(uname -n)" =~ archiso|vbox ]]; then echo "Use under vbox guest!"; exit 1; fi

user=${1?No user}


### Autologin in virtual console
fl=/etc/systemd/system/getty@tty1.service.d/override.conf
mkdir -p ${fl%/*}
cat > $fl <<EOT
[Service]
Type=idle
ExecStart=
ExecStart=-/sbin/agetty --autologin $user --noclear %I 115200 linux
EOT

### Autologin in serial
# fl=/etc/systemd/system/serial-getty@ttyS0.service.d/autologin.conf
# mkdir -p ${fl%/*}
# cat > $fl <<EOT
# [Service]
# Type=simple
# ExecStart=
# ExecStart=-/usr/bin/agetty --autologin $user -s %I 115200,38400,9600 vt102
# EOT


### ENABLE Services
systemctl enable sshd.service


## Create initial database running as root
# /usr/bin/mandb --quiet
