#!/bin/bash -e
source ~/sys_funcs
is_enabled 'vbox' || exit 0

user="${SYS_USER:?No}"

## Authorize SSH access to guest from host
if [[ -f ~/id_rsa.pub ]]; then
    home="/home/$user"
    auth="$home/.ssh/authorized_keys"
    mkdir -p ${auth%/*} && cp -vfT ~/id_rsa.pub $auth
    chown -R $user:$user ${auth%/*} && chmod 600 ${auth}

    cp -vrft $home ~/user
    chown -R $user:$user $home/user && chmod -R 700 $home/user
fi

echo ":: add VBOX to authorized_keys of '$user' "


### ENABLE Services
pacman -S --noconfirm openssh
systemctl enable sshd.service
