#!/usr/bin/env bash
if ! [[ "$(uname -n)" =~ archiso|vbox ]]; then echo "Use under vbox guest!"; exit 1; fi

user="${1?No user specified}"


### ADD users:  https://wiki.archlinux.org/index.php/Users_and_groups#User_groups
# adbusers, mpd, vboxsf, vboxusers, wireshark
groupadd $user
useradd -m -g $user -G users,wheel,uucp -s /bin/bash $user
printf $user:$user | chpasswd
echo ":: created '$user' password"


## SSH access: add host public key to vbox guest
home="/home/$user"
key="$home/.ssh/authorized_keys"
mkdir -p ${key%/*} && cp -vf ~/id_rsa.pub $key
chown -R $user:$user ${key%/*} && chmod 600 ${key}

cp -vrft $home ~/user
chown -R $user:$user $home/user && chmod -R 700 $home/user
