#!/usr/bin/env zsh
#%SUMMARY: initialize cloned git-annex repo to default settings
#%USAGE: $ ./$0
set -o errexit -o noclobber -o noglob -o nounset -o pipefail

### PREPARE ######################################
here=$0:A:h

[[ -f .gitattributes ]] || <$here/gitattributes sed '/^#%/d;/  #%.*/s///' >.gitattributes

# NOTE: don't compare comments and empty lines
diff -u -- <(sed '/^#/d;/^$/d;/  #%.*/s///' $here/gitattributes) <(sed '/^#/d;/^$/d' .gitattributes)

## RQ: for git-annex to commit anything
# NEED: $ gmy -m
git config --get user.name
git config --get user.email
echo

# git -c annex.tune.objecthash1=true annex init ⌇⡞⡀⠝⠺
#   https://git-annex.branchable.com/tuning/
# DISABLED(annex.tune.branchhash1=true): use two-level hierarchy in git-annex branch to reduce each tree-commit size
git -c annex.tune.objecthash1=true \
    -c annex.tune.objecthashlower=true \
    -c annex.tune.branchhash1=true \
  annex init $@

# WARN: maybe also must edit local .git/info/attributes by hooks/post_checkout
#  making it easier to smudge dotfiles ⌇⡞⡀⠞⢧
#    https://git-annex.branchable.com/todo/making_it_easier_to_smudge_dotfiles/


### GENERIC ######################################

## MAINT: I prefer to run $ git annex upgrade $ only when mentally prepared to fix problems
git config --local 'annex.autoupgraderepository' false

## SECU: don't store keys in files, better use memory-only GPG encrypted keys
git config --local 'annex.cachecreds' false

## CHECK: it seems by disabling it git-annex assistant won't auto-restart ?
git config --local 'annex.autoupgrade' false



### ADD ##########################################

# NOTE:(SHA256): I don't care about "special/broken" programs at all,
#   therefore I don't need hashing with SHA256E extension
#   NICE: the same files {./aaa.jpg, ./aaa.JPG, ./aaa.56.jpg} will have same hash
# 2021-03-07 CHG:(SHA256E): qute/chromium, ranger/scope.sh, imv(1), etc. always use realpath
#   NEED: renormalize all files extensions: ⌇⡠⡑⣕⡸
#   $ find -type d \( -name .git -or -name .snapshots \) -prune -o \( -type f -or -type l \) -regex '.+[.][^.]*[A-Z][^.]*' -print
git config --local 'annex.backend' SHA256E

## DECI? "git add" will never add files to git-annex
## FAIL: may accidentally add large files by 'gaa'
## BUT:BET? filter-out large files post-factum based on .git large files statistics
# git config --local 'annex.gitaddtoannex' false
git config --local 'annex.gitaddtoannex' true

## DECI: skip small files in annex, use solely "git add"
## BET? keep small files untouched to commit with better msg
git config --local 'annex.addsmallfiles' false

## NOTE: generate git-annex branch metainformation
## HACK:(metadata): used to create focused *view* branches
# * file: modification month, day, year
# * feed: author, title
# BAD:PERF:THINK: not sure if it's worth it
#   => maybe use only :: https://github.com/przemoc/metastore
# NICE: useful for media files timeline -- BUT: useless for "aura"
git config --local 'annex.genmetadata' true
# git config --local 'annex.genmetadata' false

## BAD:(=cpus): use all available CPU
## BET※⡟⠭⣧⡻:saturation(10%/job>>VFS/NVMe/SSD/HDD-USB): neo=4/5/?/1 fractal=7/7/5/1
git config --local 'annex.jobs' 5

## FIXED:ERR: You have enabled concurrency, but git-annex is not able to use ssh connection caching
git config --local 'annex.sshcaching' true


# DEBUG: $ git annex matchexpression 'largerthan=100kb or not (mimetype=text/* or mimetype=inode/x-empty)' --file=my.txt --size=100kb --mimetype=text/x-empt --largefiles
git annex config --set 'annex.largefiles' \
  'largerthan=100kb or include=*.mht or mimetype=text/html or not (mimetype=text/* or mimetype=inode/x-empty or mimetype=inode/symlink)'

## NOTE: always add '.*' files directly to git
git annex config --set 'annex.dotfiles' false

## NICE: only sync "git-annex" branch and content -- don't touch other branches
git annex config --set 'annex.synconlyannex' true


### CHECKOUT #####################################

## NOTE: always unlock my drawing-projects
## TODO: enable after CHECK -- because "git status" seems to be slow due to smudge filter
##   git status smudges unncessarily after unlock ⌇⡞⡀⠢⠉
##     https://git-annex.branchable.com/todo/git_status_smudges_unncessarily_after_unlock/
# git annex config --set 'annex.addunlocked' \
#   'include=*.kra'



### SYNC #########################################

## NOTE: checked by "git annex drop" and "git annex {--all|--unused|--key}"
## WARN:CHECK: maybe will keep copies even for old deleted files still in history (--unused)
git annex numcopies 2

## NOTE: prevent "git-annex sync" from doing commit
#  I prefer using my own heuristics from r.git-my-msg for commit msg
## TODO: enable after CHECK
git annex config --set 'annex.autocommit' false

## FIND: how exactly "annex.resolvemerge" resolves merge
## TODO: enable after CHECK
# git annex config --set 'annex.resolvemerge' false

## NOTE: always sync both metadata and content
## TODO: enable after CHECK
# git annex config --set 'annex.synccontent' true


### DEBUG #########################################
# git config --list
# git config --local --list
# git config --global --list
