#!/bin/bash -e
cd $(dirname $(readlink -m ${0})) && source ~/.shell/func.d/cfgsetup
[[ "$THEME" =~ ^(dark|light)$ ]] || THEME=dark

### LINKS ###
link "$PWD/copyq.conf" ~/.config/copyq/copyq.conf
link "$PWD/rtorrent.rc" ~/.rtorrent.rc
link "$PWD/zathurarc-${THEME}"  ~/.config/zathura/zathurarc
