[General]
JPEGSaveQuality=95
autoResizeLimit=90
autoResizeWindow=false
backgroundOpacity=1
blurBackground=false
clickableEdges=false
clickableEdgesVisible=true
confirmDelete=true
confirmTrash=true
cursorAutohiding=true
defaultCropAction=0
defaultFitMode=0
defaultViewMode=0
drawTransparencyGrid=false
enableSmoothScroll=true
expandImage=true
expandLimit=2
firstRun=false
fixedZoomLevels="0.05,0.1,0.125,0.166,0.25,0.333,0.5,0.66,1,1.5,2,3,4,5,6,7,8"
focusPointIn1to1Mode=1
folderEndAction=0
folderViewIconSize=260
imageScrolling=1
infoBarFullscreen=true
infoBarWindowed=false
jxlAnimation=false
keepFitMode=true
language=en_US
lastVerMajor=1
lastVerMicro=3
lastVerMinor=0
loopSlideshow=false
memoryAllocationLimit=1024
mouseScrollingSpeed=1
mpvBinary=/usr/bin/mpv
openInFullscreen=false
panelCenterSelection=false
panelEnabled=true
panelFullscreenOnly=true
panelPinned=false
panelPosition=top
panelPreviewsSize=250
playVideoSounds=false
scalingFilter=3
showHiddenFiles=false
showSaveOverlay=true
slideshowInterval=3000
smoothAnimatedImages=true
smoothUpscaling=true
sortFolders=true
sortingMode=0
squareThumbnails=false
thumbPanelStyle=1
thumbnailCache=true
thumbnailerThreads=4
trackpadDetection=true
unloadThumbs=true
unlockMinZoom=true
useFixedZoomLevels=false
usePreloader=true
useSystemColorScheme=false
videoPlayback=true
windowTitleExtendedInfo=true
zoomIndicatorMode=0
zoomStep=0.20000000298023224

[Controls]
shortcuts="exit=\"", "exit='", "zoomIn=+", "frameStepBack=,", "zoomOut=-", "frameStep=.", "fitWindow=1", "fitWidth=2", "fitNormal=3", "fitWindowStretch=4", "zoomIn=eq", "exit=Alt+X", "folderView=Backspace", "copyPathClipboard=C", "zoomIn=Ctrl++", "zoomOut=Ctrl+-", "zoomIn=Ctrl+eq", "copyFileClipboard=Ctrl+C", "showInDirectory=Ctrl+D", "zoomOut=Ctrl+Down", "rotateLeft=Ctrl+L", "seekVideoBackward=Ctrl+Left", "open=Ctrl+O", "print=Ctrl+P", "exit=Ctrl+Q", "rotateRight=Ctrl+R", "seekVideoForward=Ctrl+Right", "save=Ctrl+S", "copyPathClipboard=Ctrl+Shift+C", "saveAs=Ctrl+Shift+S", "zoomIn=Ctrl+Up", "pasteFile=Ctrl+V", "setWallpaper=Ctrl+W", "zoomOutCursor=Ctrl+WheelDown", "zoomInCursor=Ctrl+WheelUp", "discardEdits=Ctrl+Z", "toggleShuffle=Ctrl+`", "closeFullScreenOrExit=D", "moveToTrash=Del", "scrollDown=Down", "jumpToLast=End", "folderView=Enter", "closeFullScreenOrExit=Esc", "toggleFullscreen=F", "toggleFullscreen=F11", "renameFile=F2", "reloadImage=F5", "toggleFitMode=H", "jumpToFirst=Home", "toggleImageInfo=I", "nextImage=J", "prevImage=K", "removeFile=L", "toggleFullscreen=LMB_DoubleClick", "prevImage=Left", "contextMenu=Menu", "exit=MiddleButton", "openSettings=P", "exit=Q", "resize=R", "contextMenu=RMB", "nextImage=Right", "removeFile=Shift+Del", "prevDirectory=Shift+Left", "nextDirectory=Shift+Right", "pauseVideo=Space", "scrollUp=Up", "flipV=V", "nextImage=WheelDown", "prevImage=WheelUp", "removeFile=X", "prevImage=XButton1", "nextImage=XButton2", "copyPathClipboard=Y", "toggleSlideshow=`"

[Scripts]
script\size=0
