#!/bin/bash -e
source ~/.shell/func.d/packages
has_pr X || die

if distro arch; then
    # Install 'Adwaita' to eliminate warnings in GTK apps
    pkg_inst -l 'gtk-x11-2.0' gtk2
    pkg_inst -l 'gtk-3' gtk3
    pkg_inst -d '/usr/share/themes/Adwaita' gnome-themes-standard

    aur_inst -d '/usr/share/themes/FlatStudio' gtk-theme-flatstudio
    # mate-themes numix-themes
    aur_inst -d '/usr/share/themes/Vertex'  vertex-themes
    aur_inst -d '/usr/share/themes/Zukitwo' zuki-themes
    aur_inst -d '/usr/share/themes/Ceti-2'  ceti-2-themes

    # Icons
    pkg_inst -d '/usr/share/icons/hicolor' hicolor-icon-theme
    pkg_inst -d '/usr/share/icons/Faenza'  faenza-icon-theme

elif distro ubuntu; then
    echo "ERR: install manually"
    if [[ ! -d /usr/share/themes/Vertex-Dark ]]; then
        sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_14.04/ /' > /etc/apt/sources.list.d/vertex-theme.list"
        sudo apt-get update
        sudo apt-get install vertex-theme
    fi
fi
