#!/bin/bash -e
# tags: xorg
source ~/.shell/func.d/cfgsetup

### GENS ###
./gtk.gen

## Use gtk themes for Qt4
cfg=~/.config/Trolltech.conf
if [[ -f "$cfg" ]]; then
    if grep -q 'style=' "$cfg"
    then sed -ri '/^(style=).*/s//\1GTK+/' "$cfg"
    else sed -ri '/\[Qt\]/s//\0\nstyle=GTK+/' "$cfg"; fi
    echo "W: $cfg"
    # gconftool-2 --set --type string /desktop/gnome/interface/gtk_theme Vertex-Dark
    # Maybe install libgnomeui -- people says then theme will work?
fi
