#!/bin/bash -e
# Tool to search cycle loading order in units
# (because all such units won't be loaded)

# CHECK: works only when there are cycles?
systemd-analyze --user verify main.target \
|& perl -lne 'print $1 if m{Found.*?on\s+([^/]+)}' \
| xargs --no-run-if-empty systemd-analyze dot \
