#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
link xprofile ~/.xprofile
link xinitrc  ~/.xinitrc
link -t "${CURR_DIR_CACHE?}/bin" startx auto-start

### GENS ###
# ALT: sudo loadkeys "$dst"
# SEE: man vconsole.conf
if cfgOpt u; then
    dst='/usr/local/etc/vconsole.map'
    link -sc "${dst##*/}" "$dst"
    sudo tee /etc/vconsole.conf <<<"KEYMAP=$dst"
fi
