#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### systemd ###
link -sct /etc/X11 Xwrapper.config
usvc_activate -e \
  {demons,main,wm}.target \
  xorg.{socket,service,target}

### startx ###
link xprofile ~/.xprofile
link xinitrc  ~/.xinitrc
link -t "${CURR_DIR_CACHE:?}/bin" startx auto-start
