#!/bin/bash -e
shopt -s nullglob

session=("${@:-xmonad}")
exec >/var/tmp/"${session}_$(date +%Y%m%d_%H%M%S).log" 2>&1
export XDG_CURRENT_DESKTOP="$session"

# USAGE:
#   startx
#   startx ~/.xinitrc xmonad
#   startx /full/path/to/window-manager
#   pkill -15 Xorg

# SEE: https://wiki.archlinux.org/index.php/Xinitrc#On_the_command_line
# SEE: https://pbrisbin.com/posts/systemd-user/
# READ: http://blog.codezen.org/2012/02/09/on-wayland-systemd-and-convergence/
# ADD https://wiki.archlinux.org/index.php/Running_program_in_separate_X_display
# TRY: run startx in separate tmux server to see logout messages
#   http://jasonwryan.com/blog/2011/12/18/login/

# Merge in defaults and resources
XINT=/etc/X11/xinit
# [[ ! -f "$XINT/.Xresources" ]] || xrdb -merge "$XINT/.Xresources"
[[ ! -f "$HOME/.Xresources" ]] || xrdb -merge "$HOME/.Xresources"

# Start dbus, ... -- populated from packages
for f in "$XINT/xinitrc.d"/?*; do
    [[ ! -x "$f" ]] || source "$f"; done

# Source X settings and programs
# CHECK:SEE: double-sourcing of xprofile by DM
#   https://wiki.archlinux.org/index.php/xprofile
[[ ! -f "$HOME/.xprofile" ]] || source "$HOME/.xprofile"

case "$session"
in xterm) session=(xterm -geometry 80x66+0+0 -name login)
;;    st) session=(st -g 80x66+0+0 -name login)
esac

# Launch session
(hash auto-start &>/dev/null && auto-start -w) &
exec "${session[@]}"
# jobs -p | xargs -r kill
