#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
    pkg_inst neovim
    # aur_inst neovim-git

    pkg_inst gvim  # necessary for 'xxd'
    # ALT:(gvim):
    # aur/xxd-standalone
    # aur/go-xxd
    # aur/xxd-vim

    pkg_inst python-neovim python2-neovim
    aur_inst neovim-remote  # VIZ. $ nvr to talk to vim from inside ranger

    # pkg_inst python-yaml
    pkg_inst python-jedi
    pkg_inst ghc-mod

    ## External deps
    # pkg_inst tidy / tidy-html5
    # aur_inst js-beautify
    # BAD python-autopep8 beautify-css

elif distro ubuntu; then
    # for vimoutliner export in mindmap
    pkg_inst vim-gtk #python3-yaml

    ppa_add 'ppa:neovim-ppa/unstable'
    pkg_inst neovim

    pip_inst jedi  # neovim
    echo "Err: not all"
fi
