#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
    pkg_inst -p 'nvim' neovim
    pkg_inst -p 'vim' gvim  # necessary for 'xxd'
    pkg_inst -y 'neovim' python-neovim
    pkg_inst -Y 'neovim' python2-neovim
    # pkg_inst -y 'yaml' python-yaml
    pkg_inst -y 'jedi' python-jedi
    pkg_inst ghc-mod

    ## External deps
    aur_inst -p zeal zeal-git
    pkg_inst hlint
    ## For vim-clang-format and vim-autoformatter
#    pkg_inst -p 'clang-format' clang-tools-extra
#    pkg_inst astyle tidy
#    aur_inst js-beautify  # BAD python-autopep8 beautify-css

elif distro ubuntu; then
    # for vimoutliner export in mindmap
    pkg_inst vim-gtk #python3-yaml

    ppa_add 'ppa:neovim-ppa/unstable'
    pkg_inst neovim
    # NOTE: duplicated for $ ssh -X
    pkg_inst xsel

    # libclang-dev for autocompleter in vim
    # pkg_inst libclang-dev clang-format-3.5
    pip_inst jedi  # neovim
    echo "Err: not all"
fi

# Install vim plugins
# BAD: firstly NEED 'setup' for 'dein'
# ./update $(cfgOpt u && echo -u)
