#!/bin/bash -eu
set -euo pipefail

## Check filemarker to auto-update only once a day
marker=~/.cache/vim/dein/updated
t_upd=$(command stat -c%Y "$marker" 2>/dev/null||:)
doupdate=0
[[ " $* " =~ " -U " ]] && doupdate=1
[[ " $* " =~ " -u " ]] && (( $(date -d yesterday +'%s') > t_upd )) && doupdate=1

### PLUGINS ###
# BUG: returns non-zero errcode!
# BUG: no parallel dld on nvim -- only vimproc works
# FIXME: error on clean system, when NeoBundle is not installed yet
# DEV:TODO: use 'g:dein#install_log_filename' instead of 'redir!'

# NOTE: EDITOR=vim ./update
# -nesR -u "$PWD/vimrc" ... -- ./vimrc
shvim() { ${EDITOR:-nvim} -nR \
  -c "set nomore|redir!>/dev/tty" \
  -c "$1" \
  -c "echo''|redir END|qall!" \
  >/dev/null </dev/tty ||:; }  # return $(($?-1)); }

cmd='call dein#clear_state()'
((doupdate)) && cmd+='|call dein#update()'
cmd+='|if dein#check_install()| call dein#install() |else| call dein#recache_runtimepath() |en'
cmd+='|call dein#remote_plugins()'

shvim "$cmd"

## Update filemarker modification date
((!doupdate))||touch "$marker"
