#!/bin/bash -eu
# tags: core
source ~/.shell/func.d/cfgsetup

svc_activate -cE battery-notify@.service
linkcp -ct '/etc/udev/rules.d' unit/96-battery-nofity.rules

# env-subs 96-battery-nofity.rules | sudo tee /etc/udev/rules.d/96-battery-nofity.rules >/dev/null
if cfgOpt u; then
  sudo udevadm control --reload-rules
fi

# Disable bluetooth
# THINK: replace by blacklisting?
# svc_activate -e rfkill-block@bluetooth
# linkcp -t '/etc/modprobe.d' blacklist-powersave.conf
