#!/bin/bash -eu
source ~/.shell/func.d/packages

pkg_inst nvidia nvidia-utils lib32-nvidia-utils

# Only for standalone nvidia USE: mesa-demos=glxinfo
pkg_inst nvidia-settings mesa-demos libva-utils nvtop
