#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### GENS ###
svc_activate -cE monitor-hotplug@.service

### LINKS ###
# THINK: embed *.rules support into svc_activate
#   ALT: create 'udev_activate' or r.udev-cfg
linkcp -ct '/etc/udev/rules.d' unit/95-monitor-hotplug.rules

if cfgOpt u; then
  sudo udevadm control --reload-rules
fi
