#!/bin/sh -eu
cd "${0%/*}/gh-pages"

# NOTE: don't use 'compile' and remove '--skip-initial-build'
bundle exec jekyll serve --skip-initial-build --watch &
# bundle exec jekyll serve --detach --skip-initial-build
# => Use `--no-watch` to disable auto-regeneration.
#    kill -9 pid to kill

# TODO: sync lock to concrete window (until exited)
r.b http://localhost:4000 2>/dev/null
wait
