#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

if cfgOpt r; then
  d='gh-pages'
  printf "/%s/\n" "$d" > .gitignore
  if [[ ! -d $d ]]; then
    mkdir -p "$d"
    u=$(git remote get-url origin) || u=$PWD
    git clone "$u" "$d" --single-branch -b "${d##*/}"
  fi
  r.git-my-repo "$d"
  git branch -r | grep -qF origin/"$d" && git branch -dr origin/"$d"
fi

### LINKS ###
# linkcp -t ~/.config/git ignore attributes
