#!/bin/bash -e
source ~/.shell/func.d/packages

#| suckless-tools | 'dmenu' -- by mod+D prs
#|                | 'tabbed' -- generic tabbed fronted for surf, st, uzbl, urxvt and xterm

if distro arch; then
    pkg_inst dmenu
elif distro ubuntu; then
    pkg_inst suckless-tools
fi
