#!/bin/bash -e
source ~/.shell/func.d/packages

#| suckless-tools | 'dmenu' -- by mod+D prs
#|                | 'tabbed' -- generic tabbed fronted for surf, st, uzbl, urxvt and xterm

pkg_inst suckless-tools
