#!/bin/bash -e

# ls binaries
# dmenu-frecency

case "$1"
in -n) action(){ r.dunst-cmd; }
;;  *) action(){ "${SHELL:-/bin/sh}"; }
esac

OPTS=(-p 'yes, master?' -fn xfg:PragmataPro:size=10
     -nb '#000000' -nf '#B0E0E6' -sb '#421C84' -sf '#FFFF00')

eval dmenu_path | dmenu "${OPTS[@]}" | action &

# -misc-fixed-medium-r-normal-*-*-130-75-75-*-*-iso8859-2

# UNNECESSARY:
# rofi -now -font 'Sans-10' -fg '#606060' -bg '#000000' -hlfg '#ffc964' -hlbg '#0C0C00' -o 85
