#!/bin/bash -e
source ~/.shell/profile

# WINEDEBUG=fps
# xosd-bin
primusrun playonlinux
# PRIMUS_VERBOSE=2 primusrun glxgears 2>&1 \
    # | sed -rn 's/.*display.*, (\S+) fps,.*/\1/p' > /tmp/wine
    # | osd_cat --lines=1 --color=yellow --font="-*-fixed-*-*-*-*-18-*-*-*-*-*-*-*"


# Start PlayOnLinux, click "Install", and then "Install a non-listed program"
# 3. When you see "Install some libraries", check it.
# 4. When presented with the next list, install xact ("POL_install_xact") so XAudio2 will be available to play the music.
