#!/bin/bash -eu
source ~/.shell/func.d/packages

# atool -- previews of archives
pkg_inst atool zip unzip unrar

# pkg_inst sharutils  # OR some uuencode

if distro arch; then
  pkg_inst p7zip

elif distro ubuntu; then
  pkg_inst p7zip-full
fi
