#!/bin/bash -eu
source ~/.shell/func.d/packages

# ALSO:SEE: transparently using gz/bz2/lzma/sz
#   http://noone.org/blog/English/Computer/Debian/CoolTools/zutils.html

# atool -- previews of archives
pkg_inst atool zip unzip unrar

## 2021-06-01 [_] CHECK: if official release is distributed
# pkg_inst avfs  # archives in FUSE navigation ALT: !ratarmount
loc_inst avfs-git.pkgbuild

loc_inst t2sz-git.pkgbuild

# Multi-threaded compression with rzip/lzma, lzo, and zpaq
# pkg_inst lrzip

# pkg_inst sharutils  # OR some uuencode

if distro arch; then
  pkg_inst p7zip

elif distro ubuntu; then
  pkg_inst p7zip-full
fi
