#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

# SEE:
# http://www.techrapid.co.uk/linux/arch-linux/improve-font-rendering-on-arch-linux/

### LINKS ###
# Disabled -- use infinality-bundle instead
# link "$PWD/fonts.conf" ~/.config/fontconfig/fonts.conf

### GENS ###
"$PWD/gtk.gen"

## Use gtk themes for Qt4
cfg=~/.config/Trolltech.conf
if [[ -f "$cfg" ]]; then
    if grep -q 'style=' "$cfg"
    then sed -ri '/^(style=).*/s//\1GTK+/' "$cfg"
    else sed -ri '/\[Qt\]/s//\0\nstyle=GTK+/' "$cfg"; fi
    echo "W: $cfg"
    # gconftool-2 --set --type string /desktop/gnome/interface/gtk_theme Vertex-Dark
    # Maybe install libgnomeui -- people says then theme will work?
fi


if cfgOpt u; then
    # cfg=/etc/fonts/conf.d/10-scale-bitmap-fonts.conf
    # if [[ -L $cfg ]]; then rm $cfg; fi
    sudo ln -svf /etc/fonts/{conf.avail,conf.d}/70-no-bitmaps.conf
    mkfontscale ~/.fonts
    mkfontdir ~/.fonts
    sudo fc-cache -vf ~/.fonts  # fc-cache -fs >/dev/null
fi

## Setup
# https://wiki.archlinux.org/index.php/Font_configuration
# http://vincent.jousse.org/tech/archlinux-retina-hidpi-macbookpro-xmonad/

## Fonts
# To achieve system-wide effect, place the xml config inside
# /etc/fonts/conf.avail/29-prettify.conf and enable loading by symlinking it:
# ln -s /etc/fonts/conf.avail/29-prettify.conf /etc/fonts/conf.d/29-prettify.conf

# To disable scaling of bitmap fonts (which often makes them blurry), remove
#   /etc/fonts/conf.d/10-scale-bitmap-fonts.conf

dst=~/.Xresources
wstr(){ cat >> "$dst" <<<"$*"; }

> "$dst"
wstr "#define MAIN_DPI  ${MAIN_DPI:-96}"
wstr "#define FONT_SIZE ${FONT_SIZE:-size=10}"
for f in "${CURR_DIR_CACHE:?}"/Xres-*; do
  wstr "#include \"$f\""
done
cat "$PWD/xfontrc" >> "$dst"
echo "W: ~/.Xresources"
! xrdb -load ~/.Xresources 2>&1 | grep 'error'
# To see the current loaded resources
#   xrdb -query -all
