#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
link "$PWD/gtkrc-2.0" ~/.gtkrc-2.0
link "$PWD/settings.ini" ~/.config/gtk-3.0/settings.ini


link "$PWD/fonts.conf" ~/.config/fontconfig/fonts.conf

## Use gtk themes for Qt4
cfg=~/.config/Trolltech.conf
if [[ -f "$cfg" ]]; then
    if grep -q 'style=' "$cfg"
    then sed -i -r '/^(style=).*/s//\1GTK+/' "$cfg"
    else sed -i- r '/\[Qt\]/s//\0\nstyle=GTK+/' "$cfg"; fi
    echo "W: $cfg"
    # gconftool-2 --set --type string /desktop/gnome/interface/gtk_theme Vertex-Dark
    # Maybe install libgnomeui -- people says then theme will work?
fi


if cfgOpt u; then
    fc-cache -vf ~/.fonts
fi

## Setup
# https://wiki.archlinux.org/index.php/Font_configuration

## Fonts
# To achieve system-wide effect, place the xml config inside
# /etc/fonts/conf.avail/29-prettify.conf and enable loading by symlinking it:
# ln -s /etc/fonts/conf.avail/29-prettify.conf /etc/fonts/conf.d/29-prettify.conf

# To disable scaling of bitmap fonts (which often makes them blurry), remove
#   /etc/fonts/conf.d/10-scale-bitmap-fonts.conf
