#!/bin/bash -eu
source ~/.shell/func.d/packages
# from j4tools for i3 -- notifier in top-right corner

if distro arch; then
  # pkg_inst dunst    # BAD: no "dunstify"
  aur_inst dunst-git  # dunst+dunstify

elif distro ubuntu; then
  pkg_inst dunst
fi
