#!/bin/bash -eu
source ~/.shell/func.d/packages
# from j4tools for i3 -- notifier in top-right corner

# ALT:
# Sweets/tiramisu: Desktop notifications, the UNIX way ⌇⡠⡏⡖⣓
#   https://github.com/Sweets/tiramisu
# dudik/herbe: Daemon-less notifications without D-Bus. Minimal and lightweight. ⌇⡠⡏⡖⣤
#   https://github.com/dudik/herbe
# deifactor/ninomiya: An (incomplete) lightweight, beautiful notification daemon for Linux. ⌇⡠⡟⣂⠒
#   https://github.com/deifactor/ninomiya

if distro arch; then
  pkg_inst dunst
  # aur_inst dunst-git  # dunst+dunstify

elif distro ubuntu; then
  pkg_inst dunst
fi
