#!/bin/bash -e
# tags: xorg
# deps: xorg
source ~/.shell/func.d/cfgsetup

### GENS ###
dst=~/.config/dunst/dunstrc
linkcp -c dunstrc "$dst"

dpi=$(r.airy-registry dpi "$(r.xorg -d 2>/dev/null)" 96)
fw=$(( dpi / 60 ))
gw=$(( $(r.xorg -w 2>/dev/null||echo 1280) * 2/5 ))
iw=$(( ( (dpi + 8)/16 + 3)/6 * 16 ))
sed -ri '
  /^(\s+geometry = ")[0-9]+(x.*)/s//\1'$gw'\2/
  /^(\s+width = )[0-9]+/s//\1'$fw'/
  /^(\s+icon_folders = ).*/s/16/'$iw'/g
' "$dst"
## OBSOLETE: font size fixed in latest release
## BUG: external monitor -- different dpi
# fs=$(( (dpi + 5) / 10 ))
# /^(\s+font = \w+).*/s//\1 '$fs'/


## To disable default notification daemon
if ! distro arch; then
  dfl=/usr/share/dbus-1/services/
  if distro ubuntu; then
    dfl+=org.freedesktop.Notifications.service
  elif distro lubuntu; then
    dfl+=org.xfce.xfce4-notifyd.Notifications.service
  fi
  [[ ! -f $dfl ]] || sudo mv -n $dfl{,.disabled}
fi

svc_activate -cue dunst.service
# ALT: ! grep_prs dunst || ./run  # BUG: hangs up airy/setup
