#!/bin/bash -e

dldcmd=r.wgetf
session=wget
maincmd='source r.ranger'

while getopts 'jlc:d:o:t:yw' o; do case $o
in o) cd "${OPTARG/#\~/$HOME}"  # THINK: replace with dir= for youtube-dl, etc?
;; c) opencmd=$OPTARG
;; j) jobargs=-j
;; d) dldcmd=$OPTARG
;; l) dldcmd=r.wgetl
;; y) dldcmd=youtube-dl
;; t) session=$OPTARG
;; w) maincmd="r.notify-watch '$PWD'"
;; *) exit 3; esac; done; shift $((OPTIND-1))



if [[ $dldcmd =~ youtube ]]; then
  fnm=$(youtube-dl --get-filename "${1:?}")
  fnm=${fnm##*/}
else
  fnm=$(r.wget-nm "${@:?}")
fi


r.tmux-job -t "$session" -m "$maincmd" $jobargs -- \
  r.notify-cmd -n "Saved: $fnm" -f "Failed dld: $fnm" -- \
    $dldcmd "${@:?}"
r.notify "Started" "${@:?}"

# ADD: check if dld part of file is more then 5MB or sleep 4
# DEV: close mpv after file moved
# USE: env DSTDIR for r.dmenu-mv to be able to sort music
# -- cd dir; DSTDIR=$PWD ranger -> mpv -> r.dmenu-mv
# -- if playlist -- don't close, simply delete from list and move to next
# ADD:(wget/bin/amvnews)
# -- extracting text info from page with song/anime/description
# -- parse page and find more appropriate link if possible
if [[ $opencmd ]]; then
  # WARNING: $1 must be real prg name, not bash wrapper
  if ps -oargs= -C "$opencmd" | grep -qxF "$fnm"
  then r.n -u 'Already opened!' "$fnm"
  else
    (($(stat -c%s "$fnm") > 5*1024*1024)) || sleep 5
    ($opencmd "$fnm")  # trap 'wait' EXIT
  fi
fi
