#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
link "$PWD/pdbrc" ~/.pdbrc
# DFL: generate by $ ipython profile create
link -t ~/.ipython/profile_default 'ipython_config.py'
# pudb.cfg
# sudo chown -R $USER:$USER ~/.config/pudb
