#!/bin/bash -eu
source ~/.shell/func.d/packages

# TUT: http://www.brendangregg.com/blog/2014-05-11/strace-wow-much-syscall.html
# TUT:(debug deps): https://bastienleonard.com/blog/2011/03/12/how-to-use-strace-to-fix-program-dependencies-on-arch-linux/
# strace -- trace system calls, is much easier and safer to use.
pkg_inst strace

# ltrace -- can trace both system calls and library calls
#   -- is more prone to crash traced processes than strace.
pkg_inst ltrace

if distro arch; then :
  # BUG: git.debian.org[0: 194.177.211.202]: errno=Connection refused
  # aur_inst xtrace-git
  # ALSO: xscope -- to monitor Xorg traffic
  # ALSO: extrace-git for exec()
fi
