#!/bin/bash -eu
source ~/.shell/func.d/packages

# TUT: http://www.brendangregg.com/blog/2014-05-11/strace-wow-much-syscall.html
# TUT:(debug deps): https://bastienleonard.com/blog/2011/03/12/how-to-use-strace-to-fix-program-dependencies-on-arch-linux/
# strace -- trace system calls, is much easier and safer to use.
pkg_inst strace

# ltrace -- can trace both system calls and library calls
#   -- is more prone to crash traced processes than strace.
pkg_inst ltrace

if distro arch; then
  aur_inst xtrace-git
fi
