#!/bin/bash -e
source ~/.shell/profile
[[ "$CURR_PROF" =~ ^(home) ]] || exit

setm() { local sz=${1:-1920x1080}; shift
    if ! xrandr -q | sed '/^VGA1/,/^\S/!d' | grep -q "$sz"; then
        xrandr --addmode VGA1 "$sz"
    fi
    xrandr --output VGA1 --mode $sz --primary \
           --output LVDS1 ${@:---off};
}

case "${1#-}"
in g|game) setm 1280x720
;; d|dual) setm 1280x720 --mode 1366x768 --right-of VGA1
;; n|norm|*) setm 1920x1080 --mode 1366x768 --pos 1920x312
esac

echo "NOTE: disable composition to reduce performance impact!"
