#!/bin/bash -e
source ~/.shell/profile
[[ $CURR_PROF =~ ^neo ]] || exit

setm() { local sz=${1:-3840x2160}; shift
    xrandr --output eDP1 --mode $sz
}

# TODO: change dpi accordingly
# BUG: all X apps need to restart!

case "${1#-}"
in 3|t|third)   setm 1280x720
;; 2|h|half)    setm 1920x1080
;; 1|f|full|*)  setm 3840x2160
esac
