#!/bin/bash -eu
# tags: net chat
source ~/.shell/func.d/cfgsetup

### GENS ###
export IRC_NICK=${IRC_NICK:?} IRC_USER=${IRC_USER:?} IRC_CHAN=${IRC_CHAN:?}
weechat -a -r '/exec -sh env-subs ./cfg/weechat.conf|./run' -r /quit
# ALT: { sleep 0.5; ./run "$cfg"; ./run <<< "/quit"; } & weechat -a; wait
