#!/bin/bash -e
# Run from /home/media/_play/wineprefix/$game/drive_c/users/amer

lst=(
  'Desktop'
  'My Documents'
  'My Music'
  'My Pictures'
  'My Videos'
)

for L in "${lst[@]}"; do
  [[ -L $L || ! -e $L ]]
  rm "$L"
  ln -svf /home/media/_play/_saves "$L"
done
