#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
  aur_inst pqiv
fi

# BET:TRY: pqiv + libspectre poppler imagemagick
# https://github.com/phillipberndt/pqiv/


# ALT:(pqiv): image viewers
# https://wiki.archlinux.org/index.php/list_of_applications#Graphical_image_viewers
#
# Geeqie Image Viewer -- Main Project Page ⌇⡞⣝⢘⣱
#   http://geeqie.org/
# fbida | kraxel’s news ⌇⡞⣝⢘⣶
#   https://www.kraxel.org/blog/linux/fbida/
# eXeC64/imv: Image viewer for X11/Wayland ⌇⡞⣝⢘⣹
#   https://github.com/eXeC64/imv/
# + meh... - John Hawthorn ⌇⡞⣝⢘⣾
#   https://www.johnhawthorn.com/meh/
# oferkv/phototonic: Image Viewer and organizer ⌇⡞⣝⢙⠅
#   https://github.com/oferkv/phototonic/
# nomacs | Image Lounge ⌇⡞⣝⢙⠋
#   https://nomacs.org/
# linuxmint/pix: Image management application ⌇⡞⣝⢙⠎
#   https://github.com/linuxmint/pix
# easymodo/qimgv: Qt5 image viewer with optional video support ⌇⡞⣝⢙⠑
#   https://github.com/easymodo/qimgv/
# danboid/shufti: The persistent image viewer ⌇⡞⣝⢙⠓
#   https://github.com/danboid/shufti
# vimiv ⌇⡞⣝⢙⠖
#   http://karlch.github.io/vimiv/
# kidanger/vpv: Image viewer for image processing experts ⌇⡞⣝⢙⠚
#   https://github.com/kidanger/vpv
