#!/bin/bash -e
SWD=$(readlink -e "$0"); SWD=${SWD%/*}
PATH=$SWD/get:$SWD/mod:$SWD/set:$SWD:$PATH

# prf=krita
prf=xournalpp
# prf=okular

toggle-touch on
keys-reset

# WARN: must switch to "en" xkb layout to map keys
# r.xkb-lang en
prf-$prf

# TODO: xournalpp ring -- change color (isntead of free toolbar)
# NOTE:BAD:(unintuitive): uses next mode after zoom -- undo
# change-mode -p undo2
# change-mode -p zoom

change-curve soft

## VIZ
# zone=$1     # [full|auto|[%]WxH+X+Y]
# frame=$2    # [full|auto|cursor|[%]WxH+X+Y]
# rotate=$3   # [none|half|cw|ccw]
# output=$4   # [ {<output>|1..9} | {desktop|0} | WxH+X+Y || next ]

## TODO:OPT: pick biggest "monitor"
# map-to auto wndclick none 0  # xournalpp
map-to auto full none 0  # krita
# map-to full full none 0  # navi

keys-bind $prf
