# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[[ $- == *i* ]] || return
type -f _has_pr >/dev/null 2>&1 \
  || _has_pr(){ hash "$1" >/dev/null 2>&1; }
# BUG: cd has errors -- when '$ cd' in bash
# BUG: bash can't '.a' to jump between dirs

[[ -d ${TMPDIR:=/tmp} ]] || mkdir -p $TMPDIR
TMPPREFIX=${TMPDIR%/}/${SHELL##*/}

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Expand aliases to be available in scripts
# shopt -s expand_aliases

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# Disable old suspend-continue behaviour on C-s, C-q to intoduce forward-search
# http://unix.stackexchange.com/questions/12107/how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal/12108#12108
# to enable: stty ixany
stty -ixon
# Don't insert ^C in commandline
stty -echoctl

# make less more friendly for non-text input files, see lesspipe(1)
[[ -x /usr/bin/lesspipe ]] && eval "$(SHELL=/bin/sh lesspipe)"
export SHELL=$(which bash)  # NEED: when bash is launched from inside zsh

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [[ -f /usr/share/bash-completion/bash_completion ]]; then
    source /usr/share/bash-completion/bash_completion
  elif [[ -f /etc/bash_completion ]]; then
    source /etc/bash_completion
  fi
fi

# turn on directory spelling typos automagic
shopt -s cdspell

# See /usr/share/doc/bash-doc/examples in the bash-doc package.
source ~/.shell/bash/prompt
source ~/.shell/common
