#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
link "$PWD/bashrc" ~/.bashrc

if distro arch; then
    link "$PWD/profile" ~/.bash_profile
elif distro ubuntu; then
    link "$PWD/profile" ~/.profile
fi
