#!/bin/bash -e
source ~/.shell/func.d/system
running_X || [[ $1 == -t ]] || exec r.bt

log=${TMPDIR:-/tmp}/qute/$(date +%Y%m%d_%H%M%S).log
mkdir -p "${log%/*}"
# exec > $log 2>&1

export QT_AUTO_SCREEN_SCALE_FACTOR=1  # HiDpi for Qt>=5.6

dml(){ dmenu ${1+-l $1} -b -p 'Qute:' \
    -nb '#000000' -nf '#999999' -sb '#000000' -sf '#31AC65' \
    -fn '-misc-fixed-medium-r-normal-*-*-200-75-75-*-*-iso8859-2'
}
run(){ ((!$#)) && r.n Browser "No args" || exec qutebrowser "$@"; }

chtheme(){ local dir=~/.config/qutebrowser
  local n L t=${1:+${1}.css}
  if [[ -z $t ]]; then t=$(readlink -m "$dir/style.css")
    mapfile -t L < <(find -L "$dir/theme" \
      -type f -name '*.css' -printf '%f\n' | sort -n)
    for((i=0; i<${#L[@]:?}; i++)); do
      [[ ! $t =~ ${L[$i]}$ ]] || n=$((i+1))
    done
    n=$((n < ${#L[@]} ? n : 0))
    t=${L[$n]}
  fi
  linkcp "$dir/theme/${t:?}" "$dir/style.css"
}

case "$1"
in -p) shift; run "$(xsel -ob)"
;; -h) shift; run "$(sed 's/^[0-9]\+ //' ~/.local/share/qutebrowser/history | dml 16)"
# ;; -g) shift; run "$(dml < ~/.config/qutebrowser/search)"
;; -s) shift; exec qutebrowser ':allow-javascript=true' "$@"
;; -t) shift; chtheme "$@"
;;  *) exec qutebrowser "$@"
;; esac
