#!/bin/bash -e
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

### LINKS ###
link -t ~/.config/qutebrowser \
  qutebrowser.conf keys.conf

if cfgOpt r || [[ ! -f ~/.local/share/qutebrowser/blocked-hosts ]]; then
  if running_X; then qutebrowser :adblock-update & fi
fi
