#!/bin/bash -e
source ~/.shell/func.d/cfgsetup
[[ "$THEME" =~ ^(dark|light)$ ]] || THEME=dark

### LINKS ###
link -t ~/.config/qutebrowser \
    qutebrowser.conf keys.conf

if cfgOpt r; then
    qutebrowser :adblock-update :close
fi
