#!/bin/bash -e
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

### LINKS ###
link -t ~/.config/qutebrowser \
  qutebrowser.conf keys.conf

if cfgOpt u; then
  qutebrowser :adblock-update :close
fi
