#!/bin/bash

# CARD="${1:-0}"
# MIXER="${2:-default}" # use pulse for pulseaudio, default is alsa

case $BLOCK_BUTTON in
    1) ARG='-t' ;;
    # 2) ARG='-i 5'   ;;
    3) ARG='-g' ;;
    *)  ;;
esac
# ${ARG+~/.i3/ext/dvolbar $ARG}

VARS=$(amixer -M -D pulse get Master |
    sed -n '$s/.*\[\([0-9]\+\)%\].*\[\([onf]\{2,3\}\)\].*/VOL=\1;MUTE=\2/p')
eval $VARS

if [ "$MUTE" == "off" ]; then color="#EE0000"; fi

printf "$VOL%%\n$VOL%%\n${color:+$color\n}"
