#!/bin/bash
# Enable color support of ls and also add handy aliases
# BAD: if ssh from another (achromatic) terminal

alias ls='ls --group-directories-first --color=auto'
alias ip='ip -c'  # colored

#alias dir='dir --color=auto'
#alias vdir='vdir --color=auto'

alias  grep="noglob grep --color=auto"
alias fgrep="grep -F"
alias egrep="grep -E"

# EXPL: already in 'prezto'
# alias diff='colordiff'


### Colorscheme
if [[ -x /usr/bin/dircolors ]] && [[ -s ~/.config/dircolors ]]; then
  LS_COLORS=$(eval "$(dircolors -b ~/.config/dircolors)"; printf '%s\n' "$LS_COLORS")
fi
alias ls="${LS_COLORS:+LS_COLORS='$LS_COLORS' }${aliases[ls]:-ls}"

GREP_COLORS="mt=37;45"
alias grep="${GREP_COLORS:+GREP_COLORS='$GREP_COLORS' }${aliases[grep]:-grep}"
