#!/bin/bash

# enable color support of ls and also add handy aliases
if [[ -x /usr/bin/dircolors ]]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    AUTOCOLORS='--color=auto'
    alias ls="ls $AUTOCOLORS"
    #alias dir='dir $AUTOCOLORS'
    #alias vdir='vdir $AUTOCOLORS'

    alias  grep="grep $AUTOCOLORS"
    alias fgrep="fgrep $AUTOCOLORS"
    alias egrep="egrep $AUTOCOLORS"

    alias diff='colordiff'

fi
