#!/bin/bash
# Most of aliases contained at
#   ~/.cache/zsh/.zprezto/modules/git/alias.zsh

## --- Git ---
## Status
# Re-defined
alias gs='git status -sb && git --no-pager stash list'
alias gca='gaa && gcm'
alias gl='git pull --rebase --verbose'
alias gbl='git branch -va'
alias gbL='git branch -v'

# Additional
alias gs-='git for-each-ref --format="%(refname:short) %(push:track) --> %(upstream:short)" refs/heads'
alias gaa='git add --all'
alias gcFd='gcF --date="$(date -R)"'
alias gcom='gco master'
alias glu='gss && gl && gsp'

alias gro='git rebase --onto'  # gro master HEAD~1  #: <dst> <point>
alias grm='git rebase --preserve-merges'
alias grim='gri --preserve-merges'  # BUG: with -i can be weird!

alias gfa='git fetch --all --progress --prune --verbose'
alias gwRc='gwR origin/"$(git-branch-current 2> /dev/null)"'

gl-() { local current="$(git-branch-current 2> /dev/null)"
git for-each-ref --format="%(refname:short) %(push:track)" refs/heads |
    while read branch state; do if [[ -n "$state" ]]; then
        git checkout "$branch" && git pull --rebase --verbose
    fi; done
    git checkout "$current"
}

# BUG: recursion?
# gri(){ [[ "$1" =~ [0-9]+ ]] && git rebase -i HEAD~$* || git rebase -i $@; }
# compdef grI=git-rebase
# alias gcv='git commit --no-verify'

# New
alias gtn='git name-rev --name-only'  # Shows related to release tag name
# alias gtt='git tag'

# NOTE:
#   gwc / gwC | clean | --dry-run / --force
#   gfa && gwRF  | do on each client after 'push -f'
#   giA -- Partial commit: select several hunks from files 'y' and diskard others 'd'.
#        USE: 'git add -N <file>' before if untracked
#   gp[aA] -- push all/+force ATTENTION: all deleted on server branches will recreate from user


## Diff
alias gdf='noglob git diff'
alias gdF='gdf HEAD...origin'  # with fetched
alias gdo='gdf HEAD   origin/$(git-branch-current 2>/dev/null)'
alias gdum='gdf master upstream/master'
alias gdw='gdf --no-ext-diff --word-diff --unified=0'  # OR -U0
alias gdc='gdf --cached -w'
alias gdcw='gdf --no-ext-diff --word-diff --cached -w'
alias gdn='gdf --name-only'
alias gdr='gdf --color-words'
alias gdp='gdf HEAD~1 HEAD'
alias gdp-='gdw HEAD~1 HEAD'
alias gdl="gdf '@{1}..'"
alias gdl-="gdw '@{1}..'"
alias gds='gdf "stash@{0}"'

## Log
alias glg='git lgraph'
alias glgs='glg --source --all -S'   # search <text> in all commits content
alias glF='git log -p HEAD..origin'  # with fetched
alias gll='git lmsg'
gln(){ git ldump -n ${1:-10}; } #or -1 for inf
alias gff='git rev-list --all | xargs git grep'
# git grep -l --all-match -e <regexp1> # To search files with line
# git log -G Foo --since=2009.1.1 --until=2010.1.1 -- path_containing_change # To search commits changing line

# Utils
alias gk='gitk --all --max-count=200 --branches --remotes --tags &'
alias gv='v -c Gitv'
alias gvs='v -c Gstatus'
alias gvd='git difftool'

## Recursive repo
alias Gg='prg.d/git-recursive'
alias Gt='Gg st'  # summary
alias Gs='Gt status -su'
alias Gd='Gg st diff'
alias Gw='Gd --unified=0 --no-ext-diff --unified=0 --exit-code --no-prefix --word-diff'
alias Gl='Gg pl'
alias Gp='Gg ph'
