#!/bin/bash

# --- Different ---
alias path='echo -e ${PATH//:/\\n}'
alias now='date +"%T"'
alias nowdate='date +"%d-%m-%Y"'
alias date.='date +%Y%m%d_%H%M%S'
alias cal='cal -m'

# most often used commands
alias top20='print -l $$${(o)history%% *} | uniq -c | sort -nr | head -n 20'

# --- Process ---
# alias psg='ps aux | grep ' # Rewritten by zsh
alias topstat='dstat -cdnpmgs --top-bio --top-cpu'


# --- Net ---
alias ping='\ping -c 5'
alias pingfast='\ping -c 100 -s.2'
alias pingg='pingfast 8.8.8.8'

# {ifconfig eth0; ifconfig wlan0}  | awk '/inet addr/{print substr($2,6)}'
alias scanip='nmap -sn 192.168.0.0/24'
alias ports='netstat -tulanp'
alias openports='netstat --all --numeric --programs --inet'

# --- System ---
## pass options to free ##
alias meminfo='free -m -l -t'
## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
## get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
## Get server cpu info ##
alias cpuinfo='lscpu'
## older system use /proc/cpuinfo ##
##alias cpuinfo='less /proc/cpuinfo' ##

## get GPU ram on desktop / laptop##
alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'
