#!/bin/bash

if _has_pr pacaur; then
  alias pacman='pacaur'
elif _has_pr yaourt; then
  alias pacman='yaourt'
else
  alias pacman='sudo \pacman'
fi

if [[ $SHELL =~ zsh$ ]]; then
  alias pacman="noglob ${${$(alias pacman)#*=}:-pacman}"
fi

# USE: -r/-a to use repo/aur only
alias pacg='pacman -Sg'    # show list of package [g]roup
alias paci='pacman -S'     # install
alias pacI='pacman -U'     # install from files
alias pacl='\pacman -Ql'   # list files (installed by a given package)
alias pacL='\pacman -Qo'   # show path fr[o]m which package
alias pacLr='_(){ command pacman -Qo "$(which command "$1")"; }; _ '
alias paco='\pacman -Qdt'  # list [o]rphans
alias pacq='pacman -Si'    # info
alias pacQ='pacman -Qi'    # info local -- grep by "Required By"
alias pacs='pacman -Ss'    # search
alias pacS='pacman -Qs'    # search local
alias pacu='pacman -Su'    # install with [u]pdate
alias pacU='sudo pacman --sync --refresh && sudo abs'
alias pacx='sudo \pacman -Rsu'  # '[r]emove'
alias pacX='sudo \pacman -Rsc'  # 'Rm pkg, its deps and all depending pkgs
alias pacy='pacman -Sy'    # refresh only
alias pacY='pacman -Syu'   # '[u]pgrade all'
# alias pacU='pacman -U /var/cache/pacman/pkg'    # refresh only
# alias pacc='pacman -Scc'   # '[c]lean cache' (all not currently installed)
# alias pacexpl='pacman -D --asexp'  # 'mark as [expl]icit'
# alias pacimpl='pacman -D --asdep'  # 'mark as [impl]icit'

# Synchronizes the local package database against the repositories then
# upgrades outdated packages.
# alias pacU="sudo pacman --sync --refresh --sysupgrade"

alias pacman-list-orphans='\pacman --query --deps --unrequired'
alias pacman-remove-orphans='sudo pacman --remove --recursive $(pacman-list-orphans)'
pacman-list-explicit(){ \pacman --query --explicit --info | awk '
    BEGIN{FS=":"} /^Name|^Description/{print$2}
'; }
pacman-list-disowned(){
  local tmp=${TMPDIR:-/tmp}/pacman-disowned-$UID-$$
  local db=$tmp/db fs=$tmp/fs
  trap  'rm -rf "$tmp"' EXIT
  mkdir "$tmp"
  pacman --quiet --query --list | sort --unique > "$db"
  find /bin /etc /lib /sbin /usr ! -name lost+found \
    \( -type d -printf '%p/\n' -o -print \) | sort > "$fs"
  comm -23 "$fs" "$db"
}
