#!/bin/bash

# --- Search ---
f()  { find . -type f -iname "*$@*"; }
ff() { find . -type f -regex $@; }
# fl() { locate ${1?<what?>} | sed "/\(\/[^/]\+\)\{${2:-5}\}/d" | sort -u; }
# grep -Ri 'name' . # find in all files
# alias ff='find ./ | grep -i '

agi() { ag -G '^(?:(?!/build/|/libs/|/tags$).)*$' -S $@; }
agd() { find . -maxdepth 1 -type f | xargs agi $@; }    # in curr dir only
agw() { agi -w $@; }
agp() { agi --pager less $@; }
agpdf() {
    find . -name '*.pdf' -exec sh -c 'pdftotext "{}" - | grep --with-filename --label="{}" --color "your pattern"' \;
}
# agc() { ag -G "CMakeLists.txt|.*.cmake" $@; }

vima(){ # USAGE: vima agl -w 'pgd' -- open agl search results in vim
    local cnt=24 als='ag' args std add cmd

    if [[ $1 =~ ^[0-9]+$ ]]; then cnt=$1; shift; fi
    if [[ $1 =~ ^ag ]]; then als="$1"; shift; fi
    std=$(which "$als" | sed '
        /\<ag\>/!d; s/^.*\<ag\>\(.*\)\s*$/\1/; s/\$@//g')
    cmd="Ag!${std:- }$add"
    for k in "${@//\\/\\\\}"; do
        [[ "${k:0:1}" != - ]] && k="\"${k}\""
        cmd="$cmd$k "
    done
    printf "$cmd\n" | $EDITOR -R \
        -c "set nolist | copen $cnt " \
        -c "call histadd(':','$cmd')" -c ":$cmd" -
        # | let g:ag_qhandler='botleft lopen 7'
        # | let g:magnify_on=0
        # -c "let g:syntastic_mode_map['mode']='passive'" -c "NeoCompleteDisable" \
}

vimf(){ ag -g $@ | $EDITOR -; }
# vimq(){ $EDITOR -q <(agi --vimgrep $@); }  # Don't work in bash 4.1.5? in ubuntu12?
