#!/bin/bash

# --- Modify ---
# ALT: use dir from last history -- cd !$:h
# OR:  physical pwd for symlinks -- cd $(pwd -P) -- ALT: cd -P ~/ch
# SEE:(smart_cd) http://zshwiki.org/home/examples/functions
cdauto() { local p; ((!$#)) || p=${@: -1}
  if [[ -z $p || $p == - || -d $p ]]
  then builtin cd "$@"; return $?
  else builtin cd "${@:1:$#-1}" "${p%/*}";
fi; }
alias cd='cdauto'

# WARNING: Use 'sudo' w/o user cfgs, so viminfo, swap won't've root rights!
alias v=$EDITOR
alias sv='sudo v'
alias vi='v -u NONE --noplugin'
alias vb='v -u ~/.vim/rc/basic'
scpvim(){ $EDITOR scp://${2:-srk}/"${1:-$(xsel -o)}"; }

alias r='source r.ranger'
alias w3m='\w3m google.com'
alias w3mh='\w3m -T "text/html"'
alias tgz='tar -cvfz' # arch.tar.gz ./
alias utgz='tar xvfz'
alias utbz2='tar xvfj'

alias xargs='xargs '  # Allow alias expansion after xargs

# TODO: filter tree by pid args parent--childs (useful to list branch for $$)
# ALSO: sort in order of starting time
alias p='ps --group 0 --deselect --forest -o user,pid,pgid,pcpu,pmem,etime,args'

# because _=/usr/bin/env
alias ,.='r.dict '
alias .,='r.dict '
# en2ru() { echo "$@" | translate-bin -s google -f en -t ru; }
# ru2en() { echo "$@" | translate-bin -s google -f ru -t en; }


#ALT: scp file1 file2 ... fileN user@host:~/Downloads/
scptar() {
    local srv src z TP
    case "$1" in
        -z)   z="z"; shift ;;  # compression
        -s) TP="$1"; shift ;;  # send
    esac
    srv="${1?Need server}"
    src="$(readlink -m "${2?Need dir path}")"
    pack="cd \"${src%/*}\" && tar cvf$z - \"${src##*/}\""
    unpack="tar xvf$z - ${3+-C "$3"}"
    case "$TP" in
        -s)  bash -c "$pack" | ssh "$srv" "$unpack" ;;
         *)  ssh "$srv" "$pack" | bash -c "$unpack" ;;
    esac
}
alias scpto='scptar -s '
alias scpfr='scptar '
# ALT: scp must be double-escaped due to shell expansion on both client and host
#   ls X{} scp "{}" host:"~/'{}'"

# Deploy instant server for exposing files in current directory to LAN
alias http-server='/usr/bin/env python2 -m SimpleHTTPServer 8000'

# echo "alias firefox='nohup firefox &>/dev/null'" >> /etc/commonrc

hi() { if [ -z "$@" ]; then history | tail -20; else
    history | sed 's/^\s*\(\d\+\)\s*\(.*\)$/\2 #\1' | sort -u | agi $@;
fi; }
