#!/bin/bash

# --- Modify ---
# YCM won't load on startup
# DONT WORK. WHY?
# It can be simpler to do restarting of vim from inside by combo leader-F12
# let g:...
# source $MYVIMRC

alias vi='\vim -u ~/.vim/vimrc_basic'
vimscp(){ vim scp://${2:-srk}/"${1:-$(xsel -o)}"; }
v() { #servername == syntex (must be for LaTeX)
    local _V fl=~/.cache/vim/servername
    if [ -f "$fl" ]; then
        _V=$(cat "$fl")
        vim --servername $_V --remote-silent $@
        vim --servername $_V --remote-send ':redraw<CR>'
    else
        vim $@
    fi
}

#alias vim='\vim --cmd "let g:loaded_youcompleteme = 1"'
#alias ycm='\vim --cmd "let g:loaded_youcompleteme = 0"'

alias s='source ranger-auto; if [ $? -eq 2 ]; then exit; fi'
alias w3m='\w3m google.com'
alias w3mh='\w3m -T "text/html"'
alias tgz='tar -cvfz' # arch.tar.gz ./
alias utgz='tar xvfz'
alias utbz2='tar xvfj'

# ALT: curl ftp://ftp.com/mp3/mymusic.zip --user login:password -o mymusic.zip
#      curl -O http://link
alias wgetf='wget -i -c --content-disposition '

alias p='ps -A f -o user,pid,pgrp,priority,ni,pcpu,pmem,args'

# because _=/usr/bin/env
alias ,.='lau-dict '
alias .,='lau-dict '
# en2ru() { echo "$@" | translate-bin -s google -f en -t ru; }
# ru2en() { echo "$@" | translate-bin -s google -f ru -t en; }


#ALT: scp file1 file2 ... fileN user@host:~/Downloads/
scptar() {
    local srv src z TP
    case "$1" in
        -z)   z="z"; shift ;;  # compression
        -s) TP="$1"; shift ;;  # send
    esac
    srv="${1?Need server}"
    src="$(readlink -m "${2?Need dir path}")"
    pack="cd \"${src%/*}\" && tar cvf$z - \"${src##*/}\""
    unpack="tar xvf$z - ${3+-C "$3"}"
    case "$TP" in
        -s)  bash -c "$pack" | ssh "$srv" "$unpack" ;;
         *)  ssh "$srv" "$pack" | bash -c "$unpack" ;;
    esac
}
alias scpto='scptar -s '
alias scpfr='scptar '

# Deploy instant server for exposing files in current directory to LAN
alias http-server='/usr/bin/env python2 -m SimpleHTTPServer 8000'

alias mount='mount |column -t'
alias mountl='sudo fdisk -l'
# echo "alias firefox='nohup firefox &>/dev/null'" >> /etc/commonrc

hi() { if [ -z "$@" ]; then history | tail -20; else
    history | sed 's/^\s*\(\d\+\)\s*\(.*\)$/\2 #\1' | sort -u | agi $@;
fi; }
