#!/bin/bash

# Vim navigation inside 'info' as in 'man'
if _has_pr pinfo; then
    alias info='pinfo --vi-keys'
else
    alias info='info --vi-keys'
fi

alias make='make -j4'         # multithread build
alias sort='LC_ALL=C sort'    # fix sorting order
# ALT: sudo vbetool dpms [on/off]      # Permanent (ignores mouse and kbd)
# alias off='xset -d :0 dpms force off'  # Until mouse moves (r.core dpmsoff)

alias sha1='openssl sha1'
# alias j='jobs -l'

# --- State ---
alias free='free -hmlt'
alias reswap='sudo swapoff -a && sudo swapon -a && free'

# --- Packages ---
alias apti='apt-get install'
alias apts='apt-cache search'
alias update='apt-get update && apt-get upgrade'
# alias debup='aptitude update && aptitude safe-upgrade'
# alias debup_old='aptitude update && aptitude upgrade'


# --- Insurance and rights ---
alias mv='mv -iv'
alias cp='cp -iv'
alias ln='ln -iv'
alias rm='rm -Iv --preserve-root'
alias chmod='chmod --preserve-root'  # Mostly used w/o sudo
alias chgrp='chgrp --preserve-root'
alias chown='chown --preserve-root '
alias chownm='chown $USER:$USER'  # USE this exclusively
alias chownr='chown root:root'
alias mountl='\mount | column -t'
alias mountf='sudo fdisk -l'

# Very useful and nut aliases:
# http://brettterpstra.com//2013/03/31/a-few-more-of-my-favorite-shell-aliases/
# new commands
# alias susp="pm-suspend && xlock -mode matrix"
# alias wifi="netctl-auto switch-to"


# --- Shorts for non-root ---
if (( EUID != 0 )); then  # --calibrate
    SUDOLST=(chown mount umount powertop apt-get dpkg
             dpkg-reconfigure reboot poweroff halt shutdown
             hibernate hibernate-ram)
    for nm in "${SUDOLST[@]}"; do
        alias $nm='sudo '"$nm"
    done
    unset SUDOLST
fi
alias sudo='sudo '  # Allow using sudo with aliases
# alias su='sudo -i'
