#!/bin/bash -e
source ~/.shell/profile

# After this script you must specify 'ghub' entry in ~/.ssh/config
# In other case you will not be able to pull this gurl

# git remote show origin | grep "Push *URL" | sed "s@.*:.*:\(.*\$\)@\1@"

gurl=$(git config --get remote.origin.url \
    | sed '{s@.*git\(.*\)\.com/@g\1:@}')

git remote set-url origin "${gurl:?Not a git repo?}"
echo "C: git remote url '${PWD#$HOME/}' -> $gurl"

if [[ "${CURR_PROF?No}" == "work" ]]; then
    git config --local user.name "${MAIN_NAME?No}"
    git config --local user.email "${MAIN_MAIL?No}"
    echo "C: git local {name, email} : {$MAIN_NAME, $MAIN_MAIL}"
fi
