#!/bin/sh -eu

url=$1
nm=${2:-upstream}

if git remote | grep -qxF "$nm"; then
  git remote set-url "$nm" "$url"
else
  git remote add -f -t master -m master "$nm" "$url"
fi

git remote set-url --push "$nm" DISABLE
