#!/bin/bash -e
source ~/.shell/profile
cd $(dirname $(readlink -m ${0})) && source ~/.shell/func.d/cfgsetup

### LINKS ###
link "$PWD/gitignore" ~/.gitignore

# Customization
# http://git-scm.com/docs/git-config

### GENS ###
dst=~/.gitconfig
> $dst
git config --global user.name  "${WORK_NAME:=${MAIN_NAME?No}}"
git config --global user.email "${WORK_MAIL:=${MAIN_MAIL?No}}"
# git config --global user.signingkey = C8A2DA6E

for fl in "$PWD"/cfg_* ; do cat "$fl" >> $dst; done

echo "W: ~/.gitconfig"
