#!/bin/bash -e
source ~/.shell/profile
source ~/.shell/func.d/cfgsetup

### LINKS ###
link "$PWD/gitignore" ~/.gitignore

# Customization
# http://git-scm.com/docs/git-config

### GENS ###
dst=~/.gitconfig
> $dst
if [[ -n "${WORK_NAME:=$MAIN_NAME}" &&
      -n "${WORK_MAIL:=$MAIN_MAIL}" ]]; then
    git config --global user.name  "$WORK_NAME"
    git config --global user.email "$WORK_MAIL"
    # git config --global user.signingkey = C8A2DA6E
fi
cat "$PWD/cfg"/* >> $dst

echo "W: ~/.gitconfig"
