#!/bin/bash -e
# tags: tui, io, obsolete
source ~/.shell/func.d/cfgsetup

exit  # USE picocom instead of minicom!

dst=~/.minirc.dfl

# To work w/o sudo
if distro arch; then
    dst=${dst:-/etc/minirc.dfl}

elif distro ubuntu; then
    dst=${dst:-/etc/minicom/minirc.dfl}

    va=$(stat -c %A /etc/minicom)
    if [[ "${va:(-2):1}" != 'w' ]]; then
        sudo chmod -R o+w /etc/minicom
    fi
    # NEED: relogin
    id | grep -qwF dialout || sudo gpasswd -a "${LOGNAME:?}" dialout
fi

### LINKS ###
linkcp "$PWD/minicom-usb0" "$dst"

## To change default one in /etc
# if cfgOpt u || [[ ! -L "$dst" ]]; then
#     [[ "$src" -ef $dst ]] || sudo ln -svfT "$PWD/usb0" "$dst"
# fi
