#!/bin/bash -eu
source ~/.shell/func.d/packages
# Supports images (xterm, framebuffer console), but it doesn’t support JavaScript.

if distro arch; then
  pkg_inst w3m

elif distro ubuntu; then
  pkg_inst w3m w3m-img
fi
