#!/bin/bash -e
source ~/.shell/func.d/packages

pkg_inst festival festival-english festival-us

## Some say that HTS voices for Festival are the best ones freely available
## BUT: festival-us has cmu_us_slt_arctic_hts
# aur_inst festival-patched-hts
# aur_inst festival-hts-voices-patched
