#!/bin/bash -e
source ~/.shell/func.d/packages


if distro arch; then
    # DEPRECATED: xorg-xmessage -- use r.vim-xmessage
    pkg_inst xmonad wmctrl  # xmobar
    pkg_inst -d {/usr/share/doc/,}xmonad-contrib

    # pkg_inst 'haskell-unordered-containers'
    [[ -d ~/.cabal/bin ]] || echo "Err: Re-login session to add ~/.cabal/bin/xmobar into PATH"
    pkg_inst -l 'Xpm' libxpm
    aur_inst -d {/usr/share/doc/,}haskell-libmpd
    cab_inst -p 'xmobar' xmobar --flags="with_dbus with_utf8 with_xft with_mpd with_alsa"

elif distro ubuntu; then
    pkg_inst 'xmonad xmonad-contrib'

    echo "Err: not enough"
fi
