#!/bin/sh -eu
# Termcap

# ALT: ...=$'\E[01;38;5;74m'
### Colors ###
export LESS_TERMCAP_md=$(tput bold; tput setaf 2)
export LESS_TERMCAP_mb=$(tput bold; tput setaf 6)

# me | sgr0 | turn off bold, blink and underline
export LESS_TERMCAP_me=$(tput sgr0)

# so | smso | start standout (reverse video) | black on yellow
export LESS_TERMCAP_so=$(tput bold; tput setaf 0; tput setab 7)
# se      rmso      stop standout
export LESS_TERMCAP_se=$(tput rmso; tput sgr0)

# us      smul      start underline
export LESS_TERMCAP_us=$(tput smul; tput setaf 12)
# ue      smue      stop underline
export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)

export LESS_TERMCAP_mr=$(tput rev)
export LESS_TERMCAP_mh=$(tput dim)
export LESS_TERMCAP_ZN=$(tput ssubm)
export LESS_TERMCAP_ZV=$(tput rsubm)
export LESS_TERMCAP_ZO=$(tput ssupm)
export LESS_TERMCAP_ZW=$(tput rsupm)

# DEBUG
# export LESS_TERMCAP_DEBUG=1

exec less $@
