#!/bin/bash -e
# tags: chat demon
source ~/.shell/func.d/cfgsetup

### LINKS ###
export MAIL_EXCHANGE=${MAIL_EXCHANGE//:/\\:}
# DFL: ~/.davmail.properties
env-subs -p {,~/.config/davmail/}davmail.properties

# FIX: on home it must run only on demand, never enabled unconditionally
#   => NEED: split "install" phase and "auto-hook-on-system-defaults"
svc_activate -cu davmail.service
# svc_activate -cueR davmail.service
