#!/bin/bash -e
source ~/.shell/func.d/packages

#| netctl         | Profile based systemd network management
#| wpa_supplicant | Cli-tool to establish secure wifi connection
#| wpa_actiond    | Auto switching profiles for different wifi networks
#|________________|     =USE: netctl-auto
#| dialog         | For wifi-menu. A tool to display dialog boxes from shell scripts

pkg_inst netctl wpa_supplicant dialog
pkg_inst wpa_actiond

# iw phy
# sudo iw dev wlp3s0 scan
# sudo iwlist wlp3s0 scan | sed -n '/(Channel/p'
# iwlist wlp3s0 freq
pkg_inst iw network-manager

## GUI -- for netctl
# http://arcanis.name/ru/projects/netctl-gui/

# FAQ:
#   wpa_cli
# Enable
#   ip link set wlan0 down
#   netctl start wlan_static
# If error on connection -- see reasons:
#   journalctl -xn
#   netctl status wlan_static

# General
# LST="$LST hostapd iw haveged"
# (or procps-ng)
# haveged (optional) -- entropy for randomness
# iwconfig (you only need this if 'iw' can not recognize your adapter)

# For 'NATed' or 'None' Internet sharing method
# apt_noprompt dnsmasq
# git_install 'oblique/create_ap'
# alias wifi="netctl-auto switch-to"
