#!/bin/bash -e
source ~/.shell/func.d/packages
distro ubuntu || exit

#| grub-customizer | To change boot order, time and boot-wallpaper
# ppa_add 'ppa:danielrichter2007/grub-customizer'
# pkg_inst 'grub-customizer'

sudo apt-get install gawk
