#!/usr/bin/env bash
if ! [[ "$(uname -n)" =~ archiso|vbox ]]; then echo "Use under vbox guest!"; exit 1; fi


### Install X, etc
# pacman -Sy
LST="xorg-server xorg-server-utils xorg-xinit"
# VBox needs at least vesa GPU driver: or X will not start!
LST="$LST xorg-xdm xf86-video-vesa mesa-libgl"
# 1) mesa-libgl  2) nvidia-304xx-libgl  3) nvidia-340xx-libgl  4) nvidia-libgl
# pacman -S xorg-twm xterm xf86-input-synaptics mesa nvidia lib32-nvidia-utils

LST="$LST git i3-wm dmenu"
pacman -S --noconfirm $LST


### AUR: https://archlinux.fr/yaourt-en
# if ! grep -q '^\[archlinuxfr\]$' /etc/pacman.conf
# then echo '
# [archlinuxfr]
# SigLevel = Never
# Server = http://repo.archlinux.fr/$arch
# ' >> /etc/pacman.conf; fi
# pacman -Sy --noconfirm base-devel yaourt
