#!/usr/bin/env bash
if ! [[ "$(uname -n)" =~ archiso|vbox ]]; then echo "Use under vbox guest!"; exit 1; fi


### ENABLE Services
systemctl enable sshd.service
systemctl enable xdm.service   # Autostart X


## Create initial database running as root
# /usr/bin/mandb --quiet
