#!/bin/bash -e
source ~/.shell/func.d/packages

#| tmux | multi-window customizable terminal with vi navigation, useful for SSH connections

if distro arch; then
  pkg_inst tmux  # TrueColor support in version >=2.2

elif distro ubuntu; then
  # https://gist.github.com/P7h/91e14096374075f5316e
  ppa_add 'ppa:pi-rho/dev'
  pkg_inst tmux-next
fi
