#!/bin/zsh -eu

fs=()
args=()
while (($#)); do
  [[ ${1:0:1} == - ]] && args+=( "$1" ) || fs+=( "$1" )
  shift
done
(($#fs)) || fs=( *.dlt*(.) )

find -L $fs -type f -name '*.dlt.gz' -execdir \
  sh -c 'test -f "${0%.gz}" || gzip --decompress "$0" || true' {} \;

for f in ${fs[@]%.gz}; do
  r.dlt-view $@ -- $f &>! ${f:s/\.dlt/\.txt}
done
