#!/bin/bash -e

export KRITA_HIDPI=ON
# export QT_AUTO_SCREEN_SCALE_FACTOR=1
# export QT_SCALE_FACTOR=0.5
# export QT_SCREEN_SCALE_FACTORS=0.5
# export GDK_SCALE=2

# xrandr --output eDP1 --mode 1920x1080 --primary \
#   --output HDMI1 --auto --below eDP1
# r.video-single 2

# trap 'xrdb -load ~/.Xresources' HUP INT QUIT ILL TRAP KILL BUS TERM EXIT ERR
# xrdb -DMAIN_DPI=141 -load ~/.Xresources

# primusrun
exec krita
