#!/bin/bash -eu
# tags: demon mail
# deps: mbsync getmail notify
source ~/.shell/func.d/cfgsetup

nm=mailsync

# TODO: use DFL path ${XDG_CONFIG_HOME:-~/.config} as last _base or as first _path
#   => so localhost-only changes in ~/.config will have priority over user repo changes
#   => HACK: user can symlink files from unstructured repo into ~/.config
prf=$(cfg-overlay -M~ -s "$nm/{}" -b "${AIRY_OVERLAY_BASE-}" -o "${AIRY_OVERLAY_PATH-}" -- profile)
source "$prf"

linkcp -ct /etc/tmpfiles.d  "unit/$nm.conf"
add_sysuser "$nm" "/var/lib/$nm"
cfgOpt uU || [[ ! -d /var/lib/$nm ]] && sudo systemd-tmpfiles --create "$nm.conf"

### GENS ###
cfgOpt uU && for acc in "${MAILSYNC_ACCOUNTS[@]:?}"; do
  fpass=/var/lib/$nm/sec/$acc
  ! cfgOpt r && sudo test -f "$fpass" -a -s "$fpass" && continue
  r.query-passwd "mail/${acc}" | sudo -u "$nm" -g "$nm" -- \
    tee "$fpass" >/dev/null
done

svc_activate -cE "$nm"-{new,all}@.{service,timer}

## TEMP: run chosen ones manually instead
# for acc in "${MAILSYNC_ACCOUNTS[@]:?}"; do
#   svc_activate -erR "${nm}"-{new,all}@${acc}.timer
# done
