# NOTE: migrate cache to where DEV/SRC projects are
#   FIXED: warning: Failed to hardlink files
#   NEED: $ btrfs subvolume create /data/.cache
#   DEBUG: $ uv cache dir
cache-dir = "/data/.cache/uv"
