#!/bin/bash -eu
# tags: airy
# deps: st notify qute elinks xmonad vim dunst
source ~/.shell/func.d/cfgsetup

### LINKS ###
linkcp -ct /etc/profile.d ./cfg/airy-profile.sh

### ENVS ###
for f in ./env/{editor,pager}
do source "$f"; done
env-subs {./cfg/,~/.}pam_environment

### GENS ###
./gen/symlinks
