#!/usr/bin/env bash
source ~/.shell/profile
set -euo pipefail

# FIND: maybe part of this script is already done inside "aurutils" ?

skip(){ set -- ${!1:+"${!1}"}; (IFS=,; printf '%s\n' "${*// /\\ }"); }

d_pfx=${TMPDIR:-/tmp}/airy
silentskip=1
removelists=
ign_pkg=$(skip 'PKG_IGNORE[@]')
ign_aur=$(skip 'AUR_IGNORE[@]')

while getopts 'ix' o; do case $o in :|'?') exit 1
;; i) silentskip=     #% i = interactive install (allow answering yes/no)
;; x) removelists=1   #% r = remove prepared lists of packages
esac; done; shift $((OPTIND-1))

((removelists)) && { rm -vf "$d_pfx"/{aur,pkg}.{list,deps}; exit; }

inst(){ local nm=$1 tp=$2; shift 2
  (($#)) || set -- sudo pacman -S --needed ${silentskip:+--noconfirm}
  declare -n ign=ign_$nm
  [[ $ign ]] && set -- "$@" --ignore "$ign"
  [[ $tp == deps ]] && set -- "$@" --asdeps
  [[ -f $d_pfx/$nm.$tp ]] || return 0
  echo ">>> $nm.$tp <<<"
  xargs -a "$d_pfx/$nm.$tp" -- "$@"
}

# HACK: workaround when calling from inside Makefile
exec > /dev/tty

# NOTE: both OFF and AUR an have deps only from OFF
inst pkg deps
inst aur deps

# NOTE: update OFF beforehand to link with correct libs in AUR
inst pkg list

# NOTE: only builds AUR and puts pkgs into custom repo
inst aur list \
  aur sync --database=aur --chroot --no-view ${silentskip:+--no-confirm}

# NOTE: fetch and install newly built pkgs from custom repo
sudo pacman -Syu
inst aur list

exit 0
