#!/usr/bin/env bash
set -euo pipefail

pfx=${0##*/}; pfx=${pfx%%_*}
pfx=${TMPDIR:-/tmp}/airy/$pfx
mkdir -p "${pfx%/*}"

for ((i=1;i<=$#;++i)); do
  [[ ${!i} == --asdeps ]] && break
done

((i==1 && $#<=1)) && { echo "Err: empty list" >&2; exit 1; }

((i>1)) && printf '%s\n' "${@:1:i-1}" >> "$pfx.list"
((i<$#)) && printf '%s\n' "${@:i+1}" >> "$pfx.deps"

exit 0
