#!/bin/bash -eu
source ~/.shell/func.d/packages

pkg_inst linuxconsole
# BAD: conflicts
# pkg_inst joyutils
# lsmod | grep -qw '^joydev' || sudo modprobe -a joydev

aur_inst xboxdrv-stable-git xpadneo-dkms-git
