#!/bin/bash -eu
source ~/.shell/func.d/packages

pkg_inst evtest linuxconsole
# BAD: conflicts
# pkg_inst joyutils
# lsmod | grep -qw '^joydev' || sudo modprobe -a joydev

# aur_inst xpadneo-dkms-git

# DISABLED! build errors TRY:DFL: aur/xboxdrv-git ALT: https://gitlab.com/xboxdrv/xboxdrv
# USE: https://github.com/zerojay/xboxdrv/tree/stable
# loc_inst ./xboxdrv-airy-git.pkgbuild
# aur_inst xboxdrv-stable-git
# aur_inst xboxdrv-develop-git

# NOTE: add xinput support into Wine
# USAGE: LD_PRELOAD='/usr/lib32/koku-xinput-wine.so /usr/lib32/koku-xinput-wine64.so' wine "$@"
# aur_inst koku-xinput-wine
# REF: https://bbs.archlinux.org/viewtopic.php?id=188904
# ALT: https://github.com/kozec/dumbxinputemu
