#!/bin/bash -e
source ~/.shell/func.d/packages
has_pr X || die
# finch   | TUI interface to pidgin

pkg_inst pidgin

if distro arch; then
  # Plugin for Skype
  aur_inst -f '/usr/lib/purple-2/libskypeweb.so' purple-skypeweb
  # Plugin for MSN -- Office Communicator
  # pkg_inst -a 'pidgin-sipe'

  # Other plugins
  pkg_inst -f '/usr/lib/pidgin/enhancedhist.so' purple-plugin-pack
  pkg_inst -f '/usr/lib/purple-2/pidgin-libnotify.so' pidgin-libnotify
  aur_inst -f '/usr/lib/purple-2/libskypeweb.so' purple-skypeweb

  aur_inst -f '/usr/lib/purple-2/purple-gnome-keyring.so' purple-gnome-keyring
  # pkg_inst 'pidgin-encryption'

elif distro ubuntu; then
  # pidgin-plugin-pack | Primarily for convenient history plugin
  pkg_inst 'pidgin-plugin-pack myspell-ru'
fi
