#!/bin/bash -e
source ~/.shell/func.d/packages

# | pidgin-sipe        | Office Communicator plugin
# | pidgin-plugin-pack | Primarily for convenient history plugin

pkg_inst 'pidgin pidgin-sipe pidgin-plugin-pack myspell-ru'

### ON DEMAND ###
# finch   | TUI interface to pidgin
# tcpdump | if necessary to extract paswd
