#!/bin/bash -e
cd $(dirname $(readlink -m ${0}))

case "$1" in
-u|--update) update=1 ;;
esac

### LINKS ###
# link(){ [[ ! -e $2 || -L $2 ]] && ln -sfvT "$1" $2; }
# link "$PWD/prefs.xml" ~/.purple/prefs.xml

# WARNING: symlink is not enough, it will be replaced when you launch pidgin!
cp -vf "$PWD/prefs.xml" ~/.purple/prefs.xml

if [[ "$update" -eq 1 ]]; then
    ./accounts.gen
fi
