#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
# WARNING: symlink is not enough, it will be replaced when you launch
# pidgin! But maybe, even file will be overwritten...
# link "$PWD/prefs.xml" ~/.purple/prefs.xml
dst=~/.purple/prefs.xml
link -c ./prefs.xml "$dst"

if cfgOpt u; then
    ./accounts.gen
fi

echo "C: pidgin"
