#!/bin/bash -e
source ~/.shell/func.d/packages

#| compton  | 3d effects on workspace

if distro arch; then
    if cfgOpt u || ! has_pr compton; then
        aur_inst compton
    fi

elif distro ubuntu; then
    pkg_inst compton
fi
