#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
  # DEV:rm: android-tools
  pkg_inst android-tools
  pkg_inst android-udev
  # DISABLED: aur_inst jmtpfs
  # BET:ALT: adbfs-rootless-git && adb-sync-git
  #   ALSO:DEV: logcat-color
  # SRC: Android Debug Bridge - ArchWiki ⌇⡡⢪⢀⢉
  #   https://wiki.archlinux.org/title/Android_Debug_Bridge
  # NEED: $ adbfs /media/andr
  aur_inst adbfs-rootless-git

  # USAGE: /@/items/exe/fetch-alreader
  aur_inst android-backup-extractor-git

  # NEED:(F-Droid): kdeconnect
  pkg_inst kdeconnect

  ## NICE: screencast (e.g. present Squid)
  # aur_inst scrcpy

elif distro ubuntu; then
  # Cross-compilers
  # pkgs=( gcc-arm-linux-gnueabi) #Or ...-androideabi
  echo "Err: Not enough packages"
fi
