#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
  pkg_inst android-tools android-udev
  aur_inst jmtpfs

  # NEED:(F-Droid): kdeconnect
  pkg_inst kdeconnect

elif distro ubuntu; then
  # Cross-compilers
  # pkgs=( gcc-arm-linux-gnueabi) #Or ...-androideabi
  echo "Err: Not enough packages"
fi
