#!/bin/bash -eu
source ~/.shell/func.d/packages

if distro arch; then
  # pkg_inst fbreader
  aur_inst fbless
  # aur_inst simple-fb2-reader
  # aur/lucidor
  # aur/coolreader
  # aur/coolreader3-git

elif distro ubuntu; then
  git_inst 'matimatik/fbless'
fi
