#!/bin/sh -eu
# USAGE: export OLD_BDR='...' SRC_DIRS='src/dir1:src/dir2'
# FIND: how to extract from coredump
#   * 'cdir' to setup 'OLD_BDR'
#   * list of relative src dirs to setup 'SRC_DIRS'
# TODO:THINK: substitute-path by empty to search rel path in dirs
#   ::> impossible
# ATT: 'substitute-path' don't change visible paths (in 'bt' or 'list')
#   it simply uses new pathes when accesses sources content

cd "$(r.gdb-tmp -d)"
source ./env

cat> ./init.cfg <<EOT
# vim:ft=gdb
set pagination off
set logging overwrite on
set print thread-events off
set data-directory gdb_data
# OR: sysroot
set solib-absolute-prefix root
set solib-search-path debug:libs
${OLD_BDR+set substitute-path $OLD_BDR bdr}
set directories src:\$cdir:\$cwd${SRC_DIRS+:$SRC_DIRS}
set debug-file-directory debug:libs/debug:root/lib/.debug

## Place into local ./.gdbinit
## FIXED:(pwndbg): unsupported operand types
# set endian big
# set architecture mips
# python gdb.COMPLETE_EXPRESSION = gdb.COMPLETE_SYMBOL
# source ~/.cache/airy/pkg/pwndbg/gdbinit.py

file exe
core-file core
set logging on log.cfg
set trace-commands on
EOT
