#!/bin/bash -e
source ~/.shell/func.d/packages

# BET:
# btpd/btpd: ⚡ The BitTorrent Protocol Daemon ⌇⡠⡏⡃⠩
#   https://github.com/btpd/btpd
pkg_inst rtorrent inotify-tools
# tixati | NOT FOUND # nice dark torrent-downloader
aur_inst magnet2torrent-git
