#!/bin/sh -eu
# ALT:(oneline): copy on FAT: rsync -hrt ...

# BET? same logic  !rdiff-backup ⌇⡡⠯⢵⠭ https://rdiff-backup.net/
dbkp="../!rsync-$(date +%Y%m%d_%H%M%S)"

# SEE:(annex/symlinks -> real/files): $ rsync -L -K

exec rsync -ah --no-group \
  --stats --progress \
  --info=copy,del,remove,skip \
  --backup --backup-dir="$dbkp" \
  --remote-option=--one-file-system \
  --out-format='%t %i %f' \
  "$@"
