#!/bin/sh -eu
# USAGE: $ ./$0 -- ./dir host:/mnt/HD/HD_a2/share/$USER
# CMP: $ ./$0 --dry-run --delete-after -- dir/ lc:/me/dir

# SEE:(--backup): sync - make rsync wait for a confirmation before actually changing files - Super User ⌇⡞⣯⡸⣀
#   https://superuser.com/questions/282942/make-rsync-wait-for-a-confirmation-before-actually-changing-files
#   => create files with '~' suffix in same dir
#     WARN: will be deleted if "--delete" specified
#     BET? use in this case: --backup-dir=../backup

# WARN: "/me" must be correct symlink on dest, otherwise...
#   it may copy onto RAM rootfs instead of HDD
#   BAD:(--one-file-system): still didn't help
#   WARN: always only use "--delete-after" -- to recover files
#     <= e.g. if they were deleted wrongly and moving to ~/backup had failed
dbkp="/me/!rsync/$(date +%Y%m%d_%H%M%S)"

# ERR:FAIL: if "/me" does not exists when copying from NAS to local machine
#   rsync error: error in file IO (code 11) at rsync.c(727) [receiver=v3.2.3]
#   rsync: [generator] write error: Broken pipe (32)
# HACK: don't touch backup dir when copying TO remote
eval "dst=\${$#}"
test ! -d /me -a "x${dst##*:}" == "x${dst}" && dbkp=${dbkp#/me/}

# PERF:(-a): => -rlW
exec rsync -e ssh -avh --no-group \
  --stats --progress \
  ${dbkp:+--backup --backup-dir="$dbkp"} \
  --remote-option=--one-file-system \
  --out-format='%t %i %f' \
  "$@"
