#!/bin/sh

case $BLOCK_BUTTON in
    1) ~/.i3/ext/lang + ;;
    3) ~/.i3/ext/lang 0 ;;
    *) ;;
esac

INDEX=$( ~/.i3/ext/lang )

case "${INDEX}" in
    0) LG=US; color="#00AE00" ;;
    1) LG=RU; color="#009EAF" ;;
    2) LG=UA; color="#FFAA00" ;;
    *) color="#C60101" ;;
esac

printf "$LG\n$LG\n$color\n"
