#!/bin/sh

case $BLOCK_BUTTON in
    1) r.xkb-lang + ;;
    3) r.xkb-lang 0 ;;
    *) ;;
esac

LG=$( r.xkb-lang -n )

case "${LG}" in
    0) color="#00AE00" ;;
    1) color="#009EAF" ;;
    2) color="#FFAA00" ;;
    *) color="#C60101" ;;
esac

printf "$LG\n$LG\n$color\n"
