#!/bin/bash

track=$( mpc status | sed -n 'N;s/^\(.*\)\n\[.*\]\s\+#\(\S\+\)\s\+\(\S\+\)\s*.*/(\3) \1 < \2/p' )
 mode=$( mpc status | sed -n '2s/^\[\(.*\)\].*/\1/p' )

[ -n "$track" ] && declare $( printf "$track" |
    sed 's/^(\([0-9:]*\)\/\([0-9:]*\)) .*/curr=\1 length=\2/g' )

remain=$(( `date +%s -d "0:${length:-0}"` - `date +%s -d "0:${curr:-0}"` ))

toggle() {
    if [ "$mode" != "paused" ]; then
        mode="paused"
        mpc pause >/dev/null
    else
        mode="playing"
        mpc play >/dev/null
    fi
    if [ -z "$track" ]; then track="stopped"; fi
}

case $BLOCK_BUTTON
in 1) toggle
;; 3) pids=$(pgrep ncmpcpp)
    if [[ -z "$pids" ]]; then
        r.tf -e ncmpcpp  # Can't launch with disown!
    else
        for pid in $pids; do kill $pid; done
    fi
;; *)
esac #x=$BLOCK_X y=$BLOCK_Y

case "$mode" in
    playing) prefix='▶'; color='#CC44AA' ;;
     paused) prefix='∥'; color='#4444FF' ;;
          *) prefix='' ; color='#CC4400' ;;
esac

if [ "$mode" == "playing" ] && [ $remain -le 20 ] && [ $remain -gt 15 ]
then notify-send --urgency normal --expire-time=1000 -h int:x:500 -h int:y:500 '<b>Music</b> <i>category</i>' '<a href=a.html>You have 15s to choose</a>'
fi

printf "$track $prefix\n$track\n$color\n"
