#!/bin/bash -eu
source ~/.shell/func.d/packages

# pkg_inst bitlbee
aur_inst bitlbee-libpurple

# TODO: install plugins only if user declared related account
pkg_inst purple-skypeweb
aur_inst telegram-purple purple-discord-git purple-hangouts-hg
