#!/bin/bash
set -euo pipefail
source ~/.shell/profile

d=$(dirname "$(readlink -e "$0")")

get_pass(){ r.query-passwd "irc/${1:?}" 2>/dev/null || return 0; }

cfg="bitlbee ${IRC_USER:?} $(get_pass 'bitlbee')
common
skype    ${MAIN_SKYPE:?} $(get_pass 'skypeweb')
hangouts ${MAIN_MAIL:?}  $(get_pass 'hangouts')
telegram ${MAIN_TELGR:?} $(get_pass 'telegram')
discord  ${MAIN_MAIL:?}  $(get_pass 'discord')
"

## TODO: query list of configs from available vars
# (IFS=; declare -p) | grep -v '\s[A-Z0-9_]\+\b' | sed 's/declare -\S\+//'
# for nm in $BITLBEE_CONFIGS; do
#   cfg+="$nm ${BITLBEE_$nm_USER:?} $(get_pass "$nm")"
# done

# WARN: to use DFL values don't simply comment options in *.conf
#   -- you must set to DFL value explicitly or delete-and-recreate account beforehand
#   OR: delete whole /var/lib/bitlbee/*

"$d/exe/communicate" -- -v -c "$d/cfg" <<< "$cfg"
# "$d/exe/communicate" -- -r -c "$d/cfg" <<< "$cfg"
