#!/bin/bash
set -euo pipefail
source ~/.shell/profile

d=$(dirname "$(readlink -e "$0")")

get_pass(){ local id=irc/${1:?}
  r.query-passwd "$id" && return
  echo "Err: must store desired password beforehand: $ pass insert $id" >&2
  exit 2
}

cfg="bitlbee ${IRC_USER:?} $(get_pass 'bitlbee')"
cfg+=$'\n'
# cfg+=$'\n'some
cfg+=$'\n'"common"
cfg+=$'\n'"hangouts usr"
cfg+=$'\n'"skypeweb usr psw"

## TODO: query list of configs from available vars
# (IFS=; declare -p) | grep -v '\s[A-Z0-9_]\+\b' | sed 's/declare -\S\+//'
# for nm in $BITLBEE_CONFIGS; do
#   cfg+="$nm ${BITLBEE_$nm_USER:?} $(get_pass "$nm")"
# done

"$d/exe/communicate" "$d/cfg" <<< "$cfg"
