#!/bin/bash -eu
# tags: chat irc server
# deps: pass
source ~/.shell/func.d/cfgsetup

cfg=/etc/bitlbee/bitlbee.conf
uncomment(){ ! grep -q '^#\s*'"$1"'\s*=' "$cfg" \
  || sudo sed -ri '/^#\s*('"$1"'\s*=)/s//\1/' "$cfg"; }

# NOTE: restart bitlbee manually, if you add/change server settings
uncomment User
uncomment DaemonInterface
uncomment DaemonPort

Deprecated /etc/systemd/system/multi-user.target.wants/bitlbee.service
# MAYBE:(changes to config): $ sudo systemctl stop bitlbee.service
svc_activate -er bitlbee.socket

# BUG: after system update gpg/pass won't work until reboot -- fail for setup
#   ::: TEMP: remove lines with "bitlbee" and "weechat" from /tmp/airy-*.list
if cfgOpt u; then
  ./exe/configure $(cfgOpt r && echo --renew) -- "${BITLBEE_LIST[@]:?}"
fi
