#!/bin/bash -e

[[ $1 =~ xt=urn:btih:([^&/]+) ]] || exit

url="d10:magnet-uri${#1}:${1}e"
dst="meta-${BASH_REMATCH[1]}.torrent"

# watch_folder=~/.rtorrent/watch
# cd $watch_folder
printf '%s\n' "$url"  > "$dst"
