#!/bin/bash -e
source ~/sys_funcs
is_enabled 'lvm' || exit 0

# NOTE:(list all modules)
# $ mkinitcpio -M  # autodetected
# $ mkinitcpio -v  # pulled by hooks

## Add lvm2 hook
cfg=/etc/mkinitcpio.conf
cp -vf --backup=t ${cfg}{,}
cat > $cfg <<-'EOT'
MODULES=""
BINARIES=""
FILES=""
HOOKS="base udev autodetect modconf block lvm2 filesystems keyboard fsck"
#COMPRESSION="gzip"
#COMPRESSION_OPTIONS=""
EOT

# THINK: use systemd hook?
# ALT: HOOKS="base udev autodetect modconf block encrypt lvm2 filesystems keyboard fsck"
# WARNING: Create /etc/vconsole.conf beforehand if using 'consolefont'

## Re-create /boot/initrd.img-...
mkinitcpio -p linux


## Show available hooks and help for them
# mkinitcpio -L
# mkinitcpio -H udev
