#!/bin/bash -e
source ~/sys_funcs


### Switcher
  if is_enabled mbr; then mods='part_msdos'
elif is_enabled gpt; then mods='part_gpt'
elif is_enabled lvm; then
    mods='lvm'
    # FIXED: 'root=' -- doesn't work, seems like wiki has error. Don't use it.
    # args='root=lvm/lvm-boot'
    # systemctl enable lvm.service
fi
if is_enabled serial; then args="console=ttyS0,115200n8"; terms="serial"; fi


### Bootloader
pacman -S --noconfirm grub os-prober

## Change default grub:
# info -f grub -n 'Simple configuration'
# Press <Esc> to show menu.  Holding down the "SHIFT" key will not display the
# menu if "GRUB_TIMEOUT=" is set to "0"
# In future use 'sudo update-grub' after changes.
cfg=/etc/default/grub
cp -vf --backup=t ${cfg}{,}
cat > $cfg <<EOT
GRUB_DEFAULT=$(is_enabled lvm && echo 0 || echo saved)
GRUB_SAVEDEFAULT=$(is_enabled lvm && echo true || echo false)
GRUB_TIMEOUT=0
GRUB_TIMEOUT_STYLE=hidden  # hidden / countdown / menu
GRUB_DISABLE_RECOVERY=true
GRUB_DISABLE_OS_PROBER=$(is_enabled dual && echo false || echo true)
GRUB_DISABLE_SUBMENU=true

GRUB_DISTRIBUTOR="Arch"
GRUB_CMDLINE_LINUX_DEFAULT="quiet nosplash ${args}"
GRUB_CMDLINE_LINUX=""
GRUB_TERMINAL="console $terms"
$(is_enabled serial && echo 'GRUB_SERIAL_COMMAND="serial"' || echo)

GRUB_GFXPAYLOAD_LINUX=text  # text / keep
$(is_enabled encrypt && echo 'GRUB_ENABLE_CRYPTODISK=true' || echo)
GRUB_PRELOAD_MODULES="${mods:?No}"
## Fix broken 'lvmetad.socket: connect failed'; WARNING: not working?
# GRUB_DISABLE_SUBMENU=true
EOT


if is_enabled lvm; then
    ## Bind host /run to mitigate warnings 'lvmetad.socket: connect failded'
    mkdir -vp /run/lvm && mount --bind /hostrun/lvm /run/lvm
fi

# ERROR: --core-compress=auto  -- Not recognized?
grub-install --target=i386-pc --recheck ${SYS_DISK:?No}
grub-mkconfig -o /boot/grub/grub.cfg

if is_enabled lvm; then
    umount /run/lvm && rmdir -v /run/lvm
fi
echo ':: grub installed'

# Boot from cli:
# http://members.iinet.net/~herman546/p20/GRUB2%20How%20To%20Boot%20From%20CLI%20Mode.html#How_To_Chainload_and_Boot
