#!/bin/bash -e
source ~/sys_funcs
is_enabled 'user' || exit 0

user="${SYS_USER:?No}"


### ADD users:  https://wiki.archlinux.org/index.php/Users_and_groups#User_groups
# adbusers, mpd, vboxsf, vboxusers, wireshark
id -g $user || groupadd $user  # ALT:BET:USE: unified command $ useradd -U ...
id -u $user || useradd -m -g $user -G users,wheel,uucp,games -s /bin/bash $user
gpasswd -a $user uucp  # FIND: useradd is not enough to add to group?
printf "%s" $user:$user | chpasswd
echo ":: created '$user' password"


### sudo for user
pacman -S --noconfirm sudo

entry="$user ALL=(ALL) \
NOPASSWD:/sbin/reboot,/sbin/halt,/sbin/shutdown,/sbin/poweroff"
dst=/etc/sudoers

sed -i '/.*\(%wheel ALL=(ALL) ALL\)/s//\1/' $dst  # Uncomment group 'wheel'
sed -i "/^$user ALL=(ALL) NOPASSWD/d" $dst       # Add specific rights
echo "$entry" | tee --append $dst
echo ":: sudo '$user' enabled"
