#!/bin/bash
#%USAGE: 0=off  1=on  ''=toggle
set -euo pipefail -o noglob

# BUG: after boot must run something to launch pulse server
#   => otherwise ERR pulse not started

state=${1-}
prf0='output:analog-stereo+input:analog-stereo'
prf1='output:hdmi-stereo+input:analog-stereo'

cards=( $(pacmd list-cards | sed -rn '/^\s*name:\s*<(\S+)>.*/s//\1/p') )
((${#cards[@]} == 1)) || { echo "Err: unsupported number of audio cards (DFL=1)"; exit; }
card=${cards[0]}

profiles=( $(pacmd list-cards | awk 'p{if(match($0,/\S/)<=p)exit;sub(/:$/,"",$1);print$1} /profiles:$/{p=match($0,/\S/)}') )
[[ " ${profiles[@]} " =~ " $prf0 " ]] || { echo "Err: wrong '$prf0'"; exit; }
[[ " ${profiles[@]} " =~ " $prf1 " ]] || { echo "Err: wrong '$prf1'"; exit; }

active=$(pacmd list-cards | sed -rn '/^\s*active profile:\s*<(\S+)>.*/s//\1/p')

# pacmd set-default-sink ${NEXT:=0}
setprf(){ [[ $1 == $active ]] || pacmd set-card-profile "$card" "$1"; }

case $state
in 0) setprf "$prf0"
;; 1) setprf "$prf1"
;; '') p=$prf1; [[ $active == $p ]] && p=$prf0; echo "$p"; setprf "$p"
;; *) exit 2
esac
