#!/bin/bash -e
# tags: media
# deps: xorg
source ~/.shell/func.d/cfgsetup

if [[ $CURR_PROF != neo ]]; then
  svc_activate -cue pidgin.service
fi

### GENS ###
acc=~/.purple/accounts.xml
cfg=~/.purple/prefs.xml

if cfgOpt r || [[ ! -f $acc || ! -f $cfg ]]; then
  # WARNING: symlink is not enough, it will be replaced when you launch pidgin!
  linkcp -c ./prefs.xml "$cfg"
  ./accounts.gen
  # gnome-keyring-daemon --replace
fi

mkdir -p ~/chat
ln -svfT ~/.purple/logs ~/chat/pidgin

echo "C: pidgin"
