#!/bin/bash -e
# tags: media
# deps: xorg
source ~/.shell/func.d/cfgsetup

# FIXME: separate "setup" and "autostart" steps for user to choose
#   => user lists what to "install+setup", what "defaults" and what "autostart"
# svc_activate -cue pidgin.service

### GENS ###
# TODO: separate "purple" mod -- which is common for "pidgin" and "bitlbee"
acc=~/.purple/accounts.xml
cfg=~/.purple/prefs.xml

if cfgOpt r || [[ ! -f $acc || ! -f $cfg ]]; then
  # WARNING: symlink is not enough, it will be replaced when you launch pidgin!
  linkcp -c ./prefs.xml "$cfg"
  ./accounts.gen
  # gnome-keyring-daemon --replace
fi

linkcp -m ~/.purple/logs ~/chat/pidgin

echo "C: pidgin"
