#!/bin/bash
# Don't launch, source only!

if [ -d ~/.bash/aliases.d ]; then
    for fl in ~/.bash/aliases.d/*; do if [[ \
        "${SHELL##*/}" == zsh || \
        "${fl##*/}" != zsh*      \
        ]]; then source "$fl"; fi
    done
fi


## Inspired by Vivek Gite <vivek@nixcraft.com>
## http://www.cyberciti.biz/tips/linux-unix-osx-bash-shell-aliases.html

# See also one-liners for system commands usage:
# http://ubuntism.ru/terminal-commands-for-linux/

