#!/bin/bash
# Don't launch, source only!

DIR=~/.bash/aliases.d
FLES=(colored special pathes git std funcs system info others less-termcap)

if [ -d "$DIR" ]; then
    for fl in ${FLES[@]}; do
        source "$DIR/$fl"
    done

    case "${SHELL##*/}" in
        zsh) source "$DIR/zsh" ;;
    esac
fi


## Inspired by Vivek Gite <vivek@nixcraft.com>
## http://www.cyberciti.biz/tips/linux-unix-osx-bash-shell-aliases.html

# See also one-liners for system commands usage:
# http://ubuntism.ru/terminal-commands-for-linux/

