#!/bin/bash -e
source ~/.shell/func.d/cfgsetup
[[ "$THEME" =~ ^(dark|light)$ ]] || THEME=dark

### LINKS ###
link "$PWD" ~/.i3
mkdef x-window-manager $(which i3)

### GENS ###
THEME=$THEME ./i3-config.gen

if cfgOpt u && has_pr X; then
    i3-msg restart </dev/tty >/dev/null 2>&1 ||:
fi
