#!/bin/bash -e

# Format: <b>Music</b>\n<i>You have 15s to choose</i>
# <a href=a.html></a>
ARGS=( )
CMD=( notify-send )

while getopts 'a:c:i:p:t:uU' o; do case "$o"
in t) EXPIRE=$OPTARG
;; u) CMD+=( --urgency=low )
;; U) CMD+=( --urgency=critical )
;; i) CMD+=( --icon=$OPTARG )  # [,icon,...]
;; p) CMD+=( -h int:value:$OPTARG )
;; a|c|i) ARGS+=( -$o $OPTARG )
;; *) exit; esac; done; shift $((OPTIND-1))

if [[ ! ${CMD[*]} =~ urgency=critical ]] || ((EXPIRE > 0)); then
  CMD+=( -t $((${EXPIRE:-12}*100)) )
fi

# CMD+=( -h string:bgcolor:\#ffffff \
#        -h string:fgcolor:\#000000 )
# Pos: -h int:x:500 -h int:y:500
# Icon: -i '/usr/share/icons/oxygen/32x32/status/mail-unread-new.png'

(($#)) && ARGS+=("${1:-}" "${*:2}") || ARGS+=('(no text)')
exec "${CMD[@]}" "${ARGS[@]}"
