#!/bin/bash -e
source ~/.shell/func.d/packages

# SEE:
#   http://www.linuxveda.com/2015/03/09/how-to-install-virtualbox-in-arch-linux/

if distro arch; then
    aur_inst 'virtualbox-bin'
    pkg_inst 'virtualbox-host-modules'
    # dkms autoinstall  # For custom, also: pkg_inst virtualbox-host-dkms
    # modprobe vboxdrv  # insert driver

elif distro ubuntu; then
    echo "Dld manually!"

    # VBox guest
    # pkg_inst "virtualbox-guest-additions virtualbox-guest-utils \
    #           virtualbox-guest-dkms virtualbox-guest-x11"
fi

