#!/bin/bash -e
# tags: io
source ~/.shell/func.d/cfgsetup


# You can make A4 your default paper size ! : archlinux ⌇⡠⡇⡵⠋
#   https://www.reddit.com/r/archlinux/comments/lyy8fp/you_can_make_a4_your_default_paper_size/
#   echo 'a4' >> /etc/papersize
#   OR: echo 'LC_PAPER="en_DK.UTF-8"' >> /etc/locale.conf
#   locale LC_PAPER
