#!/bin/bash -eu
set -o pipefail
cwd=${1-}; [[ $cwd == /?* && -d $cwd ]] && { cd "$cwd"; shift; }
# WARN: color.ui works only if no other color.* set in .gitconfig
exec r.git-find | parallel -0 -k \
  r.git-status {} '&&' \
  git -C {} -c color.ui=always --no-pager \
  "${@:-remote -v}" '2>&1' #'&&' echo
