#!/bin/bash -eu
set -o pipefail
## DEV show found submodules only in status (yellow color)
cd "${1:-$PWD}"
export WCOL=$(r.git-find | awk -vd="$PWD" \
  'BEGIN{RS="\0";d=length(d)} {print length-d}' \
  | LC_ALL=C sort -rn | head -1)
exec r.git-find | parallel -0 -kX r.git-status {}
# BAD: counts all escape codes for colors
# | column -ts $'\t'
