#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

# TODO
#   https://wiki.archlinux.org/index.php/Samba/Tips_and_tricks

## Don't share samba in work network, only at home
cfgOpt f || [[ ${CURR_PROF:?} =~ ^(laptop|home|neo)$ ]] || die 0 "<Skip>"

echo "N: ATTENTION ! Generate password for samba user !"
if cfgOpt r; then
  sudo smbpasswd -a $(whoami)
fi

if cfgOpt u; then
  ### GENS ###
  ./samba.gen
  svc_activate -er smbd
  # Once Samba has restarted, use this command
  # to check your smb.conf for any syntax errors
  testparm -s >/dev/null
fi

# EXPL to see errors on start
# sudo smbd -i
# ATTENTION sudo chmod 0755 /var/cache/samba/msg
