#!/bin/bash -e
source ~/.shell/profile
source ~/.shell/func.d/cfgsetup

distro ubuntu || exit 0

## Don't share samba in work network, only at home
case "${CURR_PROF?No}" in
laptop|home)
  if cfgOpt r; then
    echo "N: ATTENTION ! Generate password for samba user !"
    sudo smbpasswd -a $(whoami)
  fi

  if cfgOpt u; then
    ### GENS ###
    ./samba.gen
    sudo service smbd restart
    # Once Samba has restarted, use this command
    # to check your smb.conf for any syntax errors
    testparm
  fi

;; *) ## FIXME: not working as supposed:
#if cfgOpt u && has_pr samba; then sudo service smbd stop
exit ;; esac
