#!/bin/bash
#To install just the headers in Ubuntu:
 sudo apt-get install linux-headers-$(uname -r)
#To install the entire Linux kernel source in Ubuntu:
 sudo apt-get install linux-source kernel-package
#Note that you should use the kernel headers that match the kernel you are running.
