#!/bin/bash -e
source ~/sys_funcs
is_enabled 'X' || exit 0

# Those scripts must provide only basic strokes to load X.
# They will be completely replaced by user setup from git.
wscript ~/.profile "\
#!/bin/sh
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -z \$DISPLAY && \$XDG_VTNR -eq 1 ]] && exec startx
# OR: ... && exec xinit -- :0 -nolisten tcp vt\$XDG_VTNR
"

wscript ~/.xinitrc "\
#!/bin/sh
xrandr --size 1 &
xsetroot -gray &
exec i3
"
