#!/bin/bash -e
# tags: media
THEME_ALLOWED='dark|light'
# THEME=light  # TEMP:CHG: .../theme/{PWD##*/}
source ~/.shell/func.d/cfgsetup

### LINKS ###
linkcp  zathurarc-"${THEME}"  ~/.config/zathura/zathurarc
