#!/bin/bash

source ~/.shell/funcs

# Windows manager
# dst=~/.dmrc
# wbegin
# # Language=en_US -- breaks
# wstr "[Desktop]
# Session=i3"
# echo "W: $dst  <- i3"

# Editor
# dst=~/.selected_editor
# wbegin
# wstr "SELECTED_EDITOR=\"/usr/bin/vim.gtk\""
# echo "W: $dst  <- vim"

# Set default prs
sudo update-alternatives --set x-window-manager /usr/bin/i3
sudo update-alternatives --set x-terminal-emulator /usr/bin/urxvt
sudo update-alternatives --set vim /usr/bin/vim.gtk
sudo update-alternatives --set editor /usr/bin/vim.gtk
sudo update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/local/bin/vimb 200
sudo update-alternatives --set x-www-browser /usr/local/bin/vimb
# sudo update-alternatives --config gnome-www-browser

# To disable default notification daemon on Lubuntu
XFCE=/usr/share/dbus-1/services/org.xfce.xfce4-notifyd.Notifications.service
[ -f "$XFCE" ] && sudo mv -n $XFCE{,.disabled}

# See all groups:
# update-alternatives --get-selections

# update-alternatives
#     gnome-www-browser
#     rview vim.gtk
#     view vim.gtk
#     www-browser w3m
#     x-session-manager cinnamon-session-cinnamon
#     x-www-browser palemoon

### Shell ###
# Choose default shell
ZSH=$(which zsh)
ZSH=${ZSH:-/bin/bash}
#sudo chsh -s `which zsh`
sudo usermod -s $ZSH "$CURR_USER"

