#!/bin/bash

source ~/.bash_functions

# Windows manager
dst=~/.dmrc
wbegin
# Language=en_US -- breaks
wstr "[Desktop]
Session=i3"
echo "W: $dst  <- i3"

# Editor
dst=~/.selected_editor
wbegin
wstr "SELECTED_EDITOR=\"/usr/bin/vim.gtk\""
echo "W: $dst  <- vim"

# Set default prs
sudo update-alternatives --set x-window-manager /usr/bin/i3
sudo update-alternatives --set x-terminal-emulator /usr/bin/urxvt
sudo update-alternatives --set vim /usr/bin/vim.gtk
sudo update-alternatives --set editor /usr/bin/vim.gtk

# See all groups:
# update-alternatives --get-selections

# update-alternatives
#     gnome-www-browser
#     rview vim.gtk
#     view vim.gtk
#     www-browser w3m
#     x-session-manager cinnamon-session-cinnamon
#     x-www-browser palemoon

### Scripts ###
# bash .\w aliases -> ranger/bookmarks
~/.config/ranger/aliases_to_bookmarks

### Shell ###
# Choose default shell
ZSH=$(which zsh)
ZSH=${ZSH:-/bin/bash}
#sudo chsh -s `which zsh`
sudo usermod -s $ZSH "$CURR_USER"

