#!/bin/bash
# pristine -- древний; первоначальный, изначальный; чистый, нетронутый; неиспорченный
# Manual install: -t_egp_bcxz

source ~/.shell/profile
source ~/.shell/funcs
source ~/.shell/func.d/packages
amScriptDir -s
if [ -z "$SCRIPT_DIR" ]; then echo "Error: SCRIPT_DIR"; exit 1; fi

## Dir for manual install and compilation (beside ppa)
mkdir -p "$CURR_DIR_PKG"
PRS_DIR="$SCRIPT_DIR/${SCRIPT_PATH##*/}.d"


## Parse my own set of params
OPTS_SET=($@)
if [ $# -eq 0 ]; then
    OPTS_SET=( $CURR_PKG_LIST )
fi

if [ "$1" == "-u" ]; then
    sudo apt-get update -y
    sudo apt-get upgrade -y
    # sudo apt-get dist-upgrade -y #&& sudo reboot
else

    cRed=$(tput setaf 1)
    cGrn=$(tput setaf 2)
    cYlw=$(tput setaf 3)
    cBlu=$(tput setaf 4)
    cPrl=$(tput setaf 5)
    cStd=$(tput sgr0)

    # Installing
printf "
| OPTS_SET: ${OPTS_SET[@]}
| FROM: ${PRS_DIR}
\n"
    for pr in "${OPTS_SET[@]}"; do
        prgb="$PRS_DIR/${pr}.pr"
        printf "\n${cPrl}INSTALL: ${prgb##*/}$cStd\n"
        if ! [ -f "$prgb" ]; then
            echo "${cRed}Error! Don't exist $prgb${cStd}"
            continue
        fi
        $prgb 2>&1 | tee /tmp/pristine.log | awk '{pf=0}
            /^E:.*/ {pf=1; printf "'"$cRed%s*$cStd"'",$0}
            /^The following/ { printf "\n" }
            /^The following packages will be upgraded/ {pf=1; next; printf "'"$cYlw%s*$cStd"'",$0}
            /^The following extra packages/,/^After this operation/ {pf=1; printf "\n%s",$0}
            /is already the newest version/ {pf=1; printf "'"$cGrn%s*$cStd"'",$1}
            /^Get:/ { printf "'"${cBlu}.$cStd"'" }
            { if(pf==0) {printf "."} } '
        printf "\n"
    done
fi


# MAN
# if add-apt-repository not found:  sudo apt-get python-software-properties
# to remove unavailable ppa:        sudo apt-get install ppa-purge, sudo ppa-purge [the ppa you want to remove]
#   ALT: Manually edit 'sudo vim /etc/apt/sources.list.d/*'
# to upgrade:                       sudo do-release-upgrade
# remove packages:                  sudo apt-get autoremove ..  or  sudo apt-get remove --purge

