#!/bin/bash

source ~/.shell/funcs
amScriptDir -s
# Search for profile in $1/ dir or in $1/../ dir
PROFILES_DIR=${1:-$SCRIPT_DIR}
ROOT_PROF=$PROFILES_DIR/$([ -z "$2" ] && echo "guest" || echo "$2").profile
[ ! -f "$ROOT_PROF" ] && ROOT_PROF="${PROFILES_DIR%/*}/${ROOT_PROF##*/}"
[ ! -f "$ROOT_PROF" ] && ROOT_PROF="${SCRIPT_DIR}/${ROOT_PROF##*/}"
[ ! -f "$ROOT_PROF" ] && squit

dst=~/.shenv
#dst=$SCRIPT_DIR/export
# Needs to create wxopt_add: for PATH and
# for CURR_INSTALLED_PACKAGES (my var for pristine list of groups)
wxopt() {
    KEY="export ${1?'No var name!'}"
    VAL="${2?'No var value!'}"

    if [ -n "$4" ];
    then SED_EXP="s|\($KEY=.*\)|\1${4}${VAL}|g" # Append value by $4 sep
    else SED_EXP="s|\($KEY=\).*|\1${VAL}|g"  # Replace value
    fi

    case `cat $dst | grep -c "$KEY="` in
      0) # (IMS: insert group as new if different, and move option line to new location)
        SEC_END="$(sed '/^### END ###/,$!d' $dst)"
        sed -i '/^### END ###/,$d' $dst
        if [ ! -z "$3" ]; then # Create group name if absent. #echo -en "\n$EXP_GROUP\n"
            wprf "\n${3}\n$KEY=$VAL\n"; wprf "$SEC_END"; return 2
        else wstr "$KEY=$VAL"; wprf "$SEC_END"; return 0; fi ;;
      1) sed -i -e "$SED_EXP" $dst; return 0 ;;
      *) echo "Error: duplicates of '$KEY' in $dst" >&2; return 1 ;;
    esac
}

export_profile(){
    if [ -f "$1" ]; then
        cat "$1" | integrate_profile "$1"
    fi
}

integrate_profile() {
    local EXP_GROUP PARENT_PROF="$1" nm val
    while read line; do
        # Read group name, grep -qc
        if echo $line | grep -q "^ *\#\#\#\ .*\ \#\#\#"
        then EXP_GROUP="$line"
        # Recursively launch existing pre-files
        elif echo $line | grep -q "^ *import .*"
        then IM_PROF="$PROFILES_DIR/${line/import }.profile"
            [ ! -f "$IM_PROF" ] && IM_PROF="${PROFILES_DIR%/*}/${IM_PROF##*/}"
            if [ "$PARENT_PROF" != "$IM_PROF" ]; then
                export_profile "$IM_PROF"
            fi
        # Work with separate options
        elif echo $line | grep -q "^ *\w*+\?=.*"
        then # Replace existing option or add new
            #echo \'${line%=*}\' "->" \'${line##*=}\'
            nm="$(echo ${line} | sed 's/\(\s*\w\+\)+\?=.*/\1/')"
            val="$(echo ${line} | sed 's/.*+\?=\(.*\)/\1/')"

            if [ "$nm" == "PATH" ]
            then wxopt "$nm" "$val" "$EXP_GROUP" ':'
            elif [ "${line/+=}" != "${line}" ]
            then wxopt "$nm" "$val" "$EXP_GROUP" '" "'
            else wxopt "$nm" "$val" "$EXP_GROUP"
            fi
            if [ $? -eq 2 ]; then EXP_GROUP=""; fi
        fi
    done
}

export_profile "$SCRIPT_DIR/default.profile"
export_profile "$PROFILES_DIR/common.profile"
export_profile "$ROOT_PROF"

echo "W: $dst <- profile $ROOT_PROF"

