#!/bin/bash

source ~/.bash/functions.d/packages

git_get 'shadowbq/Cheat-Sheets'
#git_get vispy #for python primes

# SEE for dependencies: http://www.graphviz.org/Download_source.php
git_get 'ellson/graphviz'

# System Programming:  lessons and examples -- smashing stack, etc
# https://github.com/angrave/SystemProgramming/wiki
