#!/bin/bash -eu
set -o pipefail
# WARN: unsecure -- someone with occasional access to system
#   may change this script to dump actual passwords -- use systemwide one
# BET? https://wiki.archlinux.org/index.php/Pass
#   https://github.com/roddhjav/pass-tomb
#   https://wiki.archlinux.org/index.php/Tomb

opts=; while getopts 'm' o; do case $o in :|'?') exit 1
esac; opts+=$o; done; shift $((OPTIND - 1))

prf(){ printf '%s' "$@"; }

acc=${1:-$([[ -t 0 ]]||ifne cat)}
acc=${acc:?}
pass=${2-}

## DEBUG
# > /tmp/mut
# echo "\$2=$pass" >> /tmp/mut
# prf(){ printf '%s' "$@" | tee -a /tmp/mut; }

if [[ -z $pass ]]; then
  pass=$(r.query-passwd "mutt/$acc")
fi

if [[ -z $pass ]]; then
  read -esp "Mutt pass ($acc): " pass </dev/tty
  echo >/dev/tty
fi

if [[ $opts =~ m ]]; then
  prf "set my_pass=$pass"
  if [[ $acc =~ ^[a-zA-Z]+$ ]]
  then prf "; set my_pass_$acc=$pass"
  else echo 'Err: account name must be =~ \w+' >/dev/tty; fi
else
  prf "$pass"
fi

## Debug
# echo>> /tmp/mut
