#!/bin/bash -e
source ~/.shell/profile

mkdir -p ~/.mail/"${MUTT_DEFAULT:?}"
# -c ~/.mbsyncrc
# --all
# -l
# USE:(err_1: -V) to find out file to remove/resync: <dir>/.uidvalidty
mbsync "${MUTT_DEFAULT:?}"
# Indexate db
notmuch new
