#!/bin/bash -e
source ~/.shell/func.d/packages

# SEE
#   http://masterpatricko.blogspot.com/2011/04/development-and-build-environments_20.html

pkg_inst 'schroot'

if distro arch; then
    aur_inst 'debootstrap'
    # Install for ubuntu
    aur_inst --asdeps 'gnupg1 ubuntu-keyring'
    # One or more PGP signatures could not be verified!
    # gpg --recv-keys 2071B08A33BD3F06

elif distro ubuntu; then
    echo "Err: not enough"
fi
