#!/bin/bash -e
source ~/.shell/profile

# ALT: NOTE failed to setup schroot.conf to export only choosen env variables.
# BAD: can't exit on error in awk (try run r.chroot inside r.chroot)

# USE: 'r.chroot 1' -- to load second chroot from list
case "$1" in [0-9]) index=$1; shift ;; esac
prf=${CURR_CHROOTS[${index:-0}]:?}
chroot=${CURR_DIR_CHROOT:?}/$prf

# EXPL: Derive mounted/overrided PWD for chroot
dir=$PWD
[[ ${dir#$chroot} == $dir ]] || dir=${dir#$chroot}
unset ismounted && while read line; do
    [[ ${dir#$line} == $dir ]] || ismounted=1
done < <(awk '/^\//{print$1}' /etc/schroot/default/fstab)
if ((!ismounted)) && [[ ! -d ${chroot}${dir} ]]; then
  [[ -d $CURR_DIR_WORK ]] && dir=${CURR_DIR_WORK:?} || dir=$HOME
fi

# EXPL: filter-out env vars before command
# USAGE: $ r.chroot A=4 B=some <cmd>
# ALT: use eval in: $ bash -ic 'eval "$@"' "$0" "$@"
_env=()
for arg in "$@"; do
  [[ $arg =~ ^[[:alpha:]_][[:alnum:]_]*= ]] || break
  _env+=( "$arg" )
  shift
done

# NOTE: source ~/.bash_profile by forcing interactive shell
# ATT: -l is not enough to activate SHELLRC_EVAL
# MAYBE:(exec) will be excessive limitation for cmdline?
((!$#)) && set -- "$SHELL" || set -- bash -ic 'exec "$@"' "$0" "$@"
# TODO: use ZSH in chroot if available [[ -x ${chroot}$SHELL ]]
# THINK: using tmux? how to be with nested sessions?

# EXPL Export SHELLRC_EVAL to source env in each spawned shell from ranger
exec schroot -c "$prf" -d "$dir" -- env \
  DISPLAY="$DISPLAY" SHELLRC_EVAL="${CURR_CHROOT_EVAL}" \
  "${_env[@]}" "$@"


# ALT:DEPRECATED:
# BUG: using 2>&1 don't exit interactive shell
#   $ r.chroot pwd |& cat
#   $ r.chroot pwd 2>/dev/null
# BUT: what tot do with --rcfile?
# exec schroot -c "$prf" -d "$dir" -- bash --rcfile <(cat - <<EOT
# export DISPLAY=$DISPLAY SHELLRC_EVAL="${CURR_CHROOT_EVAL}"
# source ~/.bash_profile
# ${@+trap 'exit 1' INT HUP QUIT TERM; "$@"; exit}
# EOT
# )

# NOTE: vars from rcfile aren't inherited for -c!
# ${@+-c 'trap "exit 1" INT HUP QUIT TERM; "$@"' "$0" "$@"}
