#!/bin/bash -e
source ~/.shell/profile

# ALT: NOTE failed to setup schroot.conf to export only choosen env variables.
# BAD: can't exit on error in awk (try run r.chroot inside r.chroot)

# USE: 'r.chroot 1' -- to load second chroot from list
case "$1" in [0-9]) index=$1; shift ;; esac
prf=${CURR_CHROOTS[${index:-0}]:?}
chroot=${CURR_DIR_CHROOT:?}/$prf

# EXPL: Derive mounted/overrided PWD for chroot
dir=$PWD
[[ ${dir#$chroot} == $dir ]] || dir=${dir#$chroot}
unset ismounted && while read line; do
    [[ ${dir#$line} == $dir ]] || ismounted=1
done < <(awk '/^\//{print$1}' /etc/schroot/default/fstab)
if ((!ismounted)) && [[ ! -d ${chroot}${dir} ]]; then
  [[ -d $CURR_DIR_WORK ]] && dir=${CURR_DIR_WORK:?} || dir=$HOME
fi

# EXPL Export SHELLRC_EVAL to source env in each spawned shell from ranger
# TODO: use ZSH in chroot if available [[ -x ${chroot}$SHELL ]]
# BUT: what tot do with --rcfile?
# THINK: using tmux? how to be with nested sessions?
exec schroot -c "$prf" -d "$dir" -- bash --rcfile <(cat - <<EOT
export DISPLAY=$DISPLAY SHELLRC_EVAL="${CURR_CHROOT_EVAL}"
source ~/.bash_profile
${@+trap exit INT HUP QUIT TERM; "$@"; exit}
EOT
)
