#!/bin/bash -e

dir="${PWD#/cryptfs/chroots/lucid_i386}"
if [[ "$PWD" =~ ^/cryptfs/_/ ]]; then
    dir="$PWD"
elif [[ "$PWD" == $dir ]]; then
    dir=/cryptfs/workspace
fi

# EXPL Export SHELLRC_EVAL to source env in each spawned shell from ranger
schroot -c lucid_i386 -d "$dir" -- bash --rcfile <(cat - <<EOT  ${@:+-c "$@"}
export SHELLRC_EVAL='. /cryptfs/_/cfg/env; . /cryptfs/_/cfg/bash_extension.sh; export DISPLAY='$DISPLAY'; export EDITOR=vim'
. ~/.profile
EOT
)
# ALT: NOTE failed to setup schroot.conf to export only choosen env variables.
# schroot -c lucid_i386 -d "$dir" -- bash --rcfile <(echo "
#     export SHELLRC_EVAL='. /cryptfs/_/cfg/env; . /cryptfs/_/cfg/bash_extension.sh'
#     export DISPLAY='$DISPLAY'
#     . ~/.bashrc
#     EDITOR=vim
# ") ${@:+-c $@}
