#!/bin/bash -e
# tags: dev seom#
source ~/.shell/func.d/cfgsetup

# ATTENTION: currently all chroots are configured the same -- for identical kind of tasks.
# TODO: replace by individual custom profiles, linking whole dir from pwd

if cfgOpt u; then
  ./gen/config.gen
  ./gen/fstab.gen
  ./gen/nss.gen
  ./gen/net.gen
  ./gen/debinit
fi
