#!/bin/bash -eu
source ~/.shell/func.d/packages

pkg_inst bumblebee primus lib32-primus lib32-virtualgl
pkg_inst bbswitch  # Only for laptops

# NOTE: used also to translate DirectX inside Wine to Vulkan (steam Proton)
pkg_inst primus_vk vulkan-intel vkd3d
pkg_inst lib32-primus_vk lib32-vulkan-intel lib32-vkd3d
