#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
# if [[ ${CURR_PROF:?} =~ ^neo ]]; then
  link -t ~/.config/fontconfig fonts.conf
  # OR: use infinality-bundle instead
# fi

### GENS ###
if cfgOpt u; then
    # cfg=/etc/fonts/conf.d/10-scale-bitmap-fonts.conf
    # if [[ -L $cfg ]]; then rm $cfg; fi
    link -s /etc/fonts/{conf.avail,conf.d}/70-no-bitmaps.conf
    ./update
fi

dst=~/.Xresources
wstr(){ cat >> "$dst" <<<"$*"; }

# BUG: boot linux with hdmi2 on => wrong xrandr order => wrong DPI
[[ $MAIN_DPI ]] || MAIN_DPI=$(r.xorg -d 2>/dev/null||echo 96)

> "$dst"
wstr "#ifndef MAIN_DPI"
wstr "# define MAIN_DPI  ${MAIN_DPI:?}"
wstr "#endif"
for f in "${CURR_DIR_CACHE:?}"/Xres-*; do
  wstr "#include \"$f\""
done
cat "$PWD/xfontrc" >> "$dst"
echo "W: ~/.Xresources"
! xrdb -load ~/.Xresources 2>&1 | grep 'error'
# To see the current loaded resources
#   xrdb -query -all
