#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

if cfgOpt u; then
    if distro arch; then
        link -sct /etc/conf.d 'nfs-server.conf'
        svc_activate -eR rpcbind nfs-server nfs-mountd

    elif distro ubuntu; then
        echo "Err: No NFS config conversion. Works by default?"
        svc_activate -eR nfs-kernel-server
    fi
fi
