#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

if cfgOpt u; then
    if distro arch; then
        linkcp -c nfs.conf /etc/sysconfig/nfs
        svc_activate -eR nfs-config rpcbind rpc-statd nfs-mountd nfs-server

    elif distro ubuntu; then
        echo "Err: No NFS config conversion. Works by default?"
        svc_activate -eR nfs-kernel-server
    fi
fi
