#!/bin/bash -eu
source ~/.shell/func.d/packages
# ALSO:(base) coreutils util-linux inetutils iputils procps-ng
# ALSO: xorg-utils
# ALSO: john (extended utils for passwd crack)
# TODO: $ pacs -r/-a '(tool|util)' G ^\\S C

# ALT:(ls|tree): https://github.com/ogham/exa
pkg_inst tree
pkg_inst squashfs-tools

# E.G. $ datediff 2011-11-15 2012-04-11 $ => 148
# ALT: $ echo $(( ($(date +%s -d 2012-02-03) - $(date +%s -d 2012-01-15)) / 86400 ))
pkg_inst dateutils

# SEE https://joeyh.name/code/moreutils/
# TODO: read man on each util
pkg_inst moreutils

# USAGE:READ: $ /usr/lib/plan9/bin/9 man 1 intro
# SEE: multiple possibly useful utils
pkg_inst plan9port  # OR: 9base

# SEE: https://skarnet.org/software/
# aur_inst s6-portable-utils
