#!/bin/bash -e
# vim: ft=sh
source ~/.shell/func.d/packages

# libclang-dev exuberant-ctags python-dev   | for autocompleter in vim
# clang-format-3.5          | for auto-formatting c/cpp code

if distro arch; then
    # SEE gtags (GNU Global) -- instead of ctags?
    # aur_inst neovim-git
    pkg_inst -p 'pip' python-pip
    # Used 'gvim' instead of 'gvim-python3' for YouCompleteMe
    #   and for pythoncomplete#Complete
    pkg_inst -p 'vim' gvim-python3
    pkg_inst ctags vimpager
    echo "Err: not all"

elif distro ubuntu; then
    # for vimoutliner export in mindmap
    pkg_inst vim-gtk exuberant-ctags 'python-pip' python-dev
    pkg_inst libclang-dev clang-format-3.5
fi

do_if -c 'sudo pip install --upgrade' pip jedi
