#!/bin/bash -e

# NOTE: $NVIM_TUI_ENABLE_TRUE_COLOR
#   = replaced by ':set termguicolors' for >160511
#   = no longer sets 'has("gui_running")' for >160204

_has_pr(){ hash "$1" >/dev/null 2>&1; }

if _has_pr nvim; then
  # unset NVIM_TUI_ENABLE_TRUE_COLOR
  unset NVIM_TUI_ENABLE_CURSOR_SHAPE

  case "$TERM"
  in rxvt-*)
    # BUG: open vim inside vim -- thinks it's xterm
    # BUG: on android xterm is fake = trash symbs on cursor
    export NVIM_TUI_ENABLE_CURSOR_SHAPE=1
    export TERMCMD='urxvt'
  ;; st-*)
    # export NVIM_TUI_ENABLE_TRUE_COLOR=1
    export NVIM_TUI_ENABLE_CURSOR_SHAPE=1
    export TERMCMD='st'
  ;; tmux-256color|screen-256color*)
    # Works only with tmux-24bit-color which after merge > v2.1.1
    if _has_pr tmux && tmux -V | grep -q 'tmux [2-9]\.[2-9]'; then
        # export NVIM_TUI_ENABLE_TRUE_COLOR=1
        export NVIM_TUI_ENABLE_CURSOR_SHAPE=1
    fi
    # export TERMCMD='tmux split-window "$cmd"'
  esac
fi

# EXPL: run vim if there are no 'nvim'
for pr in nvim vis vim vi; do
  if _has_pr $pr; then exec $pr "$@"; fi
done
exit 1  # ERR: if not found

# v() { #servername == syntex (must be for LaTeX)
#     local _V fl=~/.cache/vim/servername
#     if [[ -f "$fl" ]]; then
#         _V=$(cat "$fl")
#         $EDITOR --servername $_V --remote-silent $@
#         $EDITOR --servername $_V --remote-send ':redraw<CR>'
#     else
#         $EDITOR $@
#     fi
# }
