#!/bin/bash -e
[[ -t 0 ]] && ARGS='"$@"' || ARGS='<(cat -)'
eval "exec r.tf $EDITOR -c 'norm!G0' $ARGS &"

# pipe="$(mktemp -ut "st-screen.XXX")"
# trap "rm -f $pipe" HUP INT QUIT ILL TRAP KILL BUS TERM EXIT
# [[ -p $pipe ]] || mkfifo $pipe
