#!/bin/bash -e
cd $(dirname $(readlink -m ${0})) && source ~/.shell/func.d/cfgsetup

### LINKS ###
link "$PWD" ~/.vim  #vim/vimrc vim/nvimrc vim/ycm_extra_conf.py

# Dir for .swp, backup, ... files
VCACHE=~/.cache/vim
mkdir -vp "$VCACHE"
FONT="$VCACHE/powerline-fonts/DejaVuSansMono"

if [[ "$clean" -eq 1 ]]; then rm -rf "$VCACHE"; fi


### SPELL ###
# WARNING: first clean install will always fail as uk*.sug file is absent!
if [[ ! -d "$VCACHE/spell" ]]; then
    mkdir -p "$VCACHE/spell"
    src='http://ftp.vim.org/pub/vim/runtime/spell'
    for nm in ru en uk; do ( cd "$VCACHE/spell"
        wget "$src/${nm}.utf-8.spl" && wget "$src/${nm}.utf-8.sug"
    ) done
fi
# For vim-easytags
#touch ~/.vimtags


### FONTS ###
# FIXME: fonts are needless on headless system! Check what???
# https://powerline.readthedocs.org/en/latest/installation/linux.html
if [[ ! -f ~/.fonts/PowerlineSymbols.otf ]]; then
    mkdir -p ~/.fonts/
    # See: https://wiki.archlinux.org/index.php/Font_Configuration
    cp ~/.vim/res/PowerlineSymbols.otf ~/.fonts/
    mkdir -p ~/.config/fontconfig/conf.d/
    cp ~/.vim/res/10-powerline-symbols.conf ~/.config/fontconfig/conf.d/
    fc-cache -vf ~/.fonts
    echo "Powerline symbols configured"
fi

if [[ ! -d ~/.fonts/"${FONT##*/}" ]]; then
    # Patched fonts for windows usage:
    src='https://github.com/Lokaltog/powerline-fonts'
    [ ! -d "${FONT%/*}" ] && git clone --depth=1 "$src" "${FONT%/*}"
    cp -urft ~/.fonts "$FONT"
    fc-cache -vf ~/.fonts  # check active name with fc-list
    echo "Vim font '${FONT##*/}' installed"
fi


### PLUGINS ###
if [[ ! -d "$VCACHE/bundle" || "$update" -eq 1 ]]; then
    # FIXME: error on clean system, when NeoBundle is not installed yet
    vim -E -X -R -i NONE -c "set nomore" +NeoBundleClearCache +NeoBundleUpdate +qall </dev/tty
fi

# Editor
# dst=~/.selected_editor
# wbegin
# wstr "SELECTED_EDITOR=\"$(which vim.gtk)\""
# echo "W: $dst  <- vim"
