#!/bin/bash -e
source ~/.shell/func.d/system
cd $(dirname $(readlink -m ${0}))

### PLUGINS ###
# BUG: returns non-zero errcode!
# FIXME: error on clean system, when NeoBundle is not installed yet
shvim() { $EDITOR -nesR -i NONE -u "$PWD/vimrc" \
    -c "set nomore|redir!>/dev/stderr" -c "$1" \
    -c "echo''|redir END|qall!" >/dev/null ||:; }
shvim 'NeoBundleClearCache'
shvim 'NeoBundleUpdate!'

# WARNING: change to calling wrapper func of dein.vim
if $EDITOR -help | grep -q '^\s\+nvim\s'; then
  shvim 'UpdateRemotePlugins'
fi
