#!/bin/bash -eu
source ~/.shell/func.d/packages

#| netctl         | Profile based systemd network management
#| wpa_supplicant | Cli-tool to establish secure wifi connection
#| wpa_actiond    | Auto switching profiles for different wifi networks
#|________________|     =USE: netctl-auto
#| dialog         | For wifi-menu. A tool to display dialog boxes from shell scripts

# GUI:(netctl): REF http://arcanis.name/ru/projects/netctl-gui/

# BET:ALT:(wpa_supplicant): pkg_inst iwd
#   REF: https://www.reddit.com/r/archlinux/comments/cs0zuh/first_time_i_heard_about_iwd_why_isnt_it_already/

pkg_inst netctl ifplugd wpa_supplicant
aur_inst wpa_actiond
