#!/bin/bash -e
# tags: core
source ~/.shell/func.d/cfgsetup
[[ ${CURR_PROF:?} =~ neo ]] || return

### LINKS ###
if cfgOpt u; then
  linkcp -t /etc/modprobe.d \
    alsa-base.conf i915.conf iwlwifi.conf

elif cfgOpt c; then
  # modinfo
  modprobe -c | grep i915  # snd_hda_intel\|snd-hda-intel
fi
