#!/bin/bash -e
# tags: net
source ~/.shell/func.d/cfgsetup

### GENS ###
# ./synergy.gen

## NOTE: if server
# svc_activate -cu synergys.service
# svc_activate -cueR synergys.socket

## NOTE: if client
# svc_activate -cueR synergyc.service
