#!/bin/bash -e
source ~/.shell/func.d/packages

# ALT:(xdot): http://zvtm.sourceforge.net/zgrviewer.html
pkg_inst graphviz xdot

# NOTE: print in ascii
#   https://stackoverflow.com/questions/3211801/graphviz-and-ascii-output
aur_inst perl-graph-easy
