#!/bin/bash -e
source ~/.shell/func.d/packages
has_pr X || die

if distro arch; then
  # if [[ ! ${CURR_PROF:?} =~ ^neo ]] &&
  #   grep -q '^\[infinality-bundle\]' /etc/pacman.conf; then
  #     # infinality supports only 96dpi
  #     pkg_inst -a infinality-bundle
  # fi

  fd=/usr/share/fonts
  # SEE: luxi-mono, mikachan, stix, croscore
  # ttf-freefont ttf-droid
  # ATT: https://www.archlinux.org/news/ttf-dejavu-237-will-require-forced-upgrade/
  pkg_inst -f "$fd/TTF/DejaVuSans.ttf" ttf-dejavu
  pkg_inst -f "$fd/TTF/Symbola.ttf" ttf-symbola
  # SEE: https://github.com/adobe-fonts
  # NOTE: http://adobe-fonts.github.io/source-code-pro/
  # https://github.com/adobe-fonts/source-code-pro
  pkg_inst -d "$fd/adobe-source-code-pro" adobe-source-code-pro-fonts
  pkg_inst -d "$fd/adobe-source-sans-pro" adobe-source-sans-pro-fonts
  pkg_inst -d "$fd/adobe-source-serif-pro" adobe-source-serif-pro-fonts
  # ALT: ttf-arphic-{ukai,uming}, 0-lohit-*
  # https://github.com/adobe-fonts/source-han-sans
  pkg_inst -d "$fd/adobe-source-han-sans" adobe-source-han-sans-jp-fonts
  # NOTE: http://comicneue.com/
  aur_inst -f "$fd/OTF/ComicNeue-Regular.otf" ttf-comic-neue
  # NOTE: http://ipafont.ipa.go.jp/
  pkg_inst -f "$fd/OTF/ipag.ttf" otf-ipafont

  # Install manually:
  # aur_inst -a 'freetype2-ubuntu fontconfig-ubuntu cairo-ubuntu'
  # pkg_inst powerline-fonts
  # aur_inst ttf-dejavu-sans-mono-powerline-git

elif distro ubuntu; then
  echo "ERR: install manually"
  exit

  fndir=~/.local/share/fonts
  if [[ ! -f $fndir/PowerlineSymbols.otf ]]; then
    linkcp -ct "$fndir"  "$PWD/PowerlineSymbols.otf"
    linkcp -ct ~/.config/fontconfig/conf.d  ~/.vim/res/10-powerline-symbols.conf
    fc-cache -vf "$fndir"
    echo "Powerline symbols configured"
  fi

  FONT=~/.cache/vim/powerline-fonts/DejaVuSansMono
  if [[ ! -d $fndir/${FONT##*/} ]]; then
    # Patched fonts for windows usage:
    src='https://github.com/Lokaltog/powerline-fonts'
    [[ -d "${FONT%/*}" ]] || git clone --depth=1 "$src" "${FONT%/*}"
    linkcp -ct "$fndir" "$FONT"
    fc-cache -vf "$fndir"  # check active name with fc-list
    echo "Vim font '${FONT##*/}' installed"
  fi
fi
