#!/bin/bash -eu
[[ " $* " =~ " -u " ]] && rescan=1 || rescan=''

fndir=~/.local/share/fonts

## DISABLED: I don't use outdated XLFD font patterns at all
# if ((rescan)); then
#   mkfontscale "$fndir"
#   mkfontdir "$fndir"
# fi

fc-cache -v${rescan+f} "$fndir"
# fc-cache -fs >/dev/null
