#!/bin/bash -eu
# tags: util
source ~/.shell/func.d/cfgsetup

linkcp -ct /etc -- asd.conf

# NEED: $ sudo modprobe overlay
# sudo modprobe -c | grep overlay

# BAD: too much RAM for ccache on SSD laptop
svc_activate -er asd.service
