#!/bin/bash -eu
# tags: util
source ~/.shell/func.d/cfgsetup

## /etc/asd.conf
# WHATTOSYNC=(
#   '/work/_build'
#   '/work/_mirror/_ccache'
# )
# USE_OVERLAYFS="yes"

# NEED: $ sudo modprobe overlay
# sudo modprobe -c | grep overlay

# BAD: too much RAM for ccache on SSD laptop
# svc_activate -er asd.service
