#!/bin/bash -eu
source ~/.shell/func.d/packages

# OFF: https://www.cyberpower.com/ru/ru/product/sku/powerpanel%C2%AE_for_linux#downloads
#   NEW? https://www.cyberpower.com/global/en/product/sku/powerpanel_business_for_linux
aur_inst powerpanel


# aur_inst network-ups-tools
