#!/bin/bash -eu
export IMAPFILTER_HOME=~/.config/imapfilter

acc=$1
shift
[[ ${1-} == -- ]] && shift

cfg=$IMAPFILTER_HOME/acc/$acc.lua
log=$IMAPFILTER_HOME/imapfilter.log

if [[ -t 1 ]]; then  ## Colorize
  Cmsg=$(tput setaf 2)$(tput bold)
  Csrc=$(tput setaf 4)
  Cdst=$(tput setaf 6)$(tput bold)
  CR=$(tput sgr0)
  exec > >(stdbuf -oL -eL tee -a "$log" | sed -run "
  \|([0-9]+) messages moved from [^/]+/(\S+) to [^/]+/(\S+).|\
    s//$Csrc\2$CR -> $Cdst\3$CR $Cmsg(\1)$CR /p
  ") && printf '\n-----\n%s\n' "$(date +'%Y%m%d_%H%M%S')"
fi

exec imapfilter -v -c "$cfg" "$@"
