#!/bin/bash -eu
# tags: net
source ~/.shell/func.d/cfgsetup

### LINKS ###
dir=~/.config/imapfilter
linkcp -t "$dir" cfg && chmod 700 "$dir"

dfl=$dir/acc/${MUTT_DEFAULT-}.lua
! [[ -f $dfl && -s $dfl ]] || linkcp "$dfl" "$dir/config.lua"
