#!/bin/bash -e
source ~/.shell/profile

[[ ! $1 =~ -u ]] || { unmount=1; shift; }

# WARN:ALSO: you need creds in ~/.netrc 600
d=${1:-/srv/ftp}
f=${2:-${AIRY_FTP_HOST:?}}


ismnt(){ grep -qsFw "$1" /proc/mounts; }

if ((unmount)); then
  ismnt "$d" && fusermount -u "$d"
  rmdir -vp "$d"
else
  mkdir -vp "$d"
  ismnt "$d" || curlftpfs -o utf8 "ftp://$f" "$d"
fi
