#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
if cfgOpt u || [[ ! -L /etc/minirc.dfl ]]; then
    sudo ln -svf "$PWD/usb0" /etc/minirc.dfl
fi

# To work w/o sudo
if distro ubuntu; then
    sudo chmod -R o+w /etc/minicom
    if ! grep -q "dialout.*${USER:-No}" /etc/group; then
        sudo usermod -a -G dialout $USER
        echo "Relogin now to apply group info"
        # OR: apply w/o reboot only for this terminal: su - $USER
    fi
fi
