#!/bin/bash -eu
case "${1-}"
in -t) dir=$2; shift 2
;;  *) dir=/data/vd-misc/backup
# ;;  *) dir=/data/amv
esac

path=$1

# WARNING: we can move only already donwloaded files!
# -- THINK: make queuing operations, waiting for close_write event from tmux?
[[ -f $path ]] || exit
exec r.dmenu-move "$dir" "$path"
