#!/bin/bash -e
source ~/.shell/func.d/packages

#| highlight  | syntax highlighting of code
#| mediainfo or perl-image-exiftool # viewing information about media files
pkg_inst highlight mediainfo

if distro arch; then
  pkg_inst ranger
  pkg_inst -p 'fbi' fbida  # framebuffer image viewer for terminal
  # VIZ:(caca) img2txt caca-config cacaclock cacademo cacafire cacaplay cacaserver cacaview
  pkg_inst -l 'caca' libcaca  # colour ASCII art library
  pkg_inst -p 'pdftotext' poppler  # for pdf previews
  pkg_inst xchm  # for win-help and some books in *.chm

  # BUG: conflict with qutebrowser, etc
  # pkg_inst pygmentize python-pygments
  # pip_inst pygments-style-solarized

  # Pager preview
  pkg_inst ffmpegthumbnailer catdoc
  pkg_inst -d '/usr/share/perl5/vendor_perl/Image/ExifTool' perl-image-exiftool
  # aur_inst -p 'wav2png' 'wav2png-git'

else
  pkg_build() { sudo python3 setup.py install; }
  git_inst 'hut/ranger'  # 'amerlyq/ranger'

  pkg_inst fbi caca-utils poppler-utils
fi
