#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
    pkg_inst -p ranger 'ranger fbida libcaca poppler p7zip unzip'

else
    # git_inst 'amerlyq/ranger'
    git_inst 'hut/ranger'
    pkg_inst 'fbi caca-utils poppler-utils w3m-img p7zip-full zip'
fi

#| fbi        | framebuffer image viewer for terminal
#| poppler    | (pdftotext) for pdf previews
#| caca-utils | (img2txt) Colour AsCii Art library.
#|   cacaview | image viewer for the terminal. The user can zoom and scroll
#|            | the image, set the dithering method or enable anti-aliasing.
#|   cacaball | tiny graphic program that renders animated ASCII metaballs
#|            | on the screen
#|   cacafire | port of AALib's aafire and displays burning ASCII art flames
#|   cacademo | simple application that shows the libcaca rendering features
#|            | such as line and ellipses drawing, triangle filling and
#|            | sprite blitting.

pkg_inst 'w3m atool unrar mediainfo colordiff highlight'
#| w3m | supports images (xterm, framebuffer console), but it doesn’t support JavaScript.
#| atool      | previews of archives
#| highlight  | syntax highlighting of code
#| mediainfo or perl-image-exiftool # viewing information about media files

 # pkg_inst python-pygments
 # pkg_inst pandoc sharutils # or some uuencode
 # git_inst 'rkitover/vimpager'
