#!/bin/bash
# Do '$ . r.ranger' -- you must source it, not launch!

# Don't allow to launch chain of rangers inside shells of other rangers
[[ -z "$RANGER_LEVEL" ]] || exit

tempfile="${TMPDIR:-/tmp}/ranger_cwdir"
trap "rm -f -- '$tempfile' > /dev/null" EXIT

# export TERM=xterm-256color #launch even inside terms w/o color support

# for rifle when open_with -t'
export TERMCMD='r.t'
# speed up ranger start time
export RANGER_LOAD_DEFAULT_RC=FALSE

python3 $(which ranger) --choosedir="$tempfile" "${@:-$PWD}"

[[ -f "$tempfile" ]] && dir="$(cat -- "$tempfile")"


# Automatically change the directory in bash to the last visited one
# after ranger quits. To undo the effect of this function,
# you can type "cd -" to return to the original directory.
[[ "$dir" != "$PWD" && -d "$dir" ]] && cd -- "$dir"
