#!/bin/bash
# THINK:MAYBE:BETTER: do shell function for bash/zsh instead of this script
#   * and source that function only once on shell startup or on first 'r' alias launch
# EXPL: commented, because using r.ranger becomes contrintuitive.
# if [[ -z $ZSH_EVAL_CONTEXT || ! $ZSH_EVAL_CONTEXT =~ :file$ ]]\
# && [[ -z $BASH_VERSION || ${0} == ${BASH_SOURCE[0]} ]]
# then echo "Err: you must source it, don't execute!"; exit 1; fi

if ! hash ranger &>/dev/null
then echo "Err: install 'ranger' to use it"; return 1; fi

# Don't allow to launch chain of rangers inside shells of other rangers
[[ -z $RANGER_LEVEL ]] || exit

# No need because it sourced?
# trap "rm -f -- '$_ranger_tmp' > /dev/null" EXIT
export RANGER_TMPDIR=${TMPDIR:-/tmp}/ranger
[[ -d $RANGER_TMPDIR ]] || command mkdir -p "$RANGER_TMPDIR"

# FIXED: launch even inside terms w/o color support
# export TERM=xterm-256color

# TERMCMD -- for rifle when open_with -t'
# .._RC -- speed up ranger start time
TERMCMD='r.t' SHELL="$(which r.shell)" RANGER_LOAD_DEFAULT_RC=FALSE \
  ranger --choosedir="$RANGER_TMPDIR/cwd" "${@:-$PWD}"

# Automatically change the directory in bash to the last visited one
# after ranger quits. To undo the effect of this function,
# you can type "cd -" to return to the original directory.
if [[ -s $RANGER_TMPDIR/cwd ]]; then
  dir=$(<"$RANGER_TMPDIR/cwd")
  [[ $dir == $PWD || ! -d $dir ]] || cd -- "$dir"
fi
