#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
link "$PWD" ~/.config/ranger


if cfgOpt c; then while read line
do rm -vf "${PWD}${line}"; done < "$PWD/.gitignore"; fi

if cfgOpt u; then
echo "USE: ranger --copy-config=all (Be Careful!), and see diff"; exit; fi


case "${SHELL:?}" in *bash) RC=~/.bashrc ;; *zsh) RC=~/.zshrc ;; esac
RC="$RC $HOME/.cache/zsh/.zshrc"
if ! grep -q "${TMPDIR:-/tmp}/ranger_cwdir" $RC 2>/dev/null; then
    echo "===========================
    >>> Place in your shell's config ($RC):
    # To sync zsh and ranger working directories:"
    case "$SHELL" in *bash) printf 'finish()'
    ;; *zsh) printf 'function finish' ;; esac
    echo '{ echo "$PWD" > "${TMPDIR:-/tmp}/ranger_cwdir"; }
    trap finish EXIT'
fi
