#!/bin/bash -e
source ~/.shell/func.d/packages
has_pr X || die

if distro arch; then
    # Install 'Adwaita' to eliminate warnings in GTK apps
    pkg_inst gtk2 gtk3
    pkg_inst gnome-themes-standard

    aur_inst gtk-theme-flatstudio
    # mate-themes numix-themes
    aur_inst vertex-themes
    aur_inst zuki-themes
    aur_inst ceti-2-themes

    # Icons
    pkg_inst hicolor-icon-theme
    pkg_inst faenza-icon-theme

elif distro ubuntu; then
    echo "ERR: install manually"
    if [[ ! -d /usr/share/themes/Vertex-Dark ]]; then
        sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_14.04/ /' > /etc/apt/sources.list.d/vertex-theme.list"
        sudo apt-get update
        sudo apt-get install vertex-theme
    fi
fi
