#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then

    ## HACK: remove useless deps on :: at-spi2-atk
    #  SRC: https://github.com/lah7/gtk3-classic
    #  = No ATK. No 32-bit libs. No printing, cloudproviders, etc
    #  [_] TRY: also remove DEP=tracker3
    #  sudo pacman -Sddw gtk3
    ## NEED:FIXED: makedepends+=(sassc)
    #    OR:ALT: manually precompile gtk/theme/{Adwaita,HighContrast}/*.scss -> *.css
    #    SRC: https://github.com/lah7/gtk3-classic/issues/49
    #    https://aur.archlinux.org/packages/gtk3-classic-noatk-64/#news
    ## FIXED:ADD: sed -i 's/^.*atkbridge_dep/#\0/g' "gtk+-$_gtkver/meson.build" "gtk+-$_gtkver/gtk/meson.build"
    aur_inst gtk3-classic-noatk-64
    # pkg_inst gtk2 gtk3

    # Install 'Adwaita' to eliminate warnings in GTK apps
    pkg_inst gnome-themes-standard

    # BAD: integrity check, many deps
    # aur_inst gtk-theme-flatstudio
    # mate-themes numix-themes
    # aur_inst vertex-themes
    # aur_inst zuki-themes
    # aur_inst ceti-2-themes

    # Icons
    pkg_inst hicolor-icon-theme   # only dirs structure
    # pkg_inst faenza-icon-theme  # UNUSED

elif distro ubuntu; then
    echo "ERR: install manually"
    if [[ ! -d /usr/share/themes/Vertex-Dark ]]; then
        sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_14.04/ /' > /etc/apt/sources.list.d/vertex-theme.list"
        sudo apt-get update
        sudo apt-get install vertex-theme
    fi
fi
