#!/bin/bash -e
source ~/.shell/func.d/packages

#| nmap | Network exploration tool and security / port scanner
# SEE:
# http://xyne.archlinux.ca/projects/hexgrep/

pkg_inst lsof strace ltrace iftop nmap

if distro arch; then
    pkg_inst -p 'nc' openbsd-netcat
    aur_inst -p 'xtrace' xtrace-git

elif distro ubuntu; then
    pkg_inst ""
fi

# For ida:
# paci wine wine-mono wine_gecko
