#!/bin/bash -e
source ~/.shell/func.d/packages

#| bbe  | binary sed
#| nmap | Network exploration tool and security / port scanner
# SEE:
# http://xyne.archlinux.ca/projects/hexgrep/

pkg_inst "lsof strace ltrace iftop"
pkg_inst "nmap"

if distro arch; then
    pkg_inst "bbe"
    pkg_inst "openbsd-netcat"
    aur_inst "xtrace-git"
elif distro ubuntu; then
    pkg_inst ""
fi

# For ida:
# paci wine wine-mono wine_gecko
