#!/bin/bash -eu
source ~/.shell/func.d/packages

#| st     | suckless terminal -- lacks of all, but very small
#| abduco | screen-like programs detaching NEW:ALT: to dtach
#| dvtm   | tmux-like dwm-adhere split/tiling management

if distro arch; then
  # [[ $FONT_ST ]] || FONT_ST=$(( dpi * 9/72 + 1))

  # BUG: can't override font size from environment BUT: is it robust to allow this ?
  #   $ FONT_ST=20 r.airy -a st
  # echo AAAA:$FONT_ST

  # BUG: no errfail when
  #   st-airy-git and st-amerlyq-git are in conflict (st). Remove st-amerlyq-git? [y/N]
  #   ???
  # BUG: can't update pkg with new font size
  #   ==> Installing package st-airy-git with pacman -U...
  #   warning: st-airy-git-1:0.7.41.g1f24bde-1 is up to date -- skipping
  #   ::: pacx st-airy-git
  # BUG: can't rebuild pkg because of already built one
  #   WARNING: A package has already been built, installing existing package...
  #   ::: rm ~/.cache/airy/pkg/st-airy-git/*.tar.xz
  FONT_ST="${FONT_ST-}" loc_inst ./st-airy-git.pkgbuild

  # CHECK? if some needed
  ## reptyr -- attach running pr to a new terminal
  # pkg_inst dtach dvtm abduco reptyr

elif distro ubuntu; then
  pkg_inst st dtach
fi
