#!/bin/bash -eu
source ~/.shell/profile

# pacman -Qi st-amerlyq-git &>/dev/null
cd "${CURR_DIR_PKG:?}/st"
git checkout amerlyq

# [[ $FONT_ST ]] || FONT_ST=$(( dpi * 9/72 + 1))
# TODO: add '--noconfirm' and '--yes' to pacman in ./install
#   -- so it could remove conflicting 'st' package
export FONT_ST THEME
exec ./install -mbi
