#!/bin/bash -eu
set -o pipefail

case "$1"
in --url) xurls | awk -vi=1 '{printf "%02d %s\n",i++,$0}' |
    dmenu -l 10 | cut -d' ' -f2- | xargs -I@ r.b @
# DEV: if already in tmux -- open in tmux (new window)
# DEV: xmonad -- open in tab of the same window (NEED combinable layouts)
# BUG: when r.tf uses tmux --> <(cat) pipe isn't available
#   TRY: opening stdin directly in tmux
#   SEE: http://serverfault.com/questions/178457/can-i-send-some-text-to-the-stdin-of-an-active-process-running-in-a-screen-sessi
;; --vim) exec r.tf -M -e $EDITOR -u ~/.vim/rc/basic \
    -c 'StripLines|set nowrap nonu nornu nofen bt=nofile|norm!G0' -c 'syntax on' <(cat)
esac
