#!/bin/bash -eu
source ~/.shell/func.d/packages

if distro arch; then
  # pkg_inst "base-devel"  # In conflict with multilibs!
  #   => Install multilib-devel over base-devel
  pkg_inst gcc-multilib
  pkg_inst lib32-gcc-libs

elif distro ubuntu; then
  pkgs=()  # Those libs also necessary to build x32 under x64 system
  pkgs+=( build-essential gcc-multilib g++-multilib lib32stdc++6 )
  pkgs+=( make checkinstall pkg-config autoconf automake cmake )
  pkg_inst "${pkgs[@]}"
fi
