#!/bin/bash -eu
source ~/.shell/func.d/packages

#| iotop   | Show disk r/w statistics for processes like htop (press 'a')
#| dstat   | Versatile tool for generating system resource statistics
pkg_inst htop iotop iftop dstat lsof
