#!/usr/bin/env bash
#%DEBUG: $ … -v 10 … -variant ",airy" …
set -o errexit -o errtrace -o noclobber -o noglob -o nounset -o pipefail

exec setxkbmap -v 5 -I "" -I/@/airy/xkb/cfg -I/usr/share/X11/xkb \
  -model airy -rules airy -layout us,zip -option "" -option airy "$@"

# ALT: -layout airy,airy -variant 'us,zip'
# exec setxkbmap -v 5 -I "" -I/usr/share/X11/xkb \
#   -model pc104 -rules evdev -layout airy,zip -option "" -option airy "$@"
