#!/bin/bash -eu
set -o pipefail

# USAGE:
# a=all, b=bin, c=core, k=kernel, o=object, s=shared
# f=bfmt : elf
# m=masked : find masked by extension
# p=pltf : mips, x86-64

opts=; while getopts 'abcf:kmop:s' o; do case $o in :|'?') exit 1
;; a) opts+=bckos
;; f) bfmt=$OPTARG
;; p) pltf=$OPTARG
esac; opts+=$o; done; shift $((OPTIND - 1))
has(){ [[ $opts =~ [$*] ]]; }

src=${1:-$PWD}
flt=( )  # DEV: preliminary filter-out trash files

[[ -z ${opts//[^bckos]} ]] && opts=bs  # =DFL

if has m; then
  has bckos && flt+=( \( -false )
  has b && flt+=( -o \( -executable \! -regex '.*\.[ks]?o\(\.[0-9]+\)*$' \) )
  has c && flt+=( -o -name 'core.*' )
  has k && flt+=( -o -name '*.ko' )
  has o && flt+=( -o -name '*.o' )
  has s && flt+=( -o -regex '.*\.so\(\.[0-9]+\)*$' )
  has bckos && flt+=( \) )
fi

# TODO: distinguish '.o' from '.ko' by file extension
typ=''
has b && typ+='|executable'
has c && typ+='|core file'
has ko && typ+='|relocatable'
has s && typ+='|shared object'
typ="(${typ:1})"

# WARN: ignores symlinks
exec find -H "$src" -type f "${flt[@]}" \
| file -f- -e apptype -e ascii -e encoding -e cdf -e compress -e elf -e tar \
| grep -iFw "${bfmt-elf}" \
| grep -Ew  "${typ}" \
| grep -iFw "${pltf-}" \
| awk -F': ' '{print $1}'
