#!/bin/bash -eu
source ~/.shell/func.d/packages

pkg_inst qutebrowser python-tldextract
pkg_inst -d python-adblock python-pygments
pkg_inst -d python-opengl
# ALT: pkg_inst -d qt5-webkit gst-libav gst-plugins-{base,good,bad,ugly}
