#!/bin/bash -eu
source ~/.shell/func.d/system
running_X || exec r.bt

# log=${TMPDIR:-/tmp}/qute/$(date +%Y%m%d_%H%M%S).log
# mkdir -p "${log%/*}"
# exec > $log 2>&1

dml(){ dmenu ${1+-l $1} -b -p 'Qute:' \
    -nb '#000000' -nf '#999999' -sb '#000000' -sf '#31AC65' \
    -fn '-misc-fixed-medium-r-normal-*-*-200-75-75-*-*-iso8859-2'
}
run(){
  export QT_AUTO_SCREEN_SCALE_FACTOR=1  # HiDpi for Qt>=5.6
  # WARN: can crash on Nouveau
  exec qutebrowser --backend webengine \
    --qt-flag disable-reading-from-canvas "$@"
}
chk(){ [[ -n $url ]] && return; r.n Browser "No url arg"; exit 1; }

[[ ${1-} == -[tphs] ]] && { op=${1-}; shift; }

case ${op-}
in -p) url=$(xsel -ob)
  chk "$url" || set -- "$url"
;; -h) url=$(sed 's/^[0-9]\+ //' ~/.local/share/qutebrowser/history | dml 16)
  chk "$url" || set -- "$url"
# ;; -g) shift; run "$(dml < ~/.config/qutebrowser/search)"
;; -s) set -- ':set content allow-javascript true' "$@"
esac

run "$@"
