#!/bin/bash -eu
# tags: browser
THEME=light
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

Deprecated ~/.config/qutebrowser/{keys,qutebrowser}.conf

### LINKS ###
linkcp -t ~/.config/qutebrowser \
  config.py theme

# BET? link to ~/db
linkcp -m ~/.local/share/qutebrowser/history.sqlite ~/chat/qute

linkcp -t ~/.local/share/qutebrowser/ userscripts

### THEME ###
./ctl/theme ${THEME:?}

# ALT:(create symlink): @/erian/mod/qute/bin/qutebrowser -> r.qute-hidpi
# FAIL! dpi is not enough -- you also must consider distance to screen
if (( "$(r.xorg -d||echo 0)" > 141 )); then
  # run=$(r.airy-overlay-mod run)
  linkcp -m ~/.local/bin/r.qute-hidpi ~/.local/bin/qutebrowser
fi

### UPDATE ###
dst=~/.local/share/qutebrowser/blocked-hosts
if running_X && (cfgOpt r || [[ ! -f $dst ]])
then qutebrowser :adblock-update & fi
