#!/bin/bash -e
# tags: browser
THEME=light
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

### LINKS ###
linkcp -t ~/.config/qutebrowser \
  qutebrowser.conf keys.conf theme

### THEME ###
./run -t ${THEME:?}

### UPDATE ###
dst=~/.local/share/qutebrowser/blocked-hosts
if running_X && (cfgOpt r || [[ ! -f $dst ]])
then qutebrowser :adblock-update & fi
