#!/bin/bash
#%SUMMARY: reduced size for ultrawide screen (when no HiDPI support or for higher FPS rate)
set -euo pipefail -o noglob

output=${1:-DP-1}
mode=${2:-1920x800}

# OR:(?old?): $ gtf 1920 800 60
# e.g. 125.00 1920 2024 2216 2512 800 803 813 831 -hsync +vsync
params=$(cvt ${mode%x*} ${mode##*x} 60 | sed -n '2s/^\w\+\s//p' | cut -d' ' -f2-)
params=( $params )

# NEED: check if mode exist in general (otherwise --newmode fails)
# BAD: check only if output has mode added
if ! xrandr -q | awk -vo=DP-1 -vm=1920x800 '$1==o{x=1;next} x&&/^\S/{exit 1} x&&$1==m{exit 0}'; then
  xrandr --newmode "$mode" "${params[@]}"
  xrandr --addmode "$output" "$mode"
fi

xrandr --output "$output" --mode "$mode"

# Restore back:
# xrandr --output DP-1 --auto
