#!/bin/bash
set -euo pipefail

dfl=eDP-1
ext=DP-1
wide1=2560x1600
wide2=1920x800

optparse(){ case $1 in :|'?') exit 1
;; [1-4]) xrandr -q | grep -qw "^${ext}\sconnected" && ext_mod=$1 || dfl_mod=$1
;; d) dfl_mod=${2:-2}
;; e) ext_mod=${2:-2}
;; n) wide2=1920x1080  #% n = normalize resolution
;; *) exit 1
esac; }

# HACK: allow options with and without hyphen
while getopts 'd:e:n1234' o; do optparse "$o" "${OPTARG-}"; done; shift $((OPTIND - 1))
for o; do optparse "${o:0:1}" "${o:1:1}"; done
[[ -z ${dfl_mod-} && -z ${ext_mod-} ]] && { dfl_mod=1; ext_mod=1; }

# TODO: change dpi accordingly
# BUG: all X apps need to restart!

[[ ${dfl_mod-} ]] && case $dfl_mod
in 1) xrandr --output "$dfl" --auto
;; 2) xrandr --output "$dfl" --mode 1920x1080
;; 3) xrandr --output "$dfl" --mode 1280x720
;; *) echo "Err: not supported '$dfl_mod' delimiter"; exit 1
esac

[[ ${ext_mod-} ]] && case $ext_mod
in 1) xrandr --output "$ext" --auto
;; 2) r.monitor-add-mode "$ext" "$wide2"
;; 3) xrandr --output "$ext" --mode 1280x800
;; 4) xrandr --output "$ext" --mode 1024x768
;; *) echo "Err: not supported '$ext_mod' delimiter"; exit 1
esac

exit 0

# setm() { local sz=${1:-1920x1080}; shift
#     if ! xrandr -q | sed '/^VGA1/,/^\S/!d' | grep -q "$sz"; then
#         xrandr --addmode VGA1 "$sz"
#     fi
#     xrandr --output VGA1 --mode $sz --primary \
#            --output LVDS1 ${@:---off};
# }

# case "${1#-}"
# in g|game) setm 1280x720
# ;; w|work) setm 1920x1080
# ;; f|full) setm 3840x2160
# ;; d|dual) setm 1280x720 --mode 1366x768 --right-of VGA1
# ;; n|norm|*) setm 1920x1080 --mode 1366x768 --pos 1920x312
# esac

# ALT:(fb): you may adjust the "sharpness" parameter on your monitor settings to adjust the blur level introduced with scaling.
# xrandr --output eDP1 --auto --pos 0x2160 --output HDMI1 --auto --scale 2x2 --pos 0x0 --fb 3840x4320
# xrandr --output eDP1 --auto --pos 0x0 --output HDMI1 --auto --scale 2x2 --pos 3840x0 --fb 7680x2160
