#!/bin/bash
#%USAGE: $ r.monitor-switch -as
set -euo pipefail

# TODO: split into orthogonal scripts "split" and "layout"
# BUG: wrong "st" font size when $ xrandr --output DP-1 --mode 1920x1080

dfl=eDP-1
ext=DP-1
add=HDMI-1
# kw=7/27  # =0.741
kw=1/4
[[ $* =~ S ]] && kw=5/21  # more narrow
[[ $* =~ [0-9]+/[0-9]+ ]] && kw=${BASH_REMATCH[0]:?}

get_mon_dims(){ xrandr -q | awk -vm="$1" '$1==m && $2=="connected"' | sed -rn '
  /.*\s([0-9]+)x([0-9]+)\+([0-9]+)\+([0-9]+).*\s([0-9]+)mm x ([0-9]+)mm/{
    s//\1 \2 \3 \4 \5 \6/p;q}'
}
del_mon_split(){
  xrandr --listmonitors | cut -d$' ' -f3 | grep -F "$1" || return 0
  xrandr --delmonitor "$1"
}
set_mon_layout(){ for((i=1;i<=$#;++i)); do [[ ${!i} == -- ]] && break; done
  local dfl_args=( "${@:1:i-1}" ); [[ " ${dfl_args[*]} " =~ " --off " ]] || dfl_args+=( "${dfl_mode[@]:?}" )
  local ext_args=( "${@:i+1}" );   [[ " ${ext_args[*]} " =~ " --off " ]] || ext_args+=( "${ext_mode[@]:?}" )
  xrandr --output "$dfl" "${@:1:i-1}" "${dfl_args[@]}" --output "$ext" "${ext_args[@]}"
}


# NOTE: reuse current active resolutions for monitor OR: --auto
dfl_dims=$(get_mon_dims "$dfl")
read -r dflw dflh _ <<< "$dfl_dims"
((dflw && dflh)) && dfl_mode=( --mode "${dflw}x${dflh}" ) || dfl_mode=( --auto )

ext_dims=$(get_mon_dims "$ext")
read -r w h x y mw mh <<< "$ext_dims"
((w && h)) && ext_mode=( --mode "${w}x${h}" ) || ext_mode=( --auto )


# NOTE: artificially reduce physical size (mw x mh) to increase virtual dpi
s1=$((w*$kw))/$((mw*$kw))x$h/$mh+$x+$y
s2=$((w-w*$kw))/$((mw-mw*$kw))x$h/$mh+$((x+w*$kw))+$y

del_mon_split "$ext~1"
del_mon_split "$ext~2"

[[ $* =~ [sS] ]] && echo xrandr \
  --setmonitor "$ext~1" "$s1" none \
  --setmonitor "$ext~2" "$s2" "$ext"


# BUG: switching "a" -> "d" -> "e" leaves visual artifacts on screen
#   MAYBE: as with rotation -- must supply commands in special order or split into multiple commands ?

(($#)) || set -- -m
case $*
in *d*) set_mon_layout --primary -- --off
;; *e*) set_mon_layout --off -- --primary
;; *m*) set_mon_layout --right-of "$ext" -- --primary  # FIXME: don't enable other screens if they are off
;; *a*) set_mon_layout --primary --right-of "$ext" --
# DEV:(-o): switch to only one screen whichever is currently main, or do nothing if already single
;; *[sS]*) true
;; *) echo "Err: wrong option '$*'" >&2; exit 2
esac

r.feh
# r.wm restart-wm
