#!/bin/bash
#%USAGE: $ r.monitor-switch -as
set -euo pipefail

# TODO: split into orthogonal scripts "split" and "layout"
# BUG: wrong "st" font size when $ xrandr --output DP-1 --mode 1920x1080

dfl=eDP-1
ext=DP-1
kw=1/4
[[ $* =~ S ]] && kw=5/21
[[ $* =~ [0-9]+/[0-9]+ ]] && kw=${BASH_REMATCH[0]:?}

get_mon_dims(){ xrandr -q | awk -vm="$1" '$1==m && $2=="connected"' | sed -rn '
  /.*\s([0-9]+)x([0-9]+)\+([0-9]+)\+([0-9]+).*\s([0-9]+)mm x ([0-9]+)mm/{
    s//\1 \2 \3 \4 \5 \6/p;q}'
}
del_mon_split(){
  xrandr --listmonitors | cut -d$' ' -f3 | grep -F "$1" || return 0
  xrandr --delmonitor "$1"
}


# NOTE: reuse current active resolutions for monitor OR: --auto
dfl_dims=$(get_mon_dims "$dfl")
read -r dflw dflh _ <<< "$dfl_dims"
dfl_mode=( --mode "${dflw}x${dflh}" )

ext_dims=$(get_mon_dims "$ext")
read -r w h x y mw mh <<< "$ext_dims"
ext_mode=( --mode "${w}x${h}" )


# NOTE: artificially reduce physical size (mw x mh) to increase virtual dpi
s1=$((w*$kw))/$((mw*$kw))x$h/$mh+0+0
s2=$((w-w*$kw))/$((mw-mw*$kw))x$h/$mh+$((w*$kw))+0

del_mon_split "$ext~1"
del_mon_split "$ext~2"

[[ $* =~ [sS] ]] && xrandr \
  --setmonitor "$ext~2" "$s1" "$ext" \
  --setmonitor "$ext~1" "$s2" none


case $*
in *d*) xrandr --output "$dfl" --primary "${dfl_mode[@]:?}" --output "$ext" --off
;; *e*) xrandr --output "$dfl" --off --output "$ext" --primary "${ext_mode[@]:?}"
;; *a*|'') xrandr --output "$dfl" --primary "${dfl_mode[@]:?}" --below "$ext" --output "$ext" "${ext_mode[@]:?}"
;; *[sS]*) true
;; *) echo "Err: wrong option '$*'"; exit 1
esac

r.feh
# r.wm restart-wm
