#!/bin/bash -eu
#%USAGE: $ ./$0 <account> [-- [<notmuch_args>]]
source ~/.shell/profile

acc=$1
shift
[[ ${1-} == -- ]] && shift

# NOTE: set default action
(($#)) || set -- new

cfg=${XDG_CONFIG_HOME:-$HOME/.config}/notmuch/acc/"$acc"

## MAYBE: instead of config directly specify path to db ?
exec notmuch --config "$cfg" "$@"
