#!/bin/bash -eu
#%SUMMARY: sort account mails to dirs by afew
#%WARN! close neomutt (or at least save you statuses) -- otherwise it will freeze
#%USAGE: $ ./$0 <account>

acc=$1
shift
[[ ${1-} == -- ]] && shift

# NEED: send to neomutt "lock" + "sync-mailbox" then do "sort" and then again -- "reopen" same vfolder
# DEV: log -vvv to file to check problems when using from "mutt" and show in mutt only short summary
r.notmuch "$acc" -- new
r.notmuch-afew "$acc" -- -vvv --new --tag
r.notmuch-afew "$acc" -- -vvv --new --move

## HACK: propagate notmuch tag "#flagged" to maildir filenames ",F"
# r.notmuch "$acc" -- tag -flagged +flagged -- tag:flagged
