#!/bin/bash -e
source ~/.shell/func.d/packages

#| conky | show system info on screen overlay

pkg_inst conky


if distro arch; then
  pkg_inst -p 'i2cget' i2c-tools

elif distro ubuntu; then
  pkg_inst -p 'sensors' lm-sensors
fi


if cfgOpt c; then
  echo ">>> Configure cpu and etc sensors. Reply 'yes' on all questions"
  sudo sensors-detect --auto
  # Display all found sensors
  sensors
fi
