#!/bin/bash -e

# To launch shell in certain directory
# ssh -t example.com "cd /foo/bar; exec \$SHELL -l"
# { SS=autossh && hash $SS >/dev/null 2>&1; } || SS=ssh

prg=$1
shift
# HACK:(use if tmux-256color can't be copied)
# [[ ! $TERM =~ tmux ]] || export TERM=${TERM/tmux/screen}
# HACK:ALT: tmux -2

# pane_name()  { tmux send-keys "printf '\\033]2;%s\\033\\\\' '$1'" 'C-m'; }
# $(pane_name p1)
ssnm='main'
sstmux="
which zsh >/dev/null && export SHELL=\$(which zsh)
which tmux >/dev/null && if ! tmux has-session -t $ssnm
then
    tmux new-session -d -s $ssnm -n '$prg'
    tmux rename-window -t $ssnm:1 'work'
fi
tmux attach -t $ssnm
"

# HACK: nested tmux by ssh -- temporary switch host prefix
# ALT: change prf on remote (nested) -- add to $sstmux
#   tmux set prefix $(test -n "$TMUX" && echo C-s || echo C-l)
if [[ $prg == bsrv ]] && [[ $TMUX ]]; then
  trap 'tmux unbind C-s \; set -u prefix' HUP INT QUIT TERM ERR EXIT
  tmux set prefix C-s \; bind C-s send-prefix
fi

old=( -oKexAlgorithms=+diffie-hellman-group1-sha1 )

case $prg
in mpd)  ~/.bin/net.d/sir-mpd "$@"
;; bsrv) ssh bsrv   ${@:--t "$sstmux"}
;; sirx) ssh sir -X ${@:--t "$sstmux"}
;; stb)  ssh "${old[@]}" "root@192.168.1.$1" "${@:2}"
# ;; rou)  ssh "${old[@]}" rou
;; land|buld) TERM=xterm-256color ssh "$prg"
;; *) ssh "$prg" "${@:--o LocalCommand="$sstmux"}"
esac
