#!/usr/bin/env bash

usr=#
host=#
dir=/home/$usr/#
key=~/.ssh/id_rsa

# NOT: user,allow_other
opts="idmap=user,transform_symlinks"  # identityfile=$key,
opts="$opts,default_permissions,uid=$(id -u),gid=$(id -g)"

src="${usr}@${host}:$dir"
dst=~/#

trap "fusermount -u $dst && rmdir $dst" INT TERM EXIT

mkdir -p $dst && sshfs -o $opts $src $dst -C

ranger-auto $dst

## SEE: reverse sshfs!
# http://blog.dhampir.no/content/reverse-sshfs-mounts-fs-push

# paci vde2  # for dpipe
# Reverse sshfs
# dpipe /usr/lib/openssh/sftp-server = ssh CLIENT sshfs :/mnt/remote/path /mnt/local/path -o slave
