#!/bin/bash -e

dldcmd=r.wgetf
session=wget
maincmd=r.ranger

while getopts 'lc:o:t:w' o; do case "$o"
in o) cd "$OPTARG"
;; c) opencmd=$OPTARG
;; l) dldcmd=r.wgetl
;; t) session=$OPTARG
;; w) maincmd="r.wget-watch '$PWD'"
;; *) exit; esac; done; shift $((OPTIND-1))

fnm=$(r.wget-nm "${@:?}")

r.tmux-job -t "$session" -m "$maincmd" \
  r.notify-cmd -n "Saved: $fnm" -f "Can't dld: $fnm" \
    $dldcmd "${@:?}"
r.notify "Started" "${@:?}"

# ADD: check if dld part of file is more then 5MB or sleep 4
# DEV: close mpv after file moved
# USE: env DSTDIR for r.dmenu-mv to be able to sort music
# -- cd dir; DSTDIR=$PWD ranger -> mpv -> r.dmenu-mv
# -- if playlist -- don't close, simply delete from list and move to next
# ADD:(wget/bin/amvnews)
# -- extracting text info from page with song/anime/description
# -- parse page and find more appropriate link if possible
if [[ $opencmd ]]; then
  # WARNING: $1 must be real prg name, not bash wrapper
  if ps -oargs= -C "$opencmd" | grep -qxF "$fnm"
  then r.n -u 'Already opened!' "$fnm"
  else
    (($(stat -c%s) > 5*1024*1024)) || sleep 5
    ($opencmd "$fnm")  # trap 'wait' EXIT
  fi
fi
