#!/bin/bash -e
source ~/.shell/profile
set -o pipefail
[[ $CURR_PROF =~ ^home ]] || exit

# xrandr --output VGA1 --auto --output HDMI2 --off
# xrandr --output VGA1 --auto --primary --output HDMI2 --auto --left-of VGA1
# r.feh
# r.wm restart-wm

setm() { local sz=${1:-1920x1080}; shift
    if ! xrandr -q | sed '/^VGA1/,/^\S/!d' | grep -q "$sz"; then
        xrandr --addmode VGA1 "$sz"
    fi
    xrandr --output VGA1 --mode $sz --primary \
           --output LVDS1 ${@:---off};
}

case "${1#-}"
in g|game) setm 1280x720
;; w|work) setm 1920x1080
;; f|full) setm 3840x2160
;; d|dual) setm 1280x720 --mode 1366x768 --right-of VGA1
;; n|norm|*) setm 1920x1080 --mode 1366x768 --pos 1920x312
esac
