#!/bin/bash -e
# tags: browser obsolete
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

### LINKS ###
linkcp script.js ~/.surf/script.js
linkcp ../vimb/theme/"${THEME}.css" ~/.surf/style.css
