#!/bin/bash -e
# tags: net
source ~/.shell/func.d/cfgsetup

### GENS ###
linkcp ./cfg/barrier.conf ~/.local/share/barrier/.barrier.conf

## NOTE: activate only one :: server .vs. client
case $CURR_PROF
in fractal) svc_activate -cuerR barriers.service
;;     neo) svc_activate -cuerR barrierc.service
esac

## BUG: socket-activated synergys -- starts and loads Xorg even before user logins
#   << when some client tries to connect when server boots
# svc_activate -cu synergys.service
# svc_activate -cuerR synergys.socket
