#!/bin/bash -e
source ~/.shell/func.d/packages

#| xsel      | clipboard tool for rxvt extensions
#| xbindkeys | to XF86AriseVolumeUp and other media keys works
#| xdotool   | for correct working modes, and for ability naming worksps as focused wnds

pkg_inst "xsel xbindkeys xdotool"

if distro arch; then
    pkg_inst "xorg-xprop"

elif distro ubuntu; then
    echo "Err: No xprop"
fi

# xbacklight
# Obsolete by kbdd + dbus-send (set_layout), qdbus (notification)
# git_install 'ierton/xkb-switch'
