#!/bin/bash -eu
# tags: lang
source ~/.shell/func.d/cfgsetup

linkcp cfg/sbclrc ~/.sbclrc

# TEMP:HACK: allows for cl-launch to actually find system-wide quicklisp
linkcp /usr/lib/quicklisp/ ~/.quicklisp
