#!/bin/bash -e
source ~/.shell/func.d/packages

# VIZ: addr2line ar as c++filt dwp elfedit gprof ld{,.bfd,.gold}
#      nm objcopy objdump ranlib readelf size strings strip
pkg_inst -p 'readelf' binutils
#if distro ubuntu: binutils-gold

# VIZ: eu-*: addr2line ar elfcmp elfcompress elflint findtextrel
#   make-debug-archive nm objdump ranlib readelf size stack strings strip unstrip
pkg_inst -p 'eu-elfcmp' elfutils
