#!/bin/bash -e
source ~/.shell/func.d/packages

pkg_inst zathura zathura-djvu
#deb_wget "http://http.us.debian.org/debian/pool/main/z/zathura/zathura_0.2.9-2_amd64.deb"

# Can't build in end ((
# git_install "git://pwmt.org/zathura-pdf-mupdf.git" # zathura-dev libmupdf-dev
