#!/bin/bash -eu
set -o pipefail

swd=$(dirname "$(readlink -e "$0")")
patch=$1
dst=${2:-${patch%.*}}

esplitpatch=$(readlink -e "${swd%/*}/exe/splitpatch.rb")
[[ $dst == $patch ]] && dst+='.d'
dst=$(readlink -e "$dst")
dfile=$dst/files
dhunk=$dst/hunks
lfile=$dfile.lst

[[ -d $dfile ]] || splitdiff -aD "$dfile" "$patch"
[[ -s $lfile ]] || find "$dfile" -type f -printf '%p\n' > "$lfile"

# NOTE: use +++ line if not /dev/null else use ---
# NOTE: allowed \s in filename (till <Tab> before timestamp)
patchpath(){ head -3 "$1" | awk '
  /^-{3}\sa?\//{a=substr($0,5,index($0,"\t")-5)}
  /^\+{3}\sb?\//{b=substr($0,5,index($0,"\t")-5)}
  NR>3{exit}
END{
  if(b=="/dev/null")b=a
  if(b~/^[ab]\//)b=substr(b,3)
  print b
  exit length(b)<3}
'; }

splithunks(){ local d f=$1
  d=$(patchpath "$f")
  d=$dhunk/${d//\//%}
  [[ -d $d ]] && return || mkdir -p "$d"
  (cd "$d" && "$esplitpatch" --hunks "$f")
}

# ALT: | SHELL=/bin/bash parallel 'splithunks {}'
# RFC: on 4k files :: 11s for dry-run and 2m40s when splitting
while IFS= read -r line; do
  splithunks "$line"
done < "$lfile"
