#!/bin/bash -e

nm="${1:?No}"
path=~/.cache/airy/gpg/"${nm}".gpg

if [[ ! "$nm" =~ ^[[:alnum:]]+$ ]]; then
    echo "Bad file name '$1', use only \w+"
    exit 1
fi

read -s -p "Password for '$nm': " pp
if [[ "$pp" =~ [[:blank:]] ]]; then
    echo "Bad password, use only \S+"
    exit 1
fi

mkdir -p "${path%/*}"
echo "$pp" | gpg --use-agent --encrypt -o "$path"
