#!/bin/sh
#%USAGE: $ ... | xcio | ...
exec 3>&1
exec tee /dev/fd/3 | xci

# ALT:BAD:PERF: results in round-trip of copied data
# socat -4 -t 0.5 - "UNIX-CLIENT:$socket" >&- 2>&-
# exec socat -4 -t 0.5 - "UNIX-CLIENT:$socket" <&-
