#!/bin/sh
#%USAGE: $ xco | ...
read -r socket < "$XDG_RUNTIME_DIR/xc/${SSH_CONNECTION%% *}"
# BAD:anyof(-u | STDOUT | <&-): results in freeze-up NEED!:(</dev/null)
exec socat "UNIX-CONNECT:$socket" - </dev/null
