#!/bin/bash -e
# tags: io
source ~/.shell/func.d/cfgsetup

# sudo gpasswd -a "${LOGNAME:?}" plugdev
# # $ newgrp plugdev
# s.e openrazer-daemon
# s.r openrazer-daemon
# # CFG: razergenie

linkcp -t ~/.config -- openrazer
