#!/bin/bash -e

# SEE:
#   http://www.musicpd.org/doc/protocol/command_reference.html

while : ; do
    # EXPL: Explicit idle to react on changing song on same radio stream
    mpc idle player >/dev/null
    name="$(mpc current --format '%title%')"
    [[ -n "$name" ]] || continue

    mark="$(date +'%Y-%d-%m %H:%M:%S')"
    idx="$(mpc playlist | awk -vnm="$name" \
        'BEGIN{gsub(/[][^$.*?+{}\\()|]/,"\\\\&",nm)} $0 ~ nm {print NR;quit}')"
    printf '%s |%2s| %s\n' "$mark" "${idx:-0}" "$name" >> ~/.mpd/history
done
