#!/bin/bash -e
source ~/.shell/profile
source ~/.shell/func.d/cfgsetup

### LINKS ###
dir=~/.mpd
link -t "$dir" move_current
# EXPL: playlists can't be grouped in subfolders:(
(cd ./radio && linkdir ~/.mpd/playlists/ *)

case "${CURR_PROF?:No}" in
# home) link "$PWD/mpd-sir.conf" "$dir/mpd.conf" ;;
   *) link "$PWD/mpd-own.conf" "$dir/mpd.conf" ;;
esac


if cfgOpt c || [[ ! -e "$dir/pid" ]]; then
    # Stop the daemon and disable from starting on boot:
    # Because being launched by init.d it has no access to ~/.ncmpcpp
    # TODO: Maybe with systemd all will be ok?
    if distro arch; then
        sudo systemctl stop mpd

    elif distro ubuntu; then
        sudo service mpd stop
        sudo update-rc.d mpd disable
    fi

    mkdir -p "$dir/playlists"
    touch $dir/{db,log,pid,state}
    # Check if running: sudo /etc/init.d/mp status | grep -c "is running"
fi

### GENS ###
./state.gen

if cfgOpt u; then
    pgrep mpd && mpd --kill
    pgrep mpd || if ! cfgOpt d; then mpd
    else mpd --verbose --no-daemon --stdout > /tmp/mpd-verbose.log; fi

    ## Re-scan music folder
    # mpc update --wait
fi
