#!/bin/bash
cd $(dirname $(readlink -m ${0})) || exit

case "$1" in
-u|--update) update=1 ;;
--clean) clean=1 ;;
--debug) debug=1 ;;
*) ARGS="" ;;
esac

### LINKS ###
link(){ [[ ! -e $2 || -L $2 ]] && ln -sfvT "$1" $2; }

dir=~/.mpd && mkdir -p $dir
case "$CURR_PROF" in
home) link "$PWD/mpd-sir.conf" "$dir/mpd.conf" ;;
   *) link "$PWD/mpd-own.conf" "$dir/mpd.conf" ;;
esac

if [[ -n "$clean" || ! -e "$dir/pid" ]]; then
    # Stop the daemon and disable from starting on boot:
    # Because being launched by init.d it has no access to ~/.ncmpcpp
    # TODO: Maybe with systemd all will be ok?
    sudo service mpd stop
    sudo update-rc.d mpd disable
    mkdir -p "$dir/playlists"
    touch $dir/{db,log,pid,state}
    # Check if running: sudo /etc/init.d/mp status | grep -c "is running"
fi

if [[ -n "$update" ]]; then
    mpd --kill
    if [[ -n "$debug" ]]
    then mpd --verbose --no-daemon --stdout > /tmp/mpd-verbose.log
    else mpd; fi

    ## Re-scan music folder
    # mpc update --wait
fi
