#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
# EXPL: playlists can't be grouped in subfolders:(
link -t ~/.mpd/playlists ./radio/*

case ${CURR_PROF:?} in
# home) link "$PWD/mpd-sir.conf" ~/.mpd/mpd.conf ;;
   *) link "$PWD/mpd-own.conf" ~/.mpd/mpd.conf ;;
esac

svc_activate -cue mpd.{socket,service} mpd-log.service

if cfgOpt c || [[ ! -e ~/.mpd/pid ]]; then
    if distro ubuntu; then
        # Stop the daemon and disable from starting on boot:
        # Because being launched by init.d it has no access to ~/.ncmpcpp
        # Then run manually from ~/.xinitrc
        sudo service mpd stop
        sudo update-rc.d mpd disable
    fi

    mkdir -p ~/.mpd/playlists
    touch ~/.mpd/{db,log,pid,state}
    # Check if running: sudo /etc/init.d/mp status | grep -c "is running"
fi

### GENS ###
./state.gen

if cfgOpt d; then
    ! pgrep mpd || mpd --kill
    mpd --verbose --no-daemon --stdout > /tmp/mpd-verbose.log
    ## Re-scan music folder
    # mpc update --wait
fi
