#!/bin/bash -e
source ~/.shell/func.d/packages


if distro arch; then
    # system drivers
    pkg_inst -f '/usr/lib/xorg/modules/input/mouse_drv.so' xf86-input-mouse
    pkg_inst -l ntfs-3g{,}
    # sudo fc-cache && sudo mkfontscale && sudo mkfontdir

    # ALT packer (lightweight but less automatable and w/o shell completion)
    # gpg --recv-keys <KEYID>  # if unknown public key
    # AND then you can sign it:  gpg --lsign-key <KEYID>
    ayr_inst pacaur
    pkg_inst pkgfile  # To investigate packages content w/o downloading
    if cfgOpt u || [[ ! -f /var/cache/pkgfile/core.files ]]; then
      ./update
    fi

# http://askubuntu.com/questions/468466/why-this-occurs-error-diskfilter-writes-are-not-supported
else
    pkg_inst 'btrfs-tools'
fi
# elif distro ubuntu; then
    #| grub-customizer | To change boot order, time and boot-wallpaper
    # ppa_add 'ppa:danielrichter2007/grub-customizer'
    # pkg_inst 'grub-customizer'
# fi
