#!/bin/bash -e
source ~/.shell/func.d/packages


if distro arch; then
    echo "N: none"

elif distro ubuntu; then
    ppa_add 'ppa:danielrichter2007/grub-customizer'
    #| grub-customizer | To change boot order, time and boot-wallpaper

    pkg_inst 'grub-customizer'
fi
