#!/bin/bash -e
source ~/.shell/func.d/packages


if distro arch; then
    # system drivers
    pkg_inst 'ntfs-3g'
    # sudo fc-cache && sudo mkfontscale && sudo mkfontdir

# http://askubuntu.com/questions/468466/why-this-occurs-error-diskfilter-writes-are-not-supported
fi
# elif distro ubuntu; then
    #| grub-customizer | To change boot order, time and boot-wallpaper
    # ppa_add 'ppa:danielrichter2007/grub-customizer'
    # pkg_inst 'grub-customizer'
# fi
