#!/bin/bash -e
cd $(dirname $(readlink -m ${0})) && source ~/.shell/func.d/cfgsetup

### LINKS ###
link "$PWD/profile" ~/.profile


# if distro ubuntu; then:
# update-alternatives : x-session-manager cinnamon-session-cinnamon
distro(){ grep -iq "$1" <<<"${DISTRO:=$(uname -rv)}"; }
if distro ubuntu; then (cd ./ubuntu
    ./xsessionrc.gen
    ./hosts.gen
    if [[ "$update" -eq 1 ]]; then
        ./rc-local.gen
        ./nosudo_reboot
    fi
); fi
