#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
link "$PWD/profile" ~/.profile


# if distro ubuntu; then:
# update-alternatives : x-session-manager cinnamon-session-cinnamon
distro(){ grep -iq "$1" <<<"${DISTRO:=$(uname -rv)}"; }
if distro ubuntu; then (cd ./ubuntu
    ./xsessionrc.gen

    if cfgOpt u; then
        echo "N: hosts, rc-local, nosudo_reboot"
        ./hosts.gen
        ./rc-local.gen
        ./nosudo_reboot
    fi
); fi
