#!/bin/bash -e

export XDG_CURRENT_DESKTOP="${1:-xmonad}"
exec >/var/tmp/"${XDG_CURRENT_DESKTOP}_$(date +%Y%m%d_%H%M%S).log" 2>&1

# USAGE:
#   startx
#   startx ~/.xinitrc xmonad
#   startx /full/path/to/window-manager
#   ALT xinit -- :1 -nolisten tcp vt$XDG_VTNR
#   pkill -15 Xorg
# SEE: https://wiki.archlinux.org/index.php/Xinitrc#On_the_command_line

# Merge in defaults and resources
XINT=/etc/X11/xinit
[[ ! -f "$XINT/.Xresources" ]] || xrdb -merge "$XINT/.Xresources"
[[ ! -f "$HOME/.Xresources" ]] || xrdb -merge "$HOME/.Xresources"

# Start dbus, ... -- populated from packages
if [[ -d "$XINT/xinitrc.d" ]] ; then
    for f in "$XINT/xinitrc.d"/?*
    do [[ ! -x "$f" ]] || source "$f"
    done
fi

# Source X settings and programs
# CHECK:SEE: double-sourcing of xprofile by DM
#   https://wiki.archlinux.org/index.php/xprofile
[[ ! -f "$HOME/.xprofile" ]] || source "$HOME/.xprofile"

if hash auto-start >/dev/null 2>&1; then auto-start & fi

# ADD https://wiki.archlinux.org/index.php/Running_program_in_separate_X_display
# Launch session
case "$XDG_CURRENT_DESKTOP"
in xterm) exec xterm -geometry 80x66+0+0 -name login
;;    st) exec st -g 80x66+0+0 -name login
;; *) exec "$XDG_CURRENT_DESKTOP"
esac
