#!/bin/bash -e

session=("${1:-xmonad}")
exec >/var/tmp/"${session}_$(date +%Y%m%d_%H%M%S).log" 2>&1
export XDG_CURRENT_DESKTOP="$session"

# USAGE:
#   startx
#   startx ~/.xinitrc xmonad
#   startx /full/path/to/window-manager
#   ALT xinit -- :1 -nolisten tcp vt$XDG_VTNR
#   pkill -15 Xorg
# SEE: https://wiki.archlinux.org/index.php/Xinitrc#On_the_command_line

# Merge in defaults and resources
XINT=/etc/X11/xinit
[[ ! -f "$XINT/.Xresources" ]] || xrdb -merge "$XINT/.Xresources"
[[ ! -f "$HOME/.Xresources" ]] || xrdb -merge "$HOME/.Xresources"

# Start dbus, ... -- populated from packages
if [[ -d "$XINT/xinitrc.d" ]] ; then
    for f in "$XINT/xinitrc.d"/?*
    do [[ ! -x "$f" ]] || source "$f"
    done
fi

# Source X settings and programs
# CHECK:SEE: double-sourcing of xprofile by DM
#   https://wiki.archlinux.org/index.php/xprofile
[[ ! -f "$HOME/.xprofile" ]] || source "$HOME/.xprofile"


# ADD https://wiki.archlinux.org/index.php/Running_program_in_separate_X_display
case "$session"
in xterm) session=(xterm -geometry 80x66+0+0 -name login)
;;    st) session=(st -g 80x66+0+0 -name login)
esac


# SEE: https://pbrisbin.com/posts/systemd-user/
# READ: http://blog.codezen.org/2012/02/09/on-wayland-systemd-and-convergence/
# Launch session
# TRY: run startx in tmux to see logout messages
#   http://jasonwryan.com/blog/2011/12/18/login/
exec "${session[@]}" &
if hash auto-start >/dev/null 2>&1; then
    sleep 2
    auto-start
fi
wait
