#!/bin/bash -e
source ~/.shell/profile

# declare -A CURR_XKB=(
#   [layout]='us,ua,ru' [variant]='basic,winkeys,winkeys'
#   [overlay]='vim' [option]='misc:typo,amer:lvl3,amer:mods'
# )

# THINK: replace overlay for any layouts
# MAYBE: is calling setxkbmap again with only '-option "over:$over"' enough?

over=${1:-${CURR_XKB[overlay]:-vim}}
r.xkb-has-overlay ${over:?}

# setxkbmap -query -verbose 10 -print
exec setxkbmap -display ${DISPLAY:?} -option "" \
  -model pc104 -rules amer \
  -layout "${CURR_XKB[layout]:-us,ru,ua}" \
  -variant "${CURR_XKB[variant]:-amer,amer,amer}" \
  -option "${CURR_XKB[option]:-misc:typo,amer:nums,amer:lvl3,amer:mods},over:${over:?}"
