#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
if distro arch; then
  dbus=/usr/share/dbus-1/system-services
  link -sc ./unit/kbdd-dbus.service "$dbus/ru.gentoo.KbddService"

  # WARNING: 'start' can error on clean system install
  sysd=~/.config/systemd/user
  # sysd=/etc/systemd/user
  link -c {./unit,"$sysd"}/kbdd.service
  usvc_activate kbdd
else
  echo "If no systemd -- run kbdd manually"
fi


### GENS ###
if running_X; then
  ./run
fi
