#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
if distro arch; then
  # dbus=/usr/share/dbus-1/system-services
  # link -sc ./unit/kbdd-dbus.service "$dbus/ru.gentoo.KbddService"
  # BUG: usvc_activate -e kbdd.service
  # https://bbs.archlinux.org/viewtopic.php?id=172798
  usvc_activate -e xkb.service

else
  echo "If no systemd -- run kbdd manually"
fi


### GENS ###
if running_X; then
  ./run
fi
