#!/usr/bin/env bash
# On Host linux
#   ssh-keygen -N "" -f ~/.ssh/arch
#   cat ~/.ssh/arch.pub >> ~/.ssh/authorized_keys
# From within Arch vbox:
#   scp user@local.ip:~/.ssh/arch  ~/.ssh/id_rsa
#   scp user@local.ip:~/aura/airy/arch-install .

# SEE:
#   http://initrd.org/wiki/Arch_Installation_Script

### Seized ###
# https://wiki.archlinux.org/index.php/Beginners%27_guide

if ! [[ "$(uname -n)" =~ archiso ]]; then
    echo "Use this script only under archiso image!"
    exit 1
fi

opts="$1"
user="user"
sd=/dev/sda

chmod 755 ~/*
~/base-disk "$sd" "$opts" || exit $?
~/base-package || exit $?


## Mounts
fst=/mnt/etc/fstab
sed -i '4q' $fst && genfstab -U -p /mnt >> $fst #&& less $fs
echo ":: fstab generated"


### CHROOT
mkdir -p /mnt/root && cp -vft /mnt/root ~/host-* ~/user-*
arch-chroot /mnt ~/host-chroot $sd
arch-chroot /mnt ~/host-package
arch-chroot /mnt ~/host-setup $user
echo ':: host chroot ended'



# NOTE: use 'fuser' to find by what it is busy
umount -R /mnt

echo '::: install complete :::'
# Reboot now! Other scripts only after that? Or before?
