#!/usr/bin/env bash
if ! [[ "$(uname -n)" =~ archiso ]]; then echo "Use under archiso live-cd!"; exit 1; fi

## Select a mirror.
# TODO: Add fetching and sorting for mirror list?
# TODO: Replace Local IP to 'vboxhost'
pm=/etc/pacman.d/mirrorlist
pmt=/tmp/pacman.tmp
cat - <<-'EOT' > $pmt
#%BEGIN Prepended during install

## Local: pacman mirror on host server
# Server = http://192.168.56.1:8000

## Score: 0.7, Ukraine -- 6MiB/s, stable
Server = http://archlinux.bln-ua.net/$repo/os/$arch

## Score: 25.8, Ukraine -- 11MiB/s, but some packages are <1MiB/s
Server = http://mirrors.nix.org.ua/linux/archlinux/$repo/os/$arch

#%END
EOT
sed '/#%BEGIN/,/#%END/d' $pm >> $pmt
mv -vf $pmt $pm


# Don't forget to do:
#   repo-add /var/cache/pacman/pkg/custom.db.tar.gz /var/cache/pacman/pkg/*.pkg.tar.xz
#   scp -r /var/cache/pacman/pkg $VBOX_SSH:"$VMs"
# pcfg=/etc/pacman.conf
# cat - <<-'EOT' > $pmt
# ## Local: pacman mirror on host server
# [custom]
# SigLevel = Optional TrustAll
# Server = http://192.168.56.1:8000
# EOT
# sed '/#%BEGIN/,/#%END/d' $pcfg >> $pmt
# mv -vf $pmt $pcfg

echo ":: mirror selected"


### BASE SOFT
soft="base openssh sshfs"  #base-devel

if [ ! -d "/mnt/usr/bin" ]; then
    ## Install the base system  # -i -- interactive
    pacstrap /mnt $soft || exit $?
    echo ":: packstrap installed"
fi
