#!/usr/bin/env bash
if ! [[ "$(uname -n)" =~ archiso ]]; then echo "Use under archiso live-cd!"; exit 1; fi

opts="$1"
user="user"
sd=/dev/sda


### BASE
chmod 755 ~/*
~/base-disk "$sd" "$opts" || exit $?
~/base-package || exit $?
## Mounts of fstap (generate after pacstrap)
fst=/mnt/etc/fstab
sed -i '4q' $fst && genfstab -U -p /mnt >> $fst #&& less $fs
echo ":: fstab generated"


### CHROOT
mkdir -p /mnt/root && cp -vft /mnt/root ~/host-* ~/user-*
arch-chroot /mnt ~/host-chroot $sd
arch-chroot /mnt ~/host-package
arch-chroot /mnt ~/host-setup $user
echo ':: host chroot ended'


### SSH access: add host public key to vbox guest
dst="/mnt/home/$user/.ssh/authorized_keys"
mkdir -p "${dst%/*}" && cp -vf ~/id_rsa.pub "$dst"
chown "$user:$user" "$dst" && chmod 600 "$dst"


# NOTE: use 'fuser' to find by what it is busy
umount -R /mnt

echo '::: install complete :::'
# Reboot now! Other scripts only after that? Or before?
