#!/usr/bin/env bash
if ! [[ "$(uname -n)" =~ archiso|vbox ]]; then echo "Use under vbox guest!"; exit 1; fi

user="${1?No current user}"

## ROOT setup
echo ":: set root password"
printf "root:root" | chpasswd


### ADD users
# https://wiki.archlinux.org/index.php/Users_and_groups#User_groups
# adbusers, mpd, vboxsf, vboxusers, wireshark
groupadd "$user"
useradd -m -g "$user" -G users,wheel,uucp -s /bin/bash "$user"
echo ":: set $user password"
printf "$user:$user" | chpasswd
### ADD sudo powers)
# pacman -S sudo bash-completion
# visudo
# %wheel ALL=(ALL) ALL


### USER setup
dir="/home/$user/aura"
chown "$user:$user" ~/user-*
mkdir -p "$dir" && cp -vft "$dir" ~/user-*
su "$user" "$dir/user-su"


### ENABLE Services
systemctl enable sshd.service
systemctl enable xdm.service   # Autostart X


## Create initial database running as root
# /usr/bin/mandb --quiet
