#!/usr/bin/env bash
# On Host linux
#   ssh-keygen -N "" -f ~/.ssh/arch
#   cat ~/.ssh/arch.pub >> ~/.ssh/authorized_keys
# From within Arch vbox:
#   scp user@local.ip:~/.ssh/arch  ~/.ssh/id_rsa
#   scp user@local.ip:~/aura/airy/arch-install .

# SEE:
#   http://initrd.org/wiki/Arch_Installation_Script

### Seized ###
# https://wiki.archlinux.org/index.php/Beginners%27_guide

if [ "$(uname -n)" != "archiso" ]; then
    echo "Use this script only under archiso image!"
    exit 1
fi

case "$1" in
--new) bNew=1 ;;
--mnt) bNew=0 ;;
    *) bNew=  ;;
esac


sd=/dev/sda
nd=(boot root swap home)
for nm in "${nd[@]}"; do ((++i)); declare n_${nm}=$i s_${nm}=$sd$i; done

layout="
    /boot ext4       100MB
    /     ext4       8GB
    *     linux-swap 10GB
    /home ext4       100%
"

## Partitioning
if [ -n "$bNew" ]; then
    umount -fR /mnt
    gawk -v new="$bNew" -v sd="$sd" '
    BEGIN { pp="parted -s -a opt "sd; ps="1MB"; N=0
        if(new) {
            print "swapoff -a"
            print pp,"mklabel msdos"
            print "lsblk",sd,"&& echo"
        }}
    /\S/ {
        a[$1]=sd""(++N); t[$1]=$2
        if(new) { print pp,"mkpart primary",$2,ps,$3 }
        ps=$3
    } END {
        if(new) { print pp,"set 1 boot on" }
        PROCINFO["sorted_in"]="@ind_str_asc"
        for(m in a) {
            if(m == "*") { if(new) print "mkswap",a[m],"&& swapon",a[m] }
            else { if(new) { print "mkfs."t[m],a[m] }
                print "mkdir -p /mnt"m
                print "mount",a[m],"/mnt"m
            }
        }
    }' <<< "$layout" | bash
fi

## Layout
# parted -l
lsblk $sd

## Select a mirror
pm=/etc/pacman.d/mirrorlist
pmt=/tmp/mrlst
cat - <<-'EOT' > $pmt
#%BEGIN Prepended during install
## Score: 0.7, Ukraine -- 6MiB/s, stable
Server = http://archlinux.bln-ua.net/$repo/os/$arch
## Score: 25.8, Ukraine -- 11MiB/s, but some packages are <1MiB/s
Server = http://mirrors.nix.org.ua/linux/archlinux/$repo/os/$arch
#%END
EOT

sed '/#%BEGIN/,/#%END/d' $pm >> $pmt
mv -vf $pmt $pm
echo ":: mirror selected"

### BASE SOFT
soft=base  #base-devel
if [ ! -d "/mnt/usr/bin" ]; then
    ## Install the base system  # -i -- interactive
    pacstrap /mnt $soft || exit $?
    echo ":: packstrap installed"
fi

fs=/mnt/etc/fstab
sed -i '4q' $fs && genfstab -U -p /mnt >> $fs #&& less $fs
echo ":: fstab generated"


### CHROOT
mkdir -p /mnt/root
fls="base-chroot manage"
chmod u+x $fls
mv -v -t /mnt/root $fls
arch-chroot /mnt ~/base-chroot $sd
echo ':: chroot ended'

# NOTE: use 'fuser' to find by what it is busy
umount -R /mnt

echo '::: install complete :::'
# Reboot now!
