#!/usr/bin/env bash

if ! [[ "$(uname -n)" =~ archiso|vbox ]]; then
    echo "Use this script only under 'vbox...' hosts!"
    exit 1
fi


dst=~/.xinitrc
chmod u+x "$dst"
cat - << EOT > "$dst"
#!/bin/sh

exec i3
EOT

mkdir -p ~/aura
git clone https://github.com/amerlyq/airy.gin ~/aura/airy
