#!/usr/bin/env bash
if ! [[ "$(uname -n)" =~ archiso|vbox ]]; then echo "Use under vbox guest!"; exit 1; fi

dst=~/.xinitrc
touch "$dst" && chmod u+x "$dst"
cat - << EOT > "$dst"
#!/bin/sh
xrandr --size 1 &
exec i3
EOT


dst=~/.ssh/authorized_keys

# mkdir -p ~/aura
# git clone https://github.com/amerlyq/airy.git ~/aura/airy
