#!/bin/bash -e
source ~/.shell/func.d/packages

#| mutt    | console mail client
#| neomutt | mutt with many patches

if distro arch; then
  pkg_inst neomutt openldap

  # TODO:SEP: into their own modules (with docs)
  # ALSO:SEE: |community/mailutils|
  aur_inst mblaze-git
  # NOTE: required for cmdline to work $ mshow -nBFN *
  mkdir -p ~/.mblaze
  touch ~/.mblaze/seq

elif distro ubuntu; then
  pkg_inst mutt
fi
