#!/bin/bash -e
source ~/.shell/func.d/packages

#| mutt    | console mail client
#| neomutt | mutt with many patches

if distro arch; then
  pkg_inst neomutt isync notmuch openldap
  aur_inst imapfilter

elif distro ubuntu; then
  pkg_inst mutt
fi
