#!/bin/bash -eu
#%USAGE: $ ./$0 [<account>] [-- [<mutt_args>]]
#% * dmenu chooser   $ ./$0
#% * default account $ ./$0 --
lib=${XDG_CONFIG_HOME:-$HOME/.config}/mutt/acc


files(){ find -H "$1" -mindepth 1 -maxdepth 1 -xtype f \
  -printf '%f\n' | sort -n; }
choose(){ dmenu -p 'Mail:' -fn monospace:size=10 \
  -nb '#000000' -nf '#b0e0e6' -sb '#227410' -sf '#ccaa00'; }


(($#)) && acc=$1 && shift || acc=$(files "$lib" | choose)
[[ ${1-} == -- ]] && shift

[[ $acc == -- ]] && {
  source ~/.shell/profile
  acc=${MUTT_DEFAULT:?}
}

[[ -f $lib/$acc ]] || { r.n -U 'No muttrc:' "$acc"; exit 1; }

# r.wm -w MM Jump to mail workspace
exec neomutt -F "$lib/$acc" "$@"
