#!/bin/bash -eu
# BUG: how to input password from inside [qute]?
# TRY: adding passwords to keyring after entering once?
#
# TRY:BET: offline local page-keeper (used by The-Compiler)
#   PHP-server https://github.com/wallabag/wallabag
#   Python-client https://github.com/Nepochal/wallabag-cli

url=${1:?}

# BAD: hardcoded acc -- use $MAIN_MAIL
acc=amerlyq

r.mutt-acc "$acc" -s " " add@getpocket.com <<< "$url" \
&& r.n 'Sent to Pocket' "$url" \
|| r.n -U 'Error: Pocket' "$url"
