#!/bin/bash -e
# tags: term
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

### LINKS ###
linkcp -t ~/.config/mutt cfg exe
linkcp ~/.config/mutt/acc/"${MUTT_DEFAULT:?}" ~/.muttrc
linkcp ~/.config/mutt/cfg/theme-"$THEME" ~/.config/mutt/theme
# THEME=$THEME ./gen/theme-solarized.gen

# Relocate ~/.mail if necessary
# FIND:WTF: $MAIL = /var/spool/mail/user
#   CHECK: use $MAIL instead of $CURR_DIR_MAIL ?
mkdir -p -m 700 ~/.mail
# [[ $CURR_DIR_MAIL -ef ~/.mail ]] || linkcp "$CURR_DIR_MAIL" ~/.mail
linkcp -m ~/.mail ~/chat/mail

# THINK:MAYBE: write config by hands instead of generation?
# USAGE: mbsync '$mid' OR mbsync -a
# ATT: place at bottom
# dst=~/.mbsyncrc
# > "$dst"
# for creds in "${MAIL_CREDS[@]}"
# do ./gen/mbsyncrc.gen "$dst" ${creds:?}; done
# THEN: notmuch setup; notmuch new
