#!/bin/bash
set -euo pipefail -o errtrace

# r.monitor-scale 2
# onexit(){ r.monitor-scale 1; }
# trap 'onexit' HUP INT QUIT TERM ERR

r.wm -w g  # Jump to game workspace

# FIXED: VirtualGL in Steam
# [VGL] ERROR: VirtualGL attempted to load the real
# [VGL]   glXCreatePbuffer function and got the fake one instead.
# [VGL]   Something is terribly wrong.  Aborting before chaos ensues.
export LD_PRELOAD="/usr/lib/libGL.so /usr/lib32/libGL.so"

# FIXED: small fonts and video on main screen
export GDK_SCALE=2

exec optirun steam

# BAD: crash on "libvgui2_s.so"
# primusrun steam
