#!/bin/bash
set -euo pipefail -o errtrace

# r.monitor-scale 2
# onexit(){ r.monitor-scale 1; }
# trap 'onexit' HUP INT QUIT TERM ERR

r.wm -w g  # Jump to game workspace
optirun steam

# BAD: crash on "libvgui2_s.so"
# primusrun steam
