#!/bin/bash
set -euo pipefail -o errtrace

# r.monitor-scale 2
# onexit(){ r.monitor-scale 1; }
# trap 'onexit' HUP INT QUIT TERM ERR

r.wm -w g  # Jump to game workspace

# FIXED: VirtualGL in Steam
# [VGL] ERROR: VirtualGL attempted to load the real
# [VGL]   glXCreatePbuffer function and got the fake one instead.
# [VGL]   Something is terribly wrong.  Aborting before chaos ensues.
export LD_PRELOAD="libpthread.so.0 /usr/lib/libGL.so /usr/lib32/libGL.so"
export __GL_THREADED_OPTIMIZATIONS=1

# FIXED: small fonts and video on main screen
export GDK_SCALE=2

# MAYBE:ALT:REF: https://wiki.archlinux.org/index.php/Vulkan#Nvidia_-_vulkan_is_not_working_and_can_not_initialize
# export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nv_vulkan_wrapper.json
# export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json
# exec optirun -b primus steam

# USE:|community/primus_vk|: vulkan offload for Bumblebee
# export ENABLE_PRIMUS_LAYER=1

# [_] TODO:TRY: run whole "steam" and each game in separate "cgroup" or "systemd-slice"
#   => so I could easily kill whole wine game when it hangs

# NEED: $ sudo chrt --fifo --all-tasks --pid 15 $(pidof game)
# FAIL: can't set "nice" without "sudo" -- which will mess up all permissions of configs and saves
# BUT: perm-reset "sudo nice -10 sudo -u user command" will clean up above exported environment...
# exec time nice -n -4 taskset --cpu-list 0-8:2 optirun -b primus -- steam "$@"
exec steam "$@"
# exec optirun steam "$@"

# BAD: crash on "libvgui2_s.so"
# primusrun steam
