#!/bin/bash -eu
# tags: game
source ~/.shell/func.d/cfgsetup

# TODO: patch ~/.local/share/Steam/config/config.vdf
#   * "BaseInstallFolder_1" "/games/_steam"
#   * other local settings

## NOTE: Bigger fonts
# cd ~/.steam/skins
# git clone https://github.com/MoriTanosuke/HiDPI-Steam-Skin.git
# Open Steam, go to Settings -> Interface and choose the new skin HiDPI-Steam-Skin.
