#!/bin/bash -eu
# tags: game
source ~/.shell/func.d/cfgsetup


## NOTE: Bigger fonts
# cd ~/.steam/skins
# git clone https://github.com/MoriTanosuke/HiDPI-Steam-Skin.git
# Open Steam, go to Settings -> Interface and choose the new skin HiDPI-Steam-Skin.
