#!/bin/sh -eu
# NOTE: run server daemon if not running
lock=$1
port=$2
exe=$3
# ALT: systemd.service | lckdo
# BUG: server keeps lock (must not) even with '-o'
# BUG: daemon called each time -- because lock removed after server creation
exec flock -xnE13 "$lock" \
  "$exe/daemon" "$lock" "$exe/server" "$port" "$exe/auto"
