#!/bin/bash -e
source ~/.shell/func.d/packages


if distro arch; then
    pkg_inst "xf86-input-wacom"
    # pkg_inst calligra-krita

elif distro ubuntu; then
    LST="$LST build-essential autoconf libtool"
    LST="$LST libX11-dev libxi-dev x11proto-input-dev xserver-xorg-dev libxrandr-dev libncurses5-dev"
    LST="$LST linux-headers-generic xutils-dev"
    pkg_inst $LST

    git_inst -d "git://git.code.sf.net/p/linuxwacom/xf86-input-wacom"
    dir="$CURR_DIR_PKG/xf86-input-wacom/"
    pkg_build "$dir" --prefix=/usr --libdir=/usr/lib64    # on 64 bit install
fi


# NOTE:
#   http://linuxwacom.sourceforge.net/wiki/index.php/Main_Page
#   http://sourceforge.net/projects/linuxwacom/files/latest/download

# Media/control support
# apt_noprompt gnome-control-center
# В gnome 3.10 конфигуратор wacom просто шикарный!
# У меня wacom intuos 4 и «из коробки» работают даже led экранчики на планшете.
# Да, четверка почти везде сейчас из «коробки». Проблема с пятым поколением.
# Хотя, понятное дело, это временно.  И спасибо за наводку на конфигуратор, а
# то led мертвым грузом сейчас на планшете.
