#!/usr/bin/env bash
# source ~/.bash/functions.d/bash-profiler
cd "${BASH_SOURCE[0]%/*}" || exit 1

WND_ACTIVE="$(~/.i3/ctl/get_active_wnd)"

for pf in ./profile.d/*; do
    line="$(sed -n '/^#:\s*\(.*\)$/{s//\1/p;q}' "$pf")"
    if [[ "$WND_ACTIVE" != "${WND_ACTIVE//$line}" ]]; then
        WCURR_PROF="${pf##*/}"
    fi
done

echo "$WCURR_PROF"
[[ $WCURR_PROF == $(cat /tmp/aura/wacom_prof) ]] && exit
echo "$WCURR_PROF" > /tmp/aura/wacom_prof

./profile.d/default >/dev/null
${WCURR_PROF:+./profile.d/$WCURR_PROF >/dev/null}
