#!/usr/bin/env perl

# CHECK if w/o 90-monitor xrandr will return correct WxH
# BAD ALT xwininfo, xdpyinfo

use strict;
use warnings;
use strict 'vars';
use Getopt::Std;

my @state=();
my %opts=();
my $fg='owhxysWHdD';
getopts($fg.'k', \%opts);

sub dpi {
  my($px,$mm) = @_;
  return int($px*25.4/$mm + 0.5)
}

my @xout = ( qx(xrandr -q --current 2>/dev/null) ) or die "\n";
foreach (@xout) {
  # Only list used monitors, skipping off'ed
  next unless $_ =~ m/^([[:alnum:]-]+) connected (?:primary )?(\d+)x(\d+)\+(\d+)\+(\d+) .*? (\d+)mm x (\d+)mm$/;
  push @state, { o=>$1, w=>$2, h=>$3, x=>$4, y=>$5, W=>$6, H=>$7,
    d=>dpi($2,$6), D=>dpi($3,$7), s=>dpi($2,$6)/96 };
}

# TODO: sort keys by output type and place primary as very first

# HACK limit to first output. FIXME DEV general way for multihead.
foreach my $mon ($state[0]) {
  local *pr = sub { print $_[0],"=" if $opts{'k'}; print "$mon->{$_[0]}\n" };
  local *pro = sub { pr($_) if $opts{$_} };

  pr('o') unless (keys %opts);
  foreach (split //,$fg) { pro($_); }
}
