#!/bin/bash -eu
set -o pipefail

# SEE: https://btrfs.wiki.kernel.org/index.php/SysadminGuide#Snapshots

# https://bbs.archlinux.org/viewtopic.php?id=174854
# https://ramsdenj.com/2016/04/05/using-btrfs-for-easy-backup-and-rollback.html
# https://www.reddit.com/r/archlinux/comments/3dmngk/how_to_btrfssnapshot_and_roll_back_in_an_elegant/
# https://unix.stackexchange.com/questions/326348/btrfs-revert-snapshot-of-root-fs
# https://superuser.com/questions/795903/how-to-snapshot-a-btrfs-root-file-system-snapshot-of
