#!/bin/bash -e
# tags: media
# deps? wacom
source ~/.shell/func.d/cfgsetup

### LINKS ###
# CHECK: why I can't symlink only configs instead of whole folder -- are they overwritten on save ?
linkcp cfg ~/.config/xournalpp
