#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### GENS ###
if cfgOpt s; then
    case "$CFG_S"
    in elona) over="elona"
    ;; hum) over="hummer"
    ;; esac
    echo "Layout: $CFG_S"
fi

"$PWD/xkbm.gen" $over
"$PWD/run"
