#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### GENS ###
if cfgOpt s; then
    case "$ARGS" in elona) over="elona" ;; esac
    echo "Layout: $ARGS"
fi

export CURR_CACHE
"$PWD/xkbm.gen" $over
"$PWD/run"
