#!/bin/bash -eu
# tags: net
source ~/.shell/func.d/cfgsetup

# http://linux.die.net/man/8/tftpd
dir=/srv/tftp

mkdir -p "$dir"
add_sysuser tftp
[[ $(stat -c '%U:%G' "$dir") == tftp:users ]] || sudo chown tftp:users "$dir"
[[ $(stat -c '%a' /srv/tftp) == 775 ]] || sudo chmod 775 "$dir"

cfgOpt u && opts=-eR || opts=-er

if distro arch; then
  linkcp -c ./config /etc/conf.d/tftpd
  svc_activate $opts tftpd

elif distro ubuntu; then
  linkcp -c ./config /etc/default/tftpd-hpa
  svc_activate $opts tftpd-hpa
fi
