#!/bin/bash
set -euo pipefail

socket=/_dld/rtorrent/.xmlrpc

invoke(){ xmlrpc2scgi.py -p "$socket" "${@:?}"; }
pretty(){ tr \\047 \\042 | jq ''; }

opts=; while getopts 'lN' o; do case $o in :|'?') exit 2
;; l) invoke download_list ""
;; N) invoke download_list "" | tr \\047 \\042 | jq -r '.[]' | xargs -rn1 -d\\n -I{} r.rtorrent-query d.name s/{}
esac; opts+=$o; done; unset o; shift $((OPTIND-1))

if (($#)); then
  invoke "$@"
fi
