#!/bin/bash
set -euo pipefail

# TUT. https://github.com/rakshasa/rtorrent/wiki/RPC-Setup-XMLRPC
# VIZ. https://github.com/rakshasa/rtorrent/wiki/RPC-Option-Strings
# INF. https://github.com/rakshasa/rtorrent/wiki/RPC-Utility-XMLRPC2SCGI
# DEV. https://github.com/rakshasa/rtorrent-vagrant/blob/master/scripts/xmlrpc2scgi.py

socket=/_dld/rtorrent/.xmlrpc

# BUG: empty -- requires Apache to work or SCGI format is enough?
# https://github.com/rakshasa/rtorrent/issues/168
invoke(){ curl -v -d @- localhost:5000; }
# invoke(){ curl -v -d @- --unix-socket "$socket" localhost/; }

pquery(){ local method=$1; shift
  cat <<EOT
<?xml version="1.0"?>
<methodCall>
  <methodName>$method</methodName>
  <params>
    ${@+$(printf '<param><value><%1$s>%2$s</%1$s></value></param>\n' "$@")}
  </params>
</methodCall>
EOT
}

(($#)) || set -- system.listMethods
pquery "$@" | invoke
