#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

if ! id | grep -q '(wireshark)'; then
  sudo gpasswd -a "${CURR_USER:?}" wireshark
  die "!!! Re-login X session or reboot to update changes in Groups"
fi
