#!/bin/bash -e
cd $(dirname $(readlink -m ${0})) && source ~/.shell/func.d/cfgsetup
[[ "$THEME" =~ ^(dark|light)$ ]] || THEME=dark

### LINKS ###
link "$PWD/synergy-fast" ~/.cache/airy/bin/synergy-fast

### GENS ###
./synergy.gen
