#!/bin/bash -e
cd $(dirname $(readlink -m ${0}))
[[ "${THEME:=$(< ~/.cache/airy/theme)}" =~ ^(dark|light)$ ]] || THEME=dark

### LINKS ###
link(){ [[ ! -e $2 || -L $2 ]] && ln -sfvT "$1" $2; }

link "$PWD/synergy-fast" ~/.cache/airy/bin/synergy-fast

### GENS ###
./synergy.gen
