#!/bin/bash
set -euo pipefail

export DISPLAY=${DISPLAY-:0}

o=DP-1
xrandr --output eDP-1 --auto --primary --output "$o" --auto --above eDP-1

# xrandr --delmonitor DP-1~1 --delmonitor DP-1~2
# xrandr --setmonitor DP-1~1 2926/666x1600/366+914+0 DP-1 --setmonitor DP-1~2 914/208x1600/366+0+0 none
# xrandr --setmonitor DP-1~1 2845/648x1600/366+995+0 DP-1 --setmonitor DP-1~2 995/226x1600/366+0+0 none

# s1=914/208x1600/366+0+0
# s2=2926/666x1600/366+914+0
# if delargs=$(xrandr --listmonitors | grep -wo "$o~[0-9]" | sed 's/^/--delmonitor /' | paste -sd' ')
# then xrandr ${delargs:?}; fi
# xrandr --setmonitor "$o~1" "$s2" "$o" --setmonitor "$o~2" "$s1" none
