#!/bin/bash
set -euo pipefail

export DISPLAY=${DISPLAY-:0}

o=DP-1
xrandr --output eDP-1 --auto --primary --output "$o" --auto --above eDP-1

# s1=914/208x1600/366+0+0
# s2=2926/666x1600/366+914+0
# if delargs=$(xrandr --listmonitors | grep -wo "$o~[0-9]" | sed 's/^/--delmonitor /' | paste -sd' ')
# then xrandr ${delargs:?}; fi
# xrandr --setmonitor "$o~1" "$s2" "$o" --setmonitor "$o~2" "$s1" none
