#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
    aur_inst vimb-git

elif distro ubuntu; then
    pkg_inst libsoup2.4-dev libwebkit-dev libgtk-3-dev libwebkitgtk-3.0-dev
    pkg_inst gstreamer1.0-libav
    # gstreamer1.0-libav:i386'  # for youtube video
    git_inst 'fanglingsu/vimb'

    mkdef() { if ! update-alternatives --get-selections | grep -q "^$1.*$2\$"
    then sudo update-alternatives --install /usr/bin/$1 $1 "$2" 200
            sudo update-alternatives --set $1 "$2"; fi; }
fi
