# see
# http://fluxbox.sourceforge.net/docbook/en/html/app-setup.html
# Disable DPMS turning off the screen
xset -dpms
xset s off

# Disable bell
xset -b

# Enable zapping ( C-A-<Bksp> kills X)
setxkbmap -option terminate:ctrl_alt_bksp

# Enforce correct locales from the beginning
unset LC_COLLATE
export LC_CTYPE=en_US.UTF8
export LC_TIME=en_US.UTF8
export LC_NUMERIC=en_US.UTF8
export LC_MONETARY=en_US.UTF8
export LC_MESSAGES=en_US.UTF8
export LC_PAPER=en_US.UTF8
export LC_NAME=en_US.UTF8
export LC_ADDRESS=en_US.UTF8
export LC_TELEPHONE=en_US.UTF8
export LC_MEASUREMENT=en_US.UTF8
export LC_IDENTIFICATION=en_US.UTF8

# Use XToolkit in java apps
export AWT_TOOLKIT=XToolkit

# Set bgn color
xsetroot -solid "#333333
ulimit -c unlimited
