#!/bin/bash -e
source ~/.shell/func.d/packages

#| libnotify | notifier in window for long running commands (see bashrc) like $ sleep 10; alert

if distro arch; then
    pkg_inst -p 'notify-send' libnotify
elif distro ubuntu; then
    pkg_inst -p 'notify-send' libnotify-bin
fi
