#!/bin/bash -e
# tags: xorg
source ~/.shell/func.d/cfgsetup
# OR: use infinality-bundle instead

### LINKS ###
fuser=(
  # 20-fix-comic-neue.conf
  24-unhint-bold.conf
  # 30-use-comic-neue.conf
  # 30-use-source-sans-pro.conf
  40-family-generics.conf
  60-generic-family.conf
  99-user-override.conf
)
# THINK: clear dst dir from trash before creating symlinks
#   => setup is allowed only from this mod (other will be deleted)
linkcp -t ~/.config/fontconfig/conf.d -f ./cfg "${fuser[@]}"
# NOTE: need '50-user.conf' to work (ALSO: for fonts.conf)


# Minimal:
fsys=(
  # * 10-autohint.conf
  # = 10-hinting-slight.conf
  # - 10-scale-bitmap-fonts.conf
  # * 10-no-sub-pixel.conf
  10-sub-pixel-rgb.conf  # vrgb -- for hidpi
  11-lcdfilter-default.conf
  # = 30-metric-aliases.conf
  # = 50-user.conf
  # = 51-local.conf
  70-no-bitmaps.conf
)
linkcp -rt /etc/fonts/conf.d -f /etc/fonts/conf.avail "${fsys[@]}"


### GENS ###
./gen/xresources.gen

# FIND: if fc-cache need only for .otf/.ttf, and not for .conf
# cfgNo u || ./recache
