#!/bin/bash

hex() { printf "%08lx\n" $(($@)); }
dec() { printf "%ld\n" $(($@)); }
bits() {
    printf "%08lx:  " $(($@));
    dec "$@" | gawk '{
    for(i=lshift(1,31);i;i=rshift(i,1))
    printf "%d%s", (and($1,i) > 0), ++c%4==0?" ":"";
    printf"\n"; }'
}
fdd() { dd if="$1" bs=1 skip=$((${3:-0})) count=$((${2:-0})) of="${1}-"; }

note() { echo "{ notify-send --urgency normal --expire-time=10000 -i typing-monitor -h int:x:500 -h int:y:500 'Alarm' 'GO and DO this'; beep }" | at now + $1 minutes; }
# at 18:30

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# alias notes='date +"%Y-%m-%d, %T" >> ./notes.otl && vim ./notes.otl'
