#!/bin/bash

# --- Git ---

# Status
alias gt='git status -sb && (git stash list | cat)'
alias gtb='git branch -a '
# alias gtt='git tag'

# Diff
alias gdf='git diff'
alias gdn='git diff --name-only'
alias gdc='git diff --cached -w'
alias gdr='git diff --color-words'
alias gdp='git diff HEAD HEAD~1'
alias gds='git diff HEAD stash@{0}'
alias gdw='git diff --no-ext-diff --word-diff'
alias gdv='git diff'
alias gdfv='git difftool --tool=vimdiff '
alias gdfm='git difftool --tool=meld '

# Log
alias glg='git lgraph'
alias gll='git lmsg'
gln(){ git ldump -n ${1:-10}; } #or -1 for inf
alias gff='git rev-list --all | xargs git grep '
alias gsw='git show'
# git grep -l --all-match -e <regexp1> # To search files with line
# git log -G Foo --since=2009.1.1 --until=2010.1.1 -- path_containing_change # To search commits changing line

# Pull
alias gl='git pull --rebase --verbose'
alias glc='git rebase --continue'
# alias grs='git rebase --skip'
alias gss='git stash save'
alias gsp='git stash pop'
alias glu='gss && gl && gsp'
alias gco='git checkout '
# Use gco -b for topic branches
#alias gb='git branch '
# alias gf='git fetch'

# Push
alias gaa='git add --all '
alias gtr='git reset'
alias gcm='git commit -m '
alias gca='git commit -am '
alias gcu='git commit --amend '
# alias gcv='git commit --no-verify'
alias gsh='git push'


# Many repos
alias gta='~/.bin/prg.d/git-for-each st'
alias gtt='~/.bin/prg.d/git-for-each st status -su'
alias gla='~/.bin/prg.d/git-for-each pl'


alias gk='gitk --all&'


