#!/bin/bash

ARM_PREFIX=armv7l-tizen-linux-gnueabi-
alias ren='${ARM_PREFIX}nm -n '
alias res='${ARM_PREFIX}readelf -S '
alias reo='${ARM_PREFIX}objdump -m arm -D '
alias reb='${ARM_PREFIX}objdump -m arm -b binary -D '
