#!/bin/bash

# Pathes
alias .a='cd ~/aura/airy'
alias .b='cd ~/aura/airy/bin'
alias .c='cd ~/aura/airy/cfg'
alias .d='cd ~/work/dbs-amer'
alias .e='cd ~/aura/erian'
alias .g='cd ~/work/gaia'
alias .i='cd ~/work/sip'
alias .is='cd ~/work/sip/scripts'
alias .l='cd ~/aura/lyfa'
alias .m='cd ~/aura/meridia'
alias .n='cd ~/aura/airy/notes'
alias .o='cd ~/aura/erian_old'
alias .p='cd ~/work/pdrm'
alias .q='cd ~/aura/devq'
alias .t='cd ~/aura/aeternum'
alias .s='cd ~/work/sdrm'
alias .u='cd ~/aura'
alias .v='cd ~/aura/airy/cfg/vim'
alias .w='cd ~/work'
alias .y='cd ~/aura/airy/deploy'

