#!/bin/bash

# Pathes
alias .a='cd ~/aura/airy'
alias .b='cd ~/aura/airy/bin'
alias .c='cd ~/aura/airy/cfg'
alias .d='cd ~/work/dbs-amer'
alias .e='cd ~/aura/erian'
alias .g='cd ~/work/gaia'
alias .h='cd ~/aura/meridia/hack'
alias .i='cd ~/work/sip'
alias .is='cd ~/work/sip/scripts'
# alias .j=
alias .k='cd ~/aura/devq/features/kernel'
alias .l='cd ~/aura/lyfa'
alias .m='cd ~/aura/meridia'
alias .mm='cd ~/aura/devq/projects/mindmap'
alias .n='cd ~/aura/airy/notes'
alias .o='cd ~/aura/erian_old'
alias .p='cd ~/pkg'
alias .q='cd ~/aura/devq'
alias .r='cd ~/aura/airy/notes/lior'
alias .s='cd ~/sdk'
alias .t='cd ~/aura/aeternum'
alias .u='cd ~/aura'
alias .v='cd ~/aura/airy/cfg/vim'
alias .w='cd ~/work'
alias .x='cd ~/aura/airy/notes/regex'
alias .y='cd ~/aura/airy/deploy'
# alias .z=

