#!/bin/bash

# --- Modify ---
# YCM won't load on startup
# DONT WORK. WHY?
# It can be simpler to do restarting of vim from inside by combo leader-F12
# let g:...
# source $MYVIMRC

alias vi='\vim -u ~/.vim/vimrc_basic'
vimscp(){ vim scp://${2:-srk}/"${1:-$(xsel -o)}"; }
v() { #servername == syntex (must be for LaTeX)
    local _V fl=~/.cache/vim/servername
    if [ -f "$fl" ]; then
        _V=$(cat "$fl")
        vim --servername $_V --remote-silent $@
        vim --servername $_V --remote-send ':redraw<CR>'
    else
        vim $@
    fi
}

vienv(){
    local shl="$1" NM="${2:-`tempfile`}"
    if [ ! -e "$NM" ]; then
        if [[ 'py' == ${NM##*\.} ]]; then
            shl='python\n# vim: fileencoding=utf-8'
        fi
        # Python recognizes encoding: "coding[:=]\s*([-\w.]+)"
        printf "#!/usr/bin/env $shl\n\n\n" > "$NM"
        chmod 764 "$NM"
    fi
    vim "$NM"
    # vim "$NM" -c "normal i#!/usr/bin/env $shl<CR>"
}
alias vish='vienv bash '
alias vipl='vienv perl '
#alias vim='\vim --cmd "let g:loaded_youcompleteme = 1"'
#alias ycm='\vim --cmd "let g:loaded_youcompleteme = 0"'

alias s='source ranger-auto; if [ $? -eq 2 ]; then exit; fi'
alias w3m='\w3m google.com'
alias w3mh='\w3m -T "text/html"'
alias tgz='tar -cvfz' # arch.tar.gz ./
alias utgz='tar xvfz'
alias utbz2='tar xvfj'

alias p='ps -A f -o user,pid,priority,ni,pcpu,pmem,args'


#ALT: scp file1 file2 ... fileN user@host:~/Downloads/
scptar() {
    local srv src z TP
    if [ "$1" != -u ]; then z="z"; else shift; fi  # uncompressed
    if [ "$1" == -s ]; then TP="$1"; shift; fi     # send
    srv="${1?Need server}"; src="${2?Need dir path}"
    pack="cd '${src%/*}' && tar cvf$c - '${src##*/}'"
    unpack="tar xvf$c - ${3+-C "$3"}"
    case "$TP" in
        -s)  bash -c "$pack" | ssh "$srv" "$unpack" ;;
         *)  ssh "$srv" "$pack" | bash -c "$unpack" ;;
    esac
}
alias scpto='scptar -s '
alias scpfr='scptar '

alias mount='mount |column -t'
alias mountl='sudo fdisk -l'
# echo "alias firefox='nohup firefox &>/dev/null'" >> /etc/commonrc


hi() { if [ -z "$@" ]; then history | tail -20; else
    history | sed 's/^\s*\(\d\+\)\s*\(.*\)$/\2 #\1' | sort -u | agi $@;
fi; }

# old=$1, new=$2 -r | recursively  # -l | print filenames
sed_dir() { grep -rl "\<${1?Need word}\>" ./* | xargs sed -i "s@\<$1\>@$2@g"; }


# For 'reu' investigation tool in ~/.bin
for i in n s o b x l; do
    alias re$i='~/.bin/prg.d/reu '"$i"' '
done


# Very useful and nut aliases:
# http://brettterpstra.com//2013/03/31/a-few-more-of-my-favorite-shell-aliases/
# new commands
# alias susp="sudo pm-suspend && xlock -mode matrix"
# alias wifi="sudo netctl-auto switch-to"
