#!/bin/bash -e
SWD=$(readlink -e "$0"); SWD=${SWD%/*}
PATH=${SWD%/*}/mod:$PATH
set -o pipefail

trap 'onexit $((_ret)) $((num))' INT HUP QUIT TERM EXIT
# BUG: no err on script exit
onexit(){ (($1)) || return 0; printf 'Failed(%d): %d total\n' "$1" "$2"; exit "$1"; }
_ret=0

area="0 0 31496 19685"
scrn="3840x2160+0+0"

main() { local args out
  IFS='%x+' read -r gw gh gx gy <<< "${zone#%}"
  IFS='%x+' read -r fw fh fx fy <<< "${wind#%}"
  args="
    ${ro:?} ${ax:?} ${ay:?} ${aX:?} ${aY:?}
    ${ow:?} ${oh:?} ${ox:?} ${oy:?} ${pp:?}
    ${gz:?} ${gx:?} ${gy:?} ${gw:?} ${gh:?}
    ${fz:?} ${fw:?} ${fh:?} ${fx:?} ${fy:?}
  "
  readarray -tn2 out < <(area-frame <<< "$args")
  printf '%s : %s\n' "${out[@]}"
}

single(){ local ro=${1:?} pp=${2:?} zone=${3:?} wind=${4:?}
  local _rot gz fz
  declare -A _rot=([none]=0 [cw]=90 [half]=180 [ccw]=-90)
  IFS=' ' read -r ax ay aX aY <<< "$area"
  IFS='x+' read -r ow oh ox oy <<< "$scrn"
  ro=$(( ${_rot[$ro]:?} ))
  [[ $zone =~ ^% ]] && gz=0 || gz=1
  [[ $wind =~ ^% ]] && fz=0 || fz=1
  main
}

t(){ local out=$(single ${1:?})
  [[ $2 == -- ]] || { printf 't "%s" -- "%s"\n' "$1" "$out"; return 0; }
  ((++idx))
  if [[ $out != ${3:?} ]]; then ((++num))
    printf -- '%d. ----- [%s] -----\n>> ERR: %s\n> NEED: %s\n\n' \
      "$((idx))" "$1" "$out" "$3"
    ((_ret)) || _ret=1
  fi
}

### Constants ----------------------------------------------------
zero='%0x0+0+0'
full='%100x100+0+0'
fixW='%100x0+0+0'
fixH='%0x100+0+0'

cTop='0 0 31496 17717'
cRgt='20423 0 31496 19685'
cBot='0 1968 31496 19685'
cLft='0 0 11073 19685'

pRgt='0 0 34996 19685'

hCrp='3456x2160+0+0'
vCrp='1350x2160+0+0'
hPan='3840x2400+0+0'  # horz tablet
vPan='3840x6144+0+0'  # vert tablet

### Tests --------------------------------------------------------
num=0
idx=0

# Full area, distort aspect, ignore: {ro,pp}
for r in none cw half ccw; do for p in 0 1; do
  t "$r $p $full $full" -- "$area : $scrn"
done; done


# One dimension, no pp influence
t "none 0 $full $fixW" -- "$area : $hPan"
t "none 0 $full $fixH" -- "$area : $hCrp"
t "none 0 $fixW $full" -- "$cTop : $scrn"
t "none 0 $fixH $full" -- "$pRgt : $scrn"
t "none 1 $full $fixW" -- "$area : $hPan"
t "none 1 $full $fixH" -- "$area : $hCrp"
t "none 1 $fixW $full" -- "$cTop : $scrn"
t "none 1 $fixH $full" -- "$pRgt : $scrn"


# Fit other rect, scale pp=[inner..outer]
t "none 0 $full $zero" -- "$area : $hCrp"
t "cw   0 $full $zero" -- "$area : $vCrp"
t "half 0 $full $zero" -- "$area : $hCrp"
t "ccw  0 $full $zero" -- "$area : $vCrp"
t "none 0 $zero $full" -- "$cTop : $scrn"
t "cw   0 $zero $full" -- "$cRgt : $scrn"
t "half 0 $zero $full" -- "$cBot : $scrn"
t "ccw  0 $zero $full" -- "$cLft : $scrn"
t "none 1 $full $zero" -- "$area : $hPan"
t "cw   1 $full $zero" -- "$area : $vPan"
t "half 1 $full $zero" -- "$area : $hPan"
t "ccw  1 $full $zero" -- "$area : $vPan"
t "none 1 $zero $full" -- "$pRgt : $scrn"
t "cw   1 $zero $full" -- "0 0 31496 55993 : $scrn"
t "half 1 $zero $full" -- "-3500 0 31496 19685 : $scrn"
t "ccw  1 $zero $full" -- "0 -36308 31496 19685 : $scrn"


# Cross-derive
t "none 0 $fixW $fixW" -- "$area : $hPan"
t "none 0 $fixW $fixH" -- "$area : $hCrp"
t "none 0 $fixH $fixW" -- "$area : $hPan"
t "none 0 $fixH $fixH" -- "$area : $hCrp"
t "none 1 $fixW $fixW" -- "$cTop : $scrn"
t "none 1 $fixW $fixH" -- "$cTop : $scrn"
t "none 1 $fixH $fixW" -- "$pRgt : $scrn"
t "none 1 $fixH $fixH" -- "$pRgt : $scrn"


# Only one dim
t "none 0 $fixW $zero" -- "$area : $hCrp"
t "none 0 $fixH $zero" -- "$area : $hCrp"
t "none 0 $zero $fixW" -- "$area : $hPan"
t "none 0 $zero $fixH" -- "$area : $hCrp"


# Auto, always fit inside: pp=[area..frame],
t "none 0 $zero $zero" -- "$area : $hCrp"
t "cw   0 $zero $zero" -- "$area : $vCrp"
t "half 0 $zero $zero" -- "$area : $hCrp"
t "ccw  0 $zero $zero" -- "$area : $vCrp"
t "none 1 $zero $zero" -- "$cTop : $scrn"
t "cw   1 $zero $zero" -- "$cRgt : $scrn"
t "half 1 $zero $zero" -- "$cBot : $scrn"
t "ccw  1 $zero $zero" -- "$cLft : $scrn"


### Misc ---------------------------------------------------------

# Shift
t "none 0 $full %0x0+50+0" -- "$area : 3456x2160+192+0"  # Align
t "none 0 $full %0x0+100+0" -- "$area : 3456x2160+384+0"
t "none 0 $full %100x0+0+100" -- "$area : 3840x2400+0+-240"  # Pan
# Scale
t "none 0 %50x50+0+0 %50x50+0+0" -- "0 0 15748 9843 : 1920x1080+0+0"
t "none 0 %50x50+50+50 %50x50+50+50" -- "7874 4921 23622 14764 : 1920x1080+960+540"
# Blend
t "none 0.5 $zero $zero" -- "0 0 32371 19426 : 3744x2188+0+0"

### Test absolute coords

### Test external portrait screen
pscrn="1080x1920+0+0"
p(){ local scrn=$pscrn; t "$@"; }
