#!/bin/bash -e
# tags: xorg
# deps: xorg wm notify
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

### LINKS ###
# SRC: https://superuser.com/questions/877677/programatically-determine-if-an-script-is-being-executed-on-laptop-or-desktop/877796
if [[ $(</sys/class/dmi/id/chassis_type) == 3 ]]
then pltf=desktop
else pltf=laptop
fi
linkcp ./xmobarrc."$pltf" ~/.xmonad/xmobarrc

linkcp -t ~/.xmonad -- xmonad.hs
lib=~/.xmonad/lib/XMonad
linkcp -t "$lib/Config/Amer" ./cfg/*
linkcp -t "$lib/Util/Amer"   ./ext/*

svc_activate -cue xmonad.service \
  xmobar.{service,socket}

### GENS ###
if cfgOpt u; then
  # dst=~/.xmonad/xmobarrc
  # linkcp -c xmobarrc "$dst"
  # trayw=$(( 3 * (dpi * 9/72 + 4) + 6 ))
  # sed -ri '/^(, position\s*= BottomP 0).*/s//\1 '$trayw'/' "$dst"

  # THINK ServerMode.hs is too old in pacman/core, but wget is slow.
  dst=$lib/Hooks
  url='http://code.haskell.org/XMonadContrib/XMonad/Hooks/ServerMode.hs'
  [[ -f $dst/ServerMode.hs ]] || (mkdir -p "$dst" && wget "$url" -O "$dst/ServerMode.hs")
  # TRY: replace ctl.hs by bash/python XEvent script?
  # NEED:(on ERR): $ sudo ghc-pkg recache
  (cd "$lib/Util/Amer" && ghc --make ctl.hs -i -ilib -dynamic -fforce-recomp -main-is main -v0)

  # FIXED: static->dynamic linking transition 0.13.1 -> 0.13-2
  # cd ~/.xmonad && ghc --make xmonad.hs -i -ilib -dynamic -fforce-recomp -main-is main -v0 -o xmonad-x86_64-linux
fi
