#!/usr/bin/env bash
source ~/.shell/func.d/system
set -euo pipefail
# BUG: need manually 'xmonad --recompile' to create ~/.xmonad/xmonad-x86_64-linux

running_X && r.n xmonad recompile
xmonad --recompile
running_X && xmonad --restart
svc_activate -u$(running_X && echo rR) xmobar
running_X && r.n OK
exit 0
