#!/usr/bin/env bash
if ! [[ "$(uname -n)" =~ archiso ]]; then echo "Use under archiso live-cd!"; exit 1; fi

OPTS="$1"
user="tester"
zone="Europe/Kiev"
sd=/dev/sda
CURR_HOST="archvbox"
VBOX_IP="192.168.56.1"
LOCAL_SRV="http://${VBOX_IP}:23208"


hopt() { [ "${OPTS/[$1]}" != "$OPTS" ]; }
oadd() { OPTS="${OPTS}${1}"; }
die() { local ret=$?
    case "$1" in [0-9]) ret=$1; shift ;; esac
    printf "%s${1+\n}" "$1"; exit $ret
}
do_each() {  # Split args on 'most' and 'last'
sed '/#.*$/s///; /^\s*$/d' | while read L
    do ${@:1:${#@}-1} "${@:${#@}}${L}" || die
done; }


### Options chooser ###
hlst=cdpmMhsur
case "$1" in
    -[$hlst]) OPTS="-${1##*-}" ;;
    +[$hlst]*) echo "::: no chain -- choosen options only :::"
        OPTS="${1##*+}" ;;
    *) die 1 "Need option -/+'$hlst'" ;; esac
if hopt -; then
    hopt c && oadd dM  # create -> disks, unmount
    hopt d && oadd pm  # disk -> mount, packstrap
    hopt p && oadd f   # pacstrap -> fstab, repo/cache (r)
    hopt m && oadd h   # mount -> host/scripts
    hopt h && oadd s   # host -> system
    hopt s && oadd u   # system -> user
fi

timedatectl set-timezone "$zone"

### BASE step (1/3)
hopt cdpm && { chmod -R 700 ~/arch/base || die; }
hopt m && { ~/arch/base/00-disk "$sd" $(hopt d && echo "--new") || die; }

if hopt p; then
do_each /bin/bash -c ~/arch/base/ <<EOTBASE
30-pacman-conf "$LOCAL_SRV" /etc/pacman.conf
40-pacstrap "$LOCAL_SRV"
30-pacman-conf "$LOCAL_SRV" /mnt/etc/pacman.conf
EOTBASE
fi && echo ":: base disk and pacstrap ended"

if hopt f; then
    ## Automounts in fstab (generate after pacstrap)
    fst=/mnt/etc/fstab
    sed -i '4q' $fst && genfstab -U -p /mnt >> $fst #&& less $fs
fi && echo ":: fstab generated"


### HOST CHROOT step (2/3)
if hopt h; then
    cp -vrft /mnt/root/ ~/arch/{host,user} ~/id_rsa.pub || die
    chmod -R 700 /mnt/root/host || die
# ALT: systemd-nspawn
do_each arch-chroot /mnt /bin/bash -c ~/host/ <<EOTHOST
00-setup $zone
10-network $CURR_HOST $VBOX_IP
20-boot $sd
40-X
42-AUR
60-services $user
90-add-user $user
EOTHOST
fi && echo ':: host chroot ended'


### USER SU step (3/3)
if hopt u; then
do_each arch-chroot /mnt /usr/bin/su $user -c "" <<EOTUSER
chown -R $user:$user ~/user && chmod -R 700 ~/user
~/user/30-configs
EOTUSER
fi && echo ":: '$user' <su in chroot> ended"

if hopt r; then
    rep=/var/cache/pacman/pkg
    arch-chroot /mnt /bin/bash -c "repo-add $rep/custom.db.tar.gz $rep/*.pkg.tar.xz"
    scp -r /mnt/$rep frees@${VBOX_IP}:\~/home/VMs
fi

# NOTE: use 'fuser' to find by what it is busy
hopt M && umount -R /mnt

echo '::: install complete, reboot now :::'
