#!/bin/bash -e
cd $(dirname $(readlink -m ${0}))

prf=laptop-vbox

setup() {
    local src="$1" dst="$2"
    [[ "$src/arch" -ef $dst/arch ]] || cp -vfrT "$src/arch" $dst/arch
    ln -svfT ./arch/_prf/funcs      $dst/sys_funcs
    ln -svfT ./arch/_prf/${prf:?No} $dst/sys_prf
}

## Copying all output to log, as console has no scrollback
# WARNING: disables progressbar of pacman!
exec > >(tee /root/${prf}.log)
exec 2>&1

# ========================================================================
setup "${PWD%/*}" /root
source ~/sys_funcs
case "$1" in -[u]) oadd "-${1##*-}" ;; esac


if hopt u || [[ ! -d /mnt/bin ]]; then
do_each ~/arch/base/ <<EOTBASE
00-reset
05-disk-mbr
05-disk-lvm
10-mount
40-pacstrap
50-fstab
EOTBASE
fi && echo ':: <archiso> ended' || die


# ========================================================================

# THINK: if installation was interrupted, how to use only part of this setup
# directly at chroot or under su?

if hopt u || true; then
    if is_enabled lvm; then
        mkdir -vp /mnt/hostrun && mount --bind /run /mnt/hostrun
        trap "umount /mnt/hostrun && rmdir -v /mnt/hostrun" INT QUIT KILL TERM EXIT
    fi
    setup /root /mnt/root
    do_each arch-chroot /mnt /bin/bash -c ~/arch/host/ <<EOTHOST
00-setup
10-network
15-netctl-lan
15-netctl-wifi
19-mkinitcpio
20-grub
40-AUR
50-X
80-add-user
EOTHOST
fi && echo ':: <chroot> ended' || die


# ========================================================================

if is_enabled user; then
    user="${SYS_USER:?No}" dir=/home/$user
    setup /mnt/root /mnt${dir}
    arch-chroot /mnt chown -R $user:$user $dir/arch
    arch-chroot /mnt chmod -R 700 $dir/arch
    do_each arch-chroot /mnt /usr/bin/su $user -c '~/arch/user/' <<EOTUSER
30-configs
EOTUSER
fi && echo ":: <su in chroot> ended" || die

# umount -R /mnt

echo '::: install complete, reboot now :::'
