#!/bin/bash -e
source ~/.shell/func.d/packages
# SEE: http://code.jsoftware.com/wiki/Books

if distro arch; then
  # NEED: installed qt4/qmake to build
  # aur_inst "j8-git"  # J -pr-lang

  # FIXME: use "aur/customizepkg" -- download PKGBUILD, change with sed and install locally
  #   <= BAD: links are changed too frequently
  export CARCH=$(uname -m)
  # loc_inst -P 'j8-amerlyq-git' ./PKGBUILD
fi
