#!/bin/sh
#0 :0
exec /usr/lib/j8/bin/jconsole "$0" "$@"
)
NB. -jprofile
onfail=:3 :0
  1!:2&2 ARGV
  1!:2&5]13!:12''
  2!:55>:13!:11''
)
9!:27 'onfail 1'
9!:29]1

NB. echo".;:(^:_1)2}.ARGV
NB. transform=. |.@}: , {:
NB. transform=:".;:(^:_1)2}.ARGV
NB. transform=:3 :0
NB.   ". ;: (^:_1) 2}. ARGV
NB.   y
NB. )
NB. NOTE: for filters -- always print
NB. transform&.stdin ''
NB. 1!:1@3: :. stdout
NB. stdout=: 1!:2&4
NB. echo=: 0 0&$ @ (1!:2&2)

body=: ". ;: (^:_1) 2}. ARGV
echo body

NB. TODO: postfix syntax to use 'x' as data substitution
NB. TODO: sed-like key '-n' to print only explicit
NB.   OR: perl-like re-assign y=. func(y)
NB. TODO: check if stdin = tty => then submit empty list or list from single '' string
NB. TODO: convert str to num
NB.   http://www.jsoftware.com/help/jforc/input_and_output.htm
NB.   http://www.jsoftware.com/help/learning/27.htm
NB. FIND: how manipulate strings ?

exit 0
NB. SEE: http://www.jsoftware.com/help/user/hashbang.htm
NB. vim: ft=j
