#!/bin/bash -e
source ~/.shell/func.d/packages
# MOVE: into 'wm' *mod*

#| xsel      | clipboard tool for rxvt extensions
#| xbindkeys | to XF86AriseVolumeUp and other media keys works
#| xdotool   | for correct working modes, and for ability naming worksps as focused wnds

pkg_inst xsel xbindkeys xdotool

if distro arch; then
  # xorg-xdm xorg-docs
  pkg_inst xorg-server xorg-server-utils xorg-xinit
  pkg_inst xorg-xprop

elif distro ubuntu; then
  echo "Err: No xprop"
fi
