#!/bin/bash -e
# tags: io
# deps: xorg feh wm
source ~/.shell/func.d/cfgsetup


### GENS ###
# DISABLED: -- irritating at work, need DISPLAY on init install, don't work for VGA on startup anyway
#   MAYBE: don't work for any port on startup at all
#     TODO: create .service, which runs hotplug before XMonad OR run "monitor-hotplug" itself
# BAD: will be refreshed on each event (can be multiple) from each port of multiple monitors
svc_activate -cE monitor-hotplug@.service

### LINKS ###
# THINK: embed *.rules support into svc_activate
#   ALT: create 'udev_activate' or r.udev-cfg
linkcp -ct '/etc/udev/rules.d' unit/95-monitor-hotplug.rules

if cfgOpt u; then
  sudo udevadm control --reload-rules
fi

wh=$(r.xorg -WH | xargs ||:)
if [[ $wh =~ [0-9]+\ [0-9]+ ]]; then
  tmp=$(mktemp); trap "rm '$tmp'" EXIT
  sed -r '/^(\s+DisplaySize)\s.*$/s//\1 '"$wh/" \
    ./unit/90-monitor.conf > "$tmp"
  dst=/etc/X11/xorg.conf.d/90-monitor.conf
  linkcp -c "$tmp" "$dst"
fi
