#!/bin/bash
source ~/.shell/func.d/packages || exit

apt_noprompt dict dictd #dict-moby-thesaurus dict-gcide dict-freedict-eng-rus dict-wn dict-devil
# dictconv dictfmt dictzip
# mueller7-dict

# apt_noprompt libtranslate-bin
# apt_noprompt goldendict
