#!/bin/bash -e

## Server: no demon
case "$1" in --debug) dictd -d nofork -d init; exit ;; esac

if dict -h localhost -H >/dev/null; then
    dict "$@" | w3m -T "text/html" | less +/Universal
else
    dict "$@" | less "+/$@"
fi
