#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

if distro arch; then
    dir=/etc/dict
elif distro ubuntu; then
    dir=/etc/dictd
fi

# Copy files instead of symlink, as dictd drops to 'nobody' user
#   with no access to my config files inside home directory.
link -sc ./cfg "$dir"

if cfgOpt u; then
    ## Add dictionaries to dictd
    "$PWD/scripts/indexate"
    # echo "~/installer/Dics" >> /etc/dictd/dictd.order

    # sudo touch /var/lib/dictd/db.list
    if distro ubuntu; then
        sudo dictdconfig --write
        ## Re-read configuration file
        # /etc/init.d/dictd restart
        # pid=$(pgrep dictd) && sudo kill -SIGHUP $pid
    fi

    svc_enable  dictd
    svc_restart dictd

    ### GEN ###
    echo 'cd "$HOME/.wine/drive_c/Program Files (x86)/Yarxi" && wine yarxi.exe'\
        | vienv -r sh "$CURR_CACHE/bin/r.yarxi"
fi

echo "C: 'dict' done"
