#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

if distro arch; then
    dir=/etc/dict
elif distro ubuntu; then
    dir=/etc/dictd
fi
# Backup older dir (hovewer, it seems always the same)
[[ -e $dir && ! -L $dir ]] && sudo mv -vf -- $dir ${dir}_
# Create symlink, if it doesn't exist or points to another place
[[ "$PWD/cfg" -ef $dir ]] || sudo ln -sfvT "$PWD/cfg" $dir


if cfgOpt u; then
    ## Add dictionaries to dictd
    "$PWD/scripts/indexate" "$dir"
    # mv mydict.dict mydict.index /usr/share/dictd/
    # echo "~/installer/Dics" >> /etc/dictd/dictd.order
    sudo dictdconfig --write
    ## Re-read configuration file
    # /etc/init.d/dictd restart
    # pid=$(pgrep dictd) && sudo kill -SIGHUP $pid

    if distro arch; then
        sudo systemctl restart dictd
    elif distro ubuntu; then
        sudo service dictd restart
    fi
fi

echo "C: 'dict' done"
