#!/bin/bash -n

alias tmuxl='r.tmux-list'
# BAD: completion don't work
# alias tmuxa='_(){ tmux attach-session ${*:+-t"$@"}; }; _'
alias tmuxa='tmux attach-session -t'
alias tmuxk='tmux kill-session -t'

tmux_display_fix() {
    # When re-attach on ssh, DISPLAY could change and xsel become unavailable

    # Run this script outside of tmux! Set display for all sessions.
    #!!! I think you may want to look at tmux’s update-environment option, I’m pretty sure that this is the normal way of updating a tmux session’s vars.
    for name in $(tmux ls -F '#{session_name}'); do
        tmux setenv -g -t $name DISPLAY $DISPLAY
    done
}

# NOTE: w/o $ret can't return right code from 'r.chroot'
exit() { local ret=$?
  # When in SSH tmux, do detach on ',d' instead of exit
  if [[ -n ${SSH_TTY-} && -z ${TMUX-} && -z ${RANGER_LEVEL-} ]]
  then tmux detach
  else builtin exit $ret
  fi
}
