#!/bin/bash
cd $(dirname $(readlink -m ${0})) || exit $?

### LINKS ###
link(){ [[ ! -e $2 || -L $2 ]] && ln -sfvT "$1" $2; }
link "$PWD" ~/.config/ranger


case "$1" in
 dark|light) echo "colorscheme $1" ;;
--clean) while read line; do rm -vf "${PWD}${line}"; done < "$PWD/.gitignore" ;;
-u|--update) update="$1"; echo "USE: ranger --copy-config=all (Be Careful!), and see diff" ;;
esac


# bash .\w aliases -> ranger/bookmarks
"$PWD"/aliases_to_bookmarks


case "$SHELL" in *bash) RC=~/.bashrc ;; *zsh) RC=~/.zshrc ;; esac
if ! grep -q '/tmp/aura/ranger_cwdir' $RC; then
    echo "===========================
    >>> Place in your shell's config ($RC):
    # To sync zsh and ranger working directories:"
    case "$SHELL" in *bash) echo '
    finish() { echo "$PWD" > '/tmp/aura/ranger_cwdir'; }
    trap finish EXIT
    ' ;; *zsh) echo '
    function finish { echo "$PWD" > '/tmp/aura/ranger_cwdir'; }
    trap finish EXIT
    ' ;; esac
    echo "-----------------"
fi
