#!/bin/bash -e
# tags: dev
source ~/.shell/func.d/cfgsetup

# ATTENTION: currently all chroots are configured the same -- for identical kind of tasks.
# TODO: replace by individual custom profiles, linking whole dir from pwd

if cfgOpt u; then
  ./gen/config.gen
  ./gen/fstab.gen
  ./gen/nss.gen
  ./gen/net.gen
fi

# NEED: reset passwords in chroot and setup dev packages
if cfgOpt r; then
  home=$(getent passwd "$USER" | cut -d: -f6)
  for chr in "${CURR_CHROOTS[@]:?}"; do
    sudo schroot -c "${chr##*/}" -d '/' -- bash -c "passwd; passwd ${USER:?}"
    # FIXME: auto-pick script :: *-16.04 => *-xenial == ${chr%%_*}
    sudo schroot -c "${chr##*/}" -d '/' -- bash -c "cd '$home/aura/airy/chroot/prf' && ./ubuntu-16.04 -u"
  done
fi
