#!/bin/bash -eu
source ~/.shell/func.d/packages

#| iotop   | Show disk r/w statistics for processes like htop (press 'a')
#| dstat   | Versatile tool for generating system resource statistics
#| sysstat | performance monitoring tools VIZ:(iostat,isag,mpstat,pidstat,sadf,sar)
pkg_inst htop iotop iftop dstat lsof sysstat

# VIZ: lsdev procinfo socklist
pkg_inst procinfo-ng
# pkg_inst iptraf-ng  # ncurses netw mon
