#!/bin/bash -eu
source ~/.shell/func.d/packages

#| iotop   | Show disk r/w statistics for processes like htop (press 'a')
#| dstat   | Versatile tool for generating system resource statistics
#| sysstat | performance monitoring tools VIZ:(iostat,isag,mpstat,pidstat,sadf,sar)
#| vtop    | realtime ascii graph of cpu/mem
pkg_inst htop iotop iftop dstat lsof sysstat

# VIZ: lsdev procinfo socklist
pkg_inst procinfo-ng
# pkg_inst iptraf-ng  # ncurses netw mon

# NOTE: globally monitor short-living processes, etc.
# REF: http://www.brendangregg.com/blog/2014-07-28/execsnoop-for-linux.html
# VIZ: execsnoop etc.
aur_inst perf-tools
