#!/bin/bash -eu
set -o pipefail
cwd=${1-}; [[ $cwd == /?* && -d $cwd ]] && { cd "$cwd"; shift; }
# WARN: color.ui works only if no other color.* set in .gitconfig
exec r.git-find | xargs -0 -I{} sh -c '
  r.git-status "$0" && \
    git -C "$0" -c color.ui=always --no-pager "$@" 2>&1
  ' '{}' "${@:-remote -v}"
