#!/bin/bash -eu
set -o pipefail
## DEV:
# Так же вести себя и с пулом -- прошёл успешно если чистый или нужен коммит,
# стэш, merge итп -- парсить и заменять на значки
cd "${1:-$PWD}"
# ATT:(-j1): -- gpg-agent can't decrypt keys in-time
exec r.git-find | r.git-freeze ${2+"$2"} \
  | xargs -0 -L1 sh -c '
  echo && r.git-status "$0" &&
  git-up "$0" 2>&1 &&
  r.git-status "$0" && echo'
# DISABLED:(ruby/git-up) -- became very bugged
