#!/bin/bash -e
source ~/.shell/profile
cd "${1:-$PWD}"

# After this script you must specify 'ghub' entry in ~/.ssh/config
# In other case you will not be able to pull this gurl

# git remote show origin | grep "Push *URL" | sed "s@.*:.*:\(.*\$\)@\1@"
info="git:"

# BAD: explicit names => swap meaning MAIN_NAME for work and AIRY_PERSONAL_NAME for your own repos
if [[ ${CURR_PROF:?} =~ ^(work|wlux)$ ]]; then
  git config --local user.name "${MAIN_NAME:?}"
  git config --local user.email "${MAIN_MAIL:?}"
  info+="($MAIN_NAME <$MAIN_MAIL>),"
fi

gurl=$(git config --get remote.origin.url \
  | sed '{s@.*git\(.*\)\.com/@g\1:@}')

git remote set-url origin "${gurl:?Not a git repo?}"
info+=" $gurl <- '${PWD#$HOME/}'"

printf 'C: %s\n' "$info"
