#!/bin/sh -eu
cd "${1:-$PWD}"
branch=$(git rev-parse --abbrev-ref HEAD)
ahead=$(git rev-list HEAD...origin/"$branch" --ignore-submodules --count)
((ahead)) || exit 1
# FIXME:(sanity-check): exit with error (don't push)
#   * if any (still local) commit has prefix ~ /^(fix|fixup|tmp|temp):|^.?\w+!/
exec git -c color.ui=always --no-pager push --verbose
