#!/bin/bash -e
source ~/.shell/func.d/packages

pkg_inst python
pkg_inst python-pip

if distro arch; then
  pkg_inst ipython  # ALSO: jupyter for notebooks in vim
  pkg_inst python-ipdb  # pretty debugger for IPython
  pkg_inst python-pudb
  pkg_inst python2
  pkg_inst python2-pip

elif distro ubuntu; then
  pkg_inst python3 python3-pip
  pkg_inst python3-pip
  pip_inst -p 'IPython' ipython
  pip_inst -y ipdb{,}
  pip_inst -y pudb{,}
fi
