#!/bin/bash -e
source ~/.shell/func.d/packages

pkg_inst python
pkg_inst python-pip

## ALSO:USAGE: show reverse-deps
# auri pipdeptree
# pipdeptree -p faker -r

pkg_inst ipython
# ALSO: jupyter for notebooks in vim
pkg_inst python-qtconsole  # python-console

#%USAGE: py 'plot(cos(arange(30)))'
#%  ALSO: automatic usage in !ipython
#%  SEE: https://github.com/deshaw/pyflyby
#%  TUT: https://www.deshaw.com/research/desco-quansight-improving-jupyter-efficiency
pip_inst pyflyby

# SEE: https://pypi.org/project/memory-profiler/
pkg_inst python-memory-profiler  # NEED:(ipython): %memit

# https://pypi.org/project/ipdb/
# pkg_inst python-ipdb  # pretty debugger for IPython
# pkg_inst python-pudb  # DISABLED: useless TUI
