#!/bin/bash -e
# tags: lang
source ~/.shell/func.d/cfgsetup

### LINKS ###
linkcp {,~/.}pdbrc
# DFL: generate by $ ipython profile create
linkcp -t ~/.ipython/profile_default 'ipython_config.py'
# pudb.cfg
# sudo chown -R $USER:$USER ~/.config/pudb

# WARN:(search-path): '.' -> std-lib -> user-pkg -> aura -> sys-pkg
dst=$(python -m site --user-site)
echo /@/lib > "$dst/aura.pth"
python -m site  # DEBUG:INFO
