#!/bin/bash -e
# tags: lang
source ~/.shell/func.d/cfgsetup

### LINKS ###
linkcp {,~/.}pdbrc
# DFL: generate by $ ipython profile create
linkcp -t ~/.ipython/profile_default 'ipython_config.py'
# pudb.cfg
# sudo chown -R $USER:$USER ~/.config/pudb
