#!/bin/bash -e
# tags: lang
source ~/.shell/func.d/cfgsetup

### LINKS ###
# linkcp {,~/.}pdbrc
# pudb.cfg
# sudo chown -R $USER:$USER ~/.config/pudb

# DFL: generate by $ ipython profile create
linkcp -t ~/.ipython/profile_default -- cfg/ipython_config.py
linkcp -t ~/.ipython/profile_default/startup -- cfg/ipython_startup.py
linkcp -t ~/.jupyter -- cfg/jupyter_{,qt}console_config.py
linkcp cfg/mypy.ini ~/.config/mypy/config


## BET: use PKGBUILD to creates only symlink :: $SYS/site-packages/just -> /@/just/pkg
# WARN:(search-path): '.' -> std-lib -> user-pkg -> aura -> sys-pkg
# BAD: don't expose "/@/just" globally -- it will result in names collision
# dst=$(python -m site --user-site)
# mkdir -p "$dst"
# printf '%s\n' /@/just/pkg /@/just > "$dst/aura.pth"
# python -m site  # DEBUG:INFO
