#!/usr/bin/env bash
#%SUMMARY: dump yesterday's firefox history visiting times
#%USAGE: $ ./$0
set -r -o errexit -o errtrace -o noclobber -o noglob -o nounset -o pipefail

db=$(find ~/.mozilla/firefox -maxdepth 2 -type f -name 'places.sqlite' -print -quit)

sqlite3 "$db" -separator ' ' <<EOT
SELECT strftime("%H:%M", h.visit_date/1000000, 'unixepoch', 'localtime'), p.url
FROM moz_places p, moz_historyvisits h
WHERE p.id = h.place_id AND h.visit_date/1000000 > unixepoch('now', '-1 days')
ORDER BY h.visit_date
EOT
