#!/bin/sh -eu
export GTK_OVERLAY_SCROLLING=0
# export GDK_SCALE=2

## ALT:(about:config): layout.css.devPixelsPerPx = 1.7
##   BAD: fonts are not scaled after restart
export GDK_DPI_SCALE=1.7
# export GDK_DPI_SCALE=2
# export GDK_DPI_SCALE=-1

## MAYBE: needed only on #pc:neo due to very HiDPI
# export XCURSOR_SIZE=24
exec firefox "$@"
