#!/bin/bash -e
# tags: browser
source ~/.shell/func.d/cfgsetup
has_pr X || die

# TODO:SECU:
# [_] READ: Firefox - ArchWiki ⌇⡠⡏⡎⢘
#   https://wiki.archlinux.org/index.php/firefox
# [_] Files - privacy-haters - Tools and configs to help you against privacy haters like firefox. ⌇⡠⡏⡇⢄
#   http://r-36.net/scm/privacy-haters/files.html
# [_] FIXME: stop opening everything in firefox
#   mime type - How to prevent Wine from adding file associations? - Ask Ubuntu ⌇⡠⡏⡐⢢
#     https://askubuntu.com/questions/323437/how-to-prevent-wine-from-adding-file-associations


### LINKS ###
# linkcp {,~/.}pentadactylrc
linkcp {,~/.}pterosaurrc

# ALT: $ GTK_THEME=Adwaita:light firefox %u
# dst=~/.mozilla/firefox/profiles.ini
# if [[ -f $dst ]]; then
#   mprf=$(sed -rn '/Path=(.*)/s//\1/p' "$dst")
#   linkcp -t ~/.mozilla/firefox/"$mprf/chrome" userContent.css
# fi
