#!/bin/bash
set -euo pipefail

apid=${1:-ID}
ctid=${1:-IDv2}
pref=${CMAKE_PREFIX_DIR:-/work/_mirror/_prefix-host}

export LD_LIBRARY_PATH=$pref/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export PATH=$pref/bin:$PATH
dltfile=$(find -maxdepth 1 -name '*.dlt' -printf '%C@\t%f\n'|sort -rnk1|head -1|cut -f2-)

filter=("---- $ctid" "$apid ----")
((${#filter[@]})) && exec < <(printf '%s\n' "${filter[@]}")

# exec stdbuf -oL -eL tail -f "$dltfile" | stdbuf -i0 -oL -eL xxd
# exec dlt-convert -a "$@" -w /tmp/dlt.log
# exec stdbuf -oL -eL dlt-convert -a "$@"
exec stdbuf -oL -eL dlt-convert -w "$dltfile" -a -f/dev/stdin "$@"
