#!/usr/bin/env bash
#%USAGE: $ ./$0 {apid|ctid}..
set -euo pipefail

dltfile=
follow=
prefix=${CMAKE_PREFIX_PATH:-/work/cache/_prefix}
index=1
pretty=0

while getopts 'fFi:p:123456789' o; do case $o in :|'?') exit 1
;; f) follow=1
;; F) pretty=1
;; i) dltfile=$OPTARG
;; p) prefix=$OPTARG
;; [1-9]) index=$((o))
esac; done; shift $((OPTIND-1))

filter=()
for id; do filter+=("$id ----" "---- $id"); done
exec < <(printf '%s\n' "${filter[@]}")

if [[ ${prefix+x} ]]; then
  export LD_LIBRARY_PATH=$prefix/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
  export PATH=$prefix/bin:$PATH
fi

[[ -n $dltfile ]] || dltfile=$(find -maxdepth 1 -name '*.dlt' -printf '%C@\t%f\n'|sort -rnk1|head -"$index"|tail -1|cut -f2-)
[[ -f $dltfile ]] || { echo "Not found *.dlt files" >&2; exit 1; }

pretty(){
  sed 's/\s\s\+/ /' | cut -d' ' -f7,8,10,13- | sed 's/\[/| /;s/\]$//' | expand | cut -c-"$(tput cols)"; echo
}

if [[ -t 1 ]] || ((pretty)); then exec > >(pretty); fi
# exec stdbuf -oL -eL tail -f "$dltfile" | stdbuf -i0 -oL -eL xxd
# exec dlt-convert -a "$@" -w /tmp/dlt.log
# exec stdbuf -oL -eL dlt-convert -a "$@"
stdbuf -oL -eL dlt-convert -f/dev/stdin ${follow:+-w} -a "$dltfile"
