#!/bin/bash -e
source ~/.shell/func.d/packages

# SRC: https://github.com/mikf/gallery-dl
#   => download from hosting by tags
aur_inst gallery-dl


# MAYBE: |aur| photo album website
#   https://jalbum.net/en/
#     https://wiki.archlinux.org/index.php/Jalbum
#   https://lycheeorg.github.io/
#   https://github.com/TheNeikos/rust-gallery
#   https://github.com/KDE/kirigami-gallery
#   https://gitlab.com/prior99/jolly


# Waifu2x - ArchWiki ⌇⡞⣝⢏⣨
#   https://wiki.archlinux.org/index.php/Waifu2x
