#!/bin/bash -e
# tags: dev
source ~/.shell/func.d/cfgsetup

# Prune work dir -- because it can contain too many src files
if ! grep -q "PRUNEPATHS .* ${CURR_DIR_WORK:?}" /etc/updatedb.conf; then
  sudo sed -ri '/^(PRUNEPATHS = "[^"]+)"/s||\1 '"${CURR_DIR_WORK:?}"'"|' /etc/updatedb.conf
fi

cfgNo u || fork_m sudo updatedb
