#!/bin/bash -eu
source ~/.shell/func.d/packages

pkg_inst python-sphinx

# shell program output
aur_inst python-sphinxcontrib-programoutput

# aur_inst hovercraft-git
## = must fix PKGBUILD

## For PDF support
# pkg_inst texlive-latexextra
