#!/bin/bash -e

# SEE:
#   http://stackoverflow.com/questions/17360580/copy-text-in-minicom-doesnt-get-copied-completely
# minicom -w  # -c -o
# screen /dev/ttyUSB0 115200

# Exit: C-a,C-x,  --escape x
# Resize (shell inside com): stty rows lines cols columns
case "$1"
in [0-9]|"") dev=/dev/ttyUSB${1:-0}
;; *) dev="$1" ;; esac

picocom --baud 115200 --flow n --databits 8 --parity n ${dev?No}
