#!/bin/bash -eu
# tags: net chat
source ~/.shell/func.d/cfgsetup

### MANUAL ###
# /secure passphrase ********
# /secure set freenode_user xxxxxxxx
# /secure set freenode_pass ********


### GENS ###
export IRC_NICK=${IRC_NICK:?} IRC_USER=${IRC_USER:?} IRC_CHAN=${IRC_CHAN:?}

## ALT: { sleep 0.5; ./run-pipe "$cfg"; ./run-pipe <<< "/quit"; } & weechat -a; wait
if [[ -p ~/.weechat/weechat_fifo ]]
then env-subs ./cfg/weechat.conf | ./run-pipe
else WEECHAT_PASSPHRASE=' ' weechat -a \
  -r '/set sec.crypt.passphrase_file /dev/stdin' \
  -r '/exec -sh env-subs ./cfg/weechat.conf | ./run-pipe' \
  -r /quit </dev/tty >/dev/tty  # TEMP:REM:(tty):BAD:only interactive setup
fi
