#!/bin/bash -eu
# tags: net chat
source ~/.shell/func.d/cfgsetup

### MANUAL ###
# /secure passphrase ********
# /secure set znc_user xxxxxxxx
# /secure set znc_pass ********
# /secure set bitlbee_pass ********


### GENS ###
if cfgOpt r; then
  # NOTE: "export IRC_NICK" won't generate error if var doesn't exist
  # export IRC_ZNC="${IRC_ZNC:?}" IRC_ZNC_FP="${IRC_ZNC_FP:?}"
  export CHAT_IRC_NICK  CHAT_BITLBEE  CHAT_FREENODE  CHAT_FREENODE_CHAN  CHAT_OFTC  CHAT_OFTC_CHAN

  onexit(){ [[ ${wee_pid+x} ]] || return 0; r.irc-pipe <<< '/quit'; wait "$wee_pid"; }
  [[ -p ~/.weechat/weechat_fifo ]] || {
    weechat-headless --no-connect & wee_pid=$!
    trap 'onexit' HUP INT QUIT TERM ERR
  }
  while ! [[ -p ~/.weechat/weechat_fifo ]]; do printf .; sleep 0.1; done

  # r.irc-pipe <<< '/unset -mask irc.*'
  # BUG:(don't work): /server del *
  r.irc-cfg ./cfg/{anonymity,server_default,bitlbee,freenode,oftc}.conf  # znc
  # BAD:(removes too much): /unset -mask weechat.*
  r.irc-cfg ./cfg/{behavior,buflist,nicks,messages,multiline}.conf
  r.irc-pipe <<< '/save'  # OR: '/save irc'

  onexit
fi

# USE: $ WEECHAT_PASSPHRASE="$(pass irc/weechat)" weechat --no-connect
# Can't suppress passphrase prompt to update settings through script
# BAD:(space don't work for env var): $ WEECHAT_PASSPHRASE=' ' weechat --no-connect
# FAIL: $ weechat --no-connect -r '/set sec.crypt.passphrase_file /dev/stdin' \
#   -r '/exec -sh env-subs ./cfg/weechat.conf | ./run-pipe' \
#   -r /quit </dev/tty >/dev/tty  # TEMP:REM:(tty):BAD:only interactive setup

linkcp -m ~/.weechat/logs ~/chat/weechat
