#!/bin/bash -e
source ~/.shell/func.d/packages

# Mercurial
#   hgv
#   : https://bitbucket.org/lc2817/hgv

pkg_inst -p 'hg' mercurial

# DISABLED: excessive deps
# pkg_inst hgview
# pkg_inst python2-sip python2-pyqt4 python2-qscintilla-qt4
