#!/bin/bash -e
source ~/.shell/func.d/packages

# Mercurial
#   hgv
#   : https://bitbucket.org/lc2817/hgv

if distro arch; then
    pkg_inst "mercurial hgview"
    aur_inst "mercurial-server"

elif distro ubuntu; then
    pkg_inst "mercurial hgview"
fi
