#!/bin/bash -e
if ! [[ "$(uname -n)" =~ archiso ]]; then echo "Use under archiso live-cd!"; exit 1; fi

case "$1" in --new) bNew=1; shift ;; esac
sd="${1?No disk device}"

declare -A pts=( [boot]=${sd}1 [root]=${sd}2
                 [swap]=${sd}3 [home]=${sd}4 )

## Detach all previous
umount -fR /mnt

if [[ "$bNew" -eq 1 ]]; then
    ## Set MBR / GPT
    swapoff -a
    parted -s -a opt $sd mklabel msdos
    lsblk $sd && echo

    ## LVM partitions
    # ...

    ## Profile for current disk
    parted -s -a opt $sd mkpart primary ext4        1MB     100MB
    parted -s -a opt $sd mkpart primary ext4        100MB   8GB
    parted -s -a opt $sd mkpart primary linux-swap  8GB     10GB
    parted -s -a opt $sd mkpart primary ext4        10GB    100%

    parted -s -a opt $sd set ${pts[boot]} boot on
    mkswap ${pts[swap]} && swapon ${pts[swap]}

    mkfs.ext4 ${pts[root]}
    mkfs.ext4 ${pts[boot]}
    mkfs.ext4 ${pts[home]}
fi

## Mounting
if ! grep -qsw /mnt /proc/mounts; then
    mkdir -p /mnt      && mount ${pts[root]} /mnt
    mkdir -p /mnt/boot && mount ${pts[boot]} /mnt/boot
    mkdir -p /mnt/home && mount ${pts[home]} /mnt/home
fi

## Layout
# parted -l
lsblk $sd
