#!/bin/bash -e
source ~/sys_funcs
is_enabled 'mbr' || exit 0

## Set MBR / GPT
sd="${SYS_DISK:?}"
parted -s -a opt $sd mklabel msdos
lsblk $sd


## Profile for current disk
prev_sz='1MB'
order="${!SYS_PART[@]}"
for i in ${order:?}
do
    num="${SYS_PART[$i]:?}"
    sz="${SYS_SIZE[$i]:?}"
    fs="${SYS_FS[$i]:?}"
    dev="${SYS_PREF:?}${num}"
    opts="-s -a opt $sd mkpart primary"

    # TODO: primary only for boot, then create extended, all others -- logical
    #       If boot and root are merged, then primary goes to root

    case "$fs" in swap) fs=linux-swap ;; esac
    parted $opts $fs $prev_sz $sz

    case "$fs"
    in *swap) mkswap -f $dev
    ;;  ext?) mkfs.${fs} $dev  # -L Media
    ;; btrfs) mkfs.${fs} -f $dev
    ;;     *) die "Unknown FS" ;; esac

    if [[ "${SYS_MNT[$i]:?}" =~ boot$ ]]; then
        parted -s -a opt $sd set $num boot on
    fi

    prev_sz="$sz"
done


## Layout
# parted -l
lsblk $sd
echo ":: disk mbr"
