#!/bin/bash -e
source ~/sys_funcs
is_enabled 'mbr' || exit 0

## Set MBR / GPT
sd="${SYS_DISK:?No}"
parted -s -a opt $sd mklabel msdos
lsblk $sd


## Profile for current disk
prev_sz='1MB'
order="${!SYS_PART[@]}"
for i in ${order:?No}
do
    num="${SYS_PART[$i]:?No}"
    sz="${SYS_SIZE[$i]:?No}"
    fs="${SYS_FS[$i]:?No}"
    dev="${SYS_PREF?No}${num}"
    opts="-s -a opt $sd mkpart primary"

    # TODO: primary only for boot, then create extended, all others -- logical
    #       If boot and root are merged, then primary goes to root

    case "$fs" in swap) fs=linux-swap ;; esac
    parted $opts $fs $prev_sz $sz

    case "$fs"
    in *swap) mkswap -f $dev
    ;;  ext?) mkfs.${fs} $dev  # -L Media
    ;; btrfs) mkfs.${fs} -f $dev
    ;;     *) die "Unknown FS" ;; esac

    if [[ "${SYS_MNT[$i]:?No}" =~ boot$ ]]; then
        parted -s -a opt $sd set $num boot on
    fi

    prev_sz="$sz"
done


## Layout
# parted -l
lsblk $sd
echo ":: disk mbr"
