#!/usr/bin/env bash
if ! [[ "$(uname -n)" =~ archiso ]]; then echo "Use under archiso live-cd!"; exit 1; fi

srv="${1?No local pacman server}"

### Add local cache repository before [core]
cfg=/etc/pacman.conf
tmp=/tmp/pacman.tmp
# Cut first part of file
sed -r '/#%BEGIN_CUSTOM/,/#%END_CUSTOM/d; /^\[core\]/,$d' $cfg > $tmp
# Add custom repository
cat >> $tmp <<EOT
#%BEGIN_CUSTOM Prepended during install
## Custom: local pacman mirror on host server
[custom]
SigLevel = Never  # Optional TrustAll
Server = $srv
#%END_CUSTOM
EOT

# Add last part of file
sed -r '/^\[core\]/,$!d' $cfg >> $tmp

# Comment out official repo
# sed -ri '/^\[(core|extra|community)\]|^Include/s//#&/' $tmp

# Apply changes
mv -vfb $tmp $cfg

# NOTE:
#   pacman -Sy -- will be automatically called by pacstrap

# WARNING: when pacstrap, resulting /mnt/etc/pacman.conf may be different!
echo ":: [custom] set up complete"


# NOTE: Also you may use complete mirror for [core,...,community]:
# prepend >! /etc/pacman.d/mirrorlist <<EOT
## Local: pacman mirror on host server.
## Must contain official databases (base, core, ...)!
# Server = $srv
# EOT
# TODO: Replace Local IP to 'vboxhost'
