#!/bin/bash -e
source ~/sys_funcs


### Select a mirror.
fl=/etc/pacman.d/mirrorlist
tmp=/tmp/mirror.tmp
# TODO: Add fetching and sorting for mirror list?
cat > $tmp <<-'EOT'
#%BEGIN Prepended during install

## Score: 0.7, Ukraine -- 6MiB/s, stable
Server = http://archlinux.bln-ua.net/$repo/os/$arch

## Score: 25.8, Ukraine -- 11MiB/s, but some packages are <1MiB/s
Server = http://mirrors.nix.org.ua/linux/archlinux/$repo/os/$arch

#%END
EOT
sed '/#%BEGIN/,/#%END/d' $fl >> $tmp
mv -vfb $tmp $fl
echo ":: mirrors selected"


### BASE SOFT
if [[ ! -d "/mnt/usr/bin" ]]; then
    ## Install the base system  # -i -- interactive
    pacstrap /mnt ${SYS_SOFT:?No} || exit
    echo ":: packstrap installed"
fi
