#!/bin/bash -e
source ~/sys_funcs


### Automounts in fstab (generate after pacstrap)
cfg=/mnt/etc/fstab
mv -vf --backup=t ${cfg}{,}
genfstab -U -p /mnt > $cfg
# less $cfg  # WARNING: Check it!

# TODO: (on media) sudo chown -R myname:myname /media/data/

# Mount on-demand (0.15s for btrfs):  noauto,x-systemd.automount

## When editing fstab manually, get UUID of disks:
#   lsblk -f
#   lsblk -no UUID /dev/sda1


## Btrfs instead of MBR/GPT
# UUID=56edc366-a153-4eee-b2a6-471b7066b93d /     btrfs compress=lzo,autodefrag             0 0
# # Как оказалось, параметр subvol=root можно не указывать, здесь он всё равно игнорируется, передаётся опцией rootflags=subvol=root к ядру.


echo ":: fstab generated"

## Bind the mounted filesystem with permissions for the current user (or any other user/group):
# sudo mount -o user /dev/sdXN /media/disk
# sudo bindfs -u $(id -u) -g $(id -g) /media/disk /home/user/new_disk

# NTFS partitions -- user permissions, masks
# UUID=12102C02102CEB81 /mnt/dataXYZ ntfs-3g auto,users,uid=1000,gid=100,dmask=027,fmask=137,ut f8 0 0
