#!/bin/bash -e
if ! [[ "$(uname -n)" =~ archiso ]]; then echo "Use under archiso live-cd!"; exit 1; fi

## Automounts in fstab (generate after pacstrap)
fst=/mnt/etc/fstab
sed -i '4q' $fst && genfstab -U -p /mnt >> $fst #&& less $fs

## When editing fstab manually, get UUID of disks:
#   lsblk -f
#   lsblk -no UUID /dev/sda1

# После создания fstab отредактируем его, убрав из опций монтирования файловых
# систем rw,relatime,space_cache - они идут по умолчанию и в конфиге
# дублировать их незачем. Пример fstab:
# # /dev/sda
# UUID=56edc366-a153-4eee-b2a6-471b7066b93d /     btrfs compress=lzo,autodefrag             0 0
# # Как оказалось, параметр subvol=root можно не указывать, здесь он всё равно игнорируется, передаётся опцией rootflags=subvol=root к ядру.

# # /dev/sda
# UUID=56edc366-a153-4eee-b2a6-471b7066b93d /home btrfs compress=lzo,autodefrag,subvol=home 0 0

# Хитрые опции noauto,x-systemd.automount позволяют смонтировать каталог в тот
# момент, как только он потребуется, то есть не при загрузке, т.к. при старте
# системы он не особо нужен (а выигрыш в целых 0.15 секунды!).
# UUID=56edc366-a153-4eee-b2a6-471b7066b93d /var/cache/pacman/pkg btrfs noauto,x-systemd.automount,noatime,compress=lzo,autodefrag,subvol=pkg 0 0

echo ":: fstab generated"
