#!/bin/bash -eu
set -o pipefail

dir=$1

find "$dir" -mindepth 1 -type d -printf '%T@ %P\n' \
| sort -nr | cut -d' ' -f2- \
| dmenu -i -b -p "$dir" \
  -nb '#000000' -nf '#999999' -sb '#000000' -sf '#31658C' \
  -fn sans:size=9

  # -fn '-misc-fixed-medium-r-normal-*-*-200-75-75-*-*-iso8859-2'

# DEV: options
# * sort by length and alphabet (hold more results on screen)
#   $ awk '{print length,$0}' | sort -k2nr,2 -k1n,1
# * sort dirs on lvl1 by timestamp, and all nested dirs -- by alphabet
# * better choice for such usage -- frezency like fzf
#   to sort possible dirs in order
