#!/bin/bash -eu
d=$1; shift
dst=$d/$(r.dmenu-dirs "$d") || exit

exec >> "$d/.move.log"

printf '%s: %s <- %s\n' \
  "$(date +%Y%m%d_%H%M%S)" "$dst" \
  "$(realpath -s "$@")"

[[ -d $dst ]] || mkdir -p "$dst"
mv -nt "$dst" "$@"
