#!/bin/bash -e
source ~/.shell/func.d/packages

# SEE https://joeyh.name/code/moreutils/
# TODO: read man on each util
pkg_inst -p 'zrun' moreutils
pkg_inst parallel tree

# TRY:(cmdline util) align like 'column -t', but allow
#   --ignore <rgx>|<idx_list> unrelated 'rows'
#   --choose <rgx>|<idx_list> desired ones
# FIND: similar existing prs
