#!/bin/bash -e
source ~/.shell/func.d/packages

# SEE https://joeyh.name/code/moreutils/
# TODO: read man on each util
pkg_inst -p 'zrun' moreutils
pkg_inst parallel tree fzf

# SEE:ALT:(fzf) -- search 'interactive filtering'
#   ~ https://github.com/mooz/percol
#   ~ https://github.com/keiji0/canything
#   + https://github.com/zsh-users/zaw
#   + https://github.com/peco/peco

# TRY:(cmdline util) align like 'column -t', but allow
#   --ignore <rgx> unrelated 'rows'
#   --choose <rgx> desired ones
# FIND: similar existing prs
