#!/bin/bash -e
source ~/.shell/func.d/packages

pkg_inst dhex  # small ncurses binary diff programm with configurable controls
distro arch && aur_inst bvi  # small vi-like editor with binary search on '\'
pkg_inst binwalk  # many ops with firmware / binary

# ==== X only ====
has_pr X || die

pkg_inst meld  # cool text/directory comparator
pkg_inst bless
