#!/bin/bash -e
source ~/.shell/func.d/packages

pkg_inst dhex  # small ncurses binary diff programm with configurable controls
pkg_inst bbe  # binary sed
aur_inst hexgrep # http://xyne.archlinux.ca/projects/hexgrep/
distro arch && aur_inst bvi  # small vi-like editor with binary search on '\'

# ==== X only ====
has_pr X || die

pkg_inst meld  # cool text/directory comparator
pkg_inst bless
