#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
  pkg_inst xf86-video-fbdev
  pkg_inst terminus-font

  # pkg_inst 'fbterm' "fbterm cantarell-fonts"
  ## Also, you need frame buffer driver:
  # https://wiki.archlinux.org/index.php/Uvesafb
  # aur_inst 'v86d'
  # https://wiki.archlinux.org/index.php/Fbterm
fi
# elif distro ubuntu; then
    # http://blog.samat.org/2010/11/09/High-resolution-text-console-with-uvesafb-and-Debian/
# fi
