#!/bin/bash
set -euo pipefail
# TODO: override r.monitor-switch

# WTF:FIXED: prevents trashing of both LVDS-1 and DP-1 monitors
#  when VGA-1 becomes rotated
xrandr --output LVDS-1 --off

xrandr \
  --output LVDS-1 --auto --right-of DP-1 \
  --output DP-1 --primary --pos 1080x0 --rotate normal \
  --output VGA-1 --left-of DP-1 --rotate left

r.feh
