#!/bin/bash -eu
set -euo pipefail
shopt -s nullglob

# NOTE: for skip-only due to getopts you need two double hypen
#   ./$0 -- -- ...  # skip-only

### Cmdline
# a=all, x=reset_queue, g=generate
dop=maiIsSuUrR
opts=; while getopts "x${dop}dg" o; do case $o in :|'?') exit 1
esac; opts+=$o; done; shift $((OPTIND - 1))
has(){ [[ $opts =~ [$*] ]]; }

# DEV: allow install mods by full paths (or . )
for((i=1;i<=$#;++i)); do [[ ${!i} == -- ]] && break; done
mods=( "${@:1:i-1}" )
skip=( "${@:i+1}" )
defaults=$(( !${#mods[@]} && !${#skip[@]} ))


### Environment
airy=$(dirname "$(readlink -e "$0")")
"$airy/setup" -m  # BAD!RFC: dirty code duplication
source ~/.shell/exports

repo=$(git -C "$airy" rev-parse --show-toplevel)
build=$repo/_build


### Profile
source ~/.shell/profile
(( ${#mods[@]} )) || mods=( "${PKG_LIST[@]}" )
(( ${#skip[@]} )) || skip=( "${PKG_SKIP[@]}" )

# BUG:FIX: when _build/mods generated -- '-d' has no effect !
has d && mods+=( defaults )


### Run
# WARN: for {pacman, jobs, etc} USE >/dev/tty
# ALT:(tee -a): individual files "$build/log/$(date +'%Y%m%d_%H%M%S').log"
exec > >(tee -a "$build/setup.log" | r.airy-pretty)  # colorize
printf '=%.0s' {1..30}
printf ' %s ' "$(date +'%Y%m%d_%H%M%S')"
printf '=%.0s' {1..30}
printf '\n$ %s %s\n'  "$0" "$*"


### Searching mods
search_mods(){ for d in "$@"; do (cd "$d" &&
  r.airy-filter-mods "${mods[@]}" -- "${skip[@]}") done; }

has x && rm -f "$build/mods"
if ((!defaults)) || [[ ! -s $build/mods ]]; then
  # BAD:HACK: allowed mixed 'mods' and 'paths'
  # BAD: order of mod dirs -- some user mods must be 'before' and some 'after'
  [[ ${mods[*]} == . ]] && lmods=$PWD \
  || lmods=$(search_mods "$build/cfg/mod"/* "$repo/pkg" "$repo/mod")
fi
# cp -vf --backup=numbered "$build/mods" "$build/mods" && rm "$build/mods"
if ((defaults)); then [[ -s $build/mods ]] \
  && lmods=$(< "$build/mods") \
  || cat > "$build/mods" <<< "$lmods"
fi


### Processing
# INFO: general + for each mod -- if specified on cmdline!
# (( ${#opts} )) || r.airy-info <<< "$lmods"
# ALSO:(statistics): ${#mods[@]} | ${#skip[@]} | $(wc -l < "$queue")

# TODO: rename 'recache'/'rR' to smth another to free up '-r' for general reset/remove
dopts=$(tr -cd "$dop" <<< "${opts-}")
has "$dop" && r.airy-each -i $(has x && echo -r) -- \
  r.airy-do ${dopts:+"-$dopts"} <<< "$lmods"

# DEV: add one of _[un]used tags by checking in PKG_LIST
! has g || r.airy-link-tags -t "$build/tags" -f "$build/mods"
