#!/bin/bash -eu
set -euo pipefail
shopt -s nullglob

# NOTE: for skip-only due to getopts you need two double hypen
#   ./$0 -- -- ...  # skip-only

### Cmdline
# a=all, x=reset_queue, g=generate, d=defaults
dop=maiIsSuUrR
opts=; while getopts "x${dop}dgN" o; do case $o in :|'?') exit 1
esac; opts+=$o; done; shift $((OPTIND - 1))
has(){ [[ $opts =~ [$*] ]]; }

# DEV: allow install mods by full paths (or . )
for((i=1;i<=$#;++i)); do [[ ${!i} == -- ]] && break; done
mods=( "${@:1:i-1}" )
skip=( "${@:i+1}" )
defaults=$(( !${#mods[@]} && !${#skip[@]} ))


### Environment
airy=$(dirname "$(readlink -e "$0")")
"$airy/setup" -m  # BAD!RFC: dirty code duplication
source ~/.shell/exports

repo=$(git -C "$airy" rev-parse --show-toplevel)
build=$repo/_build


### Profile
source ~/.shell/profile

(( ${#mods[@]} )) || mods=( "${AIRY_MODS[@]}" )
(( ${#skip[@]} )) || skip=( ${AIRY_SKIP[@]+"${AIRY_SKIP[@]}"} )

# BUG:FIX: when _build/mods generated -- '-d' has no effect !
has d && mods+=( defaults )


### Run
# WARN: for {pacman, jobs, etc} USE >/dev/tty
# ALT:(tee -a): individual files "$build/log/$(date +'%Y%m%d_%H%M%S').log"
exec > >(tee -a "$build/setup.log" | r.airy-pretty)  # colorize
cols=$(tput cols); ((cols)) || cols=80
cols=$(( (cols - 20) / 2 ))
eval printf '=%.0s' {1..$cols}
printf ' %s ' "$(date +'%Y%m%d_%H%M%S')"
eval printf '=%.0s' {1..$cols}
printf '\n$ %s %s\n'  "$0" "$*"


### Searching mods
search_mods(){ for d in "$@"; do (cd "$d" &&
  r.airy-filter-mods "${mods[@]}" -- ${skip[@]+"${skip[@]}"}) done; }

has x && rm -f "$build/mods"
if ((!defaults)) || [[ ! -s $build/mods ]]; then
  # BAD:HACK: allowed mixed 'mods' and 'paths'
  # BAD: order of mod dirs -- some user mods must be 'before' and some 'after'
  [[ ${mods[*]} == . ]] && lmods=$PWD \
  || lmods=$(search_mods "$build/cfg/mod"/* "$repo")
fi
# cp -vf --backup=numbered "$build/mods" "$build/mods" && rm "$build/mods"
if ((defaults)); then [[ -s $build/mods ]] \
  && lmods=$(< "$build/mods") \
  || cat > "$build/mods" <<< "$lmods"
fi


### Processing
# INFO: general + for each mod -- if specified on cmdline!
# (( ${#opts} )) || r.airy-info <<< "$lmods"
# ALSO:(statistics): ${#mods[@]} | ${#skip[@]} | $(wc -l < "$queue")

# TODO: rename 'recache'/'rR' to smth another to free up '-r' for general reset/remove
# ENH: push/pop $queue in numbered file cache.[0-9] for each interrupted run
#   => you can manually drench/pop current stack by 'r.airy' w/o args
cmd=( r.airy-each )
((defaults)) && cmd+=(-i)
has x && cmd+=(-r)
has N && cmd+=(-s)
cmd+=( -- r.airy-do )
# OR: dopts=$(tr -cd "$dop" <<< "$opts")
has "$dop" && cmd+=( -"${opts//[^$dop]}" )
"${cmd[@]}" <<< "$lmods"

# DEV: add one of _[un]used tags by checking in AIRY_MODS
! has g || r.airy-link-tags -t "$build/tags" -f "$build/mods"
