#!/bin/bash -eu
# tags: airy
# NOTE: prolog must be completely independent
# BAD!RFC: dirty code duplication
#   => ALT: call ./run from ./setup to pre-initialize

cd "$(dirname "$(readlink -e "$0")")"
repo=$(git -C "$PWD" rev-parse --show-toplevel)


### LINKS ###
[[ :$PATH: == *:$PWD/bin:* ]] || export PATH=$PWD/bin:$PATH  # :linkcp
[[ :$PATH: == *:$HOME/.local/bin:* ]] || export PATH=~/.local/bin:$PATH  # :r.airy-*
./ctl/cache-links -t ~/.local/bin -q
find -H ~/.local/bin -xtype l -delete

mkdir -p ~/.config/airy
linkcp -q {,~/.}shell
linkcp -q ./pathes ~/.config/airy/pathes

r.airy-cache-alias

# TEMP:REM: until normal way to build libs awailable
r.airy-compile-src -fl -- ./lib/selfcompile.c
