#!/bin/bash -eu
# tags: airy
# NOTE: prolog must be completely independent
# BAD!RFC: dirty code duplication
#   => ALT: call ./run from ./setup to pre-initialize

cd "$(dirname "$(readlink -e "$0")")"
repo=$(git -C "$PWD" rev-parse --show-toplevel)
build=$repo/_build


### LINKS ###
[[ :$PATH: == *:$PWD/bin:* ]] || export PATH=$PWD/bin:$PATH  # :linkcp
./ctl/cache-links -t "$build/bin" -q
[[ :$PATH: == *:$HOME/.local/bin:* ]] || export PATH=~/.local/bin:$PATH  # :r.airy-*

linkcp -q {,~/.}shell
linkcp -q ./pathes "$build/cfg/pathes"

linkcp -q "$build/bin" ~/.local/bin
linkcp -q "$build/cfg" ~/.config/airy

r.airy-cache-alias

# TEMP:REM: until normal way to build libs awailable
r.airy-compile-src -fl -- ./lib/selfcompile.c
