#!/bin/bash -eu
# NOTE: prolog must be completely independent
# BAD!RFC: dirty code duplication
#   => ALT: call ./run from ./setup to pre-initialize

cd "$(dirname "$(readlink -e "$0")")"
repo=$(git -C "$PWD" rev-parse --show-toplevel)
cache=$repo/_build


### LINKS ###
[[ :$PATH: == *:$PWD/bin:* ]] || export PATH=$PWD/bin:$PATH
./ctl/cache-links -t "$cache/bin" -q

linkcp -q "$cache/bin" ~/.bin
linkcp -q "$repo/cfg/shell" ~/.shell  # REM

[[ :$PATH: == *:$HOME/.bin:* ]] || export PATH=~/.bin:$PATH
r.airy-cache-alias -o "$cache/aliases"
