#!/bin/bash -e
source ~/.shell/func.d/packages


if distro arch; then
    pkg_inst 'xmonad xmonad-contrib'  # xmobar
    [[ -d ~/.cabal/bin ]] || echo "Err: Re-login session to add ~/.cabal/bin/xmobar into PATH"
    aur_inst 'haskell-libmpd'
    cabal install xmobar --flags="with_dbus with_utf8 with_xft with_mpd with_alsa"

elif distro ubuntu; then
    pkg_inst 'xmonad xmonad-contrib'

    echo "Err: not enough"
fi
