#!/bin/bash -e
source ~/.shell/func.d/cfgsetup
[[ "$THEME" =~ ^(dark|light)$ ]] || THEME=dark

### LINKS ###
link -t ~/.xmonad  xmonad.hs xmobarrc stalonetrayrc
# mkdef x-window-manager $(which i3)

### GENS ###
# THEME=$THEME ./i3-config.gen

if cfgOpt u; then
    xmonad --recompile
    ! has_pr X || xmonad --restart
fi
