#!/bin/bash -e
source ~/.shell/func.d/cfgsetup
[[ "$THEME" =~ ^(dark|light)$ ]] || THEME=dark

### LINKS ###
link -t ~/.xmonad  xmonad.hs xmobarrc
(cd cfg && linkdir ~/.xmonad/lib/XMonad/Config/Amer/ *)

### GENS ###
if cfgOpt u; then
    xmonad --recompile
    ! has_pr X || xmonad --restart
fi
