#!/bin/bash -eu
source ~/.shell/func.d/packages

# TRY:ALT: gopasspw/gopass: The slightly more awesome standard unix password manager for teams ⌇⡠⠕⡹⣞
#   https://github.com/gopasspw/gopass

# BAD:REM: installs 'xclip' as dep
pkg_inst pass

# WARN: to install you must REF: https://aur.archlinux.org/packages/tomb/
#  $ aur sync pass-tomb
#  $ edit PKGBUILD :: https://files.dyne.org/${pkgname}/releases/*
#  $ gpg --recv-key ... for both "tomb" and "pass-tomb"
# aur_inst pass-tomb

# ALT:(tomb): encrypted filename mapping
#   alpernebbi/pass-code: A pass extension that obscures the filenames and folder hierarchy within your password store. ⌇⡠⡗⡆⢓
#     https://github.com/alpernebbi/pass-code
