#!/bin/bash -eu
# tags: util security
# deps: gnupg tomb
source ~/.shell/func.d/cfgsetup

# TODO:CHG:(cfgOpt r): when fixed "roddhjav/pass-tomb/#27"
if false; then
  set -eu  # ensure
  gpgid=${MAIN_MAIL:?}
  tmp=~/.password-store_tmp
  [[ -d ~/.password-store ]] && mv -vT ~/.password-store "$tmp"
  pass tomb --timer=2h "$gpgid"  # NOTE: it also does "pass init"
  pass git init
  # pass git remote add origin kexec.com:pass-store
  # pass git push -u --all
  [[ -d $tmp ]] && cp -aT "$tmp"/. ~/.password-store
  pass close
  pass open
  echo
  >&2 echo "WARN!!! check all passwords present and then manually remove '$tmp'"
fi
