#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
    if cfgOpt u || ! has_pr zsh; then
        aur_inst zsh-git
    fi

elif distro ubuntu; then
    pkg_inst zsh
fi

# AUR has deprecated package since 2012, therefore git:
git_inst 'clvv/fasd'
