#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
    pkg_inst zsh

elif distro ubuntu; then
    pkg_inst zsh
fi

# AUR has deprecated package since 2012, therefore git:
git_inst 'clvv/fasd'
