#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

# Main destination for Zsh
ZDOTDIR=~/.cache/zsh
mkdir -vp "$ZDOTDIR"
PREZTO="$ZDOTDIR/.zprezto"

if [[ ! -d "$PREZTO" ]]; then
    run git clone --recursive 'https://github.com/sorin-ionescu/prezto.git' "$PREZTO"
    # run git clone https://github.com/robbyrussell/oh-my-zsh.git $ZSH_DIR
fi

link "$PWD/zshenv" ~/.zshenv
#link "$PWD/zlogin" ~/.zlogin
link "$PWD/prompt" "$PREZTO/modules/prompt/functions/prompt_amer_setup"
linkdir "$ZDOTDIR/." zlogin zprofile zshrc zpreztorc

# Choose default shell
if [[ -z "$SSH_TTY" && "$(which zsh)" != ${SHELL?No} ]]; then
    sudo chsh -s /bin/bash  # Root login shell
    sudo usermod -s $(which zsh) "$(whoami)"  # User shell
fi

if cfgOpt u; then
    # chsh -s /bin/zsh
    (cd "$PREZTO" && git pull && git submodule update --init --recursive)
fi
