#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

# Main destination for Zsh
PREZTO=~/.cache/zsh/.zprezto
link -t "${PREZTO%/*}" -p. zlogin zprofile zshrc zpreztorc
if [[ -d $PREZTO ]]; then
  link "$PWD/prompt" "$PREZTO/modules/prompt/functions/prompt_amer_setup"
  link "$PWD/prompt.d" "$PREZTO/modules/prompt/functions/prompt.d"
fi

# We must have symlink anyway to keep paths actual
link ./zshenv ~/.zshenv
# Refresh cache
./update

# Choose default shell
if has_pr zsh && [[ -z $SSH_TTY && $(which zsh) != ${SHELL:?} ]]; then
  sudo chsh -s /bin/bash  # Root login shell
  sudo usermod -s "$(which zsh)" "$(whoami)"  # User shell
fi
