# vim: ft=zsh
# Executes commands at login post-zshrc.

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-"$HOME/.cache/zsh"}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Print a random, hopefully interesting, adage.
# if (( $+commands[fortune] )); then
#   if [[ -t 0 || -t 1 ]]; then
#     fortune -s
#     print
#   fi
# fi

## FIX for urxvt scrollback reflowing: mitigate content erasing
#  (force adding a line of scrollback after the initial window opening)
# WARNING: must be launched only once after terminal start/reset!
# don't place at ~/.zshrc, as it will erase scrollback on 's' in ranger
printf '\e[99999;H\n\e[H'

[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
