# vim:ft=zsh:ts=2:sw=2:sts=2
# Executes commands at login post-zshrc.
# BUG:WARNING: urxvt (but not st) sources this file on each startup!

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-"$HOME/.cache/zsh"}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" ||
    "$zcompdump" -nt "${zcompdump}.zwc") ]]
  then zcompile "$zcompdump"; fi
} &!

# Print a random, hopefully interesting, adage.
# if (( $+commands[fortune] )); then
#   if [[ -t 0 || -t 1 ]]; then
#     fortune -s
#     print
#   fi
# fi

# BUG: seems like it causes long delay before Xorg on cold system
# ((0==$#commands[r.init])) || exec r.init
dinit=~/aura/airy/cfg/core/init
[[ -f $dinit/run ]] && exec $dinit/run || ((0==$#commands[r.init])) || exec r.init
