# vim: ft=zsh
# ~/.zshenv -- always sourced by zsh (before ~/.zshrc).
[[ ! -d ~/.cache/zsh ]] || ZDOTDIR=~/.cache/zsh

# in $ man zshall --> there is recommended to use '[[ -o rcs ]]' ?
# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ -o rcs && "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]
then source "${ZDOTDIR:-$HOME}/.zprofile"; fi

# WARNING: Available even in Zsh scripts!
# :> But as I mostly writing portable scripts in bash, it's not a problem.
# WARNING: It should not contain commands that produce output or assume the
# shell is attached to a tty.
# So it can't be used to source aliases to be available in ranger.
# For bash use analogue BASH_ENV=$HOME/.zshenv before launching
