# vim: ft=zsh

## Add completions and themes from custom place
# fpath=(~/.shell/zsh/completion.d $fpath ~/.shell/zsh/theme.d)

prompt_parts="┌─└╢╼"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

### Vars ###

# export MANPATH="/usr/local/man:$MANPATH"

### Opts ###
## Disable suspending on <C-s>, <C-q>
setopt noflowcontrol && stty stop '' -ixoff -ixon
## Lets files beginning with a . be matched without explicitly specifying the dot
setopt globdots


### User Cfg ###
if [[ -f ~/.shenv ]]; then source ~/.shenv; fi
source ~/.shell/zsh/amer-widgets.zsh
source ~/.shell/zsh/amer-key-mix.zsh
source ~/.shell/zsh/filetypes.zsh
# source ~/.shell/zsh/completion.zsh  # UNUSED


# ~/.zshenv -- always sourced by zsh (before ~/.zshrc).
# WARNING: Available even in scripts! With #!/zsh
# But as I mostly writing portable scripts in bash, it's not a problem.
# WARNING: It should not contain commands that produce output or assume the
# shell is attached to a tty.
# So it can't be used to source aliases to be available in ranger.
# For bash use analogue BASH_ENV=$HOME/.zshenv before launching
if [[ -f ~/.shell/aliases ]]; then source ~/.shell/aliases ; fi

## Trap to sync zsh and ranger working directories.
# NOTE: '>!' is because of 'unsetopt CLOBBER' by 'prezto:directory'
function finish { printf "%s" "$PWD" >! '/tmp/aura/ranger_cwdir'; }
trap finish EXIT
