#!/bin/bash -e
source ~/.shell/func.d/packages

# | mdp | console music player with database
# | mpc | for control from cli / hotkeys in WM
pkg_inst mpd mpc

# TRY: https://6xq.net/pianobar/

# ALT:
# totem   | player, which not freezes in linux mint
# vlc     |
# qamixer | GUI alt for alsamixer with tray icon
