#!/bin/bash -e
# tags: media
source ~/.shell/func.d/cfgsetup

dir=~/.config/mpd

### LINKS ###
# NOTE: playlists can't be grouped in subfolders:(
linkcp -t "$dir"/playlists ./radio/*

## Local server
linkcp -t "$dir" ./cfg/mpd.conf
./cfg/state.gen "$dir"/mpd.state
svc_activate -cue mpd.{socket,service} mpd-log.service

linkcp -m ~/.config/mpd/history ~/chat/mpd  # BET? ~/db

## Broadcast server
# linkcp -t "$dir" ./cfg/mpd-cast.conf
# ./cfg/state.gen "$dir"/mpd-cast.state
# svc_activate -cue mpd-cast.{socket,service}


# OBSOLETE:
# if cfgOpt c || [[ ! -e $dir/mpd.pid ]]; then
#   if distro ubuntu; then
#     # Stop the daemon and disable from starting on boot:
#     sudo service mpd stop
#     sudo update-rc.d mpd disable
#   fi
#   # touch "$dir"/{db,mpd.{log,pid,state}}
# fi
