#!/usr/bin/env bash

# Pre-caching of slow xrandr results.
# Works only once after system startup.

FL=${TMPDIR:-/tmp}/outputs
if [ ! -f "$FL" ]; then
    xrandr -q | sed -n '/\sconnected\s/{{
        s/connected\|x\|+\|(.*$/ /g
        s/\(.*\) primary \(.*\)/\1 \2 */
    };p}' > "$FL"
fi

cat "$FL"

# Or native method without pre-caching:
# i3-msg -t get_outputs | sed -rn 's/.*\{"name":"([^"]+)","active":true,"primary":(\w+),"rect":\{"x":([0-9]+),"y":([0-9]+),"width":([0-9]+),"height":([0-9]+)\}.*/\1 \5 \6 \3 \4 \2/gp' | sed 's/true/*/g'

