#!/usr/bin/env bash
if ! [[ "$(uname -n)" =~ archiso|vbox ]]; then echo "Use under vbox guest!"; exit 1; fi

wfile() { printf "%s" "${2?No text}" > "${1?No file name}"; }
wscript() { wfile "$1" "$2" && chmod u+x "$1"; }

# WARNING: don't use '&' on the line ends, as it will consume all next linebreaks
wscript ~/.xinitrc "
#!/bin/sh
xrandr --size 1 &
exec i3
"
