#!/bin/bash -eu
source ~/.shell/func.d/packages

# VIZ: find xargs
pkg_inst findutils

# THINK: fzf :: USE: https://www.freecodecamp.org/news/fzf-a-command-line-fuzzy-finder-missing-demo-a7de312403ff/
# TRY: broot :: https://github.com/Canop/broot
#   USE: https://www.linuxuprising.com/2020/01/broot-is-interactive-treeview-directory.html
# ALT:|community/fd|: REF https://github.com/sharkdp/fd
pkg_inst fd
