#!/bin/bash -e
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

### LINKS ###
dst=~/.config/stalonetrayrc
link -c stalonetrayrc "$dst"

iw=$(( ${MAIN_DPI:?} * 9/72 + 2 ))
sed -ri '
  /^(icon_size).*/s//\1 '$iw'/
' "$dst"
