#!/bin/bash -e
source ~/.shell/func.d/cfgsetup
[[ "$THEME" =~ ^(dark|light)$ ]] || THEME=dark

### LINKS ###
dst=~/.config/stalonetrayrc
link -c stalonetrayrc "$dst"

iw=$(( ${MAIN_DPI:?} * 9/72 + 2 ))
sed -ri '
  /^(icon_size).*/s//\1 '$iw'/
' "$dst"
