#!/bin/bash -eu
source ~/.shell/func.d/packages

#| tmux | multi-window customizable terminal with vi navigation, useful for SSH connections

if distro arch; then
  # ATT:(>=2.2): TrueColor
  # ATT:(>=2.4): copy-pipe w/o cancel
  # ATT: official ==2.4.1 broken in st+tmux+neovim+ru+scrolloff
  # aur_inst tmux-git
  pkg_inst tmux

elif distro ubuntu; then
  # https://gist.github.com/P7h/91e14096374075f5316e
  ppa_add 'ppa:pi-rho/dev'
  pkg_inst tmux-next
fi
