#!/bin/bash -e
source ~/.shell/func.d/packages

#| tmux | multi-window customizable terminal with vi navigation, useful for SSH connections

if distro arch; then
  # ATT: TrueColor support in version >=2.2
  # ATT: official ==2.4.1 broken in st+tmux+neovim+ru+scrolloff
  aur_inst tmux-git

elif distro ubuntu; then
  # https://gist.github.com/P7h/91e14096374075f5316e
  ppa_add 'ppa:pi-rho/dev'
  pkg_inst tmux-next
fi
