#!/bin/bash -e
# tags: term
source ~/.shell/func.d/cfgsetup
[[ $THEME =~ ^(dark|light)$ ]] || THEME=dark

### LINKS ###
linkcp "$PWD/tmux.conf" ~/.tmux.conf
linkcp "$PWD/theme-${THEME}.conf" ~/.config/airy/theme-tmux.conf

if distro arch; then
  svc_activate -cue tmux.service
elif distro ubuntu; then
  linkcp /usr/bin/tmux-next /usr/local/bin/tmux
fi
