#!/bin/bash -eu
source ~/.shell/func.d/system
cwd_origin

# BUG: can't connect to /tmp/tmux-1000/... when no tmux is running on first install

# NOTE: install/update/clean plugins by [prefix + I/U/A-u]
tpm=~/.tmux/plugins/tpm

if [[ ! -d $tpm ]]; then
  mkdir -p "${tpm%/*}"
  git clone 'https://github.com/tmux-plugins/tpm' "$tpm"
elif [[ " $* " =~ " -u " ]]; then
  (cd "$tpm" && git-up)
fi

# Update plugins
# BUG:(clean install) unknown variable: TMUX_PLUGIN_MANAGER_PATH
# TRY: set env var to apply update on -L tmp-tmux session in case of update to 2.4 with 2.3 loaded as server
tmux source-file ~/.tmux.conf #>/dev/null 2>&1
"$tpm/scripts/install_plugins.sh" #&>/dev/null
# WARN: sometime don't pull changes from github
#   -> use "prefix + U" to update manually
"$tpm/scripts/update_plugin.sh" all
