#!/bin/bash -eu
source ~/.shell/func.d/system
cwd_origin

# BUG: can't connect to /tmp/tmux-1000/... when no tmux is running on first install
#   => workaround -- run tmux and inside it -- "make" BET: fixup for out-of-tmux installation

# NOTE: install/update/clean plugins by [prefix + I/U/A-u]
tpm=~/.tmux/plugins/tpm

if [[ ! -d $tpm ]]; then
  mkdir -p "${tpm%/*}"
  git clone 'https://github.com/tmux-plugins/tpm' "$tpm"
elif [[ " $* " =~ " -u " ]]; then
  (cd "$tpm" && git-up)
fi

# Update plugins
# BUG:(clean install) unknown variable: TMUX_PLUGIN_MANAGER_PATH
# TRY: set env var to apply update on -L tmp-tmux session in case of update to 2.4 with 2.3 loaded as server
# WARN: sometime don't pull changes from github -> use "prefix + U" to update manually
in_tmux(){ if [[ ${TMUX-} ]]; then sh -c "$@"; else tmux new-session -s "$0" "$@"; fi; }
in_tmux 'tmux source-file ~/.tmux.conf
~/.tmux/plugins/tpm/scripts/install_plugins.sh
~/.tmux/plugins/tpm/scripts/update_plugin.sh all'
