#!/bin/bash -eu
# REF:(groups list): https://www.archlinux.org/groups/

# NEED: filter-out pre-installed deps and pacstrap:
#   base base-devel yaourt
#   ?: sudo grub os-prober ntp lvm2 polkit

tmp=/tmp/pkgs.txt
also=( base base-devel yaourt "$@" )

# NOTE: generate active db w/o actual cmds execution
db=~/.cache/airy/install.txt
[[ -f $db && -s $db ]] || AIRY_DRY_RUN=1 r.airy -xI

cp -fT "$db" "$tmp"
printf '%s\n' "${also[@]}" >> "$tmp"

pacman -Qei | awk '
  /^Name\s/{n=$3}
  /^Groups\s/{print($3=="None"?n:n" "$3)}
' | grep -vwFf "$tmp"
