#!/bin/bash -eu
cd ~/sdk

### Learning ###
git clone --depth 1 'shadowbq/Cheat-Sheets'
git clone --depth 1 'BinRoot/Haskell-Data-Analysis-Cookbook'
git clone --depth 1 'sjl/learnvimscriptthehardway'
git clone --depth 1 'Gabriel439/post-rfc'  # haskell resources
git clone --depth 1 'pleac/pleac'  # lisp resources

## Real-world cooking
git clone --depth 1 'appplemac/cooking-patterns'

## Modeling With Data
# http://modelingwithdata.org/about_the_book.html
exit
### Integrate ###
# git clone --depth 1 'robbyrussell/oh-my-zsh.git'
#git clone --depth 1 vispy #for python primes interactive scientific visualization

# SEE for dependencies: http://www.graphviz.org/Download_source.php
# git clone --depth 1 'ellson/graphviz'


### System & Kernel ###
# System Programming:  lessons and examples -- smashing stack, etc
# https://github.com/angrave/SystemProgramming/wiki
# https://github.com/shihyu/Linux_Programming

# wget 'https://ftp.gnu.org/gnu/coreutils/coreutils-8.26.tar.xz'
# https://sourceware.org/git/glibc.git 69e0a87cc4c570e3b7218392fc3e743b5bddcce2
# https://github.com/fusioninventory/fusioninventory-agent
# https://github.com/m0t/gdb-heap
# https://github.com/qnikst/kbdd
# https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.10.tar.xz
# https://www.kernel.org/pub/linux/kernel/v4.x/patch-4.10.xz
# git://git.openembedded.org/openembedded-core

## Boot: modern MBR, etc
# git clone --depth 1 'http://review.coreboot.org/p/coreboot.git'


### Frameworks ###

# SDL2.0
# hg clone http://hg.libsdl.org/SDL
# git clone --depth 1 'libRocket/libRocket'
# hg_inst -d 'gabomdq/ignifuga'

# Code with examples for Qt
git clone --depth 1 'git://code.qt.io/qt/qt.git'
git clone --depth 1 'Werkov/PyQt4'
git clone --depth 1 'baoboa/pyqt5'



### Opengl ###
# hg_inst -d 'https://code.google.com/p/flyinghigh-opengl-from-python/'

echo "DONE"
