#!/bin/bash -e
#%DEPS: qt6-tools(qdbus6)

filter() {
    # sed -r '/(<blockquote>)+([^<>]*)(<\/blockquote>)+/s//\2<br>/g'
    cat
}

fdmenu() {
    local prompt=${lang:-any}
    local DMENU="dmenu -i -p ${prompt^^}: -b -nb #000000 -nf #999999 -sb #000000 -sf #31AC65 -fn -misc-fixed-medium-r-normal-*-*-200-75-75-*-*-iso8859-2"
    local fl=~/.local/share/airy/dict-words-${lang:-any}.txt
    mkdir -p "${fl%/*}"
    touch "$fl"
    local lchg='dbus-send --dest=ru.gentoo.KbddService /ru/gentoo/KbddService ru.gentoo.kbdd.set_layout'

    if [[ $lang ]]; then
      langprev=$(qdbus6 ru.gentoo.KbddService /ru/gentoo/KbddService ru.gentoo.kbdd.getCurrentLayout)
      # ^BUG: Changes lang --> but it influences current window also!
      # ALT: change language only after dmenu launched (wmctrl/xdotool &)
      # BETTER: launch $DMENU & pid=$!; then wmctrl $pid wnd and wait $pid
      { sleep 0.1; $lchg uint32:$([[ $lang == en ]] && echo 0 || echo 1); } &
    fi

    # FIXED: use reverse order for words
    word=$(tac "$fl" | cut -f2- | awk '!a[$0]++' | $DMENU)  # KEEP
    # WARNING: on errror won't be called, but we can't use trap or it will be
    # run again on EXIT or some independent error/etc in inappropriate place
    ${langprev:+$lchg uint32:$langprev}

    [[ $word ]] || return

    # FIXED: accumulate all repeated words (with timestamps) to allow "frecency" statistics
    # grep -qxF "$word" "$fl" || echo "$word" >> "$fl"
    printf '%d\t%s\n' "$(date +%s)" "$word" >> "$fl"

    fvim "$word"
}

fvim() {
    # NEED:ENH: simultaneously translate word and then open vim
    l=${lang:0:1}
    l=${l^^}${lang:1}
    exec st -e v -c "Dict $1" -c 'only' -c "call histadd(':', 'Dict $1')" -c 'silent! /\V\[^\w-]\zs'"$l"'\ze-\%('"$l"'\)\@!'

    # exec r.tf $EDITOR --noplugin -u ~/.vim/rc/basic -c 'setf markdown' <(dict "$word" | r.dict --filter)
    # exec r.tf $EDITOR -c 'setf markdown' <(dict "$word" |& r.dict --filter)
}

fshell() {
    if dict -h localhost -H >/dev/null; then
        dict "$@" |& w3m -T "text/html" | less +/Universal
    else
        dict "$@" |& less "+/$@"
    fi
}

case "$1" in --en|--ru) lang=${1#--}; shift ;; esac
case "$1"
in --debug) dictd -d nofork -d init  ## Server: no demon
;; --dmenu) fdmenu "$@"
;; --vim) shift; fvim "$@"
# TODO: use python/xml instead of pandoc
;; --filter) filter $@ | iconv -t utf-8 | pandoc -f html -t markdown | sed -r 's/(> )+/  /g; /^\s*$/d'
;; *) fshell $@
;; esac
