#!/bin/bash -eu
# tags: media
# deps: xkb
#   => CHG: only optional runtime deps
#   => NEED: pandoc BUT! remove it from runtime
source ~/.shell/func.d/cfgsetup

if distro arch; then
  dir=/etc/dict
elif distro ubuntu; then
  dir=/etc/dictd
fi
# Copy files instead of symlink, as dictd drops to 'nobody' user
#   with no access to my config files inside home directory.
linkcp -ct "$dir" ./cfg/*

# NEED: copy offline dicts first
if cfgOpt r; then
  sudo mkdir -p /usr/share/dictd
  sudo chown "${USER}:users" /usr/share/dictd
  rsync -e ssh -avhP lcloud:/me/_pj-data/dict/dicts/ /usr/share/dictd
fi
./scripts/indexate $(cfgOpt r && echo -r)

# BAD:(-R): always sudo for system services
svc_activate -cer$(cfgOpt uU&&echo R) dictd.service

# if distro ubuntu; then
#   # sudo touch /var/lib/dictd/db.list
#   sudo dictdconfig --write
# fi

# echo 'cd "$HOME/.wine/drive_c/Program Files (x86)/Yarxi" && wine yarxi.exe'\
#     | vienv -r sh ~/.local/bin/r.yarxi

echo "C: 'dict' done"
