#!/bin/bash -e
source ~/.shell/func.d/packages

# TRY:BET:
# Xonsh – put some Python in your Shell | Berkeley Institute for Data Science ⌇⡠⡏⡑⢹
#   DEMO: https://bids.berkeley.edu/events/xonsh-–-put-some-python-your-shell
#   CMP: https://xon.sh/comparison.html
# fish shell ⌇⡠⡏⡒⠄
#   https://fishshell.com/
# ALSO:USE: community/surfraw 2.3.0-3
#     Shell Users' Revolutionary Front Rage Against the Web

pkg_inst zsh

PREZTO=~/.cache/zsh/.zprezto
if [[ ! -d $PREZTO ]]; then
  mkdir -p "${PREZTO%/*}"
  # git clone https://github.com/robbyrussell/oh-my-zsh.git $ZSH_DIR
  url='https://github.com/sorin-ionescu/prezto.git'
  git clone --recursive "$url" "$PREZTO"
fi

# if distro arch; then
#   pkg_inst fasd
# elif distro ubuntu; then
#   do_if -c git_inst -p fasd 'clvv/fasd' ||:
# fi
