#!/usr/bin/zsh -eu
# Minuscule startup time enhancement
# TODO: insert into demons.target.wants/zsh-comp.service
cd ${0%/*}

zdir=$ZDOTDIR
[[ -d $zdir ]] || zdir=~/.cache/zsh
[[ -d $zdir ]] || zdir=$HOME
ZDOTDIR=$zdir

# Refresh commands list from PATH in current shell
rehash

zcompile ~/.zshenv
zcompile $zdir/.zprofile $zdir/.zprofile
zcompile $zdir/.zlogin $zdir/.zlogin

# Combine zshrc components into one file
lst=()
lst+=( $zdir/.{zshrc,zprezto{rc,/init.zsh}} )
lst+=( ./{amer-{widgets,key-mix},filetypes,completion}.zsh )
zcompile $zdir/.zshrc ${lst[@]}

# Compile the completion dump
zcd=$zdir/.zcompdump
if [[ -s $zcd && (! -s ${zcd}.zwc || $zcd -nt ${zcd}.zwc) ]]
then zcompile $zcd; fi

# BAD: it must be compiled only after all mods were setup
# [[ -s ~/.config/airy/aliases ]] && zcompile ~/.config/airy/aliases
