#!/bin/bash -eu
# tags: shell
# deps: git
# DEPR: fully move to DFL=fish / TRY=xonsh,pbpython
source ~/.shell/func.d/cfgsetup

# Choose default shell
# FIXME: pick default shell directly on clean setup
#   => BET: pick current shell by "defaults"
if cfgOpt r; then
  # BAD: when ./setup is called from ranger with SHELL=r.sh
  #   $(which zsh) != ${SHELL:?}
  if has_pr zsh && [[ -z ${SSH_TTY-} ]]; then
    sudo chsh -s /bin/bash  # Root login shell
    sudo usermod -s "$(command -v zsh)" "$(whoami)"  # User shell
  fi
fi

# Main destination for Zsh
mkdir -p "${XDG_DATA_HOME:-$HOME/.local/share}/zsh"
PREZTO=~/.cache/zsh/.zprezto
linkcp "$PWD" "${PREZTO%/*}/cfg"
linkcp -t "${PREZTO%/*}" -p. zlogin zprofile zshrc zpreztorc
if [[ -d $PREZTO ]]; then
  linkcp ./prompt "$PREZTO/modules/prompt/functions/prompt_amer_setup"
  linkcp ./prompt.d "$PREZTO/modules/prompt/functions/prompt.d"
fi

# We must have symlink anyway to keep paths actual
linkcp {,~/.}zshenv
