#!/bin/bash -e
source ~/.shell/func.d/system
cd $(dirname $(readlink -m ${0}))

PREZTO=~/.cache/zsh/.zprezto

# BUG: submodules aren't updated at all!
if [[ " $* " =~ " -u " ]]; then
  (cd "$PREZTO" && git-up &&
    git submodule -q foreach 'echo $path' |
      xargs -r -L1 -P8 /bin/bash -c \
        'cd "$0" && git pull origin master')
  # git submodule update --init --recursive --remote --merge)
fi

./recache
