# vim: ft=zsh
# Executes commands at login pre-zshrc.

if [[ -z ${_ZSH_DONE-} ]]; then
### Temp ###
# CHG:USE:(pam-tmpdir) https://sources.debian.net/src/pam-tmpdir/
#   BUG: sourced only into 'tmux -s $USER' session
#     => $TMPDIR not present in other vte->tmux->xmonad
# MAYBE: use $XDG_RUNTIME_DIR
if ! test -d "${TMPDIR-}"; then
  TMPDIR=/tmp/"${LOGNAME-}"
  mkdir -p -m 700 "$TMPDIR"
  export TMPDIR
fi

## dir for manual experiments
[[ -d /tmp/t ]] || mkdir /tmp/t


### Path ###
# DFL path defined in /etc/profile, package extensions are at /etc/profile.d/*
# TODO: distribute to ./env inside |airy/{ruby,cabal}| similar to /etc/profile.d/*
#   => symlink into ~/.config/airy/env/<group.mod> -- to source by all
# NEW: $(ruby -rubygems -e "puts Gem.user_dir")/bin
hash ruby 2>/dev/null && PATH=$PATH:$(ruby -e 'print Gem.user_dir')/bin
hash cabal 2>/dev/null && PATH=~/.cabal/bin:$PATH
PATH=~/.local/bin:$PATH

# ALT: ~/.ssh/environment + "PermitUserEnvironment PATH">>/etc/ssh/sshd_config
#   BAD:(hardcode): can't extend existing PATH
# [_] TODO: chroot/docker/qemu/vbox -- provide similar clipboard forwarding
[[ -z ${DISPLAY-} && -n ${SSH_CONNECTION+x} && -d /usr/local/libexec/xc ]] && PATH=/usr/local/libexec/xc:$PATH

export PATH
# Deduplicate
# if hash awk 2>/dev/null; then
#   PATH=$(awk -vRS=: '!a[$0]++{printf(NR>1?":%s":"%s"),$a[$1]}' <<<"$PATH")
# fi
fi

## NOTE: use on shared build server
# BAD: can't be placed in .pam_environment
# export TZ=/usr/share/zoneinfo/Europe/Kiev

### Paths ###
# Set the list of directories that Zsh searches for programs.
# path=( $path )
# Set the the list of directories that cd searches.
# cdpath=( $cdpath )
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
