# vim: ft=zsh
# zmodload zsh/zprof  # HACK Profiling
TMPPREFIX="${${TMPDIR:-/tmp}%/}/${SHELL##*/}"

## Add completions and themes from custom place
# fpath=(${ZDOTDIR}/cfg/completion.d $fpath ${ZDOTDIR}/cfg/theme.d)

source ${ZDOTDIR}/cfg/options

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ||:  # Block dirty code in prezto
fi

## workaround for handling TERM variable in multiple tmux sessions
# https://wiki.archlinux.org/index.php/Tmux#Correct_the_TERM_variable_according_to_terminal_type
#  properly by Nicholas Marriott
# if [[ -n ${TMUX} && -n ${commands[tmux]} ]]
# then case $(tmux showenv TERM 2>/dev/null) in
#     *256color) ;&
#     TERM=fbterm) TERM=screen-256color ;;
#     *) TERM=screen
# ;; esac; fi


### Opts ###
## Disable shared history between terminals (auto-importing)
# OR:USE: zle keymap 'set-local-history' to toggle exclusive history movement
# USE: $ fc -RI $ to manually import history from other terminals
setopt nosharehistory
setopt incappendhistory
## Disable suspending on <C-s>, <C-q>
setopt noflowcontrol
[[ $- != *i* ]] || stty stop '' -ixoff -ixon
## Lets files beginning with a . be matched without explicitly specifying the dot
setopt globdots
# setopt hist_ignore_space  # Already set?


### User Cfg ###
# You will see errors in tty if one of them is not found:
# source ~/.shell/env  # FIXME: must be already sourced through .zprofile/.zshenv, but is not!
source ${ZDOTDIR}/cfg/modules/gpg.zsh
source ${ZDOTDIR}/cfg/amer-widgets.zsh
source ${ZDOTDIR}/cfg/amer-key-mix.zsh
source ${ZDOTDIR}/cfg/filetypes.zsh
source ${ZDOTDIR}/cfg/completion.zsh
source ~/.shell/common
# zprof  # HACK Profiling

# Freciency completions and preexec (man fasd)
# WARNING: quotes are essential!
# (( ! $#commands[fasd ] )) || eval "$(fasd --init auto)"

((!_perf_enable)) || source r.sh-perf-trace
