#!/bin/bash -e
source ~/.shell/func.d/packages

#| cups-pdf  | virtual pdf printer

# mutagen | convert mp3 tags to utf8
# find ./ -iname "*.mp3" -print0 | xargs -0 mid3iconv -eCP1251 --remove-v1 -d

# fbreader
pkg_inst -p 'dot' graphviz
pkg_inst -p 'mogrify' imagemagick
pkg_inst -d '/usr/lib/cups' cups-pdf
# libmagick++-dev

if distro arch; then
    # Compress fb2 to zip
    # pkg_inst zip
    # find . -name '*.fb2' -exec zip {}.zip {} \;
    aur_inst fbless
    pkg_inst pandoc

elif distro ubuntu; then
    git_inst 'matimatik/fbless'
fi

## DEPRECATED: by 'tr ...'
# wget_inst 'http://www.andre-simon.de/zip/ansifilter-1.10.tar.gz'
## DISABLED: Can't compile by the reason of <lua.hpp> is inside its own directory...
# wget_install 'http://www.andre-simon.de/zip/highlight-3.19.tar.gz'
