#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
  pkg_inst tcpdump sslsplit  # mitmproxy
  pkg_inst wireshark-cli
  pkg_inst wireshark-qt

elif distro ubuntu; then
  echo "Err: fixme"
fi
