#!/bin/bash -e
# tags: re
source ~/.shell/func.d/cfgsetup

### LINKS ###
# linkcp -t ~/.wireshark preferences
# ALSO: disabled_protos hosts subnets ethers manuf services ipxnets

id | grep -qwF wireshark || sudo gpasswd -a "${LOGNAME:?}" wireshark
