#!/bin/bash -e
source ~/.shell/func.d/packages
has_pr X || die

if distro arch; then
    # USE:CHECK:(audio call): skypeforlinux-bin
    aur_inst skypeforlinux-bin
    # OBSOLETE: multilib only DEPS: lib32-qt4 NEED: paci lib32-openssl100
    #   aur_inst skype
    # DEPRECATED: sni-qt  # tray icon for skype
    # OBSOLETE:(cfg/media/pidgin already installed skypeweb plugin)
    #   aur_inst skype4pidgin-git'

elif distro ubuntu; then
    # Чтобы не возникало проблем с установкой, нужно установить некоторые 32-битные библиотеки:
    pkg_inst sni-qt:i386 libdbusmenu-qt2:i386 libqt4-dbus:i386 libxss1:i386
    # Чтобы не было проблем с темами оформления Skype, нужно обязательно доставить
    # следующие 32 - битные пакеты и тогда Skype будет выглядеть нормально:
    pkg_inst libgtk2.0-0:i386 gtk2-engines:i386 libgconf-2-4:i386
    pkg_inst pidgin-skype
    if ! has_pr skype || cfgOpt u; then
        sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"
        sudo apt-get update
        sudo apt-get install skype
    fi
fi
