#!/bin/zsh -eu
[[ -t 0 ]] || exit 0

IFS='[;'
print -n '\e7\e[r\e[999;999H\e[6n\e8'
read -sd R escape geometry

x=${geometry##*;} y=${geometry%%;*}
if [[ ${COLUMNS} -eq ${x} && ${LINES} -eq ${y} ]];then
  print "${TERM} ${x}x${y}"
else
  print "${COLUMNS}x${LINES} -> ${x}x${y}"
  stty cols ${x} rows ${y}
fi
