#!/bin/bash
set -euo pipefail

src=${1:-}
dst=${2:-_deps}
libs=$dst/libs-inner
ext=$dst/libs-external
syms=$dst/sym.all

ignore=( _Unwind_Resume )
ignore=$(IFS=$'|'; printf '%s\n' <<< "${ignore[*]}")
ignore="^($ignore)$"

mkdir -p "$dst"
# -o | to search obj files
[[ -s $libs ]] || r.find-elf -abs -- "$src" > "$libs" \
  || printf 'Err: *.a/*.so binaries not found\n' >&2

[[ -s $ext  ]] || r.find-elf -bs -- "$src" | xargs -rn1 -P$(nproc) \
  ldd | awk '$3{print$3}' | LC_ALL=C sort -u > "$ext" \
  || printf 'Err: seems like ldd error\n' >&2

## THINK: ignore $5=="WEAK" bind ???
if [[ ! -f $dst/_gen_syms ]]; then
  mkdir -p "$dst/sym" "$dst/und"
  while IFS= read -r p; do
    printf '* (syms) %s\n' "$p" >&2
    readelf -Ws -- "$p" | gawk -vignore="$ignore" '
      !$8 || $8 ~ ignore"" {
        next
      }
      $5=="GLOBAL" && $6=="DEFAULT" && $7=="UND" {
        print $8 > "/dev/stderr"; next
      }
      $4=="FUNC" || $4=="OBJECT" || $4=="TLS" {
        print $8
      }
    ' > >(LC_ALL=C sort -u > "$dst/sym/${p##*/}") \
    2> >(LC_ALL=C sort -u > "$dst/und/${p##*/}")
  done < <(cat "$libs" "$ext")
  touch "$dst/_gen_syms"
fi

[[ -s $syms ]] || find -H "$dst/sym" -type f -exec cat {} \+ \
  | LC_ALL=C sort -u > "$syms"

if [[ ! -f $dst/_gen_need ]]; then
  mkdir -p "$dst/stat"
  while IFS= read -r p; do
    [[ -s $p ]] || continue
    printf '* (need) %s\n' "$p" >&2

    d=$dst/need/${p##*/}
    mkdir -p "$d"
    grep -rHxFf "$p" \
      --include '*.a' --include '*.a.*' \
      --include '*.so' --include '*.so.*' \
      --include '*.o' "$dst/sym" \
    | awk -F'[:/]' -vd="$d" '{print$NF > d"/"$(NF-1)}' \
    || printf '!!! (empty) %s\n' "$p" >&2

    st=$dst/stat/${p##*/}
    find -H "$d" -type f -print0 \
    | wc -l --files0-from=- \
    | awk -F'/|\\s' '{print$1"\t"$NF}' \
    | sort -k1rn,1 \
    | tail -n +2 \
    > "$st"

    if [[ ! -s $st ]]; then
      printf '!!! (notfound) %s\n' "$p" >&2
      mkdir -p "$dst/notfound"
      { echo "$p"
        grep -vxFf "$syms" -- "$p" \
        | tee "$dst/notfound/${p##*/}" \
        | sed 's/^/\t/'
      } >&2
    fi
  done < <(find -H "$dst/und" -type f -print)
  touch "$dst/_gen_need"
fi

## DEBUG
# grep -rxFf "$dst"/und/libWavePlayerConfig.a \
#   --include '*.a.*sym' \
#   --include '*.o.*sym' \
#   --include '*.so.*sym' "$dst"
