#!/bin/bash -e
# tags: net
source ~/.shell/func.d/cfgsetup

### GENS ###
./config.gen

# http://docs.syncthing.net/users/autostart.html#systemd
svc_activate -e$(cfgOpt uU&&echo R) syncthing{,-inotify}@"${USER:?}"
