#!/bin/bash -e
# tags: net
source ~/.shell/func.d/cfgsetup

### GENS ###
./config.gen

if cfgOpt u; then
  # http://docs.syncthing.net/users/autostart.html#systemd
  svc_activate -er syncthing{,-inotify}@${USER:?}
fi
