#!/bin/sh

case $BLOCK_BUTTON in
    1) ;;
    3) ;;
    *) ;;
esac

# Show in Braile format
L=$(xset -q | sed -n '/.*LED mask:\s*/s//0x/p')
LED=$(( 0x2800 + 0x1*(L&0x1) | 0x2*(L&0x400) | 0x4*(L&0x2) | 0x8*(L&0x4) |
        0x10*(L&0x8) | 0x20*(L&0x100) | 0x40*(L&0x800) | 0x80*(L&0x1000) ))
LED=$(printf "%x" "$LED")

case "${INDEX}" in
    0) clr="#00AE00" ;;
    1) clr="#009EAF" ;;
    2) clr="#FFAA00" ;;
    *) clr="#C60101" ;;
esac

printf "\u$LED\n\u$LED\n$clr\n"
