#!/bin/bash -eu

pj=${1:-${PWD##*/}}
d=${2:-_build-doxygen}
cfg=$d/Doxyfile

# Generate default config, [-s]-key removes comments from it
mkdir -p _doxygen
rm -f "$cfg" && doxygen -g "$cfg"

## ALT: chg() { sed "s@\(^$1[ ]*=[ ]*\).*@\1 $2@g" -i "$cfg"; }
# BAD: fields must be split on first FS only
#   gawk -i inplace -vFS='\s*=\s*' -vOFS=' = ' -vk="$1" -vv="$2" '$1==k{$2=v}1' "$cfg"

chg() { command perl -i -wslpe 's/^($k\s*=\s*).*/$1$v/' -- -k="$1" -v="$2" "$cfg"; }
chgq() { chg "$1" "\"$2\""; }

# Project sets
chgq PROJECT_NAME     "${PWD%/*}"
chgq PROJECT_NUMBER   "$(git --no-pager log --pretty=format:'%ad' --date=short -1)"
#chgq INPUT            "inc src"
chgq OUTPUT_DIRECTORY "$PWD/_doxygen"
chgq WARN_LOGFILE     "warnings.log"
chg TAB_SIZE          4
# chg INPUT             ../

# Additional sets
chg RECURSIVE               YES
chg SOURCE_BROWSER          YES
chg SEARCHENGINE            NO
chg GENERATE_LATEX          NO
chg GENERATE_TREEVIEW       YES
chg OPTIMIZE_OUTPUT_FOR_C   YES
chg REFERENCED_BY_RELATION  YES
chg REFERENCES_RELATION     YES

chg EXTRACT_STATIC          YES
# HTML_EXTRA_STYLESHEET  = stylesheet.css
# HTML_TIMESTAMP         = YES
# GENERATE_HTMLHELP      = YES
# CHM_FILE               = ../documentation.chm
# HHC_LOCATION           = "c:\Program Files (x86)\HTML Help Workshop\hhc.exe"
# GENERATE_LATEX         = NO
## BAD: can't replace multiline value
# FILE_PATTERNS        *.c *.cpp *.h *.hpp
# EXCLUDE_PATTERNS       = */.svn/* */include/* */tests/* */sources/*

# chg EXCLUDE_PATTERNS   "$PWD/build/* $PWD/libs/*"

exec doxygen "$cfg"
