#!/bin/bash -eu
source ~/.shell/func.d/packages

pkg_inst weechat

# MOVE: create "aspell" *mod*, add it as "deps:"
pkg_inst aspell aspell-en aspell-ru aspell-uk

url_wget_to ~/.weechat/python/autoload -- \
  'https://raw.githubusercontent.com/keith/edit-weechat/master/edit.py'
