#!/bin/bash -eu
# tags: net chat
source ~/.shell/func.d/cfgsetup

### MANUAL ###
# /secure passphrase ********
# /secure set znc_user xxxxxxxx
# /secure set znc_pass ********
# /secure set bitlbee_pass ********


### GENS ###
if cfgOpt u; then
  ./exe/configure -- "${WEECHAT_LIST[@]:?}"
fi

# WARN: will break on clean install
linkcp -m ~/.weechat/logs ~/chat/weechat
