#!/bin/bash -eu
# tags: net chat
source ~/.shell/func.d/cfgsetup

### GENS ###
# WARN: will break on clean install (must store bunch of "chat/*" passwords beforehand)
if cfgOpt u; then
  ./exe/configure -- "${WEECHAT_LIST[@]:?}"
fi

linkcp -m ~/.weechat/logs ~/chat/weechat
