#!/bin/bash -e
source ~/.shell/func.d/packages
# Read commands from standard input or a specified file
# which are to be executed at a later time, using /bin/sh.

## ALT(r.wgetf):BET:USE: separate queueing mechanics
# leahneukirchen/nq: Unix command line queue utility ⌇⡠⡏⡈⣃
#   https://github.com/leahneukirchen/nq
# community/pueue 0.12.0-2
#     A command scheduler for shells
## IDEA:DEV: auto-enqueue all running commands
# NEED: detect switching to "cursor addressing mode" i.e. "set private mode" :: {47,1047,1048,1049}
#   escape characters - How do some tools (e.g. nano , less) manage to leave no content in terminals after exit? - Unix & Linux Stack Exchange ⌇⡠⡏⡼⣂
#     https://unix.stackexchange.com/questions/336609/how-do-some-tools-e-g-nano-less-manage-to-leave-no-content-in-terminals-aft
#     << same can be used to detect non-TUI app and store per-command output history
#       BET: maybe it's easier to save directly from the st(1) buffer, than to redirect from shell and ensure [[ -t 1 ]] == true

# VIZ: at atd atq atrm atrun batch
pkg_inst at
