#!/bin/bash -e
cd $(dirname $(readlink -m ${0}))

### LINKS ###
link(){ [[ ! -e $2 || -L $2 ]] && ln -sfvT "$1" $2; }
link "$PWD" ~/.vim  #vim/vimrc vim/nvimrc vim/ycm_extra_conf.py


VCACHE="$HOME/.cache/vim"  # Dir for .swp, backup, ... files
FONT="$VCACHE/powerline-fonts/DejaVuSansMono"
mkdir -p "$VCACHE"

### THEMES ###
case "$1" in
--clean) rm -rf "$VCACHE" ;;
-u|--update) update="$1" ;;
esac


### SPELL ###
if [[ ! -d "$VCACHE/spell" ]]; then
    mkdir -p "$VCACHE/spell"
    src='http://ftp.vim.org/pub/vim/runtime/spell'
    for nm in ru en uk; do ( cd "$VCACHE/spell"
        wget "$src/${nm}.utf-8.spl" && wget "$src/${nm}.utf-8.sug"
    ) done
fi
# For vim-easytags
#touch ~/.vimtags


### FONTS ###
# https://powerline.readthedocs.org/en/latest/installation/linux.html
if [[ ! -f ~/.fonts/PowerlineSymbols.otf ]]; then
    mkdir -p ~/.fonts/
    # See: https://wiki.archlinux.org/index.php/Font_Configuration
    cp ~/.vim/res/PowerlineSymbols.otf ~/.fonts/
    mkdir -p ~/.config/fontconfig/conf.d/
    cp ~/.vim/res/10-powerline-symbols.conf ~/.config/fontconfig/conf.d/
    fc-cache -vf ~/.fonts
    echo "Powerline symbols configured"
fi

if [[ ! -d ~/.fonts/"${FONT##*/}" ]]; then
    # Patched fonts for windows usage:
    src='https://github.com/Lokaltog/powerline-fonts'
    [ ! -d "${FONT%/*}" ] && git clone --depth=1 "$src" "${FONT%/*}"
    cp -urft ~/.fonts "$FONT"
    fc-cache -vf ~/.fonts  # check active name with fc-list
    echo "Vim font '${FONT##*/}' installed"
fi


### PLUGINS ###
if [[ ! -d "$VCACHE/bundle" || -n "$update" ]]; then
    vim -E -X -R -i NONE -c "set nomore" +NeoBundleClearCache +NeoBundleUpdate +qall
    sudo pip install --upgrade pip -U jedi
fi
