#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
  # aur_inst gcalcli
  # BAD:(gcalcli-git): OAuth2 don't start automatically
  # BAD:(gcalcli-git): can't add events beside 'Quick'
  # aur_inst gcalcli-git

  loc_inst -P 'gcalcli-airy-git' ./PKGBUILD  # v4.0a2

  aur_inst python2-vobject
  pkg_inst python2-parsedatetime

elif distro ubuntu; then
  echo "Err: fix use pip2"
fi
