#!/bin/bash -eu
source ~/.shell/func.d/system
opts=(
  --noincluderc
  # --configFolder=work
  --defaultCalendar='work'
  # BAD: need to copy-paste link on oauth expired
  --noauth_local_webserver
)
exec gcalcli "${opts[@]}" "$@"
