#!/bin/bash -e
# tags: xorg
# deps: xorg
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

### LINKS ###
dst=~/.config/stalonetrayrc
linkcp -c stalonetrayrc "$dst"

dpi=$(r.airy-registry dpi 96)
iw=$(( dpi * 9/72 + 2 ))
sed -ri '
  /^(icon_size).*/s//\1 '$iw'/
' "$dst"
