#!/usr/bin/python
import sys
from mimetypes import guess_type

print(sys.argv[1])
print(guess_type(sys.argv[1]))


try:
    print(__import__("magic").detect_from_filename(sys.argv[1]).mime_type)
except ModuleNotFoundError:
    pass
