#!/bin/bash -e
source ~/.shell/func.d/packages

#| mutt    | console mail client
#| neomutt | mutt with many patches

if distro arch; then
  pkg_inst isync notmuch
  aur_inst -p 'mutt' neomutt
  aur_inst imapfilter

elif distro ubuntu; then
  pkg_inst 'mutt'
fi
