#!/bin/bash -e
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

### LINKS ###
link "$PWD" ~/.mutt
mkdir -p "${CURR_DIR_MAIL:?}"
[[ $CURR_DIR_MAIL -ef ~/.mail ]] || link "$CURR_DIR_MAIL" ~/.mail

### GENS ###
THEME=$THEME ./gen/theme-solarized.gen

dst=~/.mbsyncrc
> "$dst"
for creds in "${MAIL_CREDS[@]}"
do ./gen/mbsyncrc.gen "$dst" ${creds:?}; done

# USAGE: mbsync '$mid' OR mbsync -a
