#!/bin/bash -e
# tags: term
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

### LINKS ###
linkcp "$PWD" ~/.mutt
linkcp ./cfg/theme-$THEME ~/.cache/mutt/theme

dst=~/.cache/mutt
(cd "$dst" && ln -svf "acc/${MUTT_DEFAULT:?}" default)

# Relocate ~/.mail if necessary
# FIND:WTF: $MAIL = /var/spool/mail/dkolomoiets
#   CHECK: use $MAIL instead of $CURR_DIR_MAIL ?
mkdir -p "${CURR_DIR_MAIL:?}"
[[ $CURR_DIR_MAIL -ef ~/.mail ]] || linkcp "$CURR_DIR_MAIL" ~/.mail


### GENS ###
# THEME=$THEME ./gen/theme-solarized.gen

# Gen accounts list to switch
k=0; echo '# vim:ft=muttrc' > "$dst/index"
for p in "$dst/acc"/*; do [[ -s $p ]] || continue
  ((k+=1))
  cat>> "$dst/index" <<EOT
set my_acc=${p##*/} my_key=<F$k>
source \$my_cfg/accrc
EOT
done


# THINK:MAYBE: write config by hands instead of generation?
# USAGE: mbsync '$mid' OR mbsync -a
# ATT: place at bottom
# dst=~/.mbsyncrc
# > "$dst"
# for creds in "${MAIL_CREDS[@]}"
# do ./gen/mbsyncrc.gen "$dst" ${creds:?}; done
# THEN: notmuch setup; notmuch new
