#!/bin/bash -eu
# tags: core
source ~/.shell/func.d/cfgsetup

# cfgOpt r && ./init.gen

linkcp -ct '/etc/systemd/system/snapper-cleanup.timer.d' unit/override-cleanup.conf

## NOTE: snaper-boot snapshots only ROOT -- but I have only HOME on laptop
[[ $CURR_PROF =~ ^neo ]] || svc_activate -er snapper-boot.timer

svc_activate -er snapper-{cleanup,timeline}.timer
