#!/bin/bash -e
source ~/.shell/func.d/packages

# need for opening video by mpv in qutebrowser
# TRY:ALT: https://you-get.org/ | https://github.com/soimort/you-get
pkg_inst youtube-dl

# REF: https://github.com/cdown/yturl
# USAGE: $ mpv "$(yturl 'http://www.youtube.com/watch?v=8TCxE0bWQeQ')"
#   e.g. http://r2---sn-uphxqvujvh-30al.googlevideo.com/videoplayback?source=[...]
aur_inst yturl
