#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
  # need for opening video by mpv in qutebrowser
  # TRY:ALT: https://you-get.org/ | https://github.com/soimort/you-get
  pkg_inst youtube-dl

elif distro ubuntu; then
  echo "Err: no"
fi
