#!/bin/bash -eu
# tags: dev
source ~/.shell/func.d/cfgsetup

# Prune btrfs snapshots by Snapper
if ! grep -q '^PRUNENAMES\b.*\s.snapshots\b' /etc/updatedb.conf; then
  sudo sed -ri '/^(PRUNENAMES = "[^"]+)"/s||\1 .snapshots"|' /etc/updatedb.conf
fi

# Prune work dir -- because it can contain too many src files
if ! grep -q '^PRUNEPATHS\b.*\s/work\b' /etc/updatedb.conf; then
  sudo sed -ri '/^(PRUNEPATHS = "[^"]+)"/s||\1 /work"|' /etc/updatedb.conf
fi

# MAYBE: use something more granular e.g. /data/_work/{cache,repo}
# BUT: having search for source files is also nice (BUT slow)
if ! grep -q '^PRUNEPATHS\b.*\s/data/_work\b' /etc/updatedb.conf; then
  sudo sed -ri '/^(PRUNEPATHS = "[^"]+)"/s||\1 /data/_work"|' /etc/updatedb.conf
fi
