#!/bin/bash -e
# tags: dev
source ~/.shell/func.d/cfgsetup

# Prune btrfs snapshots by Snapper
if ! grep -q '^PRUNENAMES\b.*\s.snapshots\b' /etc/updatedb.conf; then
  sudo sed -ri '/^(PRUNENAMES = "[^"]+)"/s||\1 .snapshots"|' /etc/updatedb.conf
fi

# Prune work dir -- because it can contain too many src files
if ! grep -q "^PRUNEPATHS\b.*\s${CURR_DIR_WORK:?}\b" /etc/updatedb.conf; then
  sudo sed -ri '/^(PRUNEPATHS = "[^"]+)"/s||\1 '"${CURR_DIR_WORK:?}"'"|' /etc/updatedb.conf
fi

cfgNo u || fork_m sudo updatedb
