#!/bin/bash -e
# tags: term
# deps: diff vim wget
source ~/.shell/func.d/cfgsetup

cfgNo c || git clean -Xdi -- "$PWD"

## init
# git clone --depth=1 https://github.com/alexanderjeurissen/ranger_devicons /@/airy/ranger/plugins/ranger_devicons

### LINKS ###
linkcp "$PWD" ~/.config/ranger
# FIXME: remove "inetutils/hostname" package
linkcp "/@/items/${HOSTNAME:?}/ranger/" ~/.local/share/ranger
linkcp {,~/.}mime.types
