# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
export SHELL=$BASH  # NEED: when bash run from zsh

# If not running interactively, don't do anything
[[ $- == *i* ]] || return

# NOTE: syntax highlighting and auto-suggestions in !bash
# REF: https://github.com/akinomyoga/ble.sh
source /d/plugins/zsh/ble.sh/out/ble.sh --noattach

# BUG: cd has errors -- when '$ cd' in bash
# BUG: bash can't '.a' to jump between dirs

[[ -d ${TMPDIR:=/tmp} ]] || mkdir -p "$TMPDIR"
TMPPREFIX=${TMPDIR%/}/${SHELL##*/}

## SRC
# https://askubuntu.com/questions/391082/how-to-see-time-stamps-in-bash-history
# https://www.networkworld.com/article/2923844/bash-history-remembering-what-you-did-and-when-you-did-it.html
# HISTTIMEFORMAT=': %s:0;'
# HISTTIMEFORMAT='%s '

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# SRC: https://askubuntu.com/questions/67283/is-it-possible-to-make-writing-to-bash-history-immediate
# OR:(ble.sh): bleopt history_share=1
#   https://github.com/akinomyoga/ble.sh/issues/457
PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND-}"

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=10000
HISTFILESIZE=10000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
[[ $DISPLAY ]] && shopt -s checkwinsize

# Expand aliases to be available in scripts
# shopt -s expand_aliases

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# Disable old suspend-continue behaviour on C-s, C-q to intoduce forward-search
# http://unix.stackexchange.com/questions/12107/how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal/12108#12108
# to enable: stty ixany
stty -ixon
# Don't insert ^C in commandline
stty -echoctl

# make less more friendly for non-text input files, see lesspipe(1)
# [[ -x /usr/bin/lesspipe ]] && eval "$(SHELL=/bin/sh lesspipe)"

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [[ -r /usr/share/bash-completion/bash_completion ]]; then
    source /usr/share/bash-completion/bash_completion
  fi
fi

# turn on directory spelling typos automagic
shopt -s cdspell

# Enable xsel to copy current cmdline/output (like in zsh)
# NOTE: xsel-remote works even w/o $DISPLAY set
_xc_copy_cmdline(){ xci <<< "${READLINE_LINE:-$(fc -ln -1)}"; }
_xc_copy_output(){ xci <<< "$(eval $(fc -ln -1) 2>/dev/null)"; }
bind -x '"\C-y": _xc_copy_cmdline'
bind -x '"\C-o": _xc_copy_output'

# See /usr/share/doc/bash-doc/examples in the bash-doc package.

BASH_AIRY=$(readlink -e "$BASH_SOURCE")
BASH_AIRY=${BASH_AIRY%/*}
source "$BASH_AIRY/prompt"
# source ~/.shell/common

# [⡣⢴⢄⡭] FIXED:BUG disable blinking cursor after exiting !nvim
# export PROMPT_COMMAND='echo -en "\e[2 q"'

[[ ! ${BLE_VERSION-} ]] || ble-attach
