#!/bin/bash -eu
# tags: mod
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

# ALT:(r.color-*): https://github.com/sharkdp/pastel
# aur_inst pastel

### LINKS ###
linkcp "cfg/dircolors-${THEME}.ansi" ~/.config/dircolors
