#!/bin/bash -eu
# tags: mod
THEME_ALLOWED='dark|light'
source ~/.shell/func.d/cfgsetup

# ALT:(r.color-*): https://github.com/sharkdp/pastel
# aur_inst pastel

### LINKS ###
linkcp "cfg/dircolors-${THEME}.ansi" ~/.config/dircolors

# How to disable/enable colored journalctl output? : archlinux ⌇⡠⡇⡶⠵
#   https://www.reddit.com/r/archlinux/comments/m03jbm/how_to_disableenable_colored_journalctl_output/
#   "grc" is faster than "ccze"
