#!/bin/bash -eu
set -euo pipefail

# TODO: don't resize display
#   * resize if eDP1 (laptop only)
#   * don't resize if multi-monitor
#   * OR: resize only targeted monitor
#   * resize choosen monitor on demand
#     => MAYBE: resize current monitor where mouse/keyboard focus lays (when you run M-i-g)
#   * auto-choose correct mode 1280x768 or 1280x800 depending on monitor when r.video-resize 1/2/3

lib=~/.config/airy/game
on_exit=('r.video-single 1')

choose(){ dmenu -p 'Play me:' -fn monospace:size=10
     -nb '#000000' -nf '#b0e0e6' -sb '#227410' -sf '#ccaa00'; }

overlay(){ local nm=$1
  # DEV: separate overlays to be provided directly by wrapper in $config/games
  #   FIND: setxkbmap append sep file or at least dir.
  if r.xkb-has-overlay "$nm"; then
    r.xkb "$nm" && xkbset ov1
    on_exit+=('xkbset -ov1' 'r.xkb')
  fi
}

game(){ [[ -n $1 ]] || exit; nm=$1
  overlay "$nm";
  cmd=$lib/$nm
  [[ -f $cmd ]] || { r.n 'No such game' "$cmd"; exit 1; }
}

if (($#)); then case $1
  in -p) shift; game "$(cd "$lib" && ls | choose)"
  ;; -n) shift; game "$1"
  ;;  *) exit 1
esac; else
  nm=playonlinux
  cmd=( primusrun "$(which "$nm")" )
  if (( "$(r.xorg -d)" > 141 )); then
    on_exit+=('xrdb -load ~/.Xresources')
    xrdb -DDPI=141 -load ~/.Xresources
    # ALT: echo Xft.dpi: 144 | xrdb -merge
  fi
  r.video-single 2
fi

# CHECK: called only one trap or sometimes multiple of them?
onexit(){ for c in "${on_exit[@]}"; do eval "$c"; done; }
trap 'onexit' HUP INT QUIT ILL TRAP KILL BUS TERM EXIT ERR

# TODO: query and return to current wksp on exit
r.wm -w g  # Jump to game workspace
"${cmd[@]}"
