#!/bin/bash -e
source ~/.shell/func.d/packages

# CHECK:(alternatives)
#   https://wiki.archlinux.org/index.php/Desktop_notifications

# from j4tools for i3 -- notifier in top-right corner
pkg_inst "dunst"
