#!/bin/bash -e
source ~/.shell/func.d/packages

#| dunst          | from j4tools for i3 -- notifier in top-right corner
#| libnotify-bin  | notifier in window for long running commands (see bashrc) like $ sleep 10; alert

pkg_inst "dunst libnotify-bin"
