#!/bin/bash -e
source ~/.shell/func.d/packages

#| dunst     | from j4tools for i3 -- notifier in top-right corner
#| libnotify | notifier in window for long running commands (see bashrc) like $ sleep 10; alert

pkg_inst "dunst"

if distro arch; then
    LST="libnotify"
elif distro ubuntu; then
    LST="libnotify-bin"
fi

pkg_inst -p 'notify-send' $LST
