#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

## To disable default notification daemon on Lubuntu
# XFCE=/usr/share/dbus-1/services/org.xfce.xfce4-notifyd.Notifications.service
# [[ -f "$XFCE" ]] && sudo mv -n $XFCE{,.disabled}

### LINKS ###
link "$PWD/dunstrc" ~/.config/dunst/dunstrc
link "$PWD/notify" "$CURR_CACHE/bin/notify"
