#!/bin/bash -e
# tags: vcs
source ~/.shell/func.d/cfgsetup

### GENS ###
dst=~/.hgrc
> "$dst"
if [[ ${WORK_NAME:=${MAIN_NAME-}} ]] \
&& [[ ${WORK_MAIL:=${MAIN_MAIL-}} ]]; then
  printf "[ui]\nusername=%s <%s>\n\n" "$WORK_NAME" "$WORK_MAIL" >> "$dst"
fi
cat ./hgrc >> "$dst"

echo "W: ~/.hgrc"
