#!/bin/bash -e
source ~/.shell/func.d/packages
# Newest version compilation (it has working lyrics, etc)
#   http://crunchbang.org/forums/viewtopic.php?id=37882

if distro arch; then
    pkg_inst ncmpcpp

elif distro ubuntu; then
    pkg_inst "automake libtool libboost-all-dev libmpdclient-dev libncurses5-dev
                libncursesw5-dev libfftw3-dev libreadline-gplv2-dev
                libcurl4-gnutls-dev libtag1-dev"  #libreadline-dev

    git_inst -d "arybczak/ncmpcpp"

    dir="${CURR_DIR_PKG?No}/ncmpcpp/"

    # Reason for the above is that debian / ubuntu based distros no longer have the
    # -mt suffix for boost libraries
    # sed -i "s/^\(AS_IF\|AC_ARG_VAR\)(/# \1(/" "$dir/configure.ac"

    # ABSENT: tag editor, tiny tag editor, artist info
    pkg_build "$dir" --enable-outputs --enable-visualizer --enable-clock \
            --enable-unicode --with-fftw --with-curl --with-taglib
fi
