#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

### LINKS ###
linkdir ~/.ncmpcpp/ config bindings
# EXPL: playlists can't be grouped in subfolders:(
cd ./radio && linkdir ~/.mpd/playlists/ *


# MOOD:  http://8tracks.com/explore/anime
# loadsongs() { sed 's/\s*#.*$//; /^\s*$/d' | while read song; do
#     { mpc playlist -f "[%file%]" | grep -q "$song"; } || mpc load "$song"
# done; }
