#!/bin/bash -e
cd $(dirname $(readlink -m ${0}))

### LINKS ###
link(){ [[ ! -e $2 || -L $2 ]] && mkdir -p ${2%/*} && ln -sfvT "$1" $2; }

link "$PWD/config" ~/.ncmpcpp/config
link "$PWD/bindings" ~/.ncmpcpp/bindings
