#!/bin/bash
cd $(dirname $(readlink -m ${0})) || exit

### LINKS ###
link(){ [[ ! -e $2 || -L $2 ]] && ln -sfvT "$1" $2; }

dir=~/.config/ncmpcpp && mkdir -p $dir
link "$PWD/config" "$dir/config"
link "$PWD/bindings" "$dir/bindings"
