" vim:ts=2:sw=2:sts=2
set fileformats=unix,dos,mac
if has("multi_byte")
  if &termencoding == "" | let &termencoding = &encoding | endif
  set encoding=utf-8
  setglobal fileencoding=utf-8
  set fileencodings=utf-8,cp1251,cp866
endif

fun! s:cfg(path)
  execute 'source' fnameescape(expand($VIMHOME .'/cfg/'. a:path))
endf

com! -nargs=1 Silent | exe ':silent !'.<q-args> | exe ':redraw!'

call s:cfg('detect')
call s:cfg('env')
call s:cfg('init')

fun! SourcePlugins()
  let g:mapleader="\\"
  call s:cfg('plugins/backslash.vim')
  " let g:mapleader=" "
  " call s:cfg('plugins/space.vim')
  let g:mapleader=","
  call s:cfg('plugins/autocomplete.vim')
  call s:cfg('plugins/comma.vim')
  call s:cfg('plugins/integration.vim')
  call s:cfg('plugins/languages.vim')
  call s:cfg('plugins/search.vim')
  call s:cfg('plugins/operators.vim')
  call s:cfg('plugins/decoration.vim')
endf
call s:cfg('neobundle.vim')

" syntax enable

let mapleader=","
runtime! bundle/*.vim

" call s:source_rc('encoding.rc.vim')
" call s:source_rc('edit.rc.vim')
" call s:source_rc('view.rc.vim')
" call s:source_rc('filetype.rc.vim')
" call s:source_rc('mappings.rc.vim')

" " Display diff with the file.
" command! -nargs=1 -complete=file Diff vertical diffsplit <args>
" " Disable diff mode.
" command! -nargs=0 Undiff setlocal nodiff noscrollbind wrap

call s:cfg('diff.vim')
call s:cfg('fold.vim')
call s:cfg('format.vim')
call s:cfg('func-compile.vim')
call s:cfg('func-insert.vim')
call s:cfg('grep.vim')
call s:cfg('keys-func.vim')
call s:cfg('keys-remap.vim')
call s:cfg('keys-toggle.vim')
call s:cfg('locale.vim')
call s:cfg('mng-buffers.vim')
call s:cfg('mng-copy-paste.vim')
call s:cfg('mng-files.vim')
call s:cfg('search-replace.vim')
call s:cfg('term-conf.vim')
call s:cfg('ui-colors.vim')
call s:cfg('ui.vim')

" call s:source_rc(IsWindows() ? 'windows.rc.vim' : 'unix.rc.vim')
" call s:source_rc(has('gui_running') ? 'gui.rc.vim' : 'term.rc.vim')
" call s:source_rc(has('nvim') ? 'neovim.rc.vim' : 'vim.vim')

" " Default home directory.
" let t:cwd = getcwd()

augroup MyAutoCmd
  " Open at last position
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
        \| exe "normal g'\"" | endif
augroup END

" Exec .vimrc in curr dir, but deny itc :autocmd, :shell and :write cmds
set exrc secure modeline  " also parse 'vim:...' cmds from comments
if has('cryptv')  " USE blowfish2: https://dgl.cx/2014/10/vim-blowfish
  " set cryptmethod=blowfish2   " It seems +15ms overhead.
endif
" SEE loadorder of *.vim by :scriptnames
