#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

## Downloaders
# https://github.com/squizduos/ReadMangaDownloaderGUI/releases

### LINKS ###
linkcp -bct ~/.config/mcomix ./keybindings.conf
linkcp -bct ~/.config/mcomix ./preferences.conf
