#!/bin/bash -e
source ~/.shell/func.d/cfgsetup

## Downloaders
# https://github.com/squizduos/ReadMangaDownloaderGUI/releases

### LINKS ###
link -t  ~/.config/mcomix ./keybindings.conf
link -ct ~/.config/mcomix ./preferences.conf
