#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
    echo 'N: TODO: aur: override compiling by make -j8 using env vars'
    aur_inst copyq-git  # NOTE: copyq -- tag <=2.5.0 is w/o my enhances

elif distro ubuntu; then
    # libxtst-dev (optional; auto-paste into some applications),
    pkg_inst libqt4-dev libxfixes-dev libxtst-dev \
                libxinerama-dev libqtwebkit-dev
    git_inst 'hluk/CopyQ'
fi
