#!/bin/bash -e
source ~/.shell/func.d/packages

if distro arch; then
  # NOTE: copyq -- tag <=2.5.0 is w/o my enhances
  # aur_inst copyq-git   # FIXME:(upstream): makedeps+=qt5-x11extras
  pkg_inst copyq

elif distro ubuntu; then
    # libxtst-dev (optional; auto-paste into some applications),
    pkg_inst libqt4-dev libxfixes-dev libxtst-dev \
                libxinerama-dev libqtwebkit-dev
    git_inst 'hluk/CopyQ'
fi
