#!/bin/bash -e
source ~/.shell/func.d/packages

# GUI viewers for DB
#   community/sqlitebrowser
# + aur/valentina-studio
#   aur/sqliteman
#   aur/sqlitemanager
## ALSO:
# Use Free Sqlite Reader to View Sqlite Database Files ⌇⡟⡾⡒⣦
#   https://www.sqliteviewer.com/free/
# DB Browser for SQLite ⌇⡟⡾⡒⣲
#   https://sqlitebrowser.org/

if distro arch; then
  pkg_inst mariadb
  aur_inst mariadb-connector-c
fi
