#!/bin/bash -e
shopt -s nullglob
pfx=~/.cache/airy/wallpaper_

# ALT: create symlinks $CACHE/walls/{1..3}
# DEV: rendering text/pdf/etc file into wallpaper bw/wb format for cheetsheets
# then apply feh to dir 'walls/' -- it will choose images itself

# Set new wallpaper
for ((i=1 ; i<=$# ; i++)); do
  f=$(readlink -m "${!i}")
  [[ -e $f ]] || exit
  ln -svf "$f" "${pfx}$i"
done

cmd=(feh --no-fehbg --bg-scale )
# Use parts of one wallpaper for all monitors
# cmd+=(--no-xinerama --bg-fill)

args=()
for L in "${pfx}"*; do
  [[ -e $L ]] || exit
  # Random wallpaper from dir
  f=$(find "$L" \( -type f -o -type l \) | shuf -n1)
  args+=( $f )  # Multimonitor (specify --bg-scale for each)
done

((${#args[@]})) && "${cmd[@]}" "${args[@]}" || xsetroot -gray
