#!/bin/bash -eu
source ~/.shell/func.d/packages

# ALSO:
# libgoogle-glog-dev
# google-mock

if distro arch; then
  pkg_inst gperftools

elif distro ubuntu; then
  pkg_inst google-perftools libgoogle-perftools-dev
fi
