#!/usr/bin/env bash
# 1..9 <stars> / name <genre>
set -euo pipefail

dir=/data/music/++

case "$1" in -l) ls "$dir/${2?}"; exit ;; esac

if [[ -f $1 ]]; then path=$1; else
  mdb=$(sed -rn '/^music_directory\s+"([^"]+)"$/s//\1/p' ~/.mpd/mpd.conf)
  rpath=$(mpc current -f '%file%')
  path=${mdb?}/${rpath?}
  path=${path/#\~/$HOME}  # Guard to media_directory='~/...'
  curr=$(mpc current -f '[%position%]')
fi

[[ -f $path ]] \
  && r.dmenu-move "$dir" "$path" \
  || exit
#Del current, interrupts cast by ssh: mpc del 0
${curr+mpc next >/dev/null && mpc del $curr}
