#!/usr/bin/env bash
set -euo pipefail
#%ONELINE: $ mpd add $(youtube-dl --no-check-certificate --no-playlist -f bestaudio -g $url)
# REF: https://bbs.archlinux.org/viewtopic.php?id=180478
# HACK:(when https not supported): --prefer-insecure | --no-check-certificate
# VIZ. $ youtube-dl -F sTPtBvcYkO8
# ALT: use -f140 -- lower bitrate
# OR: -f bestaudio
youtube-dl -g -f "${FMT:-bestaudio}" "$@" \
| xargs -rn1 -d\\n mpc add \
|| youtube-dl -F "$@"
