#!/bin/bash -eu
source ~/.shell/func.d/packages

if cfgOpt uU && has_pr pip2pkgbuild; then
  pip2pkgbuild -n jiracli-airy-git \
    -d python-termcolor python-jira python-tabulate \
    -- jiracli
fi

# TEMP:FIX install manually, because "makepkg" can't resolve AUR deps
aur_inst -d python-jira python-tabulate

loc_inst ./jiracli-airy-git.pkgbuild
