#!/bin/bash -e
cd $(dirname $(readlink -m ${0}))
[[ "${THEME:=$(< ~/.cache/airy/theme)}" =~ ^(dark|light)$ ]] || THEME=dark

### LINKS ###
link(){ [[ ! -e $2 || -L $2 ]] && ln -sfvT "$1" $2; }

dir=~/.surf && mkdir -p $dir
link "$PWD/script.js" "$dir/script.js"
link "$PWD/../vimb/theme/${THEME}.css" "$dir/style.css"
