#!/bin/bash -eu
source ~/.shell/func.d/packages

# nmap -- network exploration tool and security / port scanner
pkg_inst nmap
# pkg_inst net-tools  # netstat

if distro arch; then
  pkg_inst openbsd-netcat
  # nethogs - monitor per process network bandwidth
  pkg_inst nethogs
fi
