#!/bin/bash -e
# USAGE: [-][<HH>:]<MM>:<SS>[.<m>...] OR [-]<S>+[.<m>...]
fname="$1"
beg="$2"
end="$3"

src=$(readlink -m "$1")
[[ -n "$dst" ]] || dst="${src%/*}/fl-clip"
mkdir -p "$dst"

path="$dst/${fname##*/}"
sfx=${beg%.*}; sfx="_${sfx//:}"
path="${path%.*}${sfx}.${path##*.}"

if [[ -e "$path" ]]; then
    mv -vfT --backup=t "$path" "${path%.*}_${RANDOM}.${path##*.}"
fi

ffmpeg -y -nostdin -i "$fname" \
    -ss "${beg:-00:00}" -to "${end:--00:00}" \
    -codec:v copy -codec:a copy -codec:d copy \
    "$path"
        # OR -c copy \
# ALT ffmpeg -y -nostdin -ss $BEGIN -i "$SRC" -t $DURATION "$DST"
# OR ffmpeg -ss $BEGIN -i $SRC -to $END -strict -2 ${DST}.mp4
